### ISSUE TITLE
Error "Failed to decrypt conversation id" when sending activity

### ISSUE THREAD

**Issue by swatDong** [OfficeDev/TeamsFx#10059]
**Describe the bug**
Get 403 error "Failed to decrypt conversation id" when calling `context.sendActicity()`.

```
  request: {
    method: POST,
    url: https://smba.trafficmanager.net/apac/v3/conversations/.../activities/...
  },
  response: {
    body: '{"error":{"code":"BadArgument","message":"Failed to decrypt conversation id"}}',
    headers: HttpHeaders { _headersMap: [Object] },
    status: 403
  },
  body: {
    error: {
      code: 'BadArgument',
      message: 'Failed to decrypt conversation id'
    }
  }
```

The bot can correctly receive messages from Teams, but failed to send message to Teams.

**To Reproduce**
1. Create new Teams Bot App
2. Local Debug (F5) or Provision/Deploy to Azure
3. Open the bot in Teams and try it
4. See error from bot code

**Expected behavior**
Bot should be able to send message.

**Comment by swatDong** [comment]
This is caused by upstream service and the dev team is actively working on the fix.

**Comment by B45i** [comment]
Any workout with this issue?  Our Team is blocked due to this

**Comment by vaibhavnd** [comment]
Our Team is also facing the issue, getting follow error message 
[onTurnError] unhandled error: Error: Failed to decrypt conversation id

**Comment by johnmiroki** [comment]
We've also encountered this error for a couple hours. It's lighting up now.

**Comment by StCross** [comment]
We've also confronted with this issue and it keeps logging 
`{"error":{"code":"BadArgument","message":"Failed to decrypt conversation id"}`

**Comment by swatDong** [comment]
The upstream service is rolling out the fix. Some bots already work.

**Comment by vaibhavnd** [comment]
Thanks ,it's working now

**Comment by swatDong** [comment]
Fix is rolled out. This issue should be gone now.

**Comment by iloveyeseul** [comment]
@swatDong is this fix rolled out? Our team is still seeing the issue

**Comment by LikhitJagatiya** [comment]
Again started giving the same error teams:"Failed to decrypt conversation id"

**Comment by vaibhavnd** [comment]
> Thanks ,it's working now

It has stopped working again since yesterday. 
Kindly resolve it on priority

**Comment by B45i** [comment]
@swatDong 

I've the following code,

```js
        const member = await commandApp.notification.findMember(
            async m => m.account.email === req.body.email
        );

        if (!member) {
            return res.send(404, 'User not found');
        }

        await member.sendMessage(req.body.text);
        
     ```

and it still fails with the error:
     
>  Failed to decrypt conversation id

**Comment by swatDong** [comment]
> @swatDong
> 
> I've the following code,
> 
> ```js
>         const member = await commandApp.notification.findMember(
>             async m => m.account.email === req.body.email
>         );
> 
>         if (!member) {
>             return res.send(404, 'User not found');
>         }
> 
>         await member.sendMessage(req.body.text);
>         
>      ```
> 
> and it still fails with the error:
>      
> >  Failed to decrypt conversation id
> ```

When proactively messaging, `Failed to decrypt conversation id` sometimes is expected after bot changes/re-provisioned. See if this [FAQ](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams?tabs=ts1%2Cts2%2Cts3%2Cts4%2Cjsts%2Cts5#faq) helps.
<img width="539" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/7642967/2bdd02c0-33d4-402f-9dc9-8631cbb18476">

**Comment by ADRIANPGA** [comment]
Hi, I am facing now the exact same issue when posting against

https://smba.trafficmanager.net/emea/v3/conversations/...

when it has been working with no issue for weeks, and there is no apparent change neither in the bot credentials nor in my app.

Any insights in how to solve it?

**Comment by moeed-devflow** [comment]
kindly someone guide me how to resolve this issue

**Comment by ADRIANPGA** [comment]
Posting here advice in case it helps someone in the future

In my case it was due to .notification.localstore.json (The default mechanism for [storing conversation](https://github.com/OfficeDev/teams-toolkit/blob/f4116d5bf67620a8a734d3acc0fc2213de21c2a2/templates/bot/js/notification-restify/README.md#customize-storage)) having incorrect values from previous states of the app (changing app id, azure bot resource...).

Going directly to app directory and deleting the file + restarting the app made the work for me. Take care in case you're relying on this file to get conversation references (that was not my case)

And moving to a [DB conversation reference approach](https://learn.microsoft.com/en-us/dotnet/api/microsoft.teamsfx.conversation.notificationoptions.store?view=msteams-client-dotnet-latest) by extending the class methods is more than recommended before shipping.
