### ISSUE TITLE
Create Dev Tunnel failed. Response status code 303

### ISSUE THREAD

**Issue by mmsharepoint** [OfficeDev/TeamsFx#10067]
**Describe the bug**
When trying to create a dev tunnel in Teams Toolkit for Visual Studio 17.7.4 I receive an error:
"Creating the dev tunnel failed. Response status code does not indicate success: 303 (See other)"

**To Reproduce**
1. Create a bot solution
2. Execute Step 1 in GettingStarted.txt

**Expected behavior**
A dev tunnel should be created and after Prepare Teams App Dependencies F5 and local debug should be possible

**Comment by SLdragon** [comment]
Thank you for your valuable feedback as we are currently on holiday and may not be able to reply promptly. We will get back to you after 10.6 as soon as possible.

**Comment by xiaolang124** [comment]
Sorry for the inconvenience!
do you continue to experience this error when attempting to create a development tunnel? (In the debug dropdown menu, select Dev Tunnels > Create A Tunnel.) If the issue persists, I recommend updating your Visual Studio to the latest version and attempting the process again.

**Comment by mmsharepoint** [comment]
> Sorry for the inconvenience! Do you continue to experience this error when attempting to create a development tunnel? (In the debug dropdown menu, select Dev Tunnels > Create A Tunnel.) If the issue persists, I recommend updating your Visual Studio to the latest version and attempting the process again.

As said above, I am already on 17.7.4 and just checked, it is still the latest version

**Comment by xiaolang124** [comment]
When creating a development tunnel, in the account dropdown list, could you please try switching to use either your GitHub account or your work account and then try it again?

Alternatively, could you please check if there are any development tunnels listed in the 'Show all dev tunnel' wizard?
![image](https://github.com/OfficeDev/TeamsFx/assets/13211513/3bef17ea-9986-4745-b87b-71af66945464)

If you continue to experience this issue, could you please check if the development tunnel CLI can successfully create a tunnel? If you're able to create a tunnel using the CLI, you can then select this tunnel in Visual Studio to proceed with your work.
https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows

**Comment by mmsharepoint** [comment]
No luck at all

- Tried with Work account
- Tried with GitHub
- Updated to 17.7.5
- Window with dev tunnels is empty

**Comment by xiaolang124** [comment]
We will take a look at this and respond as soon as possible.

**Comment by piniouf** [comment]
I'm getting this error too. I'm using VS2022 v17.8.2.... 

![image](https://github.com/OfficeDev/TeamsFx/assets/51211314/99a61836-71d0-42c7-9f5e-75335265894d)

Fails when I try with CLI too: 

![image](https://github.com/OfficeDev/TeamsFx/assets/51211314/5417910c-8435-4663-8e0c-b8a70ec3be1d)

My guess it's something to do with proxy?

**Comment by mmsharepoint** [comment]
> @mmsharepoint Can you try to use dev tunnel CLI to see if it has the same problem? You can follow [Dev Tunnel CLI](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows) to install CLI. And creating a tunnel with "--verbose" option to see details, which may give some clues about the problem.
> 
> The devtunnel service (which VS is calling to create the tunnel) does not return HTTP 303 status for any reason, and we could not find any such events in our service telemetry. Are you using any HTTP proxy?

@xiaolang124 
Sorry, never received your answer. Please give a few days to try it. 
Not yet used to the cli.
What is latest version of VS/TT btw?

**Comment by xiaolang124** [comment]
For now, you can update your VS to 17.8 and teamsfx extension can be updated or installed in VS installer/

**Comment by mmsharepoint** [comment]
Thank you, works now:

- Same solution
- VS updated to 18.8.
- TT with it to 17.7.7 so far ...
-
Soon I will try the ne preview ones to give Copilot plugins as well but for now it helps and thank you
