### ISSUE TITLE
Channel tab not refreshed when settings change via setConfig()

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/TeamsFx#10077]
**Describe the bug**
When changing the settings of a tab from the tab's settings page & calling the `setConfig()` method, the Teams client does not reload the tab to update based on the new changes. However, navigating off & back to the tab does pick up the saved changes, proving the changes were saved.

**To Reproduce**
1. create a new tab project with a new channel tab
1. add a tab that displays the current 
1. add a configuration page that changes the `entityId` when the settings dialog's SAVE button is clicked
1. observe the tab does not refresh and shows the old value
1. navigate away from the tab and come back, observe the `entityId` value has changed, proving the save settings page worked correctly

**Expected behavior**
Channel tab is refreshed by the Teams client when the settings are saved on the tab.

**Screenshots**
See the following video that demonstrates the issue:
<div>
    <a href="https://www.loom.com/share/3f59b31125954479a2a7e5bcf38c15ea">
      <p>GH - OfficeDev/TeamsFx Issue#10077 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/3f59b31125954479a2a7e5bcf38c15ea">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/3f59b31125954479a2a7e5bcf38c15ea-with-play.gif">
    </a>
  </div>

**VS Code Extension Information (please complete the following information):**
 - OS: macOS
 - Version v5.2

n/a

**Comment by hund030** [comment]
I found there is a similar issue https://github.com/OfficeDev/microsoft-teams-library-js/issues/679 which has been fixed for a long time.
Forwarding this issue to teams-js sdk. 
@andrewconnell Could you provide the teams-js sdk version you are using? I suppose it should be the latest 2.15.0.
```
 "node_modules/@microsoft/teams-js": {
      "version": "2.15.0",
      ...
    },
```

**Comment by andrewconnell** [comment]
@hund030 I'm using Teams JS v2.15.0. 

The project in the video above was created using TTK (latest, v5.2.0) which references the package using the NPM `^` wildcard: `"@microsoft/teams-js": "^2.13.0",`. 

I checked in **node_modules**, and it's installed v2.15.0

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/9637

**Comment by hund030** [comment]
@andrewconnell FYI. teams-js SDK team is looking at this bug.
https://github.com/OfficeDev/microsoft-teams-library-js/issues/1963#issuecomment-1761450012

**Comment by adashen** [comment]
Close as the upstream issue has already been closed.

**Comment by ramsivaramsiva** [comment]
Hi Team,
Am also facing this same issue is there any solution to fix this issue?
