### ISSUE TITLE
bug report: AppStudioPlugin.DeveloperPortalAPIFailed

### ISSUE THREAD

**Issue by CarlosDevoteam** [OfficeDev/TeamsFx#10072]
API call to Developer Portal failed: Error, Request failed with status code 404, API name: get-app-package, X-Correlation-ID: 21218a10-4b1d-4e65-a6e5-2cdc37bbe8b7. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: {"type":"https:/<REDACTED: user-file-path>

**Comment by xzf0587** [comment]
Hi @CarlosDevoteam, thanks for reaching out.
The error message shows it should be an upstream intermittent service error. Do you retry and reproduce it?
