### ISSUE TITLE
Andorid Bot: Adapative Card updates show "Unknown Error" 

### ISSUE THREAD

**Issue by ichivers** [OfficeDev/TeamsFx#10104]
**Describe the bug**
When an Adaptive card is updated in a bot conversation on the Android Teams App an "Unknown Error" messages briefly appears.  The function completes as expected, but the "Unknown Error" message should not appear.  This also happens in a deployed production environment.

**To Reproduce**
From the Teams Toolkit Create a New App.  
Select Bot
Choose Basic Bot
Debug (or run) the app in Teams App on Android
Send a "Learn" message to the bot
Click the "I Like This!" Action Button.
"Unknown Error" message breifly appears

**Expected behavior**
"Unknown Error" message should not appear at all.

**Screenshots**
https://github.com/OfficeDev/TeamsFx/assets/5063940/05382728-fbf6-4746-9a9f-7d796b65779c

**VS Code Extension Information (please complete the following information):**
 - OS: Mac-OS
 - Version 5.2.0

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/9635

**Comment by adashen** [comment]
Close here and track in upsteam.
