### ISSUE TITLE
README shown after creating an Action Message Extension incorrectly says that ME can be @ mentioned from compose box

### ISSUE THREAD

**Issue by AE-MS** [OfficeDev/TeamsFx#10112]
The readme says this:

_To trigger the action command, you can click the ... under compose message area, click ...-> More actions beside a message, or @ your message extension app from the command box._

However, [the docs](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=dotnet) for Action MEs say this:

 **Note
@mentioning message extensions is no longer supported in the compose box.**

**Comment by yukun-dong** [comment]
Hi @AE-MS ,

The command box is different to compose box. The command box is at the top of Teams ([reference](https://support.microsoft.com/en-gb/office/use-the-command-box-13c4e429-7324-4886-b377-5dbed539193b)).

Currently, @mention message extension from command box is supported.
![image](https://github.com/OfficeDev/TeamsFx/assets/25220706/96765821-50a0-4fa4-b56c-4bb63f4e4803)
