### ISSUE TITLE
Multiple local environments

### ISSUE THREAD

**Issue by jchomarat** [OfficeDev/TeamsFx#10110]
**Is your feature request related to a problem? Please describe.**
Our teams app is in a Visual Studio Code solution, with multiple other services (APIs for instance). We have a huge "launch.json" that starts all services locally. However, sometimes we just need to work on the UX of the Teams App, and the idea would be to connect to our Dev environment on Azure for the API and the entire backend. The idea is still to start locally the Teams app, but calling remote APIs.

**Describe the solution you'd like**
Ideally, we should be able to create multiple local environments, with different pipelines, e.g. teamsapp.local.yml, teamsapp.hybrid.yml etc ...

**Describe alternatives you've considered**
Right now, the only alternative we have is to change .env.local and teamsapp.local.yml to suit our need and inject another API endpoint, ensuring not to check them in in Git ....

**Comment by blackchoey** [comment]
@jchomarat Thanks for sharing the feedback. Since you're connecting to an existing dev environment, I'm wondering whether you can launch the Teams app directly without taking the actions defined in `teamsapp.hybrid.yml`. Can you share what's the difference between `teamsapp.local.yml` and `teamsapp.hybrid.yml`? Do you remove / add any steps in the yml file, or you just change the parameters for some actions?

**Comment by jchomarat** [comment]
Thanks @blackchoey for your answer. Actually, I cannot even start my pipeline `teamsapp.hybrid.yml`. Basically, I have my `local` environment using `teamsapp.local.yml' and it works. Then all other environment available (we have dev/qa) are using the file `teamsapp.yml`. So when I create my `hybrid` environment, it uses `teamsapp.yml`. Maybe I did not find a way to ensure that the `teamsapp.{ENV}.yml` is started. Let me know if you need more details.

**Comment by blackchoey** [comment]
Yes, currently all envs besides `local` uses `teamsapp.yml`. What I want to understand is, if it's possible to have a `teamsapp.hybrid.yml` as you proposed, what actions do you want to do in this file (or say what's the difference comparing with `teamsapp.local.yml`)? Will you add/remove some actions, or you just edit some parameter values in it?

The information could be helpful for me to provide a possible workaround for your scenario, as well as seeing how Teams Toolkit can better support such kind of scenario.

**Comment by jchomarat** [comment]
Hello @blackchoey. I think you got my point. Let me try to be more explicit. In our current project, we have a Teams App (tab + bot) and 2 APIs (that need various other resources, such as EventHub namespace):

* The `local` environment is started with a global launch configured in VSCode that starts locally both APIs, and deploys everything we need for the Teams App (create the bot, the Entra application etc ...) and inject in the Teams App the local endpoint for the APIs to be consumed by the Teams App. It works fine, but it is heavy.
* The `dev` or `qa` environments is doing the same, but deploys everything on the target Azure tenant.

Sometimes, we just need to work on the UI, and we maintain a `dev` environment on Azure with our APIs (and all other Azure resources needed for our application including the bot and the Entra app registration). So the idea is to be able to deploy locally only the Teams App, injecting the endpoints, bot id, app id etc ... that comes from our running `dev` environment. 

So to your question, yes, the `teamsapp.hybrid.yml` would be different, because the pipeline would not deploy anything excepte packaging the Teams app as it is in the current branch, and run it locally.

Maybe what we should have done is to actually have 2 separates VSCode repo: one for Teams Only, and one for the rest - but we felt it would be easier to have everything in the same folder and use VSCode workspaces (and it works super fine).

Let me know if you need more information. Thanks a lot

**Comment by blackchoey** [comment]
Thank you @jchomarat for the information. Based on the information you shared, you may be able to move the steps to `.vscode/tasks.json` as you don't need to take Teams specific actions when debug the `hybrid` environment. Thus avoid the need of having a `teamsapp.hybrid.yml` file.

You can follow below steps to customize your project (you may need to tweak the configs to make them fit your project):
1. Add a new `.hybridConfigs` files to your tab and bot project, the content will be same with `.localConfigs` in your tab and bot folder, but with different values. It is the app settings for your dev environment. Ensure you gitignore the files so it won't be committed.
1. Add below new item to your tab and bot project's `package.json` file, you can change the command name (`hybrid:teamsfx`) as you wish:
   ``` json
   "scripts": {
        "hybrid:teamsfx": "env-cmd --silent -f .hybridConfigs npm run start"
        // other existing items
    },
   ```
1. Add below item to `.vscode/tasks.json`. This is just an example for tab, also add an item for your bot too. You can refer existing items in `.vscode/tasks.json` to tweak configuration.
   ``` json
       {
            "label": "Start frontend for hybrid environment",
            "type": "shell",
            "command": "npm run hybrid:teamsfx", // This is different with existing start frontend config
            "isBackground": true,
            "options": {
                "cwd": "${workspaceFolder}/tab"
            },
            "problemMatcher": {
                "pattern": {
                    "regexp": "^.*$",
                    "file": 0,
                    "location": 1,
                    "message": 2
                },
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": ".*",
                    "endsPattern": "Compiled|Failed|compiled|failed"
                }
            }
        }
   ```
1. Add below item to `.vscode/tasks.json`, it skips the Teams Toolkit `provision` and `deploy` step before launch as we generates `.hybridConfigs` in step 1:
   ``` json
        {
            "label": "Start Teams App Locally - hybrid",
            "dependsOn": [
                "Validate prerequisites",
                "Start local tunnel",
                "Start frontend for hybrid environment",
                "Start bot for hybrid environment",
            ],
            "dependsOrder": "sequence"
        },
   ```
1. Add below item to `.vscode/launch.json`, which starts your tab and bot under hybrid environment before launch:
   ``` json
      {
            "name": "Debug (Edge)  - hybrid",
            "configurations": [
                "Attach to Frontend (Edge)",
                "Attach to Local Service"
            ],
            "preLaunchTask": "Start Teams App Locally  - hybrid", // This is different than existing config
            "presentation": {
                "group": "all",
                "order": 1
            },
            "stopAll": true
        }
   ```

**Comment by jchomarat** [comment]
Very nice approach @blackchoey, less `hacky` than mine :). Let me give a shot and I will get back to you. Thanks for your time

**Comment by blackchoey** [comment]
@jchomarat how's everything going with the suggested solution?

**Comment by blackchoey** [comment]
@jchomarat I'm going to close this issue as we have a solution. Feel free to reopen or create new issues if you have further questions.
