### ISSUE TITLE
The notification.localstore file is not created in my ConversationBot with tab project 

### ISSUE THREAD

**Issue by Wildarth** [OfficeDev/TeamsFx#10151]
**Describe the bug**
I have two Teams projects, one with a tab, the other with a conversation bot using adaptive cards and set as `notificationOnly`. I wanted to merge the two based on the hello-world-bot-with-tab sample. I ended up with the result I wanted except that when launching the project locally, the `.notification.localstore.json` is not created, so when I post I get a 200 but `getPagedInstallations` returns nothing and so I don't receive any notification.   

**To Reproduce**
- Create a tab project
- Create a conversation bot project (like the adaptive-card-notification sample)
- Merge the bot project into the tab project, following the hierarchy of the hello-world-bot-with-tab sample.
- Modify all `tasks.json`,`package.json` and other files where necessary, following the hello-world-bot-with-tab sample.
- Run the project and try to post, checking whether you receive the card

**Expected behavior**
When launching the project locally and install the app on Teams, the `.notification.localstore.json` file should be created and filled with the expected data. 

**VS Code Extension Information (please complete the following information):**
 - macOS 14.0
 - Visual Studio Code 1.83.1
 - Teams Toolkit v5.2.0

**Comment by Wildarth** [comment]
I seem to have found the solution: in my bot project, the messageHandler route and function no longer existed. However, while investigating other projects, I noticed that it was used in bot projects to manage registration/deletion.

By adding the route again, everything now works perfectly, problem solved.

**Comment by G9000** [comment]
@Wildarth I had the same issue now similar to what you did after combining both tab and bot. What do you mean by messageHandler route?
