### ISSUE TITLE
Manifest parsing has failed when uploading the app on Teams Apps store

### ISSUE THREAD

**Issue by nekruza** [OfficeDev/TeamsFx#10185]
<img width="732" alt="Screenshot 2023-10-16 at 13 34 58" src="https://github.com/OfficeDev/TeamsFx/assets/90331576/ca4c21a9-5a54-42dc-a42e-7ff5fb26d48d">

**Comment by nliu-ms** [comment]
Hey @nekruza , can you please click `Copy error details to clipboard` and paste the error message here? Thanks!
