### ISSUE TITLE
Unable to get UserInformation in Outlook Mobile App (Iphone and Android)

### ISSUE THREAD

**Issue by manbuettner** [OfficeDev/TeamsFx#10205]
I have a Productive App that works in all Environments (Manifest  1.16) at Desktop and Web.
Now i got a Ticket from MS Teams App that App not work in Outlook for Mobile.

I also make a sample Project in Teams Toolkit. Tab with Fluent.
Just Create and Deploy. Open it On Teams Desktop and App. 
Inside the Project is aAzureFunctions.tsx.

**To Reproduce**
1) Start the App.
2) On first Tab, Build your app locally scroll down to 
3) Click on Authorize and call Azure Function

You got a result including...
"userInfoMessage": "User display name is ....",

Do the same on Outlook for Mobile.
There is no result.

**Expected behavior**
I expect that same result is in Outlook for Mobile. The "inTeams" Variable is set to true.

**Screenshots**
see screenshot

**VS Code Extension Information (please complete the following information):**
MS Windows 
Teams Toolkit 5.0.2

**Additional context**
![2023-10-24_12h53_49](https://github.com/OfficeDev/TeamsFx/assets/11453965/16749854-d6f1-4127-bdb0-453fac5db577)

**Comment by KennethBWSong** [comment]
@manbuettner Thank you for using our Toolkit! Would you please also provide information below to help us debug the problem?
1. Do you meet this problem on IOS or Android?
2. Does this app works on your Outlook on website/desktop and Teams mobile?

**Comment by manbuettner** [comment]
I have a Productive App that works in all Environments (Manifest 1.16) at Desktop and Web.
Thanks :-)

**Comment by KennethBWSong** [comment]
@manbuettner I can not reproduce this error on mobile clients. Would you please share your client version and also try if this app can work on Teams mobile clients?
