### ISSUE TITLE
Teams Tab not Adding to Team

### ISSUE THREAD

**Issue by sambetts** [OfficeDev/TeamsFx#10217]
**Describe the bug**
Teams tab do not appear in Teams when deployed from VSCode in new solutions too. 

**To Reproduce**
1. Create new app. Tab, basic tab, TypeScript, select the folder you wish.
2. Open the app and modify the tab in appPackage\manifest.json to make the tab a team tab (staticTabs):

```json
        {
            "entityId": "index0",
            "name": "Team Tab",
            "contentUrl": "${{TAB_ENDPOINT}}/tab",
            "websiteUrl": "${{TAB_ENDPOINT}}/tab",
            "scopes": [
                "team"
            ]
        }
```
3. Press F5 to deploy.
4. A browser window opens, and Teams will ask you where to deploy. Pick whatever team you want.
5. The tab will not appear anywhere.

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11 22H2
 - VSCode 1.83.1
 - Teams Toolkit v5.2.0

**Additional context**
Have tested other Teams. 
It worked yesterday 😅.

**Comment by hund030** [comment]
A static tab cannot be added to a teams channel yet. Please consider using configurable tab instead.
https://learn.microsoft.com/microsoftteams/platform/tabs/what-are-tabs
<img width="554" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/26134943/d5d29e12-2b4b-48fb-850a-3512339b3137">

You can find a sample here: https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/hello-world-bot-with-tab/appPackage/manifest.json#L58

**Comment by sambetts** [comment]
Ah ok. Strange it worked for a while then, and seemingly the manifest schema had no problem with it. Thanks for the reply!
