### ISSUE TITLE
Project with Microsoft Tunneling throws a 502 error since yesterday

### ISSUE THREAD

**Issue by rgcircum** [OfficeDev/TeamsFx#10233]
Teams Toolkit project with Microsoft Tunneling (MS Tunnel) throws a 502 error since yesterday (Teams toolkit sample included)

 - OS: win11
 - Version : 5.2.0
 
Tunneling is up (no console error un VSC).
Localhost URL working (127.0.0.1:3978 or localhost:3978)
No error on outpout tab in VSC
I'm Ping correctly MS tunnel URL
The project worked before yesterday

MS Tunnel URL do not resolve/redirect local URL (502 error) (******.uks1.devtunnels.ms)

I have this problem on all project with Tunneling service (Bot ...) since Yesterday. Anyone have this same problem ? 
The problem appearing without modifying project.

I have tested on another computer and have same problem. I work on my project since 3 week without problem.

**Comment by xiaolang124** [comment]
Hello, are you still experiencing this issue? Would you mind trying to debug a new bot project to see if it works?
If the problem persists, could you please assist by providing additional log information in VS Code (Start local tunnel)?
![image](https://github.com/OfficeDev/TeamsFx/assets/13211513/97da6df7-ec98-4646-aebc-386bf12fee4b)

**Comment by rgcircum** [comment]
It's been working since this morning, it's magic 🤣

**Comment by Nils354** [comment]
having the same error

**Comment by tomo3569** [comment]
I have the same symptoms. Please help.
I've tried the previous feedback steps but they didn't work.

**Comment by diveshadivarekar** [comment]
### Solution for 502 error while Tunneling

@tomo3569 @Nils354 @xiaolang124 

changing the **port protocol** solved the issue. 
changed to **HTTP** from **HTTPS**  

![image](https://github.com/user-attachments/assets/5f2ffc22-2871-43ea-a058-13aaadb29e2c)
