### ISSUE TITLE
Use parameter --manifest-file-path / --manifest-path

### ISSUE THREAD

**Issue by jchomarat** [OfficeDev/TeamsFx#10251]
**Describe the bug**
I am trying to run the following command

```sh
teamsfx package --env prod --manifest-path "path-to-manifest"
```

Then I got the the message asking me to select a manifest.

<img width="400" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/6317287/480271a4-945d-4630-9847-b2defcf7cc08">

Looking at the [doc](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-cli?pivots=version-two#parameters-for-teamsfx-package) the parameter is supposed to be `--manifest-file-path` but this one in unrecognized.

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by jayzhang** [comment]
@jchomarat Thanks for reporting the issue. Actually, the doc is out of date. Please use `teams-manifest-file` instead: 
<img width="671" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/1658418/69432f30-19f6-4d94-92de-705942891883">

**Comment by jchomarat** [comment]
@jayzhang, which version are you using. Here is what I have

![image](https://github.com/OfficeDev/TeamsFx/assets/6317287/25169d41-5bbb-46f4-842a-3fc1bd30c428)

**Comment by jayzhang** [comment]
@jchomarat Sorry for misunderstanding. In version `2.0.2`, the default mode is interactive, if you want to run the command in none-interactive mode, please add an option: `--interactive false` for this command.

**Comment by jchomarat** [comment]
hey @jayzhang  - oh ok, makes sense even though it was not clear. Thanks, works like a charm

**Comment by adashen** [comment]
Close as the issue is resolved
