### ISSUE TITLE
Handle Adaptive card action style in Microsoft Teams

### ISSUE THREAD

**Issue by Wildarth** [OfficeDev/TeamsFx#10271]
**Is your feature request related to a problem? Please describe.**
It is currently impossible to use style to visually indicate to the user which button is used to confirm or cancel (for example). 
This would also make the card more visually interesting.

**Describe the solution you'd like**
Handle positive and descructive style in Teams

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/9837

**Comment by adashen** [comment]
Close here and let's track in the upstream issue
