### ISSUE TITLE
Sideloading broken in `New Teams` web client

### ISSUE THREAD

**Issue by garrytrinder** [OfficeDev/TeamsFx#10280]
**Describe the bug**

App install dialog does not appear when New Teams toggle is enabled in web client

**To Reproduce**

1. Enable try New Team toggle in Teams web client
1. Start debug session (F5)
1. `This app cannot be found message.`

**Expected behavior**
App install dialog should appear in both classic and new clients

**Screenshots**

New Teams

![Snag_7036f78](https://github.com/OfficeDev/TeamsFx/assets/11563347/8a6bfa22-aaa7-4be6-af5b-efc44da9b430)

Classic Teams

![Snag_7037ad2](https://github.com/OfficeDev/TeamsFx/assets/11563347/29a870a9-6d7b-4d76-b840-7d20ff8126f9)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version: 5.2.0

**Additional context**

URL used to launch browser, `https://teams.microsoft.com/l/app/535a9681-f598-49ab-b638-8b2f4a613a02?installAppPackage=true&webjoin=true`

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/9860

**Comment by kuojianlu** [comment]
Can totally reproduce this bug. Marked as upstream.

**Comment by mmsharepoint** [comment]
Good finding with switching New/Classic Teams. Error caused headaches for me while trying to debug a bot.
Can reproduce 100% as well

**Comment by therealjohn** [comment]
I've confirmed that the New Teams client doesn't support the app deep links for sideloaded apps yet which causes this App not found dialog. It's expected that the Teams 2.x client (New Teams) will support it mid to late February.

**Comment by dcashpeterson** [comment]
@therealjohn I have also noticed that Team 2.x doesn't support Stage View links like https://teams.microsoft.com/l/stage/{appId}/0?context={"contentUrl":"contentUrl","websiteUrl":"websiteUrl","name":"Contoso"} Is the fix in late February going to support this as well?

**Comment by blackchoey** [comment]
@dcashpeterson We're confirming this internally. Will keep you posted on the update.

**Comment by saketkintali** [comment]
@dcashpeterson we would need more details along with logs if stagedeeplink is not working for you. the above url as is wouldn't work as its not encoded.

**Comment by saketkintali** [comment]
@dcashpeterson we would need more details along with logs if stagedeeplink is not working for you. the above url as is wouldn't work as its not encoded.

**Comment by dcashpeterson** [comment]
@saketkintali this is the URL I am using.

https://teams.microsoft.com/l/stage/81fef3a6-72aa-4648-a763-de824aeafb7d/0?context=%7B%22contentUrl%22%3A%22https%3A%2F%2Fforms.office.com%2Fr%2FGsSGgfdBy4A%22%2C%22websiteUrl%22%3A%22https%3A%2F%2Fforms.office.com%2Fr%2FGsSGgfdBy4A%22%7D

**Comment by blackchoey** [comment]
@garrytrinder  This sideloading issue is now fixed in New Teams. Please let us know if you still meet problem.

**Comment by garrytrinder** [comment]
Thanks for the update @blackchoey 

I've been able to confirm that this is working for me in the early rings, but not been able to get this working in the public ring.
