### ISSUE TITLE
local bot id depoyed on azure

### ISSUE THREAD

**Issue by Damianoux** [OfficeDev/TeamsFx#10283]
**Describe the bug**
Using Visual studio+Teams Toolkit, with dev and local environments, on Linux, the first time I deploy a Web App, the file ".notification.localstore.json" contains the correct bot id (env.dev). If I do some changes and debugging and then deploy again, now the  ".notification.localstore.json", contains the wrong bot id (env.local).

**To Reproduce**
1. Install Visual studio code and Teams Toolkit on Ubuntu
2. Create a new  bot project (I create a notifican bot project).
3. Adjust bicep to provision a B1 on Linux with Node18-lts. In azure.bicep set WEBSITE_RUN_FROM_PACKAGE=0, RUNNING_ON_AZURE=1, linuxFxVersion: 'NODE|18-lts', kind: 'linux', reserved: true. In appPackage/mnaifest.json set "isNotificationOnly": true.
4. Deploy and Publish BOT
5. Do some changes to the code and hit F5 to debug
6. Once you are satisfied deploy and publish again.

**Result**
SSH Login in the web app on Azure. ".notification.localstore.json" contain local bot id.

**Expected behavior**
".notification.localstore.json" on Azure should always contain dev bot id.

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - Visual Studio code 1.84  on UBuntu 20.04-Lts
 - Teams Toolkit 5.2.0

**CLI Information (please complete the following information):**
- none

**Additional context**
 Did not test with Visual Studio Code on Windows.
 An extract of my azure.bicep:

// Compute resources for your Web App
resource serverfarm 'Microsoft.Web/serverfarms@2021-02-01' = {
  kind: 'linux'
  location: location
  name: serverfarmsName
  sku: {
    name: webAppSKU
  }
  properties: {
    reserved: true
  }
}

// Web App that hosts your bot
resource webApp 'Microsoft.Web/sites@2021-02-01' = {
  kind: 'app'
  location: location
  name: webAppName
  properties: {
    serverFarmId: serverfarm.id
    httpsOnly: true
    siteConfig: {
      alwaysOn: true
      linuxFxVersion: 'NODE|18-lts'
      appSettings: [
        {
          name: 'WEBSITE_RUN_FROM_PACKAGE'
          value: '0' // Run Azure APP Service from a package file
        }
        {
          name: 'WEBSITE_NODE_DEFAULT_VERSION'
          value: '~18' // Set NodeJS version to 18.x for your site
        }
        {
          name: 'RUNNING_ON_AZURE'
          value: '1'
        }
        {
          name: 'BOT_ID'
          value: botAadAppClientId
        }
        {
          name: 'BOT_PASSWORD'
          value: botAadAppClientSecret
        }
      ]
      ftpsState: 'FtpsOnly'
    }
  }
}

**Comment by Damianoux** [comment]
The problem is related to the fact that the file .notification.localstore.json, which in my case is located in /home/site/wwwrot (not in /tmp) is overwritten at each deploy, losing any refrence bot installations, and causing error 403 when trying to post messages to the bot.

**Comment by swatDong** [comment]
@Damianoux , it's recommended to use your own storage instead of local file for bot installations on Azure. (https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams?tabs=ts1%2Cts2%2Cts3%2Cts4%2Cjsts%2Cts5#add-storage)

Or, for your specific case, could you please try moditying the `.appserviceignore` file to exclude the local one to be packaged and deployed?

**Comment by Damianoux** [comment]
> @Damianoux , it's recommended to use your own storage instead of local file for bot installations on Azure. (https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams?tabs=ts1%2Cts2%2Cts3%2Cts4%2Cjsts%2Cts5#add-storage)
> 
> Or, for your specific case, could you please try moditying the `.appserviceignore` file to exclude the local one to be packaged and deployed?

**Comment by Damianoux** [comment]
I'll try this.
Using the "".notification.localstore.json" is useful for bootstraping and test a project or even if you have notification bot thas is isntalled only once on one channel and never changes.
Not understanding which was the problem caused me some headaches ate the beginning.
Thank you.
