### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by BasetsanaNjody** [OfficeDev/TeamsFx#10314]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by adashen** [comment]
Thanks @BasetsanaNjody for the issue. Can you provide more detail about the issue for us to investigate?

**Comment by BasetsanaNjody** [comment]
unfortunately that's where it ends. i cant conclude more information.
