### ISSUE TITLE
Allow for the configuration of tenant account type while using `botAadApp/create` from a teams bot app

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [OfficeDev/TeamsFx#10347]
**Is your feature request related to a problem? Please describe.**
I have come to know that a teams bot can now work with a `SingleTenant` bot type. But even if I configure my bot to use it while initializing, the AAD app that gets created is still marked as multi tenant. I am not sure if this could cause issues down the line.

**Describe the solution you'd like**
Maybe allow another parameter in the `botAadApp/create` action, the tenant/bot type with which the correct type of AAD can be created.

**Describe alternatives you've considered**
I believe one can easily change the tenant type in the AAD app that gets created manually.

**Additional context**
Again, I am not sure of the implications and whether making this change is necessary in the first place. If not, I would appreciate some idea as to how this works in the first place.

**Comment by SayakMukhopadhyay** [comment]
I also verified that the "bot" that gets created in Bot Framework (dev.botframework.com) is also mark as multi tenant when I am setting up my app to be Single tenant as `adapterConfig` in `new Conversation()`.

**Comment by blackchoey** [comment]
Hi @SayakMukhopadhyay you can use [aadApp/create](https://github.com/OfficeDev/TeamsFx/wiki/Available-actions-in-Teams-Toolkit#aadappcreate) action to create a single tenant app and use it in your app. [This sample](https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation/nodejs) uses `aadApp/create` to create an AAD app for bot, you can refer below code snippet to better understand how it works:
* Create a multi tenant AAD app for bot (you can update the `signInAudience` parameter to create a single tenant app instead): https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-conversation/nodejs/teamsapp.local.yml#L10-L21
* Write the client id/secret from `aadApp/create` to .env file, which will be consumed by the botbuilder package: https://github.com/OfficeDev/Microsoft-Teams-Samples/blob/main/samples/bot-conversation/nodejs/teamsapp.local.yml#L84-L91

**Comment by SayakMukhopadhyay** [comment]
Would it be possible to bring in this option to `botAadApp/create` too? Also, it seems to me that `botFramework/create` also creates a multi tenant bot and there is no way to configure it.

**Comment by blackchoey** [comment]
The current recommendation is to use `aadApp/create` instead of `botAadApp/create`. Please update your action if you have such requirement.
`botFramework/create` take an AAD app client id as parameter. The AAD app determines the tenant type. So you just need to create a single tenant AAD app and provide it to `botFramework/create`. Please let me know if there's still issue after you configured in this way.

**Comment by xianlin** [comment]
So in the Azure Bot portal, we should manage to setup the msaAppTenantId value to our org tenant ID to enable this "SingleTenant" feature of the Bot?

![image](https://github.com/OfficeDev/TeamsFx/assets/1726373/5821081f-5e6e-408c-a19d-22f6759a5ce8)

**Comment by blackchoey** [comment]
Yes, please refer Azure Bot Service's document for more details about how to configure the service and your bot's code to use a single tenant app.

**Comment by xianlin** [comment]
_Support for the user-assigned managed identity and single-tenant app types was added to the Bot Framework SDK for C# and JavaScript in version 4.15.0. These app types aren't supported in the other languages or in Bot Framework Composer, Bot Framework Emulator, or ngrok._

the above was from MS doc at https://learn.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=userassigned

**Comment by xianlin** [comment]
after made the above changes to supply the `msAppTenantID` and `msAppType`, my bot works with Single Tenant mode
