### ISSUE TITLE
Create SPFx project or Add SPFx web part failed

### ISSUE THREAD

**Issue by yuqizhou77** [OfficeDev/TeamsFx#10382]
**Describe the bug**
Create a new SPFx project would fail if choosing "install the latest SPFx locally in Teams Toolkit directory". Error code: SPFx.ScaffoldFailed
Add new web part would also fail. Error code: SPFx.ScaffoldFailed
**To Reproduce**
Create a new project:
1. Create a new App in Teams Toolkit
2. Select "Tab" -> "SPFx" -> "Create a New SPFx solution"
3. Select "install the latest SPFx locally in Teams Toolkit directory"
4. Continue with the following questions.

Or add web part:
1. Open an SPFx project created using Teams Toolkit before
2. Select "Add SPFx Web Part" in "Development"

**Expected behavior**
Scaffolding or add a web part should succeed

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/86260893/a358f2e0-4e42-401a-be16-672c18c5cf21)

**Comment by yuqizhou77** [comment]
This issue is due to latest release of yo 5.

Workaround for creating a new project: 
1. Install yo@4.3.1: npm install yo@4.3.1 --global 
2. Install Yeoman SharePoint generator: npm install @microsoft/generator-sharepoint --global
3. Go back to Teams Toolkit and create a new app
4. Select "Tab" -> "SPFx" -> "Create a New SPFx solution"
5. Select "use globally installed SPFx"

**Comment by yuqizhou77** [comment]
If you want to add a web part for a project scaffolded by Teams Toolkit before, here is a workaround (please replace ${WebPartName} with the name you need)
1. Open command line prompt and go to the src folder of your SPFx project (it should be something like {SPFxProjectPath}/src)
2. Run yo @microsoft/sharepoint --skip-install true --component-type webpart --component-name ${WebPartName}--environment spo --skip-feature-deployment true --is-domain-isolated false. 
3. Open the webpart manifest file (src/webparts/${webpartname}/${webPartName}WebPart.manifest.json) in the generated webpart to find the id.
4. Update teams manifest.json in appPackage folder ( {SPFxProjectPath}/appPackage). Please replace ${WebPartName} and ${id} with the value you got from previous steps.     
     i. add static tab in manifest.local.json
  ````
              {
		            "entityId": "${id}",
		            "name": "${webPartName}",
		            "contentUrl": "[https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/TeamsWorkBench.aspx%3FcomponentId=${id}%26teams%26personal%26forceLocale={locale}%26loadSPFX%3Dtrue%26debugManifestsFile%3Dhttps%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js](https://{teamsitedomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=%7bteamSitePath%7d/_layouts/15/TeamsWorkBench.aspx%3FcomponentId=$%7bid%7d%26teams%26personal%26forceLocale=%7blocale%7d%26loadSPFX%3Dtrue%26debugManifestsFile%3Dhttps%3A%2F%2Flocalhost%3A4321%2Ftemp%2Fmanifests.js)",
		            "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
		            "scopes": [
		                "personal"
		            ]
              }
````            
   ii. add static tab in manifest.json
```
           {
	             "entityId": "${id}",
	             "name": "${webPartName}",
		     "contentUrl": "[https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=${id}%26forceLocale={locale}](https://{teamsitedomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=$%7bid%7d%26forceLocale=%7blocale%7d)",
		     "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
		     "scopes": [
			   "personal"
			]
            }
```

**Comment by paraggin** [comment]
Tab added as per above command.Works in Teams , But not working in new Teams
Old Teams : 
![image](https://github.com/OfficeDev/TeamsFx/assets/107133664/a676baef-04d9-4e36-b99e-78089d10c658)

New Teams : 
![image](https://github.com/OfficeDev/TeamsFx/assets/107133664/f866027e-5390-4904-9da0-7683b946cd77)

**Comment by yuqizhou77** [comment]
@paraggin  This issue seems different. If it still persists, could you open a new issue and provide more detailed steps, like whether you can view the page in new Teams before adding new tab, .yo-rc, package.json etc. Thanks

**Comment by yuqizhou77** [comment]
This issue has been fixed and we have improved SPFx add web part experience in v5.6.0. Closing this issue now.

**Comment by ntt77** [comment]
> This issue has been fixed and we have improved SPFx add web part experience in v5.6.0. Closing this issue now.

no it is not work till now.
`Error: generator.run is not a function`
