### ISSUE TITLE
meger

### ISSUE THREAD

**Issue by BasetsanaNjody** [OfficeDev/TeamsFx#10407]
*   -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${{ github.repository }}/actions/workflows/rerun.yml/dispatches \
           -d '{"ref":"${{ github.ref_name }}","inputs":{"run_id"

**Comment by adashen** [comment]
hi @BasetsanaNjody thanks for reporting the issue. Can you help to provide the detail steps so that we can do the further investigation?

**Comment by BasetsanaNjody** [comment]
Hi @adashen I was unable to work on something but I than managed I will close the issue.

**Comment by adashen** [comment]
Close as the issue resolved
