### ISSUE TITLE
{"Failed to get access token from OAuth identity server, please login(consent) first"}

### ISSUE THREAD

**Issue by dewuyi** [OfficeDev/TeamsFx#10443]
Describe the bug
I'm developing a Blazor Server app integrated with Microsoft Teams, using the TeamsFx SDK. I'm encountering a recurring issue where I'm unable to acquire an access token from the OAuth identity server to make Microsoft Graph API calls, despite the user being authenticated successfully. The specific error message is: "Failed to get access token from OAuth identity server, please login(consent) first", which occurs even after the user has logged in and consented to the required permissions.

To Reproduce

1. User logs in successfully using TeamsUserCredential.
2. Attempts to call  "await teamsUserCredential.GetTokenAsync(new TokenRequestContext(scopes), new System.Threading.CancellationToken());"
3. Attempts to call Microsoft Graph API (e.g., graph.Me.Events.GetAsync()).
4. Receives an error (for both step 3 and 4) indicating that the access token is not available, suggesting a consent/login issue.
-error is {"Failed to get access token from OAuth identity server, please login(consent) first"}
5. This occurs despite ensuring the user has authenticated and consented to the necessary scopes.
Expected behavior
After successful user login and consent, the app should be able to acquire an access token and make calls to the Microsoft Graph API without encountering the mentioned error.

Additional context
The GetUserInfoAsync() call works as expected, confirming that the user is authenticated. However, subsequent calls to Microsoft Graph API fail due to the access token issue. The required Microsoft Graph permissions have been configured in the app registration in Azure AD, and admin consent has been granted where necessary.

This issue seems to be a blocker for accessing the Microsoft Graph API despite following the authentication and consent flow as outlined in the TeamsFx documentation.

**Comment by dewuyi** [comment]
await teamsUserCredential.LoginAsync(_scopes);

this method was called before trying to access the graph

**Comment by dewuyi** [comment]
so I found out it's got to do with my app registration on AAD, I didn't get this with a different app I created on AAD even though they have identical settings

**Comment by KennethBWSong** [comment]
Closed as issue fixed.
