### ISSUE TITLE
bug report: AppStudioPlugin.DeveloperPortalAPIFailed

### ISSUE THREAD

**Issue by SAKET-SK** [OfficeDev/TeamsFx#10451]
API call to Developer Portal failed: Error, Request failed with status code 404, API name: get-app-package, X-Correlation-ID: 440a6595-c77b-446e-aa2f-ea3e1de2c123. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: {"type":"https:/<REDACTED: user-file-path>

**Comment by jayzhang** [comment]
@SAKET-SK Thanks, we are investigating the issue.

**Comment by yuqizhou77** [comment]
@SAKET-SK Could you please try to "open in Teams Toolkit" from the [web portal](https://dev.teams.microsoft.com/) directly and let us know if it can work？
Could also verify the "App package" page in [web portal](https://dev.teams.microsoft.com/) and verify if you can view this page with no issue and download the app package? You can find "App package" in the left panel
![image](https://github.com/OfficeDev/TeamsFx/assets/86260893/a2d3e7c4-1383-447a-9d24-868d75645aac)

**Comment by SAKET-SK** [comment]
Sure I will try and let you know soon.

**Comment by nliu-ms** [comment]
Hey @SAKET-SK , this issue has been fixed, Teams Developer Portal Teams app is currently using the same endpoint as web app. Can you please help to try and verify it? Thanks!

**Comment by SAKET-SK** [comment]
Yes it is working and the issue seems to have been resolved from my end. Thanks!!
