### ISSUE TITLE
SPFx Error: Error: TypeError: Cannot read properties of undefined (reading 'componentType')

### ISSUE THREAD

**Issue by JasonDCrandall** [OfficeDev/TeamsFx#10452]
**Describe the bug**
When testing an application built using SPFx locally, it loads into teams and I am able to use and test the app as expected. This is done using the VS Code Teams Toolkit Preview function. When I provision it into my dev environment and try to preview it there, I get this error: Error details: Error: Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType')

**To Reproduce**
1. Select the dev environment on the left tab in Teams toolkit
2. Click Provision to ensure that it is provisioned
3. Click "Preview App" next to the dev environment

**Expected behavior**
The expected behavior is to see the app loaded in the dev environment, however when trying to preview the app it will only display this error. Previewing the app locally works fine

**Screenshots**
<img width="261" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/50968840/f4405b8a-cca2-4c83-afae-897aaa2c2eb5">
<img width="987" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/50968840/367e6e97-62d3-4f06-9856-5d3201f4d3de">

**VS Code Extension Information (please complete the following information):**
 - OS: macOS
 - Version v5.2.0

**CLI Information (please complete the following information):**

**Additional context**

**Comment by JasonDCrandall** [comment]
Alright I attempted to deploy it but it failed due to me not having enough permissions. I reached out to my admins and as I don't have the access required, I zipped the app package via this button in the teams toolkit:
<img width="302" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/50968840/ff4f79df-48a3-4ad5-b376-146ce539d355">
And then submitted the app to the or in the teams app store:
<img width="601" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/50968840/b2a6633f-bc87-4c4c-a65c-bb522d306ad7">
When they approved it we attempted to run the app but still got the same "Sorry, something went wrong error". Is there a step that i'm missing where I can build it on my machine and then submit it to admins to deploy the app?

**Comment by yuqizhou77** [comment]
Hi @JasonDCrandall could you confirm whether the issue you noticed during deploy is 'spfx/deploy.insufficientPermission'? If yes, then I think you will need ask for the permission to access sharepoint appcatalog from the admin. You could verify by visiting the appCatalog. The url should be something like "https://{your_tenant_name}.sharepoint.com/sites/appcatalog/SitePages/Home.aspx" and select 'try new new manage apps page'.

**Comment by JasonDCrandall** [comment]
That worked, thank you!
