### ISSUE TITLE
OOTB project template fails preflight request to local Azure Function app

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/TeamsFx#10493]
## Describe the bug
A new tab project, created using the **TypeScript** & **React with Fluent UI** template, fails with zero configuration after deploying (F5) due to a preflight error thrown when the persona all tries to call the Azure Function app.

This worked previously, verified with known working projects created ~2mo ago. But this same known working project fails with the exact same error.

## To Reproduce
1. Create new tab project using the **React with Fluent UI** & **TypeScript** option
2. Ensure TTK logged into the same tenant for M365 & Azure AD
3. F5 to start debugging
4. When the browser loads, open the **Dev Tools** => **Network** tab
5. Install the Teams app & launch the Personal app
6. Observe preflight errors in the **Network** tab both on initial load & when selecting the **Authorize Azure Function** button

## Expected behavior
No errors and retrieve the user's details from the included Azure Function

## Screenshots

<img width="956" alt="Screenshot 2023-12-06 at 9 37 04 AM" src="https://github.com/OfficeDev/TeamsFx/assets/2068657/da495ba7-a6bc-4f06-98c3-257e4215d653">

## VS Code Extension Information (please complete the following information):
 - OS: macOS
 - Version
   - OS: v14.1.2
   - VSCode 1.84.2
   - Teams Toolkit v5.2.0

## CLI Information (please complete the following information):
 - OS: macOS
 - Version: v2.0.2

**Comment by KennethBWSong** [comment]
@andrewconnell Thank you for using our Toolkit. I cannot reproduce your error with latest Teams Toolkit. Would you please help to share the detail error of the two `getUserProfile` calls in your image?

**Comment by andrewconnell** [comment]
Appears to be an issue with the setup... I'll close this as the RCA is somewhere else... (see #10785)
