### ISSUE TITLE
translate function with promptPreamble parameter

### ISSUE THREAD

**Issue by Githamza** [OfficeDev/TeamsFx#10507]
in translate function 
` translate(request: string, promptPreamble?: string | PromptSection[]): Promise<Result<T>>;`

the request parameter mandatory. 

If I would send a promptPreamble with system and user roles , what should I put in request param ? 

for me request param  is the user role content ?

what should I put in `request` param if I fill `promptPreamble`

**Comment by adashen** [comment]
Hi @Githamza  Thanks for reporting the issue. Can you provide more detail info about the repro steps so we can do the further investigation.
