### ISSUE TITLE
npm command not found after upgrading to v5.2.0

### ISSUE THREAD

**Issue by joshua-d-brown** [OfficeDev/TeamsFx#10520]
**Describe the bug**
I upgraded my TeamsFX Toolkit plugin to version 5.2.0 today. After I upgraded my project to work with the current version, I tried to run it locally by using F5, and I ran into a number of errors. I began to work through them all, but now I am stuck and don't know what to do. The error I'm getting is this:

> Error: Script ('npm install --no-audit') execution error: /bin/sh: npm: command not found

As you can see from the screenshot, npm is definitely installed in the working directory.
<img width="464" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/84351888/78ca2285-828f-4001-b7fc-974b64f1e024">

**Expected behavior**
I expect the app to run successfully, like it did before I upgraded the plugin and the project.

**VS Code Extension Information (please complete the following information):**
 - OS: macOS 14.1.1
 - Version 5.2.0

**CLI Information (please complete the following information):**

**Additional context**
I also had to comment out the node check in tasks.json, because it was also failing. Node is also definitely installed, but TeamsFX says it is not.

**Comment by Siglud** [comment]
Looks like your default shell is not `/bin/sh` , so the `npm` command cannot be found.

Please try to use the script driver and specify the `shell` arguments like this

```yaml
  - uses: script
    with:
     run:  npm install --no-audit
     workingDirectory: ./
     shell: /bin/zsh
```

You can find more detail in [this link](https://github.com/OfficeDev/TeamsFx/wiki/Available-actions-in-Teams-Toolkit#script)

**Comment by joshua-d-brown** [comment]
This did not work for me. "/bin/zsh" is not a valid value for the "shell" property and I got an "Unable to parse yaml file" error when I tried to build the project.

**Comment by joshua-d-brown** [comment]
Changing my default shell from "/usr/local/bin/zsh" to "/bin/zsh" solved my Node check and npm command issues, but now I'm getting another issue when the project tries to run that is probably not in scope of this question.
