### ISSUE TITLE
Unable to configure teams ReactJS Typescript Tab app with multi tenant SSO

### ISSUE THREAD

**Issue by asmiah** [OfficeDev/TeamsFx#10566]
**Describe the bug**

Error received:
POST https://login.microsoftonline.com/{tenantIdremoved}/oauth2/v2.0/token 400 (Bad Request)

The following although not the most clearest of steps, outlines the steps required to accommodate for multi tenant sign on capabilities:
https://github.com/OfficeDev/TeamsFx/wiki/Multi-tenancy-Support-for-Microsoft-Entra-app

**To Reproduce**

First I successfully followed this for MyOrg SSO to work:
https://github.com/OfficeDev/TeamsFx/wiki/Develop-single-sign-on-experience-in-Teams#teams-tab-app

To begin with, following exactly as advised attempting to "Provision" and "Deploy" your project after getting to the step of changing value of `m365TenantId` which is now actually called `aadAppTenantId`! :  in `azure.parameters.json` :
from your tenantId to "common" - when you attempt to provision you receive an error as below:

`Unable to execute action aadApp/update. Error message: {"error":{"code":"HostNameNotOnVerifiedDomain","message":"Values of identifierUris property must use a verified domain of the organization or its subdomain`

and so after much struggle, you have to ensure this is a custom domain, which is nowhere clearly described in the documentation!

To resolve this, you must amend your aad.manifest.json file and ensure that your `idenifierUris` either begins with:

`"identifierUris": [
        "https://yourcustomdomain.co.uk/${{AAD_APP_CLIENT_ID}}"
    ],`

or

`"identifierUris": [
        "api://yourcustomdomain.co.uk/${{AAD_APP_CLIENT_ID}}"
],`

Your app then successfully provisions.

You can then continue to deploy your app.

Now once deployed, if you fn+f5/hit f5 to run your app locally your app will compile and as long as this is the same domain the app is registered in you can successfully sign in and the welcome message will successfully obtain your name/successfully obtain your details in the welcome message:
![image](https://github.com/OfficeDev/TeamsFx/assets/11227108/a4235ae4-e804-4b42-b8db-6e81830060a7)

However if you then open a private window/a edge session with another M365 account logged in and upload your custom app via the zip file to point to the hosted application you receive error in the console and the username is not successfully received, meaning it was not able to retrieve your details:

POST https://login.microsoftonline.com/{tenantIdremoved}/oauth2/v2.0/token 400 (Bad Request)

The console error suggests rather than talking to the /common endpoint the app is not successfully obtaining authority from the correct endpoint as the error includes the tenant in the error. (this is my assumption due to the error, please correct me if I am wrong)

I am not sure where it is getting the tenantId from, are there vital steps missing from the documentation?

Does the useTeamsUserCredential() hook need to have injected in it the correct authority? Please explain as multi tenant is not working with your steps provided!

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/11227108/8f364f93-d697-4322-b83b-394dcd706e96)

**VS Code Extension Information (please complete the following information):**
I am using TeamsToolkit version: v5.4.0

**Comment by asmiah** [comment]
Hi @MuyangAmigo @KennethBWSong  - is there any update on this?

**Comment by KennethBWSong** [comment]
Hi @asmiah Thank you for using our toolkit. Would you please try to update the CORS settings in your Azure Function and allow access from your custom domain as following?
![image](https://github.com/OfficeDev/TeamsFx/assets/63089166/b8752659-1860-4805-bf91-e247912199da)
You can also update the bicep here to update the CORS settings:
![image](https://github.com/OfficeDev/TeamsFx/assets/63089166/48e8ecfd-efec-45bd-b9d1-5801839ae913)

**Comment by asmiah** [comment]
@KennethBWSong I am not using the Azure function, I've removed it from the project. This error is happening as soon as the debugging starts locally on my machine and so it's all local, it's not talking to an Azure function or anything in Azure for that matter.

**Comment by asmiah** [comment]
@KennethBWSong  - many thanks for looking into this and taking your time out to reply back to me. In an attempt to share with you some source code for you to test/replicate on your end it seems I have managed to get it working.

Here are the steps I took, I'd like to add, the thing I did different to the first approach was that I had created the CDN front door (in the multi tenant teamsfx documentation it advises this is optional).

Please go ahead and close this issue. Apologies for wasting your time.

**Comment by asmiah** [comment]
The solution was to ensure I create the CDN resource.
