### ISSUE TITLE
Possible Bug In Graph.razor -> GetOnBehalfOfCredential()

### ISSUE THREAD

**Issue by grumpykiwi** [OfficeDev/TeamsFx#10582]
**Describe the bug**

  var tenantId = config.TeamsFx.Authentication.OAuthAuthority.TrimStart("https://login.microsoftonline.com/".ToCharArray());

If the tenantId starts with (possibly just contains) the letter f, which mine does, the F will be removed in this call.

The following message will then appear 

OnBehalfOfCredential authentication failed: AADSTS900023: Specified tenant identifier '<tenant ID>' is neither a valid DNS name, nor a valid external domain. Trace ID: <redacted> Correlation ID: <redacted> Timestamp: 2023-12-24 17:26:17Z

**To Reproduce**
1. Create a new Teams Tab App with a Tenant ID that has a leading F
2. Prepare Teams App Dependencies
3. Run the App

**Expected behavior**
The user profile image should display instead of this error

**Screenshots**
See error message above

**VS Code Extension Information (please complete the following information):**
 - Windows 11 23H2
 - Visual Studio Pro 17.9.0 Preview 2

To get around the issue, I slightly modified the GetOnBehaldOfCredentials method in Graph.razor

```
    private async Task<OnBehalfOfCredential> GetOnBehalfOfCredential()
    {
        var config = Configuration.Get<ConfigOptions>();
        var length = config.TeamsFx.Authentication.OAuthAuthority.Length;
        var position = config.TeamsFx.Authentication.OAuthAuthority.IndexOf("m/") + 2;
        var tid = config.TeamsFx.Authentication.OAuthAuthority.Substring(position, length - position);
        var tenantId = config.TeamsFx.Authentication.OAuthAuthority.TrimStart("https://login.microsoftonline.com/".ToCharArray());

        AccessToken ssoToken = await teamsUserCredential.GetTokenAsync(new TokenRequestContext(null), new CancellationToken());
        return new OnBehalfOfCredential(
            //tenantId,
            tid,
            config.TeamsFx.Authentication.ClientId,
            config.TeamsFx.Authentication.ClientSecret,
            ssoToken.Token
        );
    }
```

**Comment by yiqing-zhao** [comment]
We appreciate your feedback, @grumpykiwi ! Our team is working hard to find and fix the issue. We will keep you posted on any progress we make.

**Comment by yjmrobert** [comment]
Just a heads up that I ran into the same issue creating off the template today. Looks like #10593 will solve it once that makes it way out.

For anyone else encountering the same issue, you can easily fix your file by going to `/Components/Graph.razor` and updating 

```csharp
var tenantId = config.TeamsFx.Authentication.OAuthAuthority.Trim("https://login.microsoftonline.com/".ToCharArray());
```
to

```csharp
var tenantId = config.TeamsFx.Authentication.OAuthAuthority.Substring("https://login.microsoftonline.com/".Length);
```

**Comment by yiqing-zhao** [comment]
Thanks @yjmrobert for noticing the issue! The fix will be included in the next VS preview release in mid January. Please keep an eye out for it!

**Comment by yiqing-zhao** [comment]
Hi @grumpykiwi and @yjmrobert, [Visual Studio 2022 version 17.9 Preview 3](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#1790-pre3--visual-studio-2022-version-179-preview-3) is available now, and it includes the bug fix. Feel free to share your feedback here if you still have any issues. Thanks! 😊
