### ISSUE TITLE
Sideloading Disabled within Teams Toolkit Extension

### ISSUE THREAD

**Issue by BoostN** [OfficeDev/TeamsFx#10629]
**Describe the bug**
I'm using the Teams Toolkit vscode extension and I'm getting the error "Sideloading Disabled".  I have used my company tenant (I'm the admin, confirmed app's can be manually uploaded, confirmed and ensured the access policy is open as well). I even stood up a E5 Developer Sandbox which tells you it's configured by default to be open, and when I sign in with that account, I have the same issue. 

**To Reproduce**
1) Sign up for a new E5 Dev Sandbox. 
2) Connect to that sandbox with the teams toolkit. 
3) Once you sign it, the Sideloading Disabled message appears

**Expected behavior**

**Screenshots**
![sideloadfailed](https://github.com/OfficeDev/TeamsFx/assets/6150217/b2ff8229-c6de-48b3-8f20-b98bc844d704)

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**
Version: 1.85.1 (user setup)
Commit: 0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
Date: 2023-12-13T09:49:37.021Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by marcel-zwopr** [comment]
@BoostN what was your solution? Having the same problem.
