### ISSUE TITLE
Graph permissions consent window after upgrading to TeamsFX 2.4.0 in multi-tenant app

### ISSUE THREAD

**Issue by robertstewartnz** [OfficeDev/TeamsFx#10701]
Hi there,

We have upgraded using the latest code snippets and Nuget packages Microsoft.TeamsFX 2.4.0, Microsoft.Graph 5.38.0. But I am getting a weird issue when I go to pop up the user consent for Graph permissions. Instead of opening the permissions window it is opening the another instance of the app where the permissions consent should be.

I have a multi tenant app so have configured  GetOnBehalfOfCredential() like this. Using "common" instead of my TenantId.

```
public async Task<OnBehalfOfCredential> GetOnBehalfOfCredential()
{           
            AccessToken ssoToken = await _teamsUserCredential.GetTokenAsync(new TokenRequestContext(null), new CancellationToken());
            
            return new OnBehalfOfCredential("common",
                Configuration.ClientId,
                Configuration.ClientSecret,
                ssoToken.Token
            );
}
```

In ConsentAndShow. The call to await _teamsUserCredential.LoginAsync(scope); is causing another instance of the app open, not the permissions window.

```
public async Task<bool> ConsentAndShow(string[] scope)
{
    try
    {
        await _teamsUserCredential.LoginAsync(scope);

        return true;
    }....
```

If I use an Admin account to grant consent in Azure Identity everything is fine, but I want to have the flexibility for users to consent too. Have you seen this behaviour?

**Comment by robertstewartnz** [comment]
I'm using Visual Studio 2022 Version 17.7.4

**Comment by KennethBWSong** [comment]
Hi @robertstewartnz  Thank you for using our Toolkit! Would you please help to verify "InitiateLoginEndpoint" in "./appsettings.json" or "./appsettings.develop.json" is correctly set to your login start page? You can simple open this url in browser and see whether this page will ask you to login.

**Comment by robertstewartnz** [comment]
@KennethBWSong Thanks. I just worked that out 5 minutes ago. Thanks this was the issue.
