### ISSUE TITLE
this App Cannot be Found - Teams, any new app

### ISSUE THREAD

**Issue by JohnGalt1717** [OfficeDev/TeamsFx#10733]
**Describe the bug**
Create new tab or other app in vs.net and run it so that it launches Teams. This message pops up when it tries to load the new manifest.

**To Reproduce**
1. Create a new Teams app (any kind) in Vs.net
2. Right Click and follow the instructions to Prepare Teams App Dependencies
3. Press F5.
4. Contrary to the instructions you don't get an add button, you just get the above error message.

**Expected behavior**
Should work according to the instructions

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/1868147/946f89ad-0010-4b56-ace7-951825ed4ed9)

**VS.NETExtension Information (please complete the following information):**
 - OS: Windows 11.
 - Version: 17.9.71.48084

**CLI Information (please complete the following information):**
 - OS: Windows
 - Version 3.0.0-alpha.ec50e3de8.0

**Additional context**
It did work the first time a while ago, but now does not, although periodically one attempt will work but then it fails again.
We are using the developer sandbox for deployment and the new app experience.

**Comment by JohnGalt1717** [comment]
Yes. It's there.  I think this might be a bug with "new" teams. When I switch back to classic it seems to work?

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/10283

**Comment by nliu-ms** [comment]
@JohnGalt1717  Yes exactly. This is a known issue for New Teams. We got updates that it will be rolled out and finally supported for General at the end of Feb. Sorry for the inconvenience, you can use classic Teams right now. I will get you updated.

**Comment by maryamariyan** [comment]
I am also hitting this issue, even when creating a new echo bot teams app using VS new project templates

F5 shows:
![image](https://github.com/OfficeDev/TeamsFx/assets/5897654/c8a594ee-4920-4560-ae7f-82d750b61b3b)

**Comment by maryamariyan** [comment]
> Yes. It's there. I think this might be a bug with "new" teams. When I switch back to classic it seems to work?

how do you switch to classic teams?

**Comment by blackchoey** [comment]
@maryamariyan tenant admin may disable Teams Classic so you might meet problems when switch back. Please refer the workaround in https://github.com/OfficeDev/TeamsFx/issues/10840 to upload your app manually.

**Comment by maryamariyan** [comment]
Here's what I did to get a workaround to this problem. Starting over altogether, I:

(as per usual)
- Open VS
- Set the teams app as startup
- Select existing or create new Dev Tunnel
- Right-Click Teams Toolkit > Prepare Teams App Dependencies
- F5

- (ignore and close the message popping up: app not found)
- Navigate to "apps" on the left hand side of Teams desktop application.
- Look for "manage your apps", at the bottom left side of the page that opens
- Click on "upload app"
- Navigate to `appPackage.local.zip` to upload the app manually

Then the teams bot app shows up and works as expected.

**Comment by blackchoey** [comment]
This issue is now fixed in New Teams. Please create new issue if you still meet problem.
