### ISSUE TITLE
bug report: AppStudioPlugin.DeveloperPortalAPIFailedError

### ISSUE THREAD

**Issue by minces92** [OfficeDev/TeamsFx#10747]
API call to Developer Portal failed: Error, Request failed with status code 404, API name: get-app-package, X-Correlation-ID: 114962bd-2413-44c9-8c10-a04427b85cc7. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: {"type":"https:/<REDACTED: user-file-path>

**Comment by nliu-ms** [comment]
Hey @minces92 , are you using the Teams Developer Portal Teams app? Can you please try the website: https://dev.teams.microsoft.com?

It's a known issue for the Teams app. I will close this one, let's reference to #10451
