### ISSUE TITLE
🐞 Docs/CLI incorrect - Creating Azure Function not possible

### ISSUE THREAD

**Issue by andrewconnell** [OfficeDev/TeamsFx#10795]
**Describe the bug**
Unsure what's correct/incorrect - readme for project template **Tab => React with Fluent UI** says:

> ### Add More Functions
> 
> - From Visual Studio Code, open the command palette, select `Teams: Add Resources` and select `Azure Function App`.
> - From TeamsFx CLI: run command `teamsfx resource add azure-function --function-name <your-function-name>` in your project directory.

The second bullet is incorrect:

- there's no `resource` command in teamsfx cli
- there's no `azure-function` option when using `teamsfx add`

So, either the docs are incorrect in the README.md, or there's something missing in the TeamsFX CLI

**To Reproduce**
1. Create new project using the template **Tab > React with Fluent UI**
1. Follow instructions in 2nd bullet point on line 43 to add a new Azure Function
1. See error

**Expected behavior**
No error... instructions are correct

**Screenshots**
n/a

**VS Code Extension Information (please complete the following information):**
 - OS: macos v14.12.1
 - Version v5.4.0

**CLI Information (please complete the following information):**
 - OS: macos v14.2.1
 - Version v2.1.1

**Comment by KennethBWSong** [comment]
@andrewconnell Thank you for using our Toolkit! Would you please help to verify whether your project is created by latest TTK? Current README.md should be same as [here](https://github.com/OfficeDev/TeamsFx/blob/dev/templates/js/sso-tab-with-obo-flow/README.md). We used to support `teamsfx resource add azure-function` command previously, and now they are removed from latest CLI.

**Comment by andrewconnell** [comment]
Yup, created using TTK v5.4 in the last 2w

The template you linked to has the error as well (as does the TypeScript version). Will submit PR to fix...

See: https://github.com/OfficeDev/TeamsFx/blob/dev/templates/js/sso-tab-with-obo-flow/api/README.md?plain=1#L43

**Comment by MuyangAmigo** [comment]
> Yup, created using TTK v5.4 in the last 2w.
> 
> The template you linked to has the error as well (as does the TypeScript version). Will submit PR to fix...
> 
> There's no error in the README you referenced, it's in the Azure Function's README.
> 
> See: https://github.com/OfficeDev/TeamsFx/blob/dev/templates/js/sso-tab-with-obo-flow/api/README.md?plain=1#L43

Thanks @andrewconnell - we missed the README under `api` folder. Also thanks for fixing it!
