### ISSUE TITLE
Download files using Teams SDK

### ISSUE THREAD

**Issue by gabbsmo** [OfficeDev/TeamsFx#10813]
**Is your feature request related to a problem? Please describe.**
File downloads are hard in Teams apps because of the restrictions in embedded web browsers/Electron apps. There are numerous security and cross browser quirks to consider.

**Describe the solution you'd like**
I wish that there was methods in the SDK for starting a user friendly file download experience in the Teams apps. Some possible parameters are:
* A blob. Imagine a image editor in Teams that allows you to download the result from a canvas element.
* A URL to an already existing file in SharePoint Online.
* A URL to a file publicly available on the Internet.

**Additional context**
Saving blobs using FileSaver.js used to work in old Teams app, but no longer works correctly in new Teams. The first file will be downloaded, but subsequent downloads are blocked.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/10334

**Comment by adashen** [comment]
let track in the upstream issue and close here.
