### ISSUE TITLE
CredentialInvalidLifetimeAsPerAppPolicy error when creating new Microsoft Entra (AAD) app with client secret

### ISSUE THREAD

**Issue by blackchoey** [OfficeDev/TeamsFx#10905]
If your tenant admin created policy to restrict the max lifetime of a Microsoft Entra (AAD) app, you may meet following error from `aadApp/create` and `botAadApp/create` action

{"error":{"code":"CredentialInvalidLifetimeAsPerAppPolicy","message":"Credential lifetime exceeds the max value allowed as per assigned policy 'xxx'.","details":[{"code":"InvalidKeyEndDate","message":"Credential lifetime exceeds the max value allowed as per assigned policy 'xxx'."

VS Code Teams Toolkit v5.6.0 fixes this issue. Please upgrade to the latest version and try again.

~~Workaround~~
~~If you get this error from aadApp/create action, follow [Use an existing Microsoft Entra app for your Teams app](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code-v5#use-an-existing-microsoft-entra-app-for-your-teams-app) to create an app by yourself and use it in your project.~~

~~If you get this error from botAadApp/create action, follow [Use an existing Microsoft Entra app for your bot](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code-v5#use-an-existing-microsoft-entra-app-for-your-bot) to create an app by yourself and use it in your project.~~

**Comment by gupta-lakshay** [comment]
Yes, I am also facing the same error since last week. Initially error was around Client secrets are blocked by a tenant-wide policy. Contact your tenant administrator for more information. and then Credential lifetime exceeds the max value allowed as per assigned policy '538f1913-366a-440a-95a0-e195cb55b282'. If I try and create the app registration manually and bypass this step, it is getting stuck at arm deploy step of teamsapp.yml with error  (×) Error: arm/deploy failed.
    (×) Error: Cannot redefine property: stack

**Comment by blackchoey** [comment]
The error details is not displayed in the log. Can you try to replace the parameters in `infra/azure.parameters.json` with real value (remember to backup the file), deploy `infra/azure.bicep` along with the parameter file to same resource group using Azure CLI, and share the errors here? So I can provide solutions for the error you meet.
Here's the doc to deploy ARM template using Azure CLI: https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-cli

**Comment by gupta-lakshay** [comment]
It is working fine with deployment using azure bicep, but causing some authentication errors from bot framework. As a work around for local and dev development we used the https://github.com/OfficeDev/TeamsFx/blob/dev/packages/cli/CONTRIBUTING.md locally as it having a fix for the issue

**Comment by blackchoey** [comment]
VS Code Teams Toolkit v5.6.0 fixes this issue. Please upgrade to the latest version when meet this problem.
