### ISSUE TITLE
Axios dependency with very old version

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/TeamsFx#10937]
We are getting security vulnerability alerts from our dependency scanner regarding: @fluidframework/azure-client/1.1.1 (uses axios 0.21.4) @fluidframework/driver-utils/1.3.7 (uses axios 0.26.1) @fluidframework/server-services-client/0.1036.5001 (uses axios 0.26.1) @fluidframework/test-runtime-utils/1.3.7 (uses axios 0.26.1) 

@microsoft/teamsfx/2.3.0 (uses axios 0.27.2) 

Do you know if these packages plan to update their axios dependency? 
0.2x is more almost 2 years old now

**Comment by jayzhang** [comment]
Thanks for reporting. We will fix this in the next release.

**Comment by jayzhang** [comment]
@SubbaReddi We released a new version of TTK, could please confirm that the issue is resolved?
