### ISSUE TITLE
Build started failing

### ISSUE THREAD

**Issue by frontendphil** [OfficeDev/TeamsFx#11057]
**Describe the bug**
Our builds started failing when the new version `@microsoft/teamsapp-cli` was published. We're seeing this error, when running `teamsapp pakcage`.

![CleanShot 2024-03-12 at 11 39 25](https://github.com/OfficeDev/TeamsFx/assets/187786/1188f2c7-a0b8-4976-bebf-2d77865bcc50)

**To Reproduce**
1. Open a project
2. Run `teamsapp package`

**Expected behavior**
The `env` input should not be mandatory (at least not according to the docs)

**Screenshots**
See above

**VS Code Extension Information (please complete the following information):**
 - OS: MacOS 14.2.1 (23C71), Linux (Docker tag: `node:21.6.2-alpine3.18`)

**Additional context**
Builds started failing in the last hour. We're always using the latest version of this package in our pipeline.

**Comment by jayzhang** [comment]
@frontendphil Thanks for reporting. For a newly created project, the error is shown when there are some placeholders in the `./appPackage/manifest.json` that need to be resolved. You can run `teamsapp provision` first to resolve the placeholders or fill in them manually in the `manifest.json`. BTW, the error message should be more clear to understand.
