### ISSUE TITLE
Cannot provision with existing app ID

### ISSUE THREAD

**Issue by alex-c-wilson** [OfficeDev/TeamsFx#11078]
Cannot provision with existing app ID

**To Reproduce**
1. Go to VS Code
2. Click on Provision in Teams Toolkit 5
3. View error log
[2024-03-14T05:10:32.707Z] [Info] - Current VS Code locale is: en-us
[2024-03-14T05:10:37.315Z] [Info] - Teams Toolkit extension is now active!
[2024-03-14T05:12:42.804Z] [Info] - Executing provision 

Lifecycle stage: provision(7 step(s) in total). The following actions will be executed: 
(1/7) Action teamsApp/create: create a Teams app.
(2/7) Action botAadApp/create: create a new or reuse an existing bot Microsoft Entra app.
(3/7) Action arm/deploy: Deploy the given ARM templates to Azure.
(4/7) Action teamsApp/validateManifest: validate a Teams
[IndiePID.zip](https://github.com/OfficeDev/TeamsFx/files/14597006/IndiePID.zip)
 app.
(5/7) Action teamsApp/zipAppPackage: build a Teams app package.
(6/7) Action teamsApp/validateAppPackage: validate a Teams app.
(7/7) Action teamsApp/update: update a Teams app.

[2024-03-14T05:12:42.808Z] [Info] - Executing lifecycle provision
[2024-03-14T05:13:35.439Z] [Error] - Failed to Execute lifecycle provision due to failed action: teamsApp/create. TeamsAppCreateConflictWithPublishedApp:A Teams app with that id already exists in your organization's app store. Manually update the app id and try again.. Env output: {}
[2024-03-14T05:13:35.453Z] [Info] - Execution summary:

Summary:
(×) Error: Lifecycle stage provision failed.
  (×) Error: teamsApp/create failed.
    (×) Error: A Teams app with that id already exists in your organization's app store. Manually update the app id and try again.
  (!) Warning: botAadApp/create was not executed.
  (!) Warning: arm/deploy was not executed.
  (!) Warning: teamsApp/validateManifest was not executed.
  (!) Warning: teamsApp/zipAppPackage was not executed.
  (!) Warning: teamsApp/validateAppPackage was not executed.
  (!) Warning: teamsApp/update was not executed.

[2024-03-14T05:13:36.235Z] [Error] - code:AppStudioPlugin.TeamsAppCreateConflictWithPublishedApp, message: A Teams app with that id already exists in your organization's app store. Manually update the app id and try again.
 Help link: https://aka.ms/teamsfx-actions/teamsapp-create

**Comment by nliu-ms** [comment]
Hey @alex-c-wilson, based on the error message `A Teams app with that id already exists in your organization's app store.`, you cannot create a Teams app using the same app id that already exists in the tenant app catalog.

Can you please check if you can find the existing app in [Teams Developer Portal](https://dev.teams.microsoft.com/apps)? I'm wondering if you're the owner of that app.

**Comment by nliu-ms** [comment]
Hey @alex-c-wilson , then it is by design. You have to be either the app owner, or the tenant Teams admin to use the existing app id. Otherwise you cannot overwrite an existing app.

**Comment by nliu-ms** [comment]
@alex-c-wilson , are you previously the owner of this app? If so, have you removed the app from Teams Developer Portal?

1) As you cannot see the app in Teams developer Portal, does anyone in your team has the ownership of it? You can use this app id when you're added as the owner.
2) Or if you're the Teams tenant admin, you can overwrite an existing app as well.
