### ISSUE TITLE
Graph API Works well in Sharepoint Site but same webpart not working in Teams App. Error : Token request previously failed

### ISSUE THREAD

**Issue by paraggin** [OfficeDev/TeamsFx#11121]
Graph API Permitted from the Admin side and Working well in Sharepoint site page..but same webpart not working in Teams app only..
Error :  Token request previously failed
I am using user group list api which is permitted by admin.

![image](https://github.com/OfficeDev/TeamsFx/assets/107133664/ce443248-93aa-45b8-a7f0-89bb844897cf)

**Comment by yuqizhou77** [comment]
Could you share the content of your Teams manifest file?

**Comment by paraggin** [comment]
**Manifest.json** 
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
  "manifestVersion": "1.16",
  "packageName": "com.microsoft.teams.extension",
  "id": "${{TEAMS_APP_ID}}",
  "version": "1.29.10",
  "developer": {
    "name": "SPFx + MultiTab",
    "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
    "privacyUrl": "https://privacy.microsoft.com/en-us/privacystatement",
    "termsOfUseUrl": "https://www.microsoft.com/en-us/servicesagreement"
  },
  "name": {
    "short": "Vera",
    "full": "Full name for Vera"
  },
  "description": {
    "short": "Short description of Vera",
    "full": "Full description of Vera"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "accentColor": "#004578",
  "staticTabs": [
    {
      "entityId": "635e5f16-253b-42cf-85ab-fb92b253be6e",
      "name": "LazardGPT",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=635e5f16-253b-42cf-85ab-fb92b253be6e%26forceLocale={locale}",
      "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "8bbc4d2e-69f0-41e3-af43-3588b5319ac3",
      "name": "CorpApps",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=8bbc4d2e-69f0-41e3-af43-3588b5319ac3%26forceLocale={locale}",
      "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "061890ae-4b2e-48a0-b9ef-b1b60a8326a8",
      "name": "Purchase Order",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=061890ae-4b2e-48a0-b9ef-b1b60a8326a8%26forceLocale={locale}",
      "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "a67cd840-a30a-431f-ac19-4ac42a0189b5",
      "name": "IT-Budgeting",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=a67cd840-a30a-431f-ac19-4ac42a0189b5%26forceLocale={locale}",
      "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "06af8726-7b1a-46db-a9cd-92ee393e06c2",
      "name": "Test",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=06af8726-7b1a-46db-a9cd-92ee393e06c2%26forceLocale={locale}",
      "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
      "scopes": [
        "personal"
      ]
    },
    {
      "entityId": "60247c7e-c092-4102-aa14-0e9f393ad83c",
      "name": "Calendar",
      "contentUrl": "https://{teamSiteDomain}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest=/_layouts/15/teamshostedapp.aspx%3Fteams%26personal%26componentId=60247c7e-c092-4102-aa14-0e9f393ad83c%26forceLocale={locale}",
      "websiteUrl": "https://products.office.com/en-us/sharepoint/collaboration",
      "scopes": [
        "personal"
      ]
    }
  ],
  "configurableTabs": [
    {
      "configurationUrl": "https://{teamSiteDomain}{teamSitePath}/_layouts/15/TeamsLogon.aspx?SPFX=true&dest={teamSitePath}/_layouts/15/teamshostedapp.aspx%3FopenPropertyPane=true%26teams%26componentId=aa41b079-cf04-49db-a6d0-f17a7f517de4%26forceLocale={locale}",
      "canUpdateConfiguration": true,
      "scopes": [
        "team"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "*.login.microsoftonline.com",
    "*.sharepoint.com",
    "*.sharepoint-df.com",
    "spoppe-a.akamaihd.net",
    "spoprod-a.akamaihd.net",
    "resourceseng.blob.core.windows.net",
    "msft.spoppe.com"
  ],
  "webApplicationInfo": {
    "resource": "https://{teamSiteDomain}",
    "id": "00000003-0000-0ff1-ce00-000000000000"
  }
}

**package-solution.json**

{
  "$schema": "https://developer.microsoft.com/json-schemas/spfx-build/package-solution.schema.json",
  "solution": {
    "name": "vera-client-side-solution",
    "id": "b403259b-7eca-417e-80a6-cc7f15a6a086",
    "version": "1.0.0.0",
    "includeClientSideAssets": true,
    "skipFeatureDeployment": true,
    "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Group.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "Directory.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "GroupMember.Read.All"
      },
      {
        "resource": "Microsoft Graph",
        "scope": "User.Read"
      }
    ],
    "isDomainIsolated": false,
    "developer": {
      "name": "",
      "websiteUrl": "",
      "privacyUrl": "",
      "termsOfUseUrl": "",
      "mpnId": "Undefined-1.15.2"
    },
    "metadata": {
      "shortDescription": {
        "default": "Vera description"
      },
      "longDescription": {
        "default": "Vera description"
      },
      "screenshotPaths": [],
      "videoUrl": "",
      "categories": []
    },
    "features": [
      {
        "title": "vera Feature",
        "description": "The feature that activates elements of the vera solution.",
        "id": "c963868a-0e3a-4162-8468-b454c5a2aec6",
        "version": "1.0.0.0"
      }
    ]
  },
  "paths": {
    "zippedPackage": "solution/vera.sppkg"
  }
}

**Comment by yuqizhou77** [comment]
Seems relevant to issues reported to SPFx side https://github.com/SharePoint/sp-dev-docs/issues/9493. Could you check if this would help?
