### ISSUE TITLE
Python SSO: AttributeError: 'CloudAdapter' object has no attribute 'exchange_token'

### ISSUE THREAD

**Issue by sarhaan7** [OfficeDev/TeamsFx#11167]
Using Python for MS Teams bot with SSO, installed using instructions 'Using the SDK locally` in `https://github.com/microsoft/botbuilder-python` README

## Describe the bug
SSO for singe tenant with Cloud Adapter does not work in Teams web/desktop client. Works in Web Chat.

## To Reproduce
1. Install the repo
2. Enable SSO using `https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-bots-with-sso?source=recommendations&tabs=ngrok&tutorial-step=4`
3. Upload Manifest and try sending a message to the bot

## Expected behavior
SSO was working as of last week but is not working anymore. There was a bot infra outage a few days ago that caused an error when uploading `manifest.json` on the web/desktop app. Could it be related to that?

## Additional context
Fails here:
```
 elif not getattr(context.adapter, "exchange_token"):
                # Token Exchange not supported in the adapter.
                await context.send_activity(
                    self._get_token_exchange_invoke_response(
                        int(HTTPStatus.BAD_GATEWAY),
                        "The bot's BotAdapter does not support token exchange operations."
                        " Ensure the bot's Adapter supports the ExtendedUserTokenProvider interface.",
                    )
                )
```
in `botbuilder-python/libraries/botbuilder-dialogs/botbuilder/dialogs/prompts/oauth_prompt.py`

**Comment by blackchoey** [comment]
@sarhaan7 can you share which Python project are you trying to update to enable SSO? The link you provided seems for C#.

**Comment by sarhaan7** [comment]
i was able to fix it, thanks!
