### ISSUE TITLE
update markdown-it to version 13.0.2

### ISSUE THREAD

**Issue by mehradrafigh** [OfficeDev/TeamsFx#11206]
**Is your feature request related to a problem? Please describe.**
Please update the `markdown-it` package to `v13.0.2`. I wanted to create a PR, but there is no contribution guideline for `adaptivecards-tools-sdk` package

**Describe the solution you'd like**
`markdown-it` package is updated from `12.3.2` to `13.0.2`

**Describe alternatives you've considered**
---

**Additional context**
---

**Comment by yukun-dong** [comment]
Hi @mehradrafigh,
Could you please provide the reason of updating to 13.0.2? Is it related to below issue?
![image](https://github.com/OfficeDev/TeamsFx/assets/25220706/cae49ed4-dd6c-4933-83a2-f4609178059e)

**Comment by mehradrafigh** [comment]
Hi @yukun-dong, the fixed crash/infinite loop is the reason

**Comment by yukun-dong** [comment]
Hi @mehradrafigh 
Thanks for the info. We will update this.

**Comment by mehradrafigh** [comment]
Thanks @yukun-dong. Really appreciate this :)

**Comment by mehradrafigh** [comment]
@yukun-dong, can you please give a timeframe for when the update will be published to npm?
