### ISSUE TITLE
When Save Project After F5 It shows error :  'Heap out of memory'

### ISSUE THREAD

**Issue by paraggin** [OfficeDev/TeamsFx#11215]
When Save Project After F5 It shows error :  'Heap out of memory'

**Comment by qinezh** [comment]
@paraggin can you please share with more details about the repro steps and error call stack so that we can dig into it?

**Comment by paraggin** [comment]
![image](https://github.com/OfficeDev/TeamsFx/assets/107133664/e45a36ed-ed57-4dbb-9351-dcb871e55a99)

While running the project and after editing file and after saving above error will arise

**Comment by qinezh** [comment]
@paraggin Looks it's a react tab app, and `gulp serve` is running during F5. Is your project scaffolded from Teams Toolkit template or sample apps? If so, can you please share which template or sample app you're using?
