### ISSUE TITLE
Unable to execute dev tunnel operation 'create'. Tunnel service returned status code: 403 Forbidden

### ISSUE THREAD

**Issue by ashlytom** [OfficeDev/TeamsFx#11275]
**Describe the bug**
I am unable to run the debug operation in Teams toolkit. I have create a testing account for running debug code. The account has custom app upload capability. But im getting this error constantly. It has only started recently, I had tried the same a month back and it was working fine. 

Summary:

(×) Error: Unable to execute dev tunnel operation 'create'. Tunnel service returned status code: 403 Forbidden

Visit https://aka.ms/teamsfx-local-tunnel-task to learn more about 'Start local tunnel' task.

[2024-04-03T06:38:17.984Z] [Error] - code:Ext.DevTunnelOperationError, message: Unable to execute dev tunnel operation 'create'. Tunnel service returned status code: 403 Forbidden
 Help link: https://aka.ms/teamsfx-local-tunnel-task

**To Reproduce**
1. Go to 'Local Debug(Chrome)'
2. Once the prerequiste tests are run, the dev tunnel service starts
3. Error happens

**Expected behavior**
Tunnel should be automatically relates and Dev Teams should open up browser

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/65658907/adbe81e5-5848-406e-b1a5-96cf2ef9fb1b)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10 pro  OS Build: 19045.4046
 - Version : February 2024 (version 1.87)

**CLI Information (please complete the following information):**
 - OS: not installed
 - Version : not installed

**Additional context**

**Comment by XiaofuHuang** [comment]
@ashlytom 
Could you try to initiate the dev tunnel CLI? Did this issue occur when you used the dev tunnel CLI directly?

 - Install [dev tunnel cli](https://aka.ms/teamsfx-install-dev-tunnel).
 - Login with your M365 Account using the command `devtunnel user login`.
 - Start your local tunnel service by running the command `devtunnel host -p 3978 --protocol http --allow-anonymous`.
 - In the `env/.env.local` file, fill in the values for `BOT_DOMAIN` and `BOT_ENDPOINT` with your dev tunnel URL.
    ```
    BOT_DOMAIN=sample-id-3978.devtunnels.ms
    BOT_ENDPOINT=https://sample-id-3978.devtunnels.ms/
    ```
- Remove `"Start local tunnel"` task in `tasks.json`
- Press F5 to start again

**Comment by ashlytom** [comment]
@XiaofuHuang 
Yes, the issue is happenning even after using the dev tunnel

![image](https://github.com/OfficeDev/TeamsFx/assets/65658907/828be130-772f-4faa-88c9-18d00aae194f)

**Comment by XiaofuHuang** [comment]
@ashlytom Are you using any proxy server?

**Comment by ashlytom** [comment]
No @XiaofuHuang.
There is no proxy server involved here. I think there is something wrong with the ngrok binary package. Is there a way to test it?

**Comment by XiaofuHuang** [comment]
@ashlytom We've used the dev tunnel instead of ngrok in Teams Toolkit V5. Given that the dev tunnel CLI isn't functioning in your environment, it's likely the root cause lies within the dev tunnel.
This issue has been copied over to dev tunnel repo here: https://github.com/microsoft/dev-tunnels/issues/436

**Comment by ashlytom** [comment]
@XiaofuHuang Thank you. It was an issue caused due to the firewall on the system i was working with. Once the API within devtunnel host was whitelisted, it started working again.
