### ISSUE TITLE
getPagedInstallations() returning empty array

### ISSUE THREAD

**Issue by Kalyan492** [OfficeDev/TeamsFx#11281]
Hi,

   I am trying to send a proactive message to a user / channel. For this I am using a function app http trigger to check for installations. But I am getting empty array for installations. I have installed the bot in a Teams channel.
   I have a basic bot deployed in Azure app service and trying to send notification to channel using the bot (code for sending notification is in function app http trigger). Why am I getting empty array for installations, although I have added the bot to a channel?

 
Thanks

**Comment by qinezh** [comment]
@Kalyan492 would you please provide with a minimal repro steps? Like the Teams Toolkit version, TeamsFx SDK version and the app template you used. And does it work when you debug it locally (with the debug option `Debug in Teams` of Teams Toolkit)?
