### ISSUE TITLE
Error: botFramework/create failed

### ISSUE THREAD

**Issue by nicodecleyre** [OfficeDev/TeamsFx#11397]
**Describe the bug**
Unable to create the botFramework when using the Teams Toolkit CLI

**To Reproduce**
1. Create a basic bot
`teamsapp new`
? New Project Bot
? App Features Using a Bot Basic Bot
? Programming Language TypeScript
? Directory where the project folder will be created in ./
? Application name MyBasicBot
2.  `cd .\MyBasicBot\`
3.  `teamsapp provision --env local`
4. Error showing:
Executing action botFramework/create in lifecycle provision
Unresolved placeholders(BOT_ENDPOINT) found for Action botFramework/create in lifecycle provision
(×) Error: Failed to Execute lifecycle provision because there are unresolved placeholders ["BOT_ENDPOINT"] for action: botFramework/create. Env output...

**Expected behavior**
Bot should be created

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/35696168/46b9e881-9cad-469d-8159-b5426d2a280d)

**CLI Information (please complete the following information):**
 - OS: Windows 11
 - Cli Version 3.0.0

**Additional context**
- i'm using global admin
- using teams toolkit in visual studio code just works and from there the bot is created
- When using the cli, the Entra app registration is created but it fails to create the bot in https://dev.botframework.com/bots/

**Comment by jayzhang** [comment]
@nicodecleyre Thanks for reporting. Debugging a bot locally needs local tunnel launched, which is integrated in VS Code debug configurations. If you want to provision in CLI, you need do some extra steps described in this doc: https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local?tabs=cli
