### ISSUE TITLE
Import flow in TTK, is pointing to Devpreview schema url with incorrect schema version (raw.githubusercontent.com) 

### ISSUE THREAD

**Issue by therealjohn** [OfficeDev/TeamsFx#11448]
Create an Outlook project using yo office command, with xml manifest 
Go to TTK and try to import the project created
Check the converted manifest file.

`"$schema": "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json#",
    "manifestVersion": "devPreview",`

So even for devpreview version, the schema URL should be 
`https://developer.microsoft.com/json-schemas/teams/vDevPreview/MicrosoftTeams.schema.json`

**Comment by jayzhang** [comment]
The `manifest.json` file is generated by **office-addin-project** package.
By using **office-addin-project@0.7.0**, the output schema url is: "https://raw.githubusercontent.com/OfficeDev/microsoft-teams-app-schema/preview/DevPreview/MicrosoftTeams.schema.json#"
By using **office-addin-project@0.8.1**, the schema url is: `https://developer.microsoft.com/json-schemas/teams/v1.17/MicrosoftTeams.schema.json#`.
So maybe @millerds can answer this question?

**Comment by therealjohn** [comment]
@jayzhang Confirmed with the team that we want it to point to 1.17, so to answer your question: Use office-addin-project@0.8.1.

**Comment by jayzhang** [comment]
@therealjohn Yes. The fix will be in the next release.
