### ISSUE TITLE
I am using teams tabs and I am navigating to web app on click of button, Once Navigated to browser when we come back to teams desktop app , page goes blank.

### ISSUE THREAD

**Issue by VKZycus** [OfficeDev/TeamsFx#11447]
I am using teams tabs,  and I am navigating to web app on click of button, Once Navigated to browser when we come back to teams desktop app , page goes blank.This happens only in desktop version of teams and on browser teams its working fine.

 function openInNewTab(url) {
    const win = window.open(url, '_blank');
    win.focus();
  }

I am using the above function to open url.It uses default browser and opens the link. but when we go back to tab , screen goes white.

You have Microsoft Teams version 24074.2323.2827.4973.
![image](https://github.com/OfficeDev/TeamsFx/assets/104554101/ccf7d121-0e16-4262-bd6f-b7fe45884f9b)

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/10805

**Comment by adashen** [comment]
Let's track in the upstream issue and close here.
