### ISSUE TITLE
Error when debugging Teams bot from workspace root

### ISSUE THREAD

**Issue by amsoedal** [OfficeDev/TeamsFx#11587]
**Describe the bug**
I have a project with this structure: 
```
- root
    - .vscode
    - TeamsBot
        - .vscode
    - WebApi
        - .vscode
```
When I try to run the launch settings I configured at the root of the project, "Deploy (Test Tool)" fails with this error: 

![image](https://github.com/OfficeDev/TeamsFx/assets/13313748/2b8b6e80-8c24-4056-9c0a-6f2d10f400be)

**To Reproduce**
1. Open root directory in VS Code
2. Ensure Teams Toolkit extension is active
3. Try to run the "Deploy (Test Tool)" task from the command palette using "Tasks: Run Task"

**Expected behavior**
I would expect debugging to work from the root of the workspace. I've adapted all the launch configurations that came with the Teams bot to have the appropriate file paths (e.g. from `"cwd": "${workspaceFolder}"` to `"cwd": "${workspaceFolder}/Teams"`). Is there some limitation I'm not aware of?

**Screenshots**

![image](https://github.com/OfficeDev/TeamsFx/assets/13313748/bd60b153-fe3d-44ac-b523-a2fffed5a298)

**VS Code Extension Information (please complete the following information):**
 - OS: Microsoft Windows 11 Enterprise
 - Version: 1.89.1
 - Extension version: v5.6.0

**Additional context**
The problem only reproduces if I never debug through the Teams folder. If I first open the Teams folder and run from there, I can still debug because the test tool symlink/artifacts get set up under the devTools folder. However I would really like this to work from the root on a clean project setup.

**Comment by qinezh** [comment]
Hi @amsoedal, the error occurs because the workspace folder (`root` in your case) is not a valid teamsfx project. Currently, it's not supported yet to run VS Code Task of `teamsfx` type inside a non-teamsfx project.

In your case, you may consider moving the `WebApi` folder into the `TeamsBot` folder, then debugging from the `TeamsBot` folder.

**Comment by amsoedal** [comment]
Thank you for the reply!
