### ISSUE TITLE
Need a migration tool

### ISSUE THREAD

**Issue by sffamily** [OfficeDev/TeamsFx#1188]
I have existing web apps deployed, would like to have a tool or feature to directly open, import, and convert my existing web app into a Teams app, with minimal code or configuration change.

Ideally if it can help me to connect the tenant AAD identities between Teams account and my existing web app, and enable SSO, that would be awesome!

**Comment by zhenyasav** [comment]
What tech is your existing web app running? How is it hosted?

**Comment by adashen** [comment]
Close the testing issue.

**Comment by MuyangAmigo** [comment]
"Test some bot features on Github Notification", please ignore.
