### ISSUE TITLE
Several developers want to develop. How do I set up to develop one App with multiple IDs?

### ISSUE THREAD

**Issue by Ufarufa** [OfficeDev/TeamsFx#1236]
Hello ~!! 
thank you so much to develop team toolkit.
Several developers want to develop together. How do I set up to develop one App with multiple IDs?
I don't have MPN.
so I can't use multi tenant.
How do I set up the toolkit in order for multiple developers to develop without MPN?

thank you

**Comment by adashen** [comment]
@Ufarufa Thank you very much for the feedback. Can you give more information about "MPN" and the scenario?
The app registered by toolkit is single tenant. So it would be great if we could have know more of your scenario :).

For now  there is a way to collaborate and working on one app with one ID https://github.com/OfficeDev/TeamsFx/blob/dev/docs/vscode-extension/collaborating.md 

Please let us know if it could help and looking forward to the more detail information.

**Comment by Ufarufa** [comment]
@adashen 
I tried it by referring to the document below.
Others running it locally succeeded.
