### ISSUE TITLE
Include Configuration Schemas in Documentation

### ISSUE THREAD

**Issue by wimichel** [OfficeDev/TeamsFx#1238]
I am trying to deploy a bot configured on the old teams toolkit. I cannot find the documentation on what configurations need to be supplied in order to connect to my existing resources.  To mitigate, I provisioned to a different subscription and tried to splice the generated configuration file with my existing resources. 

If there was a template or documentation around the configuration schema, I wouldn't have to try to reverse engineer my way to deployment.

**Comment by zhenjiao-ms** [comment]
Thanks @wimichel for the great suggestion. We will add the document of the configuration file soon, and then provide the link here.

**Comment by jayzhang** [comment]
@wimichel here is the doc for config file schema: https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/config.md

**Comment by MSFT-yiz** [comment]
I'll go ahead and close the issue. Please let us know if there're more questions/feedback. Thanks for your support.
