### ISSUE TITLE
Visual Studio multi account/tenant connection info

### ISSUE THREAD

**Issue by thomyg** [OfficeDev/TeamsFx#1247]
If you have multiple users configured in Visual Studio that are connected to different Azure/M365 tenants, it would be helpful to print out the user or tenant name in the initial output form "Configure for SSO". 

![initial output](https://user-images.githubusercontent.com/10920072/120205573-63942400-c22a-11eb-8623-ea6648504b37.png)

The used tenant is visible as the URL parameter of OAUTH_AUTHORITY, but I assume novice users who have multiple tenants might be supported if you just print the name/email of the user you used to connect to the tenant.  

It took me a couple of minutes to find out where the app was deployed because the authentication window was visible for a second and closed. After that, I had no idea what tenant connection was used by the wizard.

**Comment by JerryYangKai** [comment]
Thanks @thomyg for the great suggestion. 
@therealjohn Could you please take a look at this improvement?

**Comment by therealjohn** [comment]
This is now fixed in 0.1.48.43394 available on the Marketplace.

**Comment by thomyg** [comment]
Thank you! That really helps!

![image](https://user-images.githubusercontent.com/10920072/121400361-c9ce2480-c957-11eb-8d3a-8c32de95b9db.png)
