### ISSUE TITLE
How to remove "Teams Toolkit" from VS code

### ISSUE THREAD

**Issue by Ofer-Gal** [OfficeDev/TeamsFx#1262]
Since I do not do any teams development yet, the initial load of Teams Toolkit in the terminal gets in the way of my work.
How can I remove it for now?
Sorry I now found it in the installed extensions.

**Comment by JohnJonnyJonson** [comment]
How to uninstall, no solution is documented anywhere.... how do I get rid of teams toolkit. it is blocking my normal powershell scripts I want to develop.
