### ISSUE TITLE
Link to documentation not working

### ISSUE THREAD

**Issue by OskarNet** [OfficeDev/TeamsFx#1271]
On your main page under the Getting Started header there is a link "the documentation" which is not working.

**Comment by qinezh** [comment]
Thanks @OskarNet , I just created a PR to fix the link. Meanwhile, you could go to https://aka.ms/teamsfx-docs for the documentation.

**Comment by OskarNet** [comment]
> Thanks @OskarNet , I just created a PR to fix the link. Meanwhile, you could go to https://aka.ms/teamsfx-docs for the documentation.

That was quick :)

**Comment by qinezh** [comment]
Closed this issue as the PR #1272 is merged.
