### ISSUE TITLE
Launch Remote (Edge) Fails With MissingStep

### ISSUE THREAD

**Issue by WilliamMichelMSFT** [OfficeDev/TeamsFx#1274]
When attempting to run Launch Remote (Edge) I get the below errors that my app hasnt been provisioned or deployed. 

![image](https://user-images.githubusercontent.com/82683212/120697778-ff0fd980-c462-11eb-9132-df1d27c50999.png)

![image](https://user-images.githubusercontent.com/82683212/120697829-0d5df580-c463-11eb-929e-03039f307a3e.png)

The issue persists even after running the required commands

![image](https://user-images.githubusercontent.com/82683212/120698028-557d1800-c463-11eb-92c7-4e7e4261577c.png)

**Comment by WilliamMichelMSFT** [comment]
Both of the corresponding buttons under 'project' in the extension also succeeded

![image](https://user-images.githubusercontent.com/82683212/120699031-bb1dd400-c464-11eb-9419-2c93b4eded5c.png)

**Comment by WilliamMichelMSFT** [comment]
Also, when I run in debug, I get the following errors: 

![image](https://user-images.githubusercontent.com/82683212/120699618-78103080-c465-11eb-8705-c06efb893cd8.png)

**Comment by zhenyasav** [comment]
For that last error, do you have any more debug log output from your output window for us please? The "app not found" message tends to pop up when the browser uses the wrong identity (not the same one used to deploy / not one in the same tenant) - can you please confirm (maybe by purging cache / cookies / or ensuring you've signed into the same exact tenant in both the browser that you're invoking, and the provision / deploy process?). Thanks for trying the tooling! We'll investigate!

**Comment by kuojianlu** [comment]
@WilliamMichelMSFT I cannot reproduce this issue with the following step:
1. use `teamsfx new` to create a new project
2. use `cd` to enter the project folder, and then use `code .` to open the project in VSCode
3. run `teamsfx provision`
4. run `teamsfx deploy`
5. Run *Launch Remote (Edge)* in VSCode

Could you please let us know the steps to reproduce this issue? It would be very helpful for us to figure it out. Thanks!

**Comment by adashen** [comment]
Archive for now since there is no more update from customer. Feel free to reopen if there is any issue.
