### ISSUE TITLE
I want to configure staging, production, dev environments as different apps.

### ISSUE THREAD

**Issue by Ufarufa** [OfficeDev/TeamsFx#1275]
hi ~ 
I want to configure staging, production, dev environments as different apps.
I wonder what files should be separated under the .fx folder to separate the staging, production, and dev environments.

**Comment by zhenyasav** [comment]
Great feedback, we have more work to do to straighten out the "environments" story. I don't think we support this separation very well just yet, but proper environment support like this is one of the top priorities at the moment. Thanks for kicking the tires! Stay tuned!

**Comment by Ufarufa** [comment]
Thank you for quick response. I'm hoping for a better tool to come out. I am always cheering for you.

**Comment by zhenyasav** [comment]
Thanks! Let's not close this until we actually ship the feature though, this one is important.

**Comment by dooriya** [comment]
Hey @Ufarufa! Sorry for the belated response.
We've just release the multiple-environments supports as a preview feature in the recent releases, which allows managing multiple environments for a Teams app.

You can install the [latest toolkit (v2.9.0)](https://marketplace.visualstudio.com/items?itemName=TeamsDevApp.ms-teams-vscode-extension), and enable the `Insider Preview` flag in VS Code user settings. For how to use the multi-env feature in Teams toolkit, you can refer to [this wiki](https://github.com/OfficeDev/TeamsFx/wiki/Enable-Preview-Features-in-Teams-Toolkit). 

Any feedback is welcome for using this feature!
