### ISSUE TITLE
Disable "Validate Teams Manifest..." for a fresh project

### ISSUE THREAD

**Issue by thomyg** [OfficeDev/TeamsFx#1276]
**Is your feature request related to a problem? Please describe.**
Starting a clean, fresh project. Clicking on "Project > TeamsFx > Validate Teams Manifest ..." and nothing happens. 
No output, no message, no sign of the tool doing anything. As a user, I'm clueless about what just happened. Did the Toolkit check anything? Was there an error? Does it work? 

**Describe the solution you'd like**
You are disabling the  "Update Teams Manifest ..." until I configure SSO, could you do the same for "Validate Teams Manifest..."?

**Comment by zhenyasav** [comment]
A manifest should exist in a new project and should therefore be eligible for validation, this sounds like a bug. Thank you!

**Comment by therealjohn** [comment]
This is now fixed in 0.1.48.43394 available on the Marketplace.

**Comment by thomyg** [comment]
Thx for the added output!

![image](https://user-images.githubusercontent.com/10920072/121401433-03535f80-c959-11eb-9c71-f1b9a7d61415.png)
