### ISSUE TITLE
"Validate Teams Manifest..." throws bot error on fresh project

### ISSUE THREAD

**Issue by thomyg** [OfficeDev/TeamsFx#1277]
**Describe the bug**
Starting a fresh project for a tab. Clicking on "Configure for SSO ...", getting the manifest set up. Immediately afterwards I want to check my manifest. I click on "Validate Teams Manifest ..." and the Toolkit gives me "[error] bots | Value null is not of the expected type Array." 

I never touched the manifest and I never wanted to create a bot in the first place. As a novice, I'm no confused and have no idea what this error means for my tab. 

**To Reproduce**
1. Create a fresh project in Visual Studio
2. Configure for SSO ...
3. Click on Validate Teams Manifest ...

**Expected behavior**
I would expect the Toolkit to generate a valid Teams App manifest.

**Screenshots**
![image](https://user-images.githubusercontent.com/10920072/120768984-f8459d00-c51c-11eb-9461-ae0c19fb5538.png)

**Comment by therealjohn** [comment]
This is now fixed in 0.1.48.43394 available on the Marketplace.

**Comment by thomyg** [comment]
Happy to confirm the fix! Thank you!
