### ISSUE TITLE
Deploying to already existing resources like storage account, app service is not working

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/TeamsFx#1279]
**Describe the bug**
Deploying azure resources from VS code and then deployment using "Teams: Deploy to the cloud" is working fine.
But if we create azure resources manually and then deployment using ""Teams: Deploy to the cloud"" is not working. 
Observed below error:
![image](https://user-images.githubusercontent.com/69682598/120878500-892e7e00-c5da-11eb-80fb-a0c937db49b4.png)

I am suspecting app service deployment is not happening correctly.
Any workaround or steps to resolve issue will help?

**To Reproduce**
1. Create resource group manually in azure
2. Create container for $web
4. Create storage account and enable static website
5. Create app service
6. Create azure ad app registration with redirect URI, Expose an API section, Manifest changes
6. Update env.default.JSON,default.userdata, .env files with already existing resources details
7. Open command Palatte and run "Teams: Deploy to the cloud"
8. Create Teams app manifest with updated values and install in teams

**Expected behavior**
It is expected to load tab in Teams. It is loading. But Graph API call is not working. Seeing below errors.
It seems azure website deployment is not happening.

**Screenshots**:
![image](https://user-images.githubusercontent.com/69682598/120878597-35706480-c5db-11eb-87db-9e3682b49eea.png)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version 2.0.1

**Comment by yanjiang222** [comment]
Thank you very much for the feedback. As we're still keep iterating our new product, can I try to understand a bit more about your scenario? You're manually creating some resources on Azure and use the "Teams: Deploy to the cloud" within the toolkit to deploy the resource again right? Can I ask you two questions to help us further understand your problem? 1. Why you try to manually create some resources on azure? what benefits does that bring to you? 2. what's the expected result you're trying to get? Thanks a lot!

**Comment by SubbaReddi** [comment]
Not related to specific business usecase. But trying to understand the possible options with vs code toolkit.
For example: App service and storage account exists with already running application and want to use vs code toolkit features.

**Comment by adashen** [comment]
@SubbaReddi Thanks you for the information. We consider supporting existing resources is one of the scenario we will support in the future. So add the issue to backlog. Thanks for the issue!

**Comment by sehulugh** [comment]
I am facing a similar issue, my company has a policy where you need to specify a tag for every resource you create on Azure, is there a way I can specify a tag when creating the resources during 'Provision in the cloud' ?

**Comment by sehulugh** [comment]
> **Describe the bug**
> Deploying azure resources from VS code and then deployment using "Teams: Deploy to the cloud" is working fine.
> But if we create azure resources manually and then deployment using ""Teams: Deploy to the cloud"" is not working.
> Observed below error:
> ![image](https://user-images.githubusercontent.com/69682598/120878500-892e7e00-c5da-11eb-80fb-a0c937db49b4.png)
> 
> I am suspecting app service deployment is not happening correctly.
> Any workaround or steps to resolve issue will help?
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Create resource group manually in azure
> 2. Create container for $web
> 3. Create storage account and enable static website
> 4. Create app service
> 5. Create azure ad app registration with redirect URI, Expose an API section, Manifest changes
> 6. Update env.default.JSON,default.userdata, .env files with already existing resources details
> 7. Open command Palatte and run "Teams: Deploy to the cloud"
> 8. Create Teams app manifest with updated values and install in teams
> 
> **Expected behavior**
> It is expected to load tab in Teams. It is loading. But Graph API call is not working. Seeing below errors.
> It seems azure website deployment is not happening.
> 
> **Screenshots**:
> ![image](https://user-images.githubusercontent.com/69682598/120878597-35706480-c5db-11eb-87db-9e3682b49eea.png)
> 
> **VS Code Extension Information (please complete the following information):**
> 
> * OS: Windows
> * Version 2.0.1

Azure Website Deploy actually happens during Provision in the cloud step, so without that the App Service is empty. 
Question now is : How do we deploy simple auth plugin separately?

**Comment by adashen** [comment]
Thanks @sehulugh, your scenario is valid and we will consider the support in the future versions! Will keep you updated when the feature is released.

**Comment by blackchoey** [comment]
@sehulugh There's an insider preview feature that allows you customize all the Azure resources via ARM template, so you can specify tags in the ARM template before provision. You can follow this wiki to try this preview feature: https://github.com/OfficeDev/TeamsFx/wiki/Enable-Preview-Features-in-Teams-Toolkit. This preview feature will become stable feature in upcoming release. Please stay tuned on the new releases.

For the simple auth deployment question, the bits is available at GitHub Releases: https://github.com/OfficeDev/TeamsFx/releases/download/simpleauth@0.1.0/Microsoft.TeamsFx.SimpleAuth_0.1.0.zip. If you still have the requirement to deploy it separately, you can download the bits and use your favorite way to deploy it.

**Comment by adashen** [comment]
Hey @SubbaReddi, @sehulugh ,thanks again for your feedback, we just released Teams Toolkit V3 that should support your ask - customizing the behavior of provisioning Azure resources. Please find following link for reference:

- Teams Toolkit V3: Teams Toolkit (Preview) - Visual Studio Marketplace
- Docuemenation: Use Teams Toolkit to provision cloud resources - Teams | Microsoft Docs
- Blog Announcement: Developing Enterprise-Ready Microsoft Teams Apps with Teams ToolKit v3.0 - DEV Community 👩‍💻👨‍💻
