### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by Justincyber1** [OfficeDev/TeamsFx#12867]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by adashen** [comment]
@Justincyber1 Thanks for contacting us. Since the issue has no detail info, we close it now. If there is anything needs help, please feel free to open a new one with detail.
