### ISSUE TITLE
Issue with OAuth2 Redirection During Sign-In on Copilot Declarative Agent with API Plugin

### ISSUE THREAD

**Issue by swaminawale** [OfficeDev/TeamsFx#12949]
**What I am doing**
I am creating a custom Copilot agent with API plugin calls to the Microsoft Graph API /me and /users endpoints to retrieve user details. For authentication, I am using OAuth as the security schema defined in my Open API description file.

**What I did so far**
1. Created a new Copilot agent with an API plugin using Teams Toolkit and the Open API description file.
2. Registered an app in Azure AD, generated a client secret, and granted delegated permissions (see image below).
![image](https://github.com/user-attachments/assets/676706a9-3287-4995-a8e1-a18ecb2a59a9)
3. For the redirect URL, I added "https://teams.microsoft.com/api/platform/v1.0/oAuthRedirect" as per the documentation: https://learn.microsoft.com/en-us/microsoft-365-copilot/extensibility/api-plugin-authentication
4. After this, I deployed the agent. When I ask a query like "Get me details of <user name>", it prompts me to allow API access.
5. When I click "Allow", it asks me to sign in.

**Expected behavior**
When I click "Sign In", it should open a popup for login. After entering the credentials, the popup should close.

**Issue I am facing**
When I click "Sign In", the popup opens but freezes, showing nothing. This issue suddenly started occurring, even though it was working fine yesterday. I have also tested this with multiple users.
![image](https://github.com/user-attachments/assets/76b84122-a232-4452-b093-e5ed22b9cd3a)

**Screenshots**
![image](https://github.com/user-attachments/assets/704b30ce-1ff2-48a4-8849-1124c1ccdc55)
![image](https://github.com/user-attachments/assets/ae7b7055-e20b-4cbf-836c-0819a63143e2)

**Comment by Nivedipa-MSFT** [comment]
@swamisnawale - Thank you for bringing this issue to our attention. We will look into it and get back to you shortly.

**Comment by matteoperazzolo** [comment]
I have the same problem.

**Comment by SLdragon** [comment]
hi, @swamisnawale  and @matteoperazzolo , for Declarative Agent with Microsoft Entra OAuth action, the Microsoft Entra app needs to add identify URI follow specific pattern:

![image](https://github.com/user-attachments/assets/71711957-34dc-4d9e-a45f-f93eddf7caff)

You can find this identify URI from [teams developer portal](https://dev.teams.microsoft.com/)

**Comment by swaminawale** [comment]
@SLdragon Thanks for your reply, I will try this out. Just a quick question, is this something that newly added? because earlier this was not setup and yet the agent was working without any issue.

**Comment by SLdragon** [comment]
@swamisnawale , yes, this is a new requirement to use Declarative Agent for Microsoft Entra OAuth. Previously, it was not required, so your agent was working correctly

**Comment by claraschneiker** [comment]
Hi @SLdragon, is there a full documentation yet where to add the SSO registration in the app manifest yet? I have the same issue.

**Comment by swaminawale** [comment]
@claraschneiker , I followed the steps that @SLdragon given to setup the SSO Registrations, and the agent has been working properly.

**Comment by SLdragon** [comment]
> Hi @SLdragon, is there a full documentation yet where to add the SSO registration in the app manifest yet? I have the same issue.

Currently, there is no official documentation on where to add the SSO registration in the app manifest. However, it will be available in the future. In the meantime, if you create a "from scratch" DA template with Entra SSO in TTK, it will automatically handle it for you

**Comment by SLdragon** [comment]
Close this issue, and if you need additional help, feel free to reopen it or create a new issue
