### ISSUE TITLE
C# support for Bots in TeamsFx and VS Code

### ISSUE THREAD

**Issue by sebastianzolg** [OfficeDev/TeamsFx#1308]
Hi all, the current version of **TeamsFx** and the **VS Code** plugin is really great. However, why is it limited to just TypeScript and JavaScript as programming languages? 

The most common scenario I face is a separate Bot project written in C# (from plain Bot Templates in Visual Studio 2019) and an App project (from TeamsFx in VS Code) with tabs (HTML/JavaScript). I would love to combine those two and rely on the TeamsFX/VS Code workflow.

- Is support for C# as a programming language coming to TeamsFx and the VS Code extension? 
- Is there any way to maintain the VS Code extension developer workflow and combine it with a separate C# project in Visual Studio?

Thanks
—Sebastian

**Comment by therealjohn** [comment]
@sebastianzolg Right now, C# workflows are focused in the [extension for Visual Studio 2019](https://marketplace.visualstudio.com/items?itemName=msft-vsteamstoolkit.vsteamstoolkit). We're currently designing how this would would in VS. I'd love to learn more about how you're using Bots and what requirements you'd like to see in the VS extension.

**Comment by eliem3** [comment]
Good day all, I would like to know if TeamsFx in VS19 has a way to read or get calls made by an organization.
Is there an API or an integration system in place to help us retrieve all calls made using the Teams app? 
I have a project that I am driving and we are still waiting for this update. 

Thanks
-McElie

**Comment by therealjohn** [comment]
@eliem3 I'm not sure exactly what you're looking for, but the Teams SDK seems like a good place to explore first. 

For example, https://docs.microsoft.com/en-us/microsoftteams/platform/bots/calls-and-meetings/calls-meetings-bots-overview

The Teams Toolkit doesn't have any additional support for accessing calls right now, but you always have access to whatever the base SDK provides and whatever is extensible in Teams today. Have you found an existing extensibility point you want to access?

**Comment by adashen** [comment]
Archive for now as there is no more update from customer. Feel free to open if there is any more issue.

**Comment by eliem3** [comment]
Hi @therealjohn, Your previous comment was very helpful thou. However, the objective of the project is as follows:
There is an organization that has users making calls and meetins using Microsoft Teams rather than on the mobile app or Desktop app.
I would like to capture the calls (listen, and retrieve) and to be able to run Cognitive Services on those calls such as Speech Analytics, Sentiments, etc.
I have already all the necessary tools for Cognitive Services.
Here is my questions: 
> Can the Recording Bot help me to record calls?  If Yes, then where can I retrieve the recorded calls which users make? In which location is the Recording Bot saves all the calls and in which format?
> Do you a blog/review/ or step by step process where someone creates a Recording Bot and publishes it on App Service from scratch?

These are my question and I'm sure they are clear to you to understand.

Than you

Eliem3

**Comment by therealjohn** [comment]
@eliem3 I'll reply in the other issue created at https://github.com/OfficeDev/microsoft-teams-sample-complete-csharp/issues/35
