### ISSUE TITLE
Is there a way to use the authentication retrieved from Microsoft Teams (via TeamsFX) and use it for an internal web API?

### ISSUE THREAD

**Issue by FredTheDane** [OfficeDev/TeamsFx#1363]
I am currently working on a Tab application for Microsoft Teams and have stumbled upon the extension called TeamsFx which enables easy retrieval of an authentication token from Teams without the need of prompting the user every time. Likewise, I used the Teams Toolkit extension for Visual Studio to get started. The project is implemented with .NET 5.0.

What I need, is to use the same authentication token retrieved from Teams inside the tab to then access a web API that is implemented in the same project. I have spent two full days trying to work this issue out with pretty much no result. I can retrieve an authentication token via TeamsFx, but simply using this as the bearer auth token in my web api did nothing but it telling me that the signature was wrong.

I have tried adding something like this to my Startup class:

```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddMicrosoftIdentityWebApi(Configuration, "AzureAd");
```

,but then it threw an exception because the TeamsFx library has already done the same with this call:

`services.AddTeamsFxSimpleAuth(Configuration);`

In previous Web API projects I have been able to set up Azure AD authentication to the site, and pretty seemlessly add the [Authorize] tag to any WebAPI classes and it just worked.

I hope that someone can save me from my own insanity ;D

Best,

//F_

**Comment by blackchoey** [comment]
Hi @FredTheDane , can you share how do you get the `authentication token retrieved from Teams inside the tab` you mentioned?
By default, the TeamsFx extension configured the web api to allow token got from Teams Tab single sign-on feature. You can find related configuration code at https://github.com/OfficeDev/TeamsFx/blob/dev/packages/simpleauth/src/TeamsFxSimpleAuth/SimpleAuthWebApiExtension.cs#L39-L55

**Comment by FredTheDane** [comment]
Hi @blackchoey :)

The way that I try and use the Teams Authentication token is something along the lines of this inside the OnAfterRenderAsync method of the tab.razor file (The application is pretty much as is with what you get using the Microsoft Teams App project template:

```
            var token = await teamsfx.GetAuthenticationToken();
            WebClient.DefaultRequestHeaders.Add("Authorization", "Bearer " + token.Token);
            var value = await WebClient.GetAsync("https://localhost:44357/api/Diagram");
```

The Diagram api is just a quick and dirty API controller that spits out an array within **the same project as the tab app**. However, when checking the value I get this Unauthorized error back: _{Bearer error="invalid_token", error_description="The signature is invalid"}_

When you say that I can use TeamUserCredential to get a token, where would I need to implement this in the JwtBearerOptions and how would I get the token?

**Comment by blackchoey** [comment]
Thank you @FredTheDane for the details. The project created by Teams Toolkit extension wraps the TeamsUserCredential to acquire token. @JerryYangKai will provide more instructions on how to update the code to call the internal web APIs.

**Comment by JerryYangKai** [comment]
Hi @FredTheDane, since we only got JavaScript version of microsoft/teamsfx sdk, so we including webpack to wrapper it and using JSRuntime to trigger it in Blazor.
The webpack source code is in JS/src/index.js, you could add these code to get SSO token
```
export async function getSsoToken() {
var credential = new TeamsUserCredential();
var token = await credential.getToken("");
return token;
}
```
Then under JS folder , run 'npm install' and 'npm run build' to webpack the code and refresh the webpack file (wwwroot/teamsfx.js). 
Finally you could using JSRuntime trigger the new api you just added in TeamsFx.cs.

**Comment by FredTheDane** [comment]
As suggested, adding in the getSsoToken function made all the difference and now I can query my API with no issues! :)

@JerryYangKai and @blackchoey thank you both for the great help! 🚀 🚀
