### ISSUE TITLE
Dev Teams Portal has a link for the FluentUI Toolkit

### ISSUE THREAD

**Issue by mikewalker74** [OfficeDev/TeamsFx#1373]
There is a link on the Teams Dev portal as per below
![image](https://user-images.githubusercontent.com/35928561/122469421-d89a8400-cfb4-11eb-9931-52f2a924c553.png)
That points too https://www.figma.com/file/AIkW9R1AanIlag0Lwe8ttk 

On clicking this and creating an account it shows
![image](https://user-images.githubusercontent.com/35928561/122469489-ecde8100-cfb4-11eb-936d-2605af64ec45.png)

Is there something we need to do for gaining access to this content?

**Comment by grumpykiwi** [comment]
The same thing just happened to me. Went thru the email verification process and now a 404. 

Also a warning on the portal would be nice about the need to sign up. There is no signup link. I entered my email and pressed Login more out of frustration than anything. Was very surprised to the create account workflow.

**Comment by pierceboggan** [comment]
This issue has been fixed, and the file should be now publicly available for you to access:
https://www.figma.com/community/file/916836509871353159
