### ISSUE TITLE
Manage RedirectUris at configuration file

### ISSUE THREAD

**Issue by stas-linearb** [OfficeDev/TeamsFx#1391]
Redirect URI should be managed in some way. I didn't find a way to manage it. So as a workaround to the problem I just turned on the flag "skipProvision", in order to prevent deleting manually added URIs at the Azure portal.

**Comment by KennethBWSong** [comment]
Hi @stas-linearb. Thank you very much for your feedback. Currently we expect no extra config will be performed on AAD app, thus we will overwrite the Redirect URI. Turning "skipProvision" flag on would be a good practice in this case. 
Here may I ask you two question to help us further understand your problem? 
1. Why you try to manually add Redirect URI and what's your step? 
2. What's the expected experience for your scenario? 
Thanks a lot!

**Comment by stas-linearb** [comment]
We want to enable tenant administrators to install our APP using "proactive installation" and manage teams at our website, so we want an administrator to authorize himself at our website. 
This is the reason for the additional redirect URI (callback after login).

**Comment by adashen** [comment]
@stas-linearb Thanks for the information. To clarify the app registration steps, are the following what you expected?
1. Use teams vscode toolkit to register the app in provision/localdebug
2. Go to portal to add other redirect url
3. Use the same app in toolkit but make sure the configurations are not overriden?

**Comment by stas-linearb** [comment]
1. Use teams vscode toolkit to register the app in provision/localdebug
2. Update configuration with additional redirectUri
3. The toolkit will update portal configuration in provision/localdebug

**Comment by KennethBWSong** [comment]
@stas-linearb Thanks for your idea! We still have more work to do on the context, and I will file your idea in our internal backlog to see whether we can improve your experience.

**Comment by MuyangAmigo** [comment]
Hey @stas-linearb I know this is super delayed, but now Teams Toolkit uses AAD manifest template to provision AAD app, so now you can now customize the AAD app. Here is a documentation: https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/aad-manifest-customization.
