### ISSUE TITLE
XAML Styles for Teams Fluent Theme

### ISSUE THREAD

**Issue by xperiandri** [OfficeDev/TeamsFx#1428]
I want to build my Teams app using [Uno Platform](https://github.com/unoplatform/uno/) which is UWP code running on WASM.
So that I need UWP XAML Styles of Teams Fuent Theme to make the same look and feel.

Are they available?
Can you make such styles?

**Comment by therealjohn** [comment]
👋 @xperiandri 

We don't have anything available right now as part of TeamsFx. However, you may try opening an issue and starting a discussion at the FluentUI repository: https://github.com/microsoft/fluentui. Someone there may be more familiar with what's already available or in-progress for FluentUI.
