### ISSUE TITLE
Custom Status via Graph API

### ISSUE THREAD

**Issue by grumpykiwi** [OfficeDev/TeamsFx#1432]
**Is your feature request related to a problem? Please describe.**
When will a custom status set in the Teams client (desktop, web or mobile) be surfaced via the Graph API?

Slack has had this for a long time. My company management have come to reply on staff's ability to more accurately describe their status and have it surfaced on an internal web page, accessible to all staff.

**Describe the solution you'd like**
The Presence API to be updated to include this

**Describe alternatives you've considered**
Staying with Slack or writing my own status app, possibly using custom fields in on premises AD and exposing them to AAD for consumption.

**Comment by MuyangAmigo** [comment]
Hello @grumpykiwi, Thanks for sharing your use cases! Upon checking Graph API documentation, we have found an API support to retrieve all users presence status: https://docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-1.0

Here are some additional things that might be helpful:
* We provide an SDK package that lets you easily create and authenticate a Graph Client: https://github.com/OfficeDev/TeamsFx/tree/dev/packages/sdk#create-and-authenticate-a-microsoftgraphclient
* You might need to specify additional delegated permission (`Presence.Read.All`) in the `permission.json` file if you created the Teams App project with the Teams Toolkit.

Lastly, I'm interested in learning your experience of finding APIs you need for your project. We certainly want to improve API discoverability so any feedbacks are valuable to us!

**Comment by grumpykiwi** [comment]
I set my status in Teams to the attached.
![Custom Status](https://user-images.githubusercontent.com/43825887/123435534-4afdfc00-d593-11eb-9681-61c0fe2bf212.png)

When I retrieve my status via Graph Explorer or the Graph API with the GraphServiceClient (specifying Presence.Read.All as my required permission) I get this:

`{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('{{ID}}')/presence/$entity",
    "id": "{{ID}}",
    "availability": "Available",
    "activity": "Available"
}`

As you can see, my custom status of "working from home" is not shown. This is the fundamental issue.

As far as finding APIs. Mostly googling or digging thru the docs. I have not found them easy to find. Far too often there are only examples for pure Rest calls. It would make my life easier if there was also an example C# example using the Graph API and graph service client. 

Using the select keyword to filter output on group queries is especially lacking in real examples for C#. It takes a lot of trial and error to get the syntax right.

The documentation itself tends to be a bit vague on required parameter types sometimes. Permission Scope usage varies widely. Space delimited, string array, comma separated?. Yet again an example would help

This for example:
[https://docs.microsoft.com/en-us/javascript/api/@microsoft/teamsfx/teamsusercredential?view=msteams-client-js-latest](url)

Not very helpful at all.

Anyway. Hope this helps, but I really could do with that custom status

Thanks

**Comment by MuyangAmigo** [comment]
Thank you for sharing your scenario and feedback! As we are not Graph expert, you might get better answers/suggestions from Graph Support: https://developer.microsoft.com/en-us/graph/support 

We also hear your pain points of API discoverability, from a tooling perspective we may think of a way to provide better support, so stay tuned!

**Comment by grumpykiwi** [comment]
Thanks. I added a comment over at the Graph support portal. Seems I am not the only one requesting this feature.

**Comment by MuyangAmigo** [comment]
We will close this as issue reported to Graph Support channel. Please feel free to reopen if there is any issue.
