### ISSUE TITLE
ability to create and deploy Tabs and functions to Azure Static Webapps

### ISSUE THREAD

**Issue by Josverl** [OfficeDev/TeamsFx#1440]
[Azure static webapps and functions](https://azure.microsoft.com/en-us/services/app-service/static/#features) appear to be a vary good match to deploy and host Teams Tabs Apps, and offer a quite affordable hosting solution with pricing and capabilities in between Azure Webapp and Sharepoint hosted.

**Describe the solution you'd like**
I would like to have the ability and/or example documentation in Teams Toolkit to : 
 * select Static Web Apps and Functions as a hosting type ( for Tabs and BE functions) 
 * specify the hosting regions or existing static host as part provisioning or dicumented as part of the .fx configuration files
 * deploy to the static web app from teams Toolkit (just commit and push) 
 * generate and publish a teams manifest using the static app URLs 

**Describe alternatives you've considered**
I've tried to : 
 - create a simple project using Typescript with a Tab and Azure Function 
 - create a repo and commit a base project 
 - add a static webapp specifying the `/tabs`  '/api' and `build` folders 
 - deployment of the repo to ASW fails with 'The function language detected is unsupported or invalid.'
   while typescript is a supported langue for azure functions.

**Comment by eriolchan** [comment]
Thanks @Josverl for this advice, and we are looking into this possibility as well. We are investigating it and will update to you if we have more information.
