### ISSUE TITLE
Add/document ability to 'Provision' to a specified Azure region

### ISSUE THREAD

**Issue by Josverl** [OfficeDev/TeamsFx#1478]
Currently all deployments default to the azure region `East US`,
while I would prefer to be able to deploy to a different region.

**Describe the solution you'd like**
-  the ability to specify the default deployment region for all Teams Toolkit projects as as part of the Toolkit configuration 
- the ability to specify a per-project region , possibly in `.fx\env.default.json`  - solution.location : "East US",
   for this it would be very helpful to have a scaffold json file with the input values, and possibly defaults, that can be changed,
and/or a clear link to the documentation.

** Result** 
A specified region should them be used for all (new) azure resources deployed 

**Alternatives considered**
- Tried to specify the region / location in env.default.json.
   However this gets ignored / overwritten 
- move / recreate all resources - requires quite some effort and breaks too much stuff

**Comment by MuyangAmigo** [comment]
@Josverl, Thank you for your input! It's valuable to our product development. 

There is a similar ask https://github.com/OfficeDev/TeamsFx/issues/1251 about more granular control on the Azure resources like customizing tags, resource group names and regions you want to deploy. 

We are working on a feature that provides ARM support so that you can customize the regions you want the resources to be deployed. Please stay tuned!

**Comment by Josverl** [comment]
yes I see the overlap 
but please when adding even more levels of templating, could you make sure the solution does not require a PHD in bicep.
clear documentation would go a long way IMO
- on the main use cases ( RG naming , region ) 
- how the templating / env flow works 
  - which are in/out variables, 
  - processing order of the json and env variables 
  - the role of the various `teamsfx` actions and specifically what inputs they use

**Comment by MuyangAmigo** [comment]
Hey, we have included a preview feature in the latest Teams Toolkit with ARM support, if you wish to give it a try, please follow the [Wiki Page to Enable ARM Support](https://github.com/OfficeDev/TeamsFx/wiki/Enable-Preview-Features-in-Teams-Toolkit)! Feel free to raise an issue should you meet any problems.
