### ISSUE TITLE
Select capabilities screen cuts off text

### ISSUE THREAD

**Issue by pierceboggan** [OfficeDev/TeamsFx#1479]
**Describe the bug**
When creating a new Teams project, the Select capabilities step includes text that doesn't fit in the dropdown window:
![image](https://user-images.githubusercontent.com/1091304/124050385-b7379000-d9d7-11eb-8e22-7cab1b445e2c.png)

My expectation would be that I could hover over the text to get the full description.

**To Reproduce**
1. Create a new Teams project
2. Scaffold a new project

**Expected behavior**
Text is readable, and if space runs out, I can hover over the text for the full text opy.

**Screenshots**
![image](https://user-images.githubusercontent.com/1091304/124050444-d2a29b00-d9d7-11eb-96b3-d4db5cf84682.png)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version 2.1.1

**CLI Information (please complete the following information):**

**Additional context**

**Comment by adashen** [comment]
@jaeyonglee05 for better design.

**Comment by MuyangAmigo** [comment]
This is fixed in the latest version of Teams Toolkit, I'll close this for now. @pierceboggan Thank you for reporting the issue, feel free to open it again you found other issues.
![image](https://user-images.githubusercontent.com/11220663/127436703-2ea3ed2b-02b4-4b13-bfb2-03b9e2a39daf.png)
