### ISSUE TITLE
Tab app takes too long to npm install

### ISSUE THREAD

**Issue by hund030** [OfficeDev/TeamsFx#1576]
**Describe the bug**
When local debug tab app, it takes ~5 minutes to finish build and start tab app (more than 3 minutes it's doing npm install). This may be too long for a getting started project.

**To Reproduce**
1. Create a new project, select the capability: Tab.
2. F5 to local debug.

**Expected behavior**
Hope any solution to improve the performance.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version 1.5.7

**Comment by hund030** [comment]
I found a faster package manager - [pnpm](https://www.npmjs.com/package/pnpm). It's about 2x faster than npm in my machine.
By simply replace the `frontend npm install` task with below, it becomes much faster to start the tab app for the first time.
```
{
            "label": "frontend npm install",
            "type": "shell",
            "command": "pnpm install",
            "options": {
                "cwd": "${workspaceFolder}/tabs"
            }
        }
```
The task is defined in `.vscode/tasks.json`.

**Comment by kuojianlu** [comment]
> I found a faster package manager - [pnpm](https://www.npmjs.com/package/pnpm). Installing the dependencies of a tab app with pnpm only takes about 1 minute in my machine.
> By simply replace the `frontend npm install` task with below, it becomes much faster to start the tab app for the first time.
> 
> ```
> {
>             "label": "frontend npm install",
>             "type": "shell",
>             "command": "pnpm install",
>             "options": {
>                 "cwd": "${workspaceFolder}/tabs"
>             }
>         }
> ```
> 
> The task is defined in `.vscode/tasks.json`.

Does this way mean that a new dependency has to be introduced? Seems user should have `pnpm` globally before local debug.

**Comment by Josverl** [comment]
I gave pnpn a try, and did not see that much differences on the initial install, but only on subsequent projects .

I also note that create-react-app has been based on yarn , and there are still a few artefacts of that visible:
```
You can now view teamsfx-template-tab in the browser.

  Local:            https://localhost:3000
  On Your Network:  https://172.26.48.1:3000

Note that the development build is not optimized.
To create a production build, use yarn build.
```
