### ISSUE TITLE
Should 'Install Node.js' step go to different landing page? 

### ISSUE THREAD

**Issue by pierceboggan** [OfficeDev/TeamsFx#1720]
**Describe the bug**
The Teams Toolkit quickstart page directs users to install Node.js at the following location:
https://nodejs.org/dist/latest-v14.x/

This page contains many different downloads. Should we point users at the more friendly [main Node.js download page](https://nodejs.org/en/download/) instead?

I would imagine we would always support Node.js LTS, so this shouldn't be a problem.

**VS Code Extension Information (please complete the following information):**
 - OS: macOS 
 - Version: 2.2.0

**Comment by yanjiang222** [comment]
The page suggested by @pierceboggan is more user friendly and easy to understand. We can replace the existing one with this new page. thanks!
