### ISSUE TITLE
Download page for .NET SDK is incorrect

### ISSUE THREAD

**Issue by pierceboggan** [OfficeDev/TeamsFx#1722]
**Describe the bug**
When the .NET SDK fails to install correctly on first run, the user is redirected to this page in the error text:
https://dotnet.microsoft.com/download/visual-studio-sdks

However, this page only contains SDKs for Windows, not macOS.

Should we be pointing at https://dotnet.microsoft.com/download instead and support .NET 5?

**Comment by yanjiang222** [comment]
The new page suggested is more concise and user friendly. I suggest we should do the change. thanks!

**Comment by meifans** [comment]
Thanks @pierceboggan for the great suggestion. 

But I found the download page was already the link you suggested. 
Here's the [helplink](https://aka.ms/teamsfx-envchecker-help) that has two points for downloading .NET SDK in "Overall" and "How to install .NET SDK" section.

Here's my reproduce steps:
1. Install teamsfx extension and scaffold a new teams app included function api.
2. Clean .NET SDK and f5
3. Failed to install .NET SDK and select **Learn more**
![image](https://user-images.githubusercontent.com/12523371/126930361-64f48859-4317-4fcf-bc15-96cee9834f2d.png)

4. Redirect to the [page](https://github.com/OfficeDev/TeamsFx/blob/main/docs/vscode-extension/envchecker-help.md#failtoinstalldotnet)
![image](https://user-images.githubusercontent.com/12523371/126930685-2f7959b4-7f77-4355-a6b2-8e7df3619974.png)

5. Click **the guide** then **the official website**  in the _How to install .NET SDK?_

![image](https://user-images.githubusercontent.com/12523371/126930840-ae1ec66e-582d-4cb3-b40c-ca01753cd1fb.png)

![image](https://user-images.githubusercontent.com/12523371/126930827-fc0566bf-2bef-4b70-a85f-a6e3a83555df.png)

6. Redirect to the [download page](https://dotnet.microsoft.com/download)

![image](https://user-images.githubusercontent.com/12523371/126930931-041475d7-198d-4083-9fc1-b5abc068f38b.png)


If possible, I'd like to know how you do it to this download page: https://dotnet.microsoft.com/download/visual-studio-sdks
I looking forward to your reply and please let us know if there're more questions/feedback.

**Comment by meifans** [comment]
Thanks @pierceboggan for the great suggestion. 

But I found the download page was already the link you suggested. 
Here's the [helplink](https://aka.ms/teamsfx-envchecker-help) that has two points for downloading .NET SDK in "Overall" and "How to install .NET SDK" section.

Here's my reproduce steps:
1. Install teamsfx extension and scaffold a new teams app included function api.
2. Clean .NET SDK and f5
3. Failed to install .NET SDK and select **Learn more**
![image](https://user-images.githubusercontent.com/12523371/126930361-64f48859-4317-4fcf-bc15-96cee9834f2d.png)

4. Redirect to the [page](https://github.com/OfficeDev/TeamsFx/blob/main/docs/vscode-extension/envchecker-help.md#failtoinstalldotnet)
![image](https://user-images.githubusercontent.com/12523371/126930685-2f7959b4-7f77-4355-a6b2-8e7df3619974.png)

5. Click **the guide** then **the official website**  in the _How to install .NET SDK?_

![image](https://user-images.githubusercontent.com/12523371/126930840-ae1ec66e-582d-4cb3-b40c-ca01753cd1fb.png)

![image](https://user-images.githubusercontent.com/12523371/126930827-fc0566bf-2bef-4b70-a85f-a6e3a83555df.png)

6. Redirect to the [download page](https://dotnet.microsoft.com/download)

![image](https://user-images.githubusercontent.com/12523371/126930931-041475d7-198d-4083-9fc1-b5abc068f38b.png)



If possible, I'd like to know how you do it to this download page: https://dotnet.microsoft.com/download/visual-studio-sdks

I looking forward to your reply and please let us know if there're more questions/feedback.
