### ISSUE TITLE
new bug report: bot npm install.npmInstall

### ISSUE THREAD

**Issue by eriolchan** [OfficeDev/TeamsFx#1736]
NPM install encountered an error. Please refer to the output window for detailed error information or click 'Report Issue' button to report the issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**Additional context**

**Error detail**
{"nodeVersion":"v12.16.1","npmVersion":"v6.13.4","cwd":"D:\\work\\project\\testenv\\erichenbot\\bot","exitCode":1,"errorMessage":["56 error code E401","57 error Unable to authenticate, need: Basic realm=\"https://pkgsprodwus21.pkgs.visualstudio.com/\""]}

**Comment by xiaolang124** [comment]
Thank you for your feedback, looks like you're running into authentication issues with your company's internal npm registry. TeamsFx toolkit uses public npm registry so you don't need any private regitstry. I'd try one of these solutions:
 - Run ```npm config ls```, you will likely see a ```registry``` line. There should be a filename above it ending in ```.npmrc```; if you edit this file you can change the registry to the public one. (Usually it's ```~/.npmrc``` but may depend on your configuration.)
 - Try to use ```npm install --registry https://registry.npmjs.org``` on your project manually. This will install from the public registry, which you should not need to authenticate to.
