### ISSUE TITLE
new bug report: bot npm install.npmInstall

### ISSUE THREAD

**Issue by Radhika10-1997** [OfficeDev/TeamsFx#1739]
NPM install encountered an error. Please refer to the output window for detailed error information or click 'Report Issue' button to report the issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**Additional context**

**Comment by xiaolang124** [comment]
Thank you for your feedback, can you provide more detail to help us find the root cause? Like screenshots, or log details from VsCode Output `Teams Toolkit` channel when you encounter this scenario.
