### ISSUE TITLE
When running a local preview, let me choose my Edge / Chrome profile

### ISSUE THREAD

**Issue by sebastienlevert** [OfficeDev/TeamsFx#1772]
When building for Teams, you will oftern have a **ton** of different browser profiles. Some on multiple M365 tenants, your personal one, work one, etc. I would love to be able to do the following when previewing my work. This would allow me to have a simpler flow as I won't have to close the browser that pops up, then copy the url, then opening up a new browser, then pasting the URL!

`teamsfx preview --local --browser edge --profile "Profile X"`

**Comment by MuyangAmigo** [comment]
Hey @sebastienlevert, Thank you for the feedback! We will consider this as a feature request in the future roadmap, please stay tuned!
