### ISSUE TITLE
When running teamsfx in WSL, I can't open any browser

### ISSUE THREAD

**Issue by sebastienlevert** [OfficeDev/TeamsFx#1773]
**Describe the bug**
When using teamsfx + Teams Toolkit in WSL2, I can't open any browser and I'm getting the following error : 

`[TeamsfxCLI.OpeningBrowserFailed]: Failed to open edge browser. Check if edge exists on your system.`

This makes sense as there is no edge or chrome in WSL, but there is one in the host. 

**To Reproduce**
1. Open a project in WSL
2. Run `teamsfx preview --browser edge --local`
3. Error happens

![image](https://user-images.githubusercontent.com/7620955/127574704-2affff59-f8e6-4b8c-890f-d67511db46f8.png)

**Expected behavior**
I am OK with 2 behaviors : 

1. WSL is not supported for opening the browser. In this case, I want an options with `--browser none` so I just need to copy paste the generated sideload URL and I can deal with the rest!
2. WSL opens the right browser from my hose machine

**VS Code Extension Information (please complete the following information):**
 - OS: WSL Ubuntu 20.04
 - Version: 2.3.1

**CLI Information (please complete the following information):**
 - OS: WSL Ubuntu 20.04
 - Version 0.3.1

**Comment by MuyangAmigo** [comment]
@sebastienlevert Thank you for reporting this issue, we will improve `teamsfx preview` command experience for WSL recently and will update you once it's released.

**Comment by MuyangAmigo** [comment]
Hi @sebastienlevert, we have released a new CLI version `teamsfx-cli@0.4.0` to address this issue. Please have a try!
