### ISSUE TITLE
new bug report: sa.ZipDeployError

### ISSUE THREAD

**Issue by deepakupretims** [OfficeDev/TeamsFx#1783]
Failed to deploy Simple Auth bits: getaddrinfo ENOTFOUND prodtabsa371538.scm.azurewebsites.net

undefined

**Comment by KennethBWSong** [comment]
Hi @deepakupretims . Thank you very much for your feedback. Normally this error comes from network problem. Would you please try the command again and see whether it is fixed?
Thanks a lot!
