### ISSUE TITLE
AppStudioPlugin.LocalAppIdUpdateFailed

### ISSUE THREAD

**Issue by NickersWeb** [OfficeDev/TeamsFx#1795]
Failed to update local app id in app studio due to Error: failed to update app due to Error: Cannot get the app definition with app ID.

`[Error] - code:AppStudioPlugin.LocalAppIdUpdateFailed, message: Failed to update local app id in app studio due to Error: failed to update app due to Error: Cannot get the app definition with app ID `

Get this error every time I debug.

Still runs fine. 

```"dependencies": {
"@fluentui/react": "^8.21.1",
"@fluentui/react-northstar": "^0.54.0",
"@microsoft/teams-js": "^1.6.0",
"@microsoft/teamsfx": "^0.2.0",
"msteams-react-base-component": "^3.1.0",
"axios": "^0.21.1",
"bootstrap": "^5.0.2",
"jsx-runtime": "^1.2.0",
"lodash": "^4.17.21",
"office-ui-fabric-react": "^7.164.1",
"prop-types": "^15.7.2",
"react": "^16.14.0",
"react-dom": "^16.14.0",
"react-query": "^3.13.0",
"react-router-dom": "^5.1.2",
"react-scripts": "3.4.1",
"react-select": "^3.2.0",
"react-select-async-paginate": "^0.3.10",
"universal-cookie": "^4.0.4",
"tslib": "^2.0.0"
}```

Made with Teams Toolkit v2.3.1

**Comment by MSFT-yiz** [comment]
@NickersWeb, thanks for reporting the issue. Our engineer will troubleshoot the problem you have encountered. If necessary, our engineer will get touch with you for more details.

**Comment by nliu-ms** [comment]
Hi @NickersWeb, this error may occur when the teams app for local debug is removed from [Dev Portal](https://dev.teams.microsoft.com/).

Your local teams app id can be found under ${projectRoot}/.fx/env.default.json.
```
{
    "solution": {
        "remoteTeamsAppId": xxxx
    }
}
```
Please check if this app exists in Dev Portal. You can simply fix it by removing "remoteTeamsAppId" from env.default.json and debug again. This will create a new teams app for you.

**Comment by NickersWeb** [comment]
This is from v2.3.1 of teams toolkit, creating a new tab project.
```
   "solution": {
        "programmingLanguage": "javascript",
        "teamsAppTenantId": "{{solution.teamsAppTenantId}}",
        "localDebugTeamsAppId": "{{solution.localDebugTeamsAppId}}"
    }
```
I don't know what `solution.teamsAppTenantId` is but it doesn't seem to be set in the project?

**Comment by NickersWeb** [comment]
Here's a log of when I try to debug. I can still run fine. I have a feeling that my configuration is in correct. Is there a way to default this in my project?

[error_log.txt](https://github.com/OfficeDev/TeamsFx/files/6932869/error_log.txt)

**Comment by nliu-ms** [comment]
Thanks @NickersWeb, the logs and version are very helpful!

Please go to `${projectRoot}/.fx/default.userdata`, remove the following two lines:
```
solution.localDebugTeamsAppId=xxx
solution.teamsAppTenantId=xxx
```

And the content in `${projectRoot}/.fx/env.default.json` should keep the same as your scaffolded new project
```
"solution": {
        "programmingLanguage": "javascript",
        "teamsAppTenantId": "{{solution.teamsAppTenantId}}",
        "localDebugTeamsAppId": "{{solution.localDebugTeamsAppId}}"
    }
```

And then run debug again. 

Let's see if it works for you, thanks!

**Comment by NickersWeb** [comment]
This solves my issue. I can run without an error. However I still can't build a package. I'll close this and open a new issue/find related issue.
