### ISSUE TITLE
new bug report: API.Error

### ISSUE THREAD

**Issue by res63661** [OfficeDev/TeamsFx#1797]
Getting this while performing step 2 from the faq-plus TeamsFx sample.
I have successfully provisioned my QnA maker service in azure.
Getting this error after message saying 'FaqPlus successfully provisioned to the cloud...

Lock is not acquired/owned by you

Error: Lock is not acquired/owned by you
    at c:\Users\res63\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.3.1\out\src\extension.js:2:8044536
    at LOOP (fs.js:1834:14)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by MSFT-yiz** [comment]
@res63661, thanks for reporting the issue. Our engineer will troubleshoot the problem you have encountered. If necessary, our engineer will get touch with you for more details.

**Comment by jayzhang** [comment]
@res63661 Did you delete the lock file: `.fx.lock` in the progress of proivisioning? We have reproduce such scenario, the same error happens:
![image](https://user-images.githubusercontent.com/1658418/127840504-7e8555c3-6ac8-4e74-9e64-91f31e1eccfb.png)
![image](https://user-images.githubusercontent.com/1658418/127840547-79304ad9-1601-4e15-8cbc-b97a3b1f591f.png)
