### ISSUE TITLE
Provisioning in the cloud issues.

### ISSUE THREAD

**Issue by KristapsD** [OfficeDev/TeamsFx#1846]
Hello! The current situation is the following: we've created a custom teams app, and we want to provision it in the cloud through Teams Toolkit extension for VSC. However, when provisioning it, we get an error, saying that it can't create a resource group for the app. What we want to do is define a previously created resource group for it to use. For example, it's trying to provision eParaksts-rg, but we want it to use a previously made resource group - eparaksts-dev-westeu-rg. Where can we define the resource group we want it to use?

Another problem is also that it's trying to provision resources in EAST US when our companys policy only allows resources in WEST EU, where do we change the default from EAST US to WEST EU?

**Comment by MuyangAmigo** [comment]
Hi @KristapsD, Thanks for your feedback! We are in the progress of enabling resource provision using ARM templates and you will be able to customize the regions and resource groups. We will enable this feature with an early preview soon so please stay tuned!

**Comment by KristapsD** [comment]
hi! @KristapsD  thanks for your response, how *soon* are we talking? because we need this ASAP. Or maybe there is some work around that we can do for now?

**Comment by MuyangAmigo** [comment]
Hey @KristapsD, may I understand what capabilities/resources (tab, bot, function, SQL, etc., ) you have included in your Teams app project? We have an early version that supports ARM right now but it's limited to the tab the only project, wondering if that would be sufficient for you right now. Meanwhile, let me find out what workarounds we can do right now.

**Comment by KristapsD** [comment]
@MuyangAmigo The teams app is using the following capabilities:
- tab application
- azure functions
- graph

And the language im using is react.

**Comment by KristapsD** [comment]
For now we've decided to provision the teams app, where it wants to privision itself, but this feature is still going to be needed.

**Comment by galytoh** [comment]
Hey @MuyangAmigo, @KristapsD!
> We have an early version that supports ARM right now but it's limited to the tab the only project,
Do we have any updates guys? If yes, where can we get this early version?

We have exactly the same configuration and needs as @KristapsD.
We stay tuned!

**Comment by MuyangAmigo** [comment]
Hey, we have included a preview feature in the latest Teams Toolkit with ARM support, if you wish to give it a try, please follow the [Wiki Page to Enable ARM Support](https://github.com/OfficeDev/TeamsFx/wiki/Enable-Preview-Features-in-Teams-Toolkit)! Feel free to raise an issue should you meet any problems.

**Comment by schinna** [comment]
@MuyangAmigo : Did not work for me. Please let me know if you have any reference.

**Comment by shuenSL** [comment]
Hello, I too need the ability to specify my geolocation badly. I enabled ARM support but encountered the following errors. I see the folder .\infra\azure\parameters was created but it is empty. Please advise. Thanks.
....
[Error] - [Teams Toolkit] Failed to get expanded parameter from c:\_codes\sample01\infra\azure\parameters\parameters.template.json.
[Error] - fail to provision 'sh-sample01' in the cloud!
....
....
[Info] - [core] finish task:provisionResources
[Error] - code:Teams Toolkit.FailedToDeployArmTemplatesToAzure, message: ENOENT: no such file or directory, open 'c:\_codes\sample01\infra\azure\parameters\parameters.template.json', stack: FailedToDeployArmTemplatesToAzure: ENOENT: no such file or directory, open 'c:\_codes\sample01\infra\azure\parameters\parameters.template.json'

**Comment by MuyangAmigo** [comment]
Just want to make some more updates in this thread: 
* As we have made several updates to ARM support, it should be more stable and resilient for now. Please use the latest version of [Teams Toolkit (Ver. 2.9.0)](https://marketplace.visualstudio.com/items?itemName=TeamsDevApp.ms-teams-vscode-extension) and follow this [Wiki Page](https://github.com/OfficeDev/TeamsFx/wiki/Enable-Preview-Features-in-Teams-Toolkit) to enable the insider feature.
* There are changes to the file structure, so it might be better to create a new project. But Toolkit also provides help to upgrade your old project to adapt to the new file structures, you can read more about the upgrading [here](https://github.com/OfficeDev/TeamsFx/wiki/Upgrade-project-to-use-latest-Toolkit-features)

I'm closing this thread for now, but feel free to report any issues you have encountered with the insider features.

Thanks a lot for the interest and continuous feedback!

**Comment by KristapsD** [comment]
@MuyangAmigo When trying to provision into a rg. it's showing me this error in the activity log of specified rg.

Deployment template validation failed: 'The template parameters 'identity_managedIdentityName' in the parameters file are not valid; they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'resourceBaseName, frontendHosting_storageName, m365ClientId, m365ClientSecret, m365TenantId, m365OauthAuthorityHost, function_serverfarmsName, function_webappName, function_storageName, simpleAuth_sku, simpleAuth_serverFarmsName, simpleAuth_webAppName, simpleAuth_packageUri'. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.

**Comment by blackchoey** [comment]
@KristapsD Can you remove `identity_managedIdentityName` from `.fx/config/azure.parameters.{your_env_name}.json` and try again? ARM does not allow passing extra parameters when provision. According to the error message, `identity_managedIdentityName` does not exist in the ARM template (authored in bicep) so it cannot be included in `.fx/config/azure.parameters.{your_env_name}.json`.

By the way, can you help recall what modifications have you made to `.fx/config/azure.parameters.{your_env_name}.json` and bicep files under `templates/azure/`? So I can try to figure out how can I improve your experience on such kind of errors. Thanks!
