### ISSUE TITLE
code:BT.PreconditionError, message: 'subscription id' is missing.

### ISSUE THREAD

**Issue by ianbroad** [OfficeDev/TeamsFx#1851]
I modified my code and I'm trying to 'Deploy to the Cloud', but I receive the following error:

code:BT.PreconditionError, message: 'subscription id' is missing. Suggestions: Please click 'Get Help' button for more details. Please retry the current step.

I did change our plan from the Free version to the Basic version, so the service could be 'Always On'. Is this what's causing this error?

Where do I set the missing subscription id?

The subscriptionInfo.json file seems to contain the correct information, so I'm not sure what's going on?

**Comment by xiaolang124** [comment]
Our guess is that the subscription is not specified correctly. Can you try the following steps to see if it can solve your issue?
1. Use treeView to login Azure account.
2. Select subscription by clicking this button.
![image](https://user-images.githubusercontent.com/13211513/128476500-28411d17-81f1-4580-95cb-9ca330315b66.png)
3. Try to deploy.
To optimize our workflow to provide better user experience, we will fix this in a few days.

**Comment by ianbroad** [comment]
That did work! Thank you

**Comment by adashen** [comment]
close as it already solved.
