### ISSUE TITLE
[Incident Notification] new bug report: AppStudioPlugin.LocalAppIdCreateFailed

### ISSUE THREAD

**Issue by shishiradas** [OfficeDev/TeamsFx#1852]
Failed to create localDebug teams app id in app studio.

undefined

**Comment by SLdragon** [comment]
Same here
```
[2021-08-06T01:57:05.056Z] [Error] - code:AppStudioPlugin.LocalAppIdCreateFailed, message: Failed to create localDebug teams app id in app studio.
```

**Comment by shishiradas** [comment]
It was working perfectly fine till a while ago. I just updated the name of the Personal Tab in manifest and started seeing this issue again and again. I pulled back my changes, tried clearing all cache but now luck. Completely blocked

**Comment by zhenjiao-ms** [comment]
@shishiradas thanks for reporting it and very sorry for the inconvenience to you. It seems like an live site incident in the underlying app studio service, we are actively working on it, will keep updating the status in this issue.

**Comment by shishiradas** [comment]
Thanks a lot for the update. Will be looking forward to the fix

**Comment by eriolchan** [comment]
@shishiradas we have release a hotfix Teams Toolkit v2.3.2 to fix this issue. You can download the latest version from marketplace or VSCode will auto-upgrade this extension. Feel free to try it again and provide your feedback.
