### ISSUE TITLE
Local Debug Feature (f5) not working in VsCode "Manifest parsing has failed."

### ISSUE THREAD

**Issue by capjonathanyoung** [OfficeDev/TeamsFx#1871]
**Describe the bug**
Starting this week, the local debug feature stopped working for me even from a newly generated app. 

**To Reproduce**
1. Generate a new Project with Tab capability
2. Run the project with F5 in Visual Studio Code
3. Pass SSO
4. I get the messages : 
- Manifest parsing has failed.
- Error while reading manifest.json: Unable to validate your app package. Please try again later.

**Expected behavior**
No Error Message and i can install the App in local Teams.

**Screenshots**
![image](https://user-images.githubusercontent.com/52447403/128549250-139ffa11-0af4-4b66-a296-92dfa75e0457.png)

**VS Code Extension Information (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Version [e.g. 22] 2.3.2

**CLI Information (please complete the following information):**
 - OS: [e.g. iOS8.1] Windows 10
 - Version [e.g. 22] 0.3.1

**Additional context**
When trying the same steps on a project that was working last week i get the same Error. 
Below is the manifest extracted from App Studio: 
```
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json",
  "manifestVersion": "1.9",
  "version": "1.0.0",
  "id": "567dadc4-d485-4f15-b298-ee09618fd662",
  "packageName": "com.microsoft.teams.extension",
  "developer": {
    "name": "Teams App, Inc.",
    "websiteUrl": "https://localhost:3000",
    "privacyUrl": "https://localhost:3000/index.html#/privacy",
    "termsOfUseUrl": "https://localhost:3000/index.html#/termsofuse"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "mybug-local-debug",
    "full": ""
  },
  "description": {
    "short": "Short description of mybug.",
    "full": "Full description of mybug."
  },
  "accentColor": "#FFFFFF",
  "configurableTabs": [
    {
      "configurationUrl": "https://localhost:3000/index.html#/config",
      "canUpdateConfiguration": true,
      "scopes": [
        "team",
        "groupchat"
      ]
    }
  ],
  "staticTabs": [
    {
      "entityId": "index",
      "name": "Personal Tab",
      "contentUrl": "https://localhost:3000/index.html#/tab",
      "websiteUrl": "https://localhost:3000/index.html#/tab",
      "scopes": [
        "personal"
      ]
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "localhost:3000",
    "localhost"
  ],
  "webApplicationInfo": {
    "id": "f370f720-a12e-425d-9364-09614657319d",
    "resource": "api://localhost/f370f720-a12e-425d-9364-09614657319d"
  }
}
```

**Comment by zhenjiao-ms** [comment]
@capjonathanyoung thanks for reporting it. I tried it in v2.3.2 but cannot reproduce it, so @kimizhu could you please help to do further investigations? If we still cannot reproduce this issue, @capjonathanyoung could you please do us a favor to paste the error details here by clicking the "copy error details to clipboard" as below? Thanks.
![image](https://user-images.githubusercontent.com/14193223/128653440-e8656325-f3c2-4901-a0ab-6a93f0ff28ca.png)

**Comment by capjonathanyoung** [comment]
@zhenjiao-ms The message i get is : 
"Error while reading manifest.json: Unable to validate your app package. Please try again later."

**Comment by capjonathanyoung** [comment]
@zhenjiao-ms Little update : 
I tried creating a new app on another computer with the same characteristics and software version installed (Teamsfx version, node version, vscode extension version). I get the same Error. 

The only thing in common was the teams tenant i was deploying to and the windows account used to log in. 

So i tried creating a developer sandbox with https://developer.microsoft.com/en-us/microsoft-365/dev-program 
On the new sandbox, everything works. 

Any idea how i can pinpoint what is wrong with my regular teams organisation (I do not have Admin rights) ?

**Comment by zhenjiao-ms** [comment]
@capjonathanyoung thanks for the additional information, very helpful. It doesn't need admin permission to get it run. For the error message you provided, @asnow003, do you have any insight of what the problem is?
