### ISSUE TITLE
Feature suggestions on Teams

### ISSUE THREAD

**Issue by paorodma-ms** [OfficeDev/TeamsFx#1913]
I recently hosted a virtual event on my personal Teams account. These are some features that can be useful to include:
 1 - When people log in from a mobile device only a part of their camera is shown. Each person needs to right click on the user's image and select "Fit to frame" in order for it to show the whole scene or all people on the camera. It would be good to have an option as the host to have people join with "Fit to frame" as default and make this replicate on all participants' views. To counteract this effect, I tried sharing my screen with people's images fitted to frame, but did not have time to do it with all since there were many.
2 - When there are many people connected there is no way to see everyone's camera, it would be good to have a sorting option, like connection time or name and then some way to navigate through all connections (like pagination), so you can capture a screenshot of everyone attending. Like a picture. An extra option would be to choose how many people you want to see per page, like 9,12,16, etc.
3 - As the host I am able to spotlight myself for everyone but my own image shows really small, so I can't see what other's are seeing. There should be a way where I can see myself large onscreen, so I know others can see what I want to show.
4 - Guests are unable to react to a message in the chat, it would be useful to allow them to do that. 
5 - There is no way of recording an event with Teams using a personal account, I would have been willing to pay for the recording of that one event. That could be considered to include it in a subscription like OneDrive Family or a pay per event sort of thing.

**Comment by yanjiang222** [comment]
Thanks for your feedback @paorodma-ms. As I look into your problems, these looks more like Teams client problems. You can report Teams client based problems by clicking the left bottom "help" in Teams client and then choose "report a problem". This is repo is for TeamsFX which is a tooling of making Teams app and in general isn't used by Teams developer instead of Teams users. Please let me know if you have more questions.
