### ISSUE TITLE
new bug report: aad.AadGetAppError

### ISSUE THREAD

**Issue by LALITAMITTAL18** [OfficeDev/TeamsFx#1946]
Failed to get app info with current Object Id in env.default.json. Please make sure object id is valid, or delete 'objectId' under fx-resource-aad-app-for-teams in env.default.json and try again. Detailed error: Request failed with status code 500. Reason: Resource '608497e7-223b-4d10-bf32-e8705210896b' does not exist or one of its queried reference-property objects are not present.

undefined

**Comment by KennethBWSong** [comment]
Hi @LALITAMITTAL18. Thank you very much for your feedback. 
Main cause of this error is that toolkit can not find the AAD app in your current tenant. This may comes from logging in with a different account or some network issue. 
Would you please make sure the account is correct and trigger provision again?

**Comment by LALITAMITTAL18** [comment]
Yes, I created the app with my default tenant and then when I was provisioning, I signed out and sign in to my dev tenant. I am no longer now able to debug the solution. I do not want to switched back to my default tenant, what changes I can do in order to make my solution to get the new values for my dev tenant.
Also I see two different tenant id in env.default.json and default.userdata. But in my opinion that should be fine as the first one is for provisioning your solution and the later one is for your local debug.  Could you please correct me where I am doing wrong. I want to debug the solution.

**Comment by KennethBWSong** [comment]
Hi @LALITAMITTAL18. Thank you for your reply!
To clarify your first question, I want to ask two more quesions:
1. Do you only switched your M365 account? Or you want to switch your Azure account also?
2. Do you want to keep your local environment?

For tenant id, we are saving two tenant ids currently:
1. "solution.teamsAppTenantId" in "default.userdata" is the tenant id of your teams app and Azure AD app, which is the same as the M365 account you logged in when provisioning/running local debug.  
2. "tenantId" under "solution" in "env.default.json" is for the tenant id of your provisioned resources on Azure which is the same as the Azure account when provisioning.

**Comment by LALITAMITTAL18** [comment]
I switched off both my accounts M365 and Azure 
![image](https://user-images.githubusercontent.com/51710902/129694078-65a14ba0-e7c1-4308-989e-4194a77d0ae9.png)

When I do Launch Remote (Chrome), it takes the right account and my  extension works:

![image](https://user-images.githubusercontent.com/51710902/129694327-bd98c5ed-ab03-4b24-80f5-35a8f2f85499.png)

But when I do Launch debug (chrome) it gives me the error I reported above and says that app not found.

![image](https://user-images.githubusercontent.com/51710902/129694593-0d8bcdcb-3e72-4c9e-ae4e-1925935bb4db.png)

**Comment by KennethBWSong** [comment]
Hi @LALITAMITTAL18. Thank you for your reply!
The main reason is that you logged in with a different M365 account, and our toolkit can not find the Azure AD app under your current tenant.
To fix this, you need to remove the existing configs for local debug. Please follow the steps below:
1. Remove all configs with "local" prefix under "fx-resource-aad-app-for-teams" in "env.default.json"
2. If bot enabled, remove all configs with "local" prefix under "fx-resource-bot" in "env.default.json"
3. Remove all configs that start with "fx-resource-aad-app-for-teams.local" prefix in "default.userdata"
4. If bot enabled, remove all configs with "fx-resource-bot" prefix in "default.userdata"
5. Remove "solution.localDebugTeamsAppId", "solution.teamsAppTenantId" in "default.userdata"

After the steps above, please check your account is correct and try to launch local debug again tand our toolkit should successfully create a new local debug env for you.

**Comment by LALITAMITTAL18** [comment]
Awesome. I am able to debug again my solution. Thanks a lot :-)
