### ISSUE TITLE
Debug doesnt work when creating message extension and tab capabilities together

### ISSUE THREAD

**Issue by LALITAMITTAL18** [OfficeDev/TeamsFx#1974]
**Describe the bug**
Debugger doesnt get attached

**To Reproduce**
1. create new teams app
2. Select Tab and Message extension as capability
![image](https://user-images.githubusercontent.com/51710902/129901134-711ced0f-bc93-4b53-b069-8e8ca76afd61.png)
3. select create new bot registration
4. Select typescript in language and create the teams app.
5. Place degugger in tabs\src\components\App.tsx and bot\index.ts and hit f5
6. open the app from chat
![image](https://user-images.githubusercontent.com/51710902/129902254-fb8f1389-ccc6-406c-a275-2e792693ab5c.png)

7. in code:
![image](https://user-images.githubusercontent.com/51710902/129902172-1fe7ea39-8be1-4b4c-ae7d-791bfaae852b.png)

8. when you close the browser, you receive below screen:

![image](https://user-images.githubusercontent.com/51710902/129900510-2b84bb61-2788-44ac-8461-464f6ee71c5b.png)

**Expected behavior**
debugger should get hit

**VS Code Extension Information (please complete the following information):**
 
![image](https://user-images.githubusercontent.com/51710902/129902706-dd5d22bd-a969-4e15-b983-1ac069f10dfe.png)

**Comment by kuojianlu** [comment]
@LALITAMITTAL18 Thanks for reporting the issue. The reason is that the bot service was not started successfully.
- Can you always reproduce this issue?
- Could you please provide the screenshots of `start ngrok` and `bot start` terminal (like the images below)?

![image](https://user-images.githubusercontent.com/37978464/130001445-1857c4c0-499d-45d0-b77c-f608e933d2ad.png)

![image](https://user-images.githubusercontent.com/37978464/130001480-7b8384f9-a522-4afe-8a92-25d50f924c38.png)

**Comment by LALITAMITTAL18** [comment]
Yes, I could always reproduce the issue till yesterday. Now its all working. I tested my old solutions and created new solution. Not able to reproduce the issue. So I think its resolved. If I see that issue again I will provide you the information you requested.

**Comment by LALITAMITTAL18** [comment]
I am having this issue again,  I re-started my laptop several times. As you asked earlier I can see ngrok start never finish. it keeps loading forever: what can i do to resolve this. Now Teams toolkit solution not working at all, even the new one.

![image](https://user-images.githubusercontent.com/51710902/130781281-ce55b633-bae3-484f-acbc-c67828d5d0e8.png)

**Comment by LALITAMITTAL18** [comment]
The ngrok is very unstable. If there is a lucky day it starts and work perfectly and now it just dont start, just get stuck. 

![image](https://user-images.githubusercontent.com/51710902/131300674-23f783cb-1812-4b6f-8ae8-be2874ccf4ac.png)

**Comment by kuojianlu** [comment]
@LALITAMITTAL18 I am not sure why the "start ngrok" task is unstable for you. I will reopen this issue for track. We will deep into this bug. There is a **workaround** you can do to **bypass this issue**, please refer to [this help doc](https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/localdebug-help.md#what-to-do-if-i-want-to-use-my-own-tunneling-service-instead-of-the-built-in-one-for-bot-or-messaging-extension). By the way, the command to start ngrok is `ngrok http 3978 --log=stdout` if you have ngrok globally installed, or `npx ngrok http 3978 --log=stdout` if not.

**Comment by kuojianlu** [comment]
@LALITAMITTAL18 Did you ever encounter the same issue if you run `ngrok http xxx` in a terminal?

**Comment by LALITAMITTAL18** [comment]
Nop. I can successfully start ngrok using the above command.

**Comment by kuojianlu** [comment]
@LALITAMITTAL18 I am not sure whether it is ngrok command that makes ngrok stuck. What I want to know is that whether you can reproduce it by manually running `ngrok http 3978 --log=stdout` in a terminal  outside VSCode.

However, if you encounter this issue again, you can refer to[ this help doc](https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/localdebug-help.md#what-to-do-if-i-want-to-use-my-own-tunneling-service-instead-of-the-built-in-one-for-bot-or-messaging-extension) to **bypass it**.
