### ISSUE TITLE
teamsfx account set --subscription

### ISSUE THREAD

**Issue by iliasjennane** [OfficeDev/TeamsFx#1993]
I am trying to set the Azure subscription for using teamsfx, I am getting the following error:
teamsfx account set --subscription ************
**Error: [TeamsfxCLI.ConfigNotFound]: Config file C:\repos\skilltopia\.fx\env.default.json does not exists**

**Comment by Alive-Fish** [comment]
Hi @iliasjennane , thanks a lot for your feedback.

It seems that you run `teamsfx account set --subscription` under a non-teamsfx project, so Teams Toolkit CLI could not find the configuration file under your current working directory. This command just sets the subscription to this specified project. You can try to run this command under a Teamsfx project.

**Comment by iliasjennane** [comment]
> Hi @iliasjennane , thanks a lot for your feedback.
> 
> It seems that you run `teamsfx account set --subscription` under a non-teamsfx project, so Teams Toolkit CLI could not find the configuration file under your current working directory. This command just sets the subscription to this specified project. You can try to run this command under a Teamsfx project.

This is not working as well, unfortunately.

**Comment by Alive-Fish** [comment]
Sorry for any convenience. As we talked in the email thread, the Teams Toolkit CLI does more for JS/TS projects created by Teams toolkit. Running these commands in the C# project will meet unexpected problems. Some of us are talking about this scenario and thinking more about Dotnet + CLI.

**Comment by iliasjennane** [comment]
Thank you for the clarification

**Comment by adashen** [comment]
close as it is resovled
