### ISSUE TITLE
Filter and Pagination on Search Message extension

### ISSUE THREAD

**Issue by LALITAMITTAL18** [OfficeDev/TeamsFx#2038]
**Is your feature request related to a problem? Please describe.**
I am using Search Message extension to create my app, I also want a way to filter and provide pagination option as well to my user. I coudn't find a clear document if that is achievable. Something like this:

![image](https://user-images.githubusercontent.com/51710902/130623236-dad8324e-8d7f-4acf-88df-2746615ca7b2.png)

**Describe the solution you'd like**
events for filter and pagination.

**Describe alternatives you've considered**
Web based task action message extension.

**Comment by MuyangAmigo** [comment]
Hey @LALITAMITTAL18, [StackOverFlow](https://stackoverflow.com/questions/tagged/teams-toolkit) might be a better place for this question as you can get more insights with real examples from more developers and Teams / Bot Framework experts.

**Comment by adashen** [comment]
Close as we will discuss in stackoverflow
