### ISSUE TITLE
 Get SSO token failed with error: App resource defined in manifest and iframe origin do not match

### ISSUE THREAD

**Issue by KristapsD** [OfficeDev/TeamsFx#2039]
**Describe the bug**
Not being able to get the SSO token, with the error:
Get SSO token failed with error: App resource defined in manifest and iframe origin do not match

**To Reproduce**
1. register app in AAD, configure it for multitenancy
3. add the webApplicationInfo object in project manifest, with registered app info
4. create a teamsusercredential object in code
5. try to log in with it in code
6. provision & deploy the project
7. install the appPackage to your teams (web version to see console)
8. launch the app in teams look for the error when it tries to log in with the teamsusercredential object

**Expected behavior**
getting the SSO token from logging in

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: windows 10
 - Version 2.5.0

**CLI Information (please complete the following information):**

**Additional context**
I'm thinking this might be an issue with the newest version for teams toolkit, that was released yesterday, because the installed app on teams worked yesterday, before the new update, for one of my colligues who tested my teams app.
The error also doesn't appear at all whenever i "f5" debug it locally.

**Comment by blackchoey** [comment]
Hi @KristapsD thanks for reaching us. Per your description, you're creating / updating the AAD application, and Teams app manifest file by yourself manually, am I understanding correctly?
If yes, you may need to check the content of `webApplicationInfo` object manually. The expected value for it is:
```
"webApplicationInfo": {
    "id": "{AAD App client id}",
    "resource": "api://{Your tab app domain}/{AAD App client id}"
  }
```
If the the domain in `webApplicationInfo` is not same with your tab app's domain, Teams will return an error to you.

If my understanding is not correct, can you share more details on the repro steps? A sample project that can help us repro this issue would also be helpful.

**Comment by KristapsD** [comment]
hi @blackchoey, if im understanding what you suggested, then if my tab app is hosted on azure on a domain, in my case this: eparakstsfe0121b2.z13.web.core.windows.net, so the app domain in webApplicationInfo should also be the same?
If that's the case then we need to add the mentioned domain as a verified domain to our AAD tenant, but he say's that we can't do it since it doesn't belong to us.

**Comment by hund030** [comment]
@KristapsD It's possible to use your own domain for tab frontend.
1. Follow this [docs](https://docs.microsoft.com/en-us/azure/storage/blobs/static-website-content-delivery-network#enable-azure-cdn-for-your-static-website) to enable CDN for your frontend storage. 
2. Then setup custom domain in your CDN. 
3. Finally update the frontend endpoint and domain with your custom endpoint/domain in .fx/env.default.json and re-provision your project. All configs should be update with your custom domain.

![image](https://user-images.githubusercontent.com/26134943/131811897-581f3125-6577-4ddd-a07f-a0c337c24955.png)

**Comment by KristapsD** [comment]
OK, after doing what @hund030 suggested, everything works the way it should, thank you for your help. Though i think that the fact that the apps domain and AAD registered apps domain needs to be the same should be mentioned somewhere in the documentations, if it already isn't mentioned and i just missed it somewhere. I also had to enable CORS for my domain on the automatically provisioned SA app service.

**Comment by omrihaim** [comment]
@blackchoey how does you suggestion above apply for local testing of an app?
While we've assumed we will be able to use the production flow, we get the error above:
"App resource defined in manifest and iframe origin do not match"

**Comment by blackchoey** [comment]
@omrihaim The error indicates the tab app domain configured in Teams app manifest does not match the actual domain of the tab app. You can check below content in your Teams app manifest:
```
"webApplicationInfo": {
    "id": "{AAD App client id}",
    "resource": "api://{Your tab app domain}/{AAD App client id}"
  }
```
In local testing scenario, the domain usually starts with `localhost`.

**Comment by omrihaim** [comment]
Thanks @blackchoey but can you please show what do you mean the actual domain of the tab app.
Where is the domain that is not in the webApplicationInfo? How is it configured?
Thanks in advance.

**Comment by blackchoey** [comment]
@omrihaim Usually you will configure your tab app url to Teams app manifest like following:
```
"staticTabs": [
        {
            "entityId": "index",
            "name": "Personal Tab",
            "contentUrl": "https://localhost:53000/index.html#/tab",
            "websiteUrl": "https://localhost:53000/index.html#/tab",
            "scopes": [
                "personal"
            ]
        }
    ],
```

For above example, the expected `webApplicationInfo` in Teams app manifest is (please update the AAD app id accordingly) :
```
    "webApplicationInfo": {
        "id": "66064627-734b-433c-8668-0ed33441846f",
        "resource": "api://localhost:53000/66064627-734b-433c-8668-0ed33441846f"
    }
```

Are you building your own Teams app project (not created by Teams Toolkit) with Teams Toolkit? Or you created a project with Teams Toolkit but didn't get enough information / guide about how it works? This could help us optimize our production if you can share. Thank you.
