### ISSUE TITLE
Visual Studio 2022 support

### ISSUE THREAD

**Issue by thomyg** [OfficeDev/TeamsFx#2051]
Any plans, updates or statements you can share according to Visual Studio 2022 already? 
Will the extension be available at some point during the preview phase? 
Will it be available when VS 2022 hits GA? 
Should we stick to 2019 for the foreseeable future?

**Comment by mcmpistachio** [comment]
Is 17.1.0 still the target or is the toolkit still on the backlog?

**Comment by thomyg** [comment]
The 17.1 preview is now out roughly for a month. Still no support for installing the extension in VS 2022?
