### ISSUE TITLE
Adaptive card on Select Item event of Search Message Extension

### ISSUE THREAD

**Issue by LALITAMITTAL18** [OfficeDev/TeamsFx#2074]
I am trying to return an adaptive card when search result is selected in Search Message extension. Below is my class to return the card:

    import { IEntity } from '../model/IEntity';
    import { Attachment, CardFactory } from "botbuilder";
    
    export class AccountResultCard {
    
        public static getCard(account: IEntity): Attachment {
    
            // Get map
            let logo = `https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg`;
            let url = `https://pbs.twimg.com/docs/test.aspx?GoPage=AccountCard.aspx?AccountID='${account.ID}'&_Division_='${account.Division}'`;
            const accountDetail = account.Code ? account.Code + ' - '  + account.Description : '';
            const accountcontextinfo1 = account.ContextInfo[1] ? account.ContextInfo[1] : '';
            const accountcontextinfo2 = account.ContextInfo[3] ? account.ContextInfo[3] + ' '+ account.ContextInfo[2] : '';
    
            
            const card =  CardFactory.adaptiveCard(
                {
                    "type": "AdaptiveCard",
                    "body": [
                        {
                            "type": "TextBlock",
                            "size": "Large",
                            "weight": "Bolder",
                            "text": "Title"
                        },
                        {
                            "type": "TextBlock",
                            "size": "Medium",
                            "weight": "Bolder",
                            "text": accountDetail
                        },
                        {
                            "type": "ColumnSet",
                            "columns": [
                                {
                                    "type": "Column",
                                    "items": [
                                        {
                                            "type": "TextBlock",
                                            "text": accountcontextinfo1,
                                            "wrap": true
                                        },
                                        {
                                            "type": "TextBlock",
                                            "spacing": "None",
                                            "text": accountcontextinfo2,
                                            "wrap": true
                                        },
                                        {
                                            "type": "TextBlock",
                                            "spacing": "None",
                                            "text": "Missing state and country",
                                            "wrap": true
                                        }
                                    ],
                                    "width": "stretch"
                                },
                                {
                                    "type": "Column",
                                    "items": [
                                        {
                                            "type": "Image",
                                            "style": "Person",
                                            "url": logo,
                                            "size": "Small"
                                        }
                                    ],
                                    "width": "auto"
                                }
                            ]
                        }
                    ],
                    "actions": [
                        {
                            "type": "Action.OpenUrl",
                            "title": "Open in Aurora",
                            "url": url,
                            "width": "Small",
                            "style": "default"
                        }
                    ],
                    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                    "version": "1.2"
                }
            );
    
            return card;
        }
    }

and below is my select item event:

     public async handleTeamsMessagingExtensionSelectItem(
        context: TurnContext,
        obj: any
      ): Promise<any> {
       const item = this.response.find(e => e.ID == obj.name) 
        return {
          composeExtension: {
            type: "result",
            attachmentLayout: "list",
            attachments: [AccountResultCard.getCard(item)],
          },
        };
      }

But it never return anything. I deleted everything from get card and sent just a one single text block with hard coded value in body. That also didn't work.Can you guys suggest me where I am doing wrong.

**Comment by LALITAMITTAL18** [comment]
Finally I was able to start ngrok and debug my code again, here is the debug results for Card : 
![image](https://user-images.githubusercontent.com/51710902/131302119-3db9b943-e1d0-4fb5-81d0-7683febc4b52.png)

and I see its a valid card with valid values inside, all variables calculated correctly, but i see nothing on the chat:

![image](https://user-images.githubusercontent.com/51710902/131302241-c43aebbd-faaa-4761-a935-3ed72309c0f4.png)

**Comment by YitongFeng-git** [comment]
@LALITAMITTAL18 Any error message in your "Debug" console or "Terminal" console after you F5 and start your code?

**Comment by LALITAMITTAL18** [comment]
Nop, nothing. it remain same in Terminal

![image](https://user-images.githubusercontent.com/51710902/131318247-f760aaff-4912-4902-bd86-a02b1771d402.png)

**Comment by YitongFeng-git** [comment]
Hi, @LALITAMITTAL18 as in adaptive card there is no "Title" field, you should use hero card as preview, you can write your return clause in `handleTeamsMessagingExtensionSelectItem` as the following:
```
return {
      composeExtension: {
        type: "result",
        attachmentLayout: "list",
        attachments: [{preview: CardFactory.heroCard("title", ""),
          ...yourAdaptiveCard}],
      },
    };
```

**Comment by LALITAMITTAL18** [comment]
Awesome, worked without any issue. Thanks for helping me out.
