### ISSUE TITLE
Dot Net core install fail in macOS with m1 cpu

### ISSUE THREAD

**Issue by zhv9** [OfficeDev/TeamsFx#2093]
**Describe the bug**

I am using a mac with m1 CPU.

Fail to install .Net core when debugging the Typescript app which was created by vscode teams toolkit extension.

**To Reproduce**
1. Go to Teams Toolkit(v2.5.0)
2. Click on Create a new Teams app
3. Select `Create a new Teams app -> Tab -> Azure -> no resource -> Typescript`
4. Goto App code then Debug with Edge
5. The Output of "Teams Toolkit" have below errors

```
dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.412/dotnet-sdk-3.1.412-osx-arm64.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.412/dotnet-sdk-3.1.412-osx-arm64.tar.gz is not available.
dotnet-install: Downloading legacy link https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.412/dotnet-dev-osx-arm64.3.1.412.tar.gz
curl: (22) The requested URL returned error: 404 
dotnet-install: The resource at https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.412/dotnet-dev-osx-arm64.3.1.412.tar.gz is not available.
', stderr = 'dotnet_install: Error: Could not find `.NET Core SDK` with version = 3.1.412
dotnet_install: Error: Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
', timecost = '14.23s'
```

**Expected behavior**

No errors.

**Screenshots**

NA

**VS Code Extension Information (please complete the following information):**
 - OS: macOS Big Sur 11.5.2
 - Version V2.5.0

**CLI Information (please complete the following information):**
 - OS: macOS Big Sur 11.5.2
 - Version: NA

**Additional context**

node version: V16.3.0

**Comment by meifans** [comment]
Thanks @zhv9 for the feedback!

Currently neither .NET 5.0 SDK or .NET Core 3.1 SDK supports M1 Mac. You can see [this GitHub issue](https://github.com/dotnet/core/issues/4879) or our docs about [DotNet M1](https://github.com/OfficeDev/TeamsFx/blob/main/docs/vscode-extension/envchecker-help.md#how-to-install-net-sdk) to learn more about it.

A workaround: install dotnet manually([how to install dotnet sdk](https://github.com/OfficeDev/TeamsFx/blob/main/docs/vscode-extension/envchecker-help.md#how-to-install-net-sdk)) and teamstoolkit will use dotnet sdk on your machine.

Feel free to try it and provide your feedback.
