### ISSUE TITLE
publisher should be microsoft

### ISSUE THREAD

**Issue by zhenyasav** [OfficeDev/TeamsFx#2289]
https://github.com/OfficeDev/TeamsFx/blob/7171991f445a437053afa27c29bf0a5b9014c002/packages/vscode-extension/package.json#L6

**Comment by zhenjiao-ms** [comment]
@zhenyasav This is the publisher id for publishing this extension to VS Code marketplace, which was setup by Karthig from beginning. In marketplace page, the name is shown as Microsoft.
