### ISSUE TITLE
bug report: unknown.Error

### ISSUE THREAD

**Issue by TanglingTreats** [OfficeDev/TeamsFx#2296]
{"error":{}}

stack:
Error: {"error":{}}
    at Object.assembleError (<REDACTED: user-file-path>:2:4616393)
    at FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path>:2:4720405)

I received this error message while I was trying to debug the application after adding a static tab on top of the default one. 

Any advice on this?

**Comment by jayzhang** [comment]
@TanglingTreats Thank you for feedback, we are investigating this issue.

**Comment by TanglingTreats** [comment]
I'd be glad to provide more information if needed. The error has since not appeared a little while after I submitted this bug report.
I'm also unable to replicate the issue.

**Comment by adashen** [comment]
close as cannot reproduce
