### ISSUE TITLE
Running locally overwrites Developer Portal settings

### ISSUE THREAD

**Issue by NiclasMolby** [OfficeDev/TeamsFx#2316]
**Describe the bug**
I've made a teams app using tabs, and are trying to manage the manifest through the dev.teams.microsoft portal. So I've created a developer environment for localhost and used the templating strings the necessary places. However, whenever I run the app locally through VS Code by pressing F5, it overwrites or resets some of the settings in the developer portal. 

Most importantly, it removes all environments I've created. So when I download the app as a zip, the manifest will contain the template string. Ex: "websiteUrl": "{{url}}" instead of "websiteUrl": "https://localhost".

Additionally it resets the app names to **\*name-of-app\*-local-debug**.

I've concluded that it is due to the **prepare local environment** VSCode task, as when i exclude that from the the debug session, it does not alter the Developer Portal settings.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10
 - Version 2.6.0

**Comment by yanjiang222** [comment]
@NiclasMolby Thank you very much for reporting this to us. As we investigate why this came up for you so, it would be immensely helpful if we could understand a couple things:

-  "So I've created a developer environment for localhost", what kind of developer environment are you referring to? 
-  "used the templating strings the necessary places.", do you mean use the templating string in the manifest file?
-  Can you also tell us which manifest file were you trying to edit? 

Thank you so much for any insights you can share, and please let us know if you have any questions.

**Comment by NiclasMolby** [comment]
- "So I've created a developer environment for localhost", what kind of developer environment are you referring to?
  - I'm just referring to an environment in the app which I've called "development" as described here [https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal#set-up-an-environment](url)
- "used the templating strings the necessary places.", do you mean use the templating string in the manifest file?
  - Yes, or in the browser interface. As described here under "To use variables" [https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/teams-developer-portal#set-up-an-environment](url)
- Can you also tell us which manifest file were you trying to edit?
  - The app manifest describing my Teams app. The manifest file, which the Developer Portal attempts to be a GUI for.
 
Hope this clears up any confusions

**Comment by yanjiang222** [comment]
Thanks for the clarification and giving us the feedback! @NiclasMolby

By reading your feedback, my understanding is that you created a teams app on dev portal as well as in the Teams toolkit for VS code. And even if you changed the manifest on the dev portal, when you F5 and do local debug in VS code, it automatically overwrite the settings you did for dev portal. Is my understanding correct?

We are still keep iterating our product. At the moment, local debug in the VS code team toolkit will automatically update the manifest in the dev portal to reflect the changes. We're planning to add new features to allow users to update the manifest file in dev portal whenever they want to. Please stay tuned. 

Would you mind tell us more about your scenario like why you want to change the manifest file for your local debug? 

If you have more feedbacks, please let us know! Really appreciate your interest in the toolkit!

**Comment by NiclasMolby** [comment]
By reading your feedback, my understanding is that you created a teams app on dev portal as well as in the Teams toolkit for VS code. And even if you changed the manifest on the dev portal, when you F5 and do local debug in VS code, it automatically overwrite the settings you did for dev portal. Is my understanding correct? **Mostly. I've created a teams app with the Teams toolkit for VS code, which created an app on the dev portal for me. Yes, any changes I make in the dev portal are overwritten when i F5 and do local debugging in VS code.**

We are still keep iterating our product. At the moment, local debug in the VS code team toolkit will automatically update the manifest in the dev portal to reflect the changes. We're planning to add new features to allow users to update the manifest file in dev portal whenever they want to. Please stay tuned. **If it is intended to overwrite the settings in the dev portal, I must have misunderstood something. Is the dev portal not meant to be the editor of the manifest file? By overwriting changes in the dev portal kind of defeat its purpose then. Especially overwriting environments. Or maybe I'm doing something wrong locally?**

Would you mind tell us more about your scenario/information like what you want to change for the manifest file of your local debug and why? We want to keep improving the feature regarding the manifest file. **I don't want to change my local manifest and I don't do it. I want to handle it through the dev portal. But as stated earlier, when I do local debugging with F5, the dev portal is overwritten.**

**Comment by yanjiang222** [comment]
Thanks for the clarification! 

Mostly. I've created a teams app with the Teams toolkit for VS code, which created an app on the dev portal for me. Yes, any changes I make in the dev portal are overwritten when I F5 and do local debugging in VS code. **Yes, when you do local debug, Teams toolkit will overwrites the config of the app in the dev portal to make local debugging works.** 


If it is intended to overwrite the settings in the dev portal, I must have misunderstood something. Is the dev portal not meant to be the editor of the manifest file? By overwriting changes in the dev portal kind of defeat its purpose then. Especially overwriting environments. Or maybe I'm doing something wrong locally?**Actually, developers have two independent ways to update the manifest. One is through dev portal and the other way is through the toolkit. Local debugging is a bit different and it relies on the app created in the dev portal to work. that's why it get updated when users do F5. However, if you deploy your app to a remote cloud backend, the teams toolkit won't update the manifest. **

I don't want to change my local manifest and I don't do it. I want to handle it through the dev portal. But as stated earlier, when I do local debugging with F5, the dev portal is overwritten. If something should happen to it, it should be synched with the manifest on the dev portal whenever i debug with F5. So that the local is overwritten by the dev portal and not the other way around. **The manifest you were trying to edit by dev portal is the app for local debugging. If you can kindly let us know what you want to change particularly for the manifest to understand your scenario further, that would be very helpful.**

**Comment by NiclasMolby** [comment]
Okay, so to be clear.
The app I have in the dev portal is only for debugging?
So when I want to deploy my app to a test server or production, I should create a seperate app on the dev portal for that purpose? So I would have 2 or 3 of the same app on the dev portal?

_However, if you deploy your app to a remote cloud backend, the teams toolkit won't update the manifest._ **Do you mean deploying by using the teams toolkit, i.e "Provision in the cloud" -> "Deploy to the cloud"?**

**Comment by yanjiang222** [comment]
The app with *name-of-app*-local-debug is only for local debugging for VS code teams toolkit.  You can do "Provision in the cloud" -> "Deploy to the cloud" to deploy to one remote test server (environment) at the moment. The "provision" process will create a teams app automatically. We're making new improvement to enable multiple environments provision/deployment. Both teams toolkit and dev portal can be used to update teams app manifest but teams toolkit will only do one way update to the remote teams app manifest.

**Comment by NiclasMolby** [comment]
Alright.
What's the intended way to deploy to production then?
Lets say, I've developed an app using React, which I've tested locally and am satisfied with.
The code is on my private repository and I want to use my deployment pipeline to deploy the app to an Azure App Service I've created manually with an App Registration which I've also created manually.

In this case, should I then manually create an app on the dev portal as my production app, and just use my pipeline to build and deploy the React code? Or are there an intended way to do this?

Hope you understand my question.

**Comment by yanjiang222** [comment]
If you do have an app deployed already and just want to integrate it into teams, you can manually create an app on the dev portal and change the manifest accordingly to point to your react app. If you don't have an existing react app and just want to scaffold a new react app from scratch and publish to teams, the teams toolkit for vs code is the way to go. The app scaffolded by the toolkit would automatically get the extra feature like SSO with teams. Our toolkit is still rapidly changing so if you have more feedbacks want to share, please let us know and thank you for trying and testing!

**Comment by NiclasMolby** [comment]
Alright thank you.
I am still uncertain why using the Teams Toolkit is the best way to deploy.
Say, during development, I've used my own personal MSDN for testing and deploying a testing server.
However, when my company want to deploy my teams app for public production, wouldn't it require our admin to download the Teams Toolkit, log in with his administrator credentials and then click provision -> publish in the toolkit?

Is this how it is intended?

**Comment by yanjiang222** [comment]
The toolkit itself is still focusing on app development phase. You can use the toolkit to scaffold new project and doing local debugging for the app and deploy it to "testing tenant". For company that have very formal CI/CD process for production, users don't need to download the toolkit. We are making new feature to deliver CI/CD helper CLI and scripts to address that. It's still not in formal release yet. The toolkit is not intended for formal CI/CD production release but only dev phase testing. Hope this can help!

Thank you for your feedback!

**Comment by NiclasMolby** [comment]
I see. Thank you for clarifying! I'll close the issue.
