### ISSUE TITLE
Customization option in provision in azure

### ISSUE THREAD

**Issue by ArijitCloud** [OfficeDev/TeamsFx#2447]
I am not sure if this is just me, I couldn't find an option where can I customize the resources that are about to be provisioned in Azure.

Something like,
teamsfx provision - armlocation "D:\myarmtemplates\teamsapp.json"
or possibly a default arm template part of the scaffolded files in VS

Thanks,
Arijit

**Comment by adashen** [comment]
Hi @ArijitCloud  Thanks for the suggestion. Actually we are already working on this :) . And the feature could be enabled with feature flag turned on in the latest release of VSCode extension tool. If you would like to have a try please find the instructions at https://github.com/OfficeDev/TeamsFx/wiki/Enable-Preview-Features-in-Teams-Toolkit#provision-azure-resources-with-arm-template .  And for the cli, we will also have it integrated in the near future.
