### ISSUE TITLE
Extension issue : extension load time is slowing down VSCode 

### ISSUE THREAD

**Issue by Josverl** [OfficeDev/TeamsFx#2455]
- Issue Type: `Bug`
- Extension Name: `ms-teams-vscode-extension`
- Extension Version: `2.7.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.60.2`

could you please take some time with the profiler to make the startup time < 500 ms 
now it eats up almost a second for any VSCode startup , which accounts to a lot of seconds given a broad installed base 

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 4308,
		"activateCallTime": 84,
		"activateResolvedTime": 4484,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "TeamsDevApp.ms-teams-vscode-extension",
				"_lower": "teamsdevapp.ms-teams-vscode-extension"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by 1openwindow** [comment]
Thanks for your feedback, @Josverl  we are investigating this issue.

**Comment by HuihuiWu-Microsoft** [comment]
Hi @Josverl ,

According to your pasted data, the startup activation time is about 5s which includes codeLoadingTime and activateCallTime:
![image](https://user-images.githubusercontent.com/73154171/138019959-f68da921-abc3-4cdd-839a-6ba1d99b5a53.png)

I tried to reproduce your issue with the same VSC version and extension version. For most of the startup, it just spends 200+ms:
![4_Capture](https://user-images.githubusercontent.com/73154171/138020453-86243ef0-739d-47cc-ba82-c9dc5b4e973e.PNG)
![image](https://user-images.githubusercontent.com/73154171/138020607-1e44d0dd-2546-48f0-afe8-83fd47e2d39b.png)

Could you share more info with me? Does this happen all the time?

**Comment by Josverl** [comment]
generally TT is slow on both machines that i have tested it on.
if you heve steps that i can do to do better / other measurements then I'd be happy to follow these , and hopefully find another source for the delays.

as a sidenote: I tend to turn TT off on other projects as it keeps on shoving itself up front when there is an update or something , that i could not be bothered about when starting a different project in Codespace,

**Comment by HuihuiWu-Microsoft** [comment]
@Josverl Thanks for your response.  Actually there's nothing special for my steps except for opening vscode and checking the startup performance. But maybe we could check different scenarios and see if there's any differences: 1>start VS code with no workspace/folder open 2> start VS code with teams app project open 3>start VS code with huge folder open. Could you help try the below scenarios and check the loading time?

BTW, to make sure we're on the same page, the way I'm using to measure the loading time is to run the 'Developer: Startup Performance' command in command palette after VSCode activated and check the 'Load Code'+'Call Activate' time. Is that the same to your measurements?
![image](https://user-images.githubusercontent.com/73154171/141921729-5b1d900d-d41c-47d1-a244-71c2f250c489.png)

To double confirm with you, do you mean that you disable Teams Toolkit in generally and enable&reload to activate TT when you need to develop teams app project?

**Comment by Josverl** [comment]
Yes it's disabled most of the time,
Yes that is the way i/vscode mesured the delays in startup

**Comment by HuihuiWu-Microsoft** [comment]
Thanks @Josverl , we'll have further investigation and try to optimize our toolkit startup time.

**Comment by Josverl** [comment]
closing as outdated
