### ISSUE TITLE
Auth Failed

### ISSUE THREAD

**Issue by t-lji** [OfficeDev/TeamsFx#2463]
**Describe the bug**
After generating a new project and using my old project code with bot, auth always failed.

![image](https://user-images.githubusercontent.com/87359629/134838162-a74c0ed1-f67f-4f7d-90ff-2db8e94dedef.png)

**To Reproduce**
1. Go to [example](https://github.com/t-lji/fx-example) to get my project code
2. Generate a new project by [Release vscode-extension-2.7.1-alpha.6dc3b9f5.0 · OfficeDev/TeamsFx (github.com)](https://github.com/OfficeDev/TeamsFx/releases/tag/vscode-extension-2.7.1-alpha.6dc3b9f5.0)
3. Use bot folder of my project instead of new project bot folder
4. Press 'F5' and input 'me' in Chat page
5. Press 'continue' button to get ssoToken
6. See the error

**Expected behavior**
Get a ssoToken and show my profile card

![image](https://user-images.githubusercontent.com/87359629/134838662-e94559e1-5f5c-4bdd-90c8-f5743558063e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/87359629/134838563-289cda30-3df6-4a43-818c-4352a0344e6a.png)

**VS Code Extension Information (please complete the following information):**
 - OS: [windows 10]
 - Version [1.60.2(user setup)]

**Additional context**
Or can you give me an official documentation for how to create a ssoDialog in new project?
@dilin-MS @YitongFeng-git

**Comment by t-lji** [comment]
I modified process.env.INITIATE_LOGIN_ENDPOINT from "https://703a-2404-f801-9000-1a-9a09-9b9d-5226-5a12.ngrok.io"(generated by ngnok) to "https://703a-2404-f801-9000-1a-9a09-9b9d-5226-5a12.ngrok.io/auth-start.html" and the auth succeeded.

![image](https://user-images.githubusercontent.com/87359629/134850260-965cd0e4-325c-4208-bb09-1d56e2b6044f.png)

But I still can't get my profile card.

**Comment by t-lji** [comment]
@kuojianlu

**Comment by kuojianlu** [comment]
@t-lji Thanks for reporting this bug. This bug is due to missing `/auth-start.html` after [bot login endpoint](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/fx-core/src/plugins/resource/localdebug/index.ts#L462). This only happens when multiple env is enabled. Will fix it as soon as possible.

**Comment by kuojianlu** [comment]
#2475

**Comment by t-lji** [comment]
> #2475

@kuojianlu Thanks for your reply! Please notice me when a updated Teams Toolkit release.

**Comment by kuojianlu** [comment]
> > #2475
> 
> @kuojianlu Thanks for your reply! Please notice me when a updated Teams Toolkit release.

No new version will be released this sprint. You may expect new version release on 10/18.
