### ISSUE TITLE
multi env can't support ssoDialog

### ISSUE THREAD

**Issue by t-lji** [OfficeDev/TeamsFx#2486]
**Describe the bug**
After set System Environment Variables "TEAMSFX_MULTI_ENV" to true and got ssoToken successfully, I can't get my profile card from Microsoft Graph

![image](https://user-images.githubusercontent.com/87359629/135041124-37a5e252-63cd-4aff-a24a-1050bfa864fc.png)

**To Reproduce**
1. Set System Environment Variables "TEAMSFX_MULTI_ENV" to true and confirm it's valid (may need reboot or reopen vs code)
2. Create a new project by Teams Toolkit (2.7.1-alpha.6dc3b9f5.0), include "bot" capability (may need modify manifest.template.json)
3. Go to [bot-sso](https://github.com/OfficeDev/TeamsFx-Samples/tree/main/bot-sso/ts) to get project code
4. Use bot folder in bot-sso instead of the same folder in scaffolding
5. Press 'F5' and input 'show' in Chat page
6. Press 'continue' button to get ssoToken
7. See the error

**Expected behavior**
Show profile card

**Screenshots**
![image](https://user-images.githubusercontent.com/87359629/135041415-87b7cf64-7779-4005-89c7-86a58664f6eb.png)

**VS Code Extension Information (please complete the following information):**
 - OS: [windows 10]
 - Version [1.60.2(user setup)]
 - Teams Toolkit Version [ms-teams-vscode-extension-2.7.1-alpha.6dc3b9f5.0]

**Additional context**
When I comment dedupStep function in bot/dialogs/ssoDialog.js, like this:

![image](https://user-images.githubusercontent.com/87359629/135041686-282d6550-41e2-4df8-b542-b9cdbf8697f5.png)

I will get multiple pictures if I open 2 or many clients of Teams under local debug mode.

![image](https://user-images.githubusercontent.com/87359629/135041986-d527a833-0195-4d8e-88d7-7eaa95b796fd.png)

But I still can't get profile card under remote debug mode after I provision and deploy my app.

![image](https://user-images.githubusercontent.com/87359629/135042178-1dd6819d-76c4-4870-8d91-64f43c48c0b1.png)

**Comment by kuojianlu** [comment]
BTW, I found two issues in [simplified Bot SSO template](https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/bot-sso/ts/bot) which @YitongFeng-git may need pay attention to.
1. The dependency `adaptivecards-templating^2.1.0` will actually install its 2.2.0 version, which will introduce a compile error when `npm run build`.
![image](https://user-images.githubusercontent.com/37978464/136934809-7c26ee1a-6033-4887-9744-9614bcf69183.png)
Fix the version to 2.1.0 will fix this issue.
2. `npm run build` will not copy `adaptiveCards` folder to `lib`.

Both two issues will result in remote debug failure.

**Comment by eriolchan** [comment]
Close this since Bot SSO is removed from template and it well support multiple env
