### ISSUE TITLE
bug report: unknown.Error

### ISSUE THREAD

**Issue by ShakuAutopilot** [OfficeDev/TeamsFx#2487]
{"stack":"Error: <REDACTED: user-file-path> new RestError (<REDACTED: user-file-path>:2:3391574)<REDACTED: user-file-path> <REDACTED: user-file-path>:2:<REDACTED: user-file-path> processTicksAndRejections (<REDACTED: user-file-path>:93:5)","message":"","statusCode":403,"request":{},"response":{"body":""}}

stack:
Error: 
	at new RestError (<REDACTED: user-file-path>:2:3391574)
	at <REDACTED: user-file-path>:2:3368957
	at processTicksAndRejections (<REDACTED: user-file-path>:93:5)

**Comment by adashen** [comment]
Hi @ShakuAutopilot  Thanks for reaching us for the issue. Can you help us to provide the steps of getting this error?
