### ISSUE TITLE
Cannot generate the local debug manifest and app package from Team toolkit

### ISSUE THREAD

**Issue by zhenjiao-ms** [OfficeDev/TeamsFx#2518]
Right now there is no way to generate the app package and manifest file for the app in localhost. The "zip Teams metadata package" command only supports to generate the package for the app deployed to Azure, so it is not convenient for developer who wants to install the local version by manual.

**Comment by MuyangAmigo** [comment]
Now that "Zip teams metadata package" command supports to select a target environment. So closing this issue now.
