### ISSUE TITLE
setFrameAndLoadOrigin failed when running Side Panel app in debug mode

### ISSUE THREAD

**Issue by MSJohnnyLee** [OfficeDev/TeamsFx#2601]
**Describe the bug**
Following the instructions described on this tutorial (https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?tabs=vscode), I tried to enable this application to run in the meeting side panel by adding the "meetingSidePanel" context in the manifest.source.json.

![image](https://user-images.githubusercontent.com/83673822/137227479-f5653934-e987-4238-aef9-11b8c477c37b.png)

But upon debugging the application (pressing F5) with the Teams Toolkit, the side panel application would be stuck in the loading screen. The following error would also be thrown:
_CID[main] HostedWebContent: setFrameAndLoadOrigin failed for AppId: 30bfb90d-1d7f-45e1-9c14-48c494c187d7 frameContext: sidePanel, appSessionId : 84a490ec-d955-4c00-ab82-b7f85b3b4291_

**To Reproduce**
1. Follow the tutorial laid out in this URL https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/first-app-react?tabs=vscode
2. Adding the "meetingSidePanel" context to the manifest.source.json file
3. Debug the application by pressing F5 in VSCode
4. Attempt to load the side panel application in a meeting

**Expected behavior**
The application should load in the side panel and not remain stuck in the loading screen. Or, if there are extra configuration steps required for enabling a side panel app, it would help a lot to include that in the tutorial as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/83673822/137227873-6731327a-7200-46fe-bf87-0eda12657ea8.png)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10 / 11
 - Version 2.7.0

**Comment by JerryYangKai** [comment]
Hi! Could you please show me more about this issue, like the mainifest or the code.

**Comment by xelossan** [comment]
I have the same problem, I have a tab app configured as available also for meetings, and it works fine when added to channel tabs or as pre-meeting app, but when trying to add it as sidebar during the meeting, it's just stuck at loading with the same error as in issue's description. Both sidebar and configuration page does not load during meeting.

Here's my tab config from manifest:
```json
"configurableTabs": [
    {
      "configurationUrl": "https://localhost:3000?meetingId={meetingId}&userId={userId}&tenantId={tenantId}&tid={tid}&userPrincipalName={userPrincipalName}#/config/meeting",
      "canUpdateConfiguration": true,
      "scopes": [
        "team",
        "groupchat"
      ],
      "context": [
        "channelTab",
        "meetingChatTab",
        "meetingDetailsTab",
        "meetingSidePanel",
        "meetingStage",
        "privateChatTab"
      ]
    }
  ],
```

**Comment by xelossan** [comment]
So, after some trial and error, it looks like that meeting sidebar apps don't like localhost and/or port numbers in URLs - after changing it to a custom domain (without any changes in code) it started to work, which is strange because localhost:3000 that I used works perfectly fine for personal, channel and group tabs as well as pre-meeting tab, the problem was only during the meeting.

**Comment by JerryYangKai** [comment]
@xelossan  Thanks for raising the issue and your solution, I will tracking this and give more info after I have more investigation result.
