### ISSUE TITLE
Provision in the cloud cleared tags assigned to existing resource group

### ISSUE THREAD

**Issue by stephenhuen** [OfficeDev/TeamsFx#2777]
**Steps to reproduce the behavior**
1. Create resource group in Azure. Name it <appName>-rg and assign tags.
2. Click Provision in the cloud.
3. Azure resources provisioned to resource group but tags assigned to resource group are now removed.

**Expected behavior**
Retain tags assigned to Azure resources

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10
 - Version: 2.8 (Teams Toolkit)

**Additional context**
Client has Azure policy in place to require all Azure resources to have tags assigned during creation/provisioning. Currently no way to add tags for provisioning in Teams Toolkit. Tried adding tags to C:\Users\<user>\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.8.0\out\templates\plugins\resource\sql\bicep\sql.template.bicep as a test but no tags were created. Now trying "Inherit a tag from the resource group" policy and created a resource group with tags and have teams toolkit deployed to it.

**Comment by a1exwang** [comment]
Hi @stephenhuen, this bug is fixed in our latest release (v2.9.0). Please upgrade Teams Toolkit to the latest version and retry it again.

**Comment by stephenhuen** [comment]
Thanks @a1exwang. I tested it and it is no longer clearing the tags of my existing resource group!

**Comment by a1exwang** [comment]
Thank you @stephenhuen. I will close this issue since this is solved. If you still have questions about this, feel free to reopen it.
