### ISSUE TITLE
[Incident Notification] Fail to local debug Bot due to update endpoint failure

### ISSUE THREAD

**Issue by eriolchan** [OfficeDev/TeamsFx#2861]
There is a live site incident in the underlying App Studio service, and we are actively working on it and will keep updating the status in this issue.

You can occur the below error when you click F5 to debug Bot app.
![bot_error](https://user-images.githubusercontent.com/2046804/140595492-981a3c21-ed39-4b93-a7d5-02cb6ab7a2a6.png)

**Comment by zhenjiao-ms** [comment]
The underlying service has fixed the issue, so everything should work well now.
