### ISSUE TITLE
new bug report: Solution.FailedToLoadManifestFile

### ISSUE THREAD

**Issue by marcelopepisatos** [OfficeDev/TeamsFx#2872]
Failed to read manifest file

Error: Failed to read manifest file
	at TeamsAppSolution.reloadManifest (c:\Users\marce\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.2.0\out\src\extension.js:2:5590766)
	at async TeamsAppSolution.reloadManifestAndCheckRequiredFields (c:\Users\marce\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.2.0\out\src\extension.js:2:5590928)
	at async TeamsAppSolution.getQuestionsForUserTask (c:\Users\marce\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.2.0\out\src\extension.js:2:5633951)
	at async FxCore._getQuestionsForUserTask (c:\Users\marce\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.2.0\out\src\extension.js:2:4675658)
	at async FxCore.exports.QuestionModelMW (c:\Users\marce\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.2.0\out\src\extension.js:2:4691034)
	at async FxCore.<anonymous> (c:\Users\marce\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.2.0\out\src\extension.js:2:4692270)
	at async FxCore.exports.ContextLoaderMW (c:\Users\marce\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.2.0\out\src\extension.js:2:4688308)
	at async FxCore.exports.ConcurrentLockerMW (c:\Users\marce\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.2.0\out\src\extension.js:2:4683455)
	at async FxCore.exports.ErrorHandlerMW (c:\Users\marce\.vscode\extensions\teamsdevapp.ms-teams-vscode-extension-2.2.0\out\src\extension.js:2:4689250)

**Comment by nliu-ms** [comment]
Hey @marcelopepisatos, thanks for your report! When did you trigger this bug? Usually it happens when you click `Provision in the Cloud` or do local debugging.

This can happen if manifest.source.json file is not a valid json after some manual updates. Can you please check your file? Thanks!

**Comment by marcelopepisatos** [comment]
This error happens when I try to run the application's debug mode. I just created an app using the extension, and as soon as I tried to run the debug the problem already happens even without modifying anything in the code.
Even apps that were created a few months ago stopped working. But when I deploy to azure, everything works fine.



***@***.***

Marcelo Pepis
System Analyst and Developer
Av. Theodoro Victorelli, 150 - Jardim Helena | Londrina, PR - Brasil
atos.net/br<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fatos.net%2Fbr&data=04%7C01%7Cmarcelo.pepis%40atos.net%7C8895ac38afdc48215f4408d8fe884b78%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637539208622544934%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=uhMQFMJ%2BI5ov2aDxeM%2FJ8bOplmcvoiVpEIkeJEP0MRA%3D&reserved=0>
[LinkedIn icon]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2F1259%2F&data=04%7C01%7Cmarcelo.pepis%40atos.net%7C8895ac38afdc48215f4408d8fe884b78%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637539208622574798%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yXVFuKR%2FmJYcYKjb2NpGxfCIGVr0QJC%2FHl2owgT9j5o%3D&reserved=0> [Twitter icon] <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2Fatos&data=04%7C01%7Cmarcelo.pepis%40atos.net%7C8895ac38afdc48215f4408d8fe884b78%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637539208622604672%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0ERvwtkXFxklCS9xc1lACvmRCr387CteWhWVOOtjIeo%3D&reserved=0>  [Facebook icon] <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FAtos%2F&data=04%7C01%7Cmarcelo.pepis%40atos.net%7C8895ac38afdc48215f4408d8fe884b78%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637539208622634536%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UI8klKPaATWj0aBzP9ZaODB7Y%2BG%2BrX01eB4irdjfF1c%3D&reserved=0>  [Instagram icon] <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.instagram.com%2Fatosglobal%2F&data=04%7C01%7Cmarcelo.pepis%40atos.net%7C8895ac38afdc48215f4408d8fe884b78%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637539208622664412%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=3oic4xSpIbgWwRp9lrdo1L3FSnwGi6b9aVTcmnCpljc%3D&reserved=0>  [Youtube icon] <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fuser%2FAtos&data=04%7C01%7Cmarcelo.pepis%40atos.net%7C8895ac38afdc48215f4408d8fe884b78%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637539208622694278%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IEd%2F36xJjy1951DHaRvg9TbZdH1E5m5n3Q8haG6ea2o%3D&reserved=0>





***@***.***

P Antes de imprimir pense em seu compromisso com o Meio Ambiente.
P Before printing, think about your responsibility and commitment to the Environment.



De: Ning Liu ***@***.***>
Enviada em: terça-feira, 9 de novembro de 2021 04:07
Para: OfficeDev/TeamsFx ***@***.***>
Cc: PEPIS, MARCELO ***@***.***>; Mention ***@***.***>
Assunto: Re: [OfficeDev/TeamsFx] new bug report: Solution.FailedToLoadManifestFile (Issue #2872)


Caution! External email. Do not open attachments or click links, unless this email comes from a known sender and you know the content is safe.

Hey @marcelopepisatos<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarcelopepisatos&data=04%7C01%7Cmarcelo.pepis%40atos.net%7Ce183641b07d14dc64f4508d9a34f8c24%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637720384908784237%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=33bEnm6UBrgnoMQbMXR8Wo%2BZ2l9l7A%2BUg8m817G35uQ%3D&reserved=0>, thanks for your report! When did you trigger this bug? Usually it happens when you click Provision in the Cloud or do local debugging.

This can happen if manifest.source.json file is not a valid json after some manual updates. Can you please check your file? Thanks!

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2FTeamsFx%2Fissues%2F2872%23issuecomment-963871015&data=04%7C01%7Cmarcelo.pepis%40atos.net%7Ce183641b07d14dc64f4508d9a34f8c24%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637720384908789215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TCjU0%2F1UhqswNEThgjU5ZLIPlHIZRUYA38uQWG6WF6U%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAOV4ABVWKFT4XNUWWKPSSSDULDCBDANCNFSM5HONRWOQ&data=04%7C01%7Cmarcelo.pepis%40atos.net%7Ce183641b07d14dc64f4508d9a34f8c24%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637720384908794200%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Jb47aySGdSf1zNnv0MFeW1TQQ7PwViHTLW4L%2FQYCvzs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cmarcelo.pepis%40atos.net%7Ce183641b07d14dc64f4508d9a34f8c24%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637720384908804151%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ZAJXthAJSC%2FfE42IdCENGodzCJwLIEJa7TiFNczsYOE%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cmarcelo.pepis%40atos.net%7Ce183641b07d14dc64f4508d9a34f8c24%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C637720384908809134%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XzdhbJxRu3lRxk3FxqCeCHVSRPHOss4Sla8qqGfx%2Fzs%3D&reserved=0>.

This email and the documents attached are confidential and intended solely for the addressee; it may also be privileged. If you receive this e-mail in error, please notify the sender immediately and destroy it.
As its integrity cannot be secured on the internet, the Atos group liability cannot be triggered for the message content. Although the snder endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted.

**Comment by nliu-ms** [comment]
Thanks @marcelopepisatos , from the stack trace are you using 2.2.0 version of Teams Toolkit extension?

I tried with this version but cannot reproduce it. Would you mind to either upgrading to the latest 2.9.0 version, or creating a new app and sending configs under `${project}/.fx` to me? Thank you!
