### ISSUE TITLE
new bug report: Task 'spfx npm install' failed

### ISSUE THREAD

**Issue by eliem3** [OfficeDev/TeamsFx#2908]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**Additional context**

**Comment by sffamily** [comment]
In the latest Teams Toolkit extensions we have made significant improvements on SPFx Teams app experience, as well as quality improvements and bug fixing. Please try it out using the new features. As this doesn't have details, and we close this for now, and if you still encounter the issue with the new versions, reopen this or report a new bug. Thanks!
