### ISSUE TITLE
activitites in manifest.source.json

### ISSUE THREAD

**Issue by ErikSkaarup** [OfficeDev/TeamsFx#2909]
We are working to implement SendActivityNotifications from our teams app, and we need to add activities in the manifest, however every time we add them in the manifest.source.json it will not update the app manifest in the developer portal for the app. If we add them in the developer portal it will be removed on the first debug session even though we have them in the manifest.source.json.
To reproduce:
1. add the following to the manifest,source.json:
 "activities": {
        "activityTypes": [
          {
            "type": "mentionTask",
            "description": "Task message for x",
            "templateText": "Hallo there is a new action for {userPrincipalName}"
          }
        ]
      }
2. save and run debug 
3. Check developer portal for the app settings and activity feed notification is not enabled.

**Expected behavior**
That the manifest is updated correctly, it works for setting names and etc.

**Comment by nliu-ms** [comment]
Hey @ErikSkaarup , thanks for the heads up! It's a bug of the extension, we didn't include activities when updating the app. Thank you so much! Will fix it in release CY21-11.2.

**Comment by ErikSkaarup** [comment]
Super - when will CY21-11.2 be published?

**Comment by nliu-ms** [comment]
@ErikSkaarup  It should be around 11/29.
