### ISSUE TITLE
Image Size Shirinkage in adaptive Cards

### ISSUE THREAD

**Issue by OshoK** [OfficeDev/TeamsFx#3029]
**Describe the bug**
For our Teams app for some users images sent through adaptive card is getting shrunk horizontally. This started to happen only few hours ago and no code change was done on our end.

![image](https://user-images.githubusercontent.com/94609532/142407605-56b302e2-9ae0-4777-bcb2-45bfe844d639.png)

**Comment by OshoK** [comment]
Hi Team, 

Do we have any update on this issue?

**Comment by YitongFeng-git** [comment]
Hi, @OshoK Could you please confirm if your image size does not exceed the [resolution and size limit](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/cards/cards-reference#inline-card-images)?
