### ISSUE TITLE
Need to restart the debug session for a few times before a success launch

### ISSUE THREAD

**Issue by SwagiWagi** [OfficeDev/TeamsFx#3174]
**Describe the bug**
Every time I start the default debug profile ("Debug (Chrome)"), I get the error:
`[Error] - [Login] Failed to retrieve token silently: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientAuthError: openid_config_error: Could not retrieve endpoints. Check your authority and verify the .well-known/openid-configuration endpoint returns the required endpoints. Attempted to retrieve endpoints from: https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration`

And need to restart the debug session a few times until a successful launch.
This has happened for multiple projects.

**To Reproduce**
1. Create a teams tab app hosted on azure using the vscode extension.
2. Launch a debug session ("Debug (Chrome)").
3. Login in the popup (multiple popups).

**Expected behavior**
A debug session.

**Screenshots**
![image](https://user-images.githubusercontent.com/19839556/144018527-21f0f9ae-c4bb-49a3-827f-47579b7eb63e.png)

**VS Code Extension Information (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 2.10.0 

**CLI Information (please complete the following information):**
 - OS: [e.g. iOS8.1] Windows
 - Version [e.g. 22] 10

**Comment by xiaolang124** [comment]
Hi, I open an issue for msal. You can find more detail on this issue. 
https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4293

For now, they want to know whether you use any proxy in your configuration?

**Comment by SwagiWagi** [comment]
> Hi, I open an issue for msal. You can find more detail on this issue. [AzureAD/microsoft-authentication-library-for-js#4293](https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4293)
> 
> For now, they want to know whether you use any proxy in your configuration? And can you open https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration directly?

Thanks.
I am not using a proxy and I can open https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration directly.

**Comment by SwagiWagi** [comment]
Hey, any update on this?

**Comment by xiaolang124** [comment]
A few days ago, M365 team had fixed an issue which can cause cannot open login URL. Do you have this issue now? https://twitter.com/MSFT365Status/status/1471296124774281220

**Comment by SwagiWagi** [comment]
Looks like the issue has been resolved, thank you.

**Comment by adashen** [comment]
Close as resolved
