### ISSUE TITLE
bug report: EPERM: Operation not permitted, mkdir

### ISSUE THREAD

**Issue by q00u** [OfficeDev/TeamsFx#3207]
>EPERM: operation not permitted, mkdir 'C:\Program Files\Microsoft VS Code\%USERPROFILE%'

On Windows 10. Trying to set the Default Project Root Directory to be in the 'dev' folder, under my home directory.

e.g., `C:\Users\q00u\dev\TeamsApps`

The setting description is:

>Set the default root directory for creating new teams app project. By default, the root directory is $HOME_DIR/TeamsApps.

`$HOME_DIR/dev/TeamsApps` doesn't work. `%USERPROFILE%\dev\TeamsApps` doesn't work. Only a full path works, but I have different user folders on different computers.

**Comment by 1openwindow** [comment]
Thanks for report this issue @q00u . this is a common scenario, I will look at this. if you have any suggestion, feel free to comment.

**Comment by 1openwindow** [comment]
@q00u, in our next release, the extension will support "${homeDir}" global variable, please try it out once new release is published. The next release date should be early of next week. Thanks for your feedback, if any else, please kindly let us know.
![image](https://user-images.githubusercontent.com/26411726/146704431-96759cfe-4ef7-429a-b30d-0a9971e741c2.png)
