### ISSUE TITLE
Updating nuget package Microsoft.TeamsFx to 0.3.0-rc breaks Visual Studio project template

### ISSUE THREAD

**Issue by thomyg** [OfficeDev/TeamsFx#3327]
**Describe the bug**

Updating the TeamsFx nuget package breaks the default project build. 

**To Reproduce**

- Create a new project based on extension version 0.1.107.31731
- Update package Microsoft.TeamsFx to 0.3.0-rc
- Build project
- Build fails

**Expected behavior**
The shipped default projects should work with the latest library version.

**Screenshots**

![image](https://user-images.githubusercontent.com/10920072/145680043-c84be85a-3e34-4f9f-b774-c7ded12c7c80.png)

**Comment by JerryYangKai** [comment]
@thomyg  Thanks for your feedback! The TeamsFx nuget package has upgraded to 0.3.0-rc to support Team Toolkit in VS 2022 , so there are some breaking changes in it. 
Our plan is to maintain Teams toolkit for VS 2019 and continuous support VS 2022 in the future. 0.1.0-rc is focusing on 2019, the new version of TeamsFx nuget package is for Teams toolkit for VS 2022 and support .NET 6.

@tecton Could you please provide some more info about API change, so our user could run 0.3.0 in previous project?

**Comment by thomyg** [comment]
Thank you for your response.

Two things:

1.) please provide documentation so that your intentions are clear for people from the outside
2.) isn't there a way of defining dependencies, meaning, if I don't have .NET 6 in my project, the package won't install? That would solve the case already, I guess.

**Comment by eriolchan** [comment]
@therealjohn can you help take a look at Thomas's suggestion?

**Comment by tecton** [comment]
@thomyg Thanks for your suggestions, I've created a PR to update the documentation.
For #2, I agree that in VS2019 a user shall not be able to install a package depending on .NET 6, I'll try to add some restrictions.

**Comment by tecton** [comment]
0.3.0-rc has the only dependency of .NET 6 but is still be able to install. Seems that nuget allows the installation for now. I'm closing this issue.
