### ISSUE TITLE
Multi Langauge support in Teams App Package

### ISSUE THREAD

**Issue by LALITAMITTAL18** [OfficeDev/TeamsFx#3333]
**Describe the bug**
When I click on "Zip Teams Metadata package", it doesnt include language file in app package and uploading the package fails on Teams

**To Reproduce**
Add localization info in Manifest.remote.template.json:

 "localizationInfo": {
        "defaultLanguageTag": "en-us",
        "additionalLanguages": [
          {
            "languageTag": "nl-NL",
            "file": "nl-NL.json"
          }
        ]
      },

place the json file in AppName->templates->App Package
![image](https://user-images.githubusercontent.com/51710902/145843685-6a9de234-b5c5-48ca-86a2-a88dee0f8f74.png)

click on "Zip Teams Metadata package"
![image](https://user-images.githubusercontent.com/51710902/145843730-4928e95f-85e1-4c85-90ed-9ec458632556.png)

Invalid app package zip folder without language specific file.

![image](https://user-images.githubusercontent.com/51710902/145843778-bc3de93f-31d8-4299-a97c-4065d5a412a9.png)

**Expected behavior**
The app package should include language files. and while uploading to dev.teams.microsoft.com, should upload without any issue.

**Comment by nliu-ms** [comment]
Thank @LALITAMITTAL18 for contacting us! This issue has been reported in https://github.com/OfficeDev/TeamsFx/issues/3026. It has been fixed and will be delivered in version 3.1.0.
