### ISSUE TITLE
App created with Toolkit won't run with teamsfx CLI

### ISSUE THREAD

**Issue by mig82** [OfficeDev/TeamsFx#3368]
**Describe the bug**
I'm unable to preview the app by running from CLI

**To Reproduce**
1. Create a new Teams app using the Teams Toolkit in VS Code by going to **_Development > Create a new Teams app_** and only add the bot capability to it.
2. Open a terminal
3. Install CLI by running `pnpm install -g @microsoft/teamsfx-cli`  
4. Attempt to preview locally by running `teamsfx preview --local`
5. See error:

```
(✖) [TeamsfxCLI.PreviewCommandFailed]: The preview command failed: TeamsfxCLI.NgrokStartFailed.
(✖) Call stack:
(✖) Error: The preview command failed: TeamsfxCLI.NgrokStartFailed.
    at Object.PreviewCommandFailed (/Users/miguelangelfernandez/Library/pnpm-global/5/node_modules/.pnpm/@microsoft+teamsfx-cli@0.8.0/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:3013789)
    at Preview.<anonymous> (/Users/miguelangelfernandez/Library/pnpm-global/5/node_modules/.pnpm/@microsoft+teamsfx-cli@0.8.0/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:3036787)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/miguelangelfernandez/Library/pnpm-global/5/node_modules/.pnpm/@microsoft+teamsfx-cli@0.8.0/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:3020126)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

The error is not enough to understand why Ngrok could not start. The `ngrok-start.log` file reads:

```
npx ngrok http 3978 --log=stdout 
/Users/miguelangelfernandez/ws/TeamsApps/hello-world-bot/bot/node_modules/.bin/ngrok: /Users/miguelangelfernandez/ws/TeamsApps/hello-world-bot/bot/node_modules/.bin/ngrok: cannot execute binary file
```

**Expected behavior**

I expected that a project created by the Teams Toolkit for VS Code would be runnable via the CLI.

I also tried creating a project by using `teamsfx new` and then the `teamsfx preview` command works perfectly. I could not find any differences between a project created by the VS Code Teams Toolkit and the CLI, so I tried adding a capability to the project using the CLI in the hopes that it would fix the project. It did not work.
 
**Screenshots**

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/10434613/146283545-9a1bdec9-42a9-4e9b-a116-0ff912b8e446.png">

**VS Code Extension Information (please complete the following information):**
 - OS: MacOS 11.6.1 (Big Sur) (Intel chip)
 - Version Teams Toolkit (Preview) v3.0.0

**CLI Information (please complete the following information):**
 - OS: MacOS 11.6.1 (Big Sur) (Intel chip)
 - Version teamsfx 0.8.0

**Additional context**

For context, I'm trying to put together a Docker image to run my bot's handler logic. Is there any documentation as to how to go about this? This is the reason that even after creating the project manually I need to use the `teamsfx` CLI to run it from the image.

**Comment by swatDong** [comment]
@mig82 thanks for the detailed log and steps.
The error log says *"cannot execute binary file"* so it's probably due to ngrok install failure. Could you please try following steps to see why ngrok was not correctly installed?
(teamsfx CLI runs `npm install` and `npx ngrok` under *bot/* folder as well)
- Check if `"ngrok": "^3.4.0"` is in `devDependencies` of *bot/package.json*
- Run `npm install` under *bot/* folder and see if there's any error
- Check if ngrok binary exists: *bot/node_modules/ngrok/bin/ngrok* and *bot/node_modules/.bin/ngrok*
- Run `npx ngrok http 3978 --log=stdout` under *bot/* folder to see if ngrok can start successfully.

I did know some scenarios that may impact ngrok (network policy, npm version, npm registry, etc.), and need more info to determine the cause on your machine.

**Comment by mig82** [comment]
Hi @swatDong,

These are the contents of the `bot/package.json` file. Notice that Ngrok _is_ in `devDependencies`.

```json
{
  "name": "echobot",
  "version": "1.0.0",
  "description": "Microsoft Teams Toolkit hello world Bot sample",
  "author": "Microsoft",
  "license": "MIT",
  "main": "./lib/index.js",
  "scripts": {
    "build": "tsc --build && shx cp -r ./adaptiveCards ./lib/",
    "start": "node ./lib/index.js",
    "test": "echo \"Error: no test specified\" && exit 1",
    "watch": "nodemon --watch ./src -e ts --exec \"npm run start\""
  },
  "repository": {
    "type": "git",
    "url": "https://github.com"
  },
  "dependencies": {
    "adaptive-expressions": "^4.14.1",
    "adaptivecards-templating": "^2.1.0",
    "botbuilder": "~4.14.0",
    "botbuilder-dialogs": "~4.14.0",
    "isomorphic-fetch": "^3.0.0",
    "restify": "^8.5.1"
  },
  "devDependencies": {
    "@types/restify": "8.4.2",
    "ts-node": "~9.1.1",
    "typescript": "~3.9.2",
    "ngrok": "^3.4.0",
    "nodemon": "^2.0.7",
    "shx": "^0.3.3"
  }
}
```

This is the output of `npm install` in the `bot` directory.

```
➜   cd bot && npm install
audited 402 packages in 1.478s

36 packages are looking for funding
  run `npm fund` for details

found 2 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

Both the ngrok binary and its symlink under the node_modules directory exist.

```
➜  test -f bot/node_modules/ngrok/bin/ngrok && echo "exists" 
exists
➜  test -L bot/node_modules/.bin/ngrok && echo "exists"
exists
```

Running Ngrok on its own fails.

```
➜ cd bot && npx ngrok http 3978 --log=stdout 
/Users/miguelangelfernandez/ws/TeamsApps/hello-world-bot/bot/node_modules/.bin/ngrok: /Users/miguelangelfernandez/ws/TeamsApps/hello-world-bot/bot/node_modules/.bin/ngrok: cannot execute binary file
```

The binary is executable and it has the right permissions.

```
➜  hello-world-bot test -x bot/node_modules/ngrok/bin/ngrok && echo "is executable"
is executable
➜  hello-world-bot ls -l  bot/node_modules/ngrok/bintotal 58704
-rwxr-xr-x  1 miguelangelfernandez  staff  30053267 Dec 15 18:35 ngrok
```

**Comment by mig82** [comment]
Readding ngrok as a dependency fixed it.
```
➜ cd bot && npm i --save-dev ngrok@3.4.0
...
ngrok - unpacking binary
ngrok - binary unpacked to /Users/miguelangelfernandez/ws/TeamsApps/hello-world-bot/bot/node_modules/ngrok/bin/ngrok
+ ngrok@3.4.0
updated 1 package and audited 402 packages in 5.647s
...
```

```
➜  cd bot && npx ngrok http 3978 --log=stdout
INFO[12-16|12:20:24] no configuration paths supplied 
INFO[12-16|12:20:24] using configuration at default config path path=/Users/miguelangelfernandez/.ngrok2/ngrok.yml
INFO[12-16|12:20:24] open config file                         path=/Users/miguelangelfernandez/.ngrok2/ngrok.yml err=nil
t=2021-12-16T12:20:24+0100 lvl=info msg="starting web service" obj=web addr=127.0.0.1:4040
t=2021-12-16T12:20:24+0100 lvl=info msg="tunnel session started" obj=tunnels.session
t=2021-12-16T12:20:24+0100 lvl=info msg="client session established" obj=csess id=ce9135edf7b0
t=2021-12-16T12:20:24+0100 lvl=info msg="started tunnel" obj=tunnels name="command_line (http)" addr=http://localhost:3978 url=http://7df2-82-158-133-3.ngrok.io
t=2021-12-16T12:20:24+0100 lvl=info msg="started tunnel" obj=tunnels name=command_line addr=http://localhost:3978 url=https://7df2-82-158-133-3.ngrok.io
```

**Comment by swatDong** [comment]
Good to know it works well now.
Right, the binary is unpacked on *post-install* step so need force re-install to fix.
I'm closing this since the original issue is resolved. Feel free to comment or reopen if any other related issue.
