### ISSUE TITLE
Can not login M365

### ISSUE THREAD

**Issue by xiaolang124** [OfficeDev/TeamsFx#3369]
**Describe the bug**
Sign in to m365 account, no browser pop out and login will hang.

![image](https://user-images.githubusercontent.com/13211513/146294604-677f0cf8-3bac-411c-beb1-94d183276ddf.png)

**Comment by xiaolang124** [comment]
For now, we use MSAL SDK to login M365. Today we can not get right response from 
```https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration```, so login will hang. We are following this issue right now.

**Comment by adashen** [comment]
now totally fixed so close
