### ISSUE TITLE
Azure Storage account availability issue

### ISSUE THREAD

**Issue by SophieBok** [OfficeDev/TeamsFx#3395]
Building Tab: Checking Azure Storage account availability. (x) Failed.

Hi team, 
I'm having the below error. Could you let me know some possible reasons that might have caused this issue? 
<img width="396" alt="Screenshot 2021-12-20 103320" src="https://user-images.githubusercontent.com/46836149/146699536-4ea47198-9b7c-40eb-8d9d-c581403f9d50.png">

Thank you.

**Comment by xiaolang124** [comment]
Sorry for the Inconvenience. Do you use the same account to provision and deploy? If yes, in your scenario, do you mean you can provision successfully but cannot deploy?

**Comment by SophieBok** [comment]
Thank you for your reply. I provisioned manually and I'm having the above issue with  deployment only. Also, yes. I used the same account to provision and deploy!

**Comment by IvanJobs** [comment]
> Thank you for your reply. I provisioned manually and I'm having the above issue with deployment only. Also, yes. I used the same account to provision and deploy!

Hi Sophie, could you kindly provide more details? @SophieBok 
1. which version of Teams Toolkit/teamsfx-cli you're using in this project?
2. Open package.json in the root folder of your project to see its devDependencies, which version of `@microsoft/teamsfx-cli`' is used in the devDependencies?
Thanks a lot ~

**Comment by SophieBok** [comment]
I'm using v3.1. Please check out the screenshot for the 2nd one. 
<img width="510" alt="Screenshot 2021-12-22 014514" src="https://user-images.githubusercontent.com/46836149/146967186-bb7e7edd-e66b-41e0-9c8e-b5b6344dc27e.png">

**Comment by IvanJobs** [comment]
@SophieBok I just verified your case in CI/CD scenario, and I cannot reproduce it. Maybe @xiaolang124  can keep looking into it since it may related to some account type issue, thanks.

**Comment by swatDong** [comment]
The error "*Server returned an unknown AccountType*" should be from msal login step. (See msal source code [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/maintenance/adal-node/lib/token-request.js#L437))

@SophieBok - one possible scenario is that some of your account/tenant settings/policies prevent your account to be automatically login via username+password.

A quick way to check is to try [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli) login. Use following command to login your account via username+password and see if any detailed error:
`az login -u {your-account-name} -p {your-account-password} -t {your-tenant-id} --verbose`
(You can also replace `--verbose` with `--debug` to see more internal technical details)
