### ISSUE TITLE
Can not add scope which has been added in Azure Portal

### ISSUE THREAD

**Issue by YesOhh** [OfficeDev/TeamsFx#3416]
**Describe the bug**
I have changed the scope in Graph call and added it in the Azure Portal, but when i try to Authorize, i still need admin approval.

**To Reproduce**
1. change _scope in Graph.razor
2. add permissions in Azure Portal
3. Authorize in the teams app
4. still need admin approval

**Expected behavior**
log in successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/22308850/146748272-605f0842-f86e-42b0-92a8-ec1c871ac187.png)
![image](https://user-images.githubusercontent.com/22308850/146748364-01d3a892-474e-4b32-9f40-65893a57659b.png)

**Comment by KennethBWSong** [comment]
Hi @YesOhh, thank your for reporting this issue. We need to clarify that your tenant admin can change the config that which permission requires admin consent and the change will NOT show here on Azure Portal. You need to contact your tenant admin to make sure which permission requires admin consent.
