### ISSUE TITLE
Deployment to our production environment is not working (although it says successfully deployed)

### ISSUE THREAD

**Issue by FxWxP** [OfficeDev/TeamsFx#3559]
**Describe the bug**
I am expecting the new version of our app to be deployed to our production environment after a deployment. We upgraded our project from version 2 of TeamsFx, and were able to deploy a bunch of times after the upgrade. But I have tried again

**To Reproduce**
I am running a deployment from the Teams Toolkit. 
I run "Deploy to the cloud from" the deployment section. 
And only select "Tab Front-end" and "Azure Functions" as our bot is not implemented so far.

**Expected behavior**
An new version being deployed

**Screenshots**
Log file in the console of VScode
![image](https://user-images.githubusercontent.com/94601125/148360664-8fd9d380-c324-4529-a331-0874182356d2.png)

Deployment tab in the azure console
![image](https://user-images.githubusercontent.com/94601125/148360857-5d2015c9-9cb0-4046-980c-c7f1dcdb9852.png)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10
 - Version v3.1.1

**CLI Information (please complete the following information):**
 - OS: Windows 10
 - Version Unsure how to get this, maybe add this to the template?

**Comment by hund030** [comment]
Thanks for filing the issue. 
From the log seems you deploy your app to a `dev` environment. Do you select a correct environment while deploying?
![image](https://user-images.githubusercontent.com/26134943/148502280-fab528d0-ec2e-4814-93d7-af578057bf81.png)

Or you just mean your app works in local debug but doesn't work in the remote Azure environment?

**Comment by FxWxP** [comment]
It turned out to be something from the migration from 2.0 to 3.0 of teamsfx or something, because after I deleted the old environment and created a new one, everything works fine.
