### ISSUE TITLE
TeamsBotSsoPrompt cannot be instantiated (TypeError)

### ISSUE THREAD

**Issue by ClaudioConsolmagno** [OfficeDev/TeamsFx#3668]
**Describe the bug**
Trying to instantiate `TeamsBotSsoPrompt` results in `TypeError: Class constructor Dialog cannot be invoked without 'new'`

**To Reproduce**
1. Created a brand new bot project using Teams Toolkit on VSCode (using this guide: https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript?tabs=vscode%2Cvsc%2Cviscode%2Cvcode)
2. Updated botbuilder and teamsfx to current latest - toolkit comes with teamsfx version 0.4.0 which has a different problem.
3. Tried using TeamsBotSsoPrompt as per instructions https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-sdk
```
        loadConfiguration();
        this.addDialog(new TeamsBotSsoPrompt("TeamsBotSsoPrompt", {
               scopes: ["User.Read"],
             }));
```

**Screenshots**
Error Log:
```
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `node --inspect=9239 -r ts-node/register index.ts`
Debugger listening on ws://127.0.0.1:9239/08ccff6a-3dff-4d75-9c86-123441234234
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

/home/user/Workspace/microsoft-teams-integration/bot/node_modules/@microsoft/teamsfx/src/bot/teamsBotSsoPrompt.ts:150
    super(dialogId);
    ^
TypeError: Class constructor Dialog cannot be invoked without 'new'
    at new TeamsBotSsoPrompt (/home/user/Workspace/microsoft-teams-integration/bot/node_modules/@microsoft/teamsfx/src/bot/teamsBotSsoPrompt.ts:150:5)
```
package.json:
```
  "dependencies": {
    "@microsoft/adaptivecards-tools": "^0.1.2",
    "@microsoft/teamsfx": "^0.4.1",
    "botbuilder": "~4.15.0",
    "botbuilder-dialogs": "~4.15.0",
    "isomorphic-fetch": "^3.0.0",
    "restify": "^8.5.1"
  },
```

**VS Code Extension Information (please complete the following information):**
 - OS: Ubuntu Mate 21.10
 - VSCode: 1.62.1
 - `@microsoft/teamsfx`: 0.4.1

**Comment by ClaudioConsolmagno** [comment]
Extension version: v3.2.0 (Preview)

**Comment by dilin-MS** [comment]
Hi, @ClaudioConsolmagno , this is mainly cause by compiling the es6 file to es5 target. We have fixed the issue in https://github.com/OfficeDev/TeamsFx/pull/3716 and will in next sdk release. Feel free to comment and reopen the issue if next sdk release does not fix the issue in your project. Thx!

**Comment by ClaudioConsolmagno** [comment]
Thanks, that's great to hear! We decided to use the java sdk in the end so won't be checking if the fix works so closing this issue.
