### ISSUE TITLE
Time zone selector (Teams calendar)

### ISSUE THREAD

**Issue by drabanus** [OfficeDev/TeamsFx#3767]
I the calendar view of Microsoft Teams, there is the wrong UTC offset stored for Santiago, Chile. Note that the change dates for switching to daylight saving and back are non-standard ion Chile!

It is not clear to me whether this is a bug in the Teams software itself, or rather in the source of information in the time zone database.

Regards - David

**Comment by MuyangAmigo** [comment]
Hi @drabanus, maybe it would be easier to get help from Teams support via reporting this issue directly in the Teams Software. You can do this by:
* Click the help icon located in the bottom left side.
* Select `Report an issue`.
* Set the category as `Calendar`.

![image](https://user-images.githubusercontent.com/11220663/151294897-758e6060-97e1-478c-97f3-b6698fce1e9b.png)


I hope this would help you get support faster.
