### ISSUE TITLE
Manifest validation mismatch between cloud and local run in case of `fetchTask: false`

### ISSUE THREAD

**Issue by Foaloke** [OfficeDev/TeamsFx#3833]
**Is your feature request related to a problem? Please describe.**
In the VSCode extension for Teams App development, the local manifest has errors in the validator.

In the specific, I have a command configured as in the snippet below for the cloud.
As I want to avoid having a bot service, I embed one of the tabs in the in-chat dialog as it was an external link.

This works perfectly when I deploy on the cloud:

```json
"composeExtensions": [
        {
            "botId": "{{state.fx-resource-appstudio.teamsAppId}}",
            "commands": [
                {
                    "id": "myComm",
                    "type": "action",
                    "title": "{{config.manifest.commands.myComm.title}}",
                    "description": "{{config.manifest.commands.myComm.description}}",
                    "context": [
                        "compose"
                    ],
                    "fetchTask": false,
                    "taskInfo": {
                      "title": "{{config.manifest.commands.myComm.taskInfo.title}}",
                      "width": "400",
                      "height": "400",
                      "url": "{{{state.fx-resource-frontend-hosting.endpoint}}}/index.html#/inChat/myComm"
                    }
                  }
            ],
```

BUT when I run locally (F5), after the build process the app cannot be installed on the locally run service because of an "invalid manifest" error.

**Describe the solution you'd like**

I'd like manifests that work on the cloud to work on local as well, without misleading error messages.
I'd like manifest validation to be the same locally and on the cloud, so I can focus on programming problems.
I'd like to avoid running a whole bot service on the cloud for in-chat-dialogs if it's not necessary.

**Describe alternatives you've considered**

I ended up running a very thin bot service locally for debugging purposes that serves the redirect object.
Every time I debug I have to change the projectSettings.json (and have care not to commit it on main).

This is how the manifest looks for local debug run.
Notice how the local validator considers `commands: { parameters: ` as mandatory (despite this is not required for the actual template validator, and in fact it works perfectly fine when deployed on the cloud).

```json
"composeExtensions": [
        {
            "botId": "{{localSettings.bot.botId}}",
            "commands": [
                {
                    "id": "myComm",
                    "type": "action",
                    "title": "MY COMM (Local)",
                    "description": "My Command",
                    "initialRun": false,
                    "context": [
                        "compose"
                    ],
                    "fetchTask": true,
                    "parameters": [
                        {
                            "name": "",
                            "title": ""
                        }
                    ]
                }
            ],
```

In the bot for local runs I'm forced to serve the page hardcoding the url this way in the bot.
(Please note, ON THE CLOUD THIS IS NOT NECESSARY and WORKS PERFECTLY fine without it).

```javascript

return {
    task: {
      type: 'continue',
      value: {
        width: 400,
        height: 400,
        title: '[DEBUG_MODE_MY_COMM]',
        url: 'https://localhost:53000/index.html#/inChat/myComm',
      },
    },
  };

```

**Comment by KennethBWSong** [comment]
Hi @Foaloke. Thank you for reporting this issue. We will investigate this issue and reach you once we have any update.
Add @nliu-ms for more information.

**Comment by nliu-ms** [comment]
Hye @Foaloke , I will try to reproduce it and get back to you ASAP. Thank you!

**Comment by nliu-ms** [comment]
Sorry @Foaloke , I cannot reproduce your problem. Can you please provide more information about `after the build process the app cannot be installed on the locally run service because of an "invalid manifest" error.`? E.g. the screenshot / detailed error message. 

I'd be better if you can zip your project and send it to me. I'm afraid if I went through the different steps or the manifest change is different so failed to reproduce the error. Thanks!

**Comment by Foaloke** [comment]
### Steps to recreate

**1)** Add this command to _manifest.local.template.json_

```json
"composeExtensions": [
        {
            "botId": "{{state.fx-resource-appstudio.teamsAppId}}",
            "commands": [
                {
                    "id": "myComm",
                    "type": "action",
                    "title": "MyTitle",
                    "description": "MyDescription",
                    "context": [
                        "compose"
                    ],
                    "fetchTask": false,
                    "taskInfo": {
                      "title": "TaskTitle",
                      "width": "400",
                      "height": "400",
                      "url": "{{{state.fx-resource-frontend-hosting.endpoint}}}/index.html#/someValidTabsUrl"
                    }
                  }
            ],
 ```

**2)** Hit F5 - Debug(Edge)
**3)** Wait for the local environment to load

### Current Behaviour

On the browser instance run for local debugging, a message "The app could not be loaded" appears.
A button allowing to save the error reason to the clipboard is available. Using it an pasting the error code to any text editor will reveal a "error in manifest" message.

### Expected Behaviour

On the browser instance run for local debugging, the app can be added normally.
When opening the command as an in-chat extension, a MSTeams dialog appears and it embeds the `{{{state.fx-resource-frontend-hosting.endpoint}}}/index.html#/someValidTabsUrl` url

**Comment by Foaloke** [comment]
Have a look at this, I will create some screenshots as soon as I have a sec.

**Comment by nliu-ms** [comment]
Unluckily I cannot reproduce it, the in-chat dialog pop up without `The app could not be loaded` error.
![image](https://user-images.githubusercontent.com/71362691/154204287-35fcde98-150f-4dde-903b-6a91267a3f85.png)

![image](https://user-images.githubusercontent.com/71362691/154190351-2e167c92-cd8e-4593-8534-1567adaffc75.png)

Can you please visit [Teams Developer Portal](http://dev.teams.microsoft.com/apps), find your local debug Teams app
![image](https://user-images.githubusercontent.com/71362691/154204042-d8b4642d-9371-41f1-a326-c842cce2e96b.png)

And check if there is any validation errors? Thanks!
![image](https://user-images.githubusercontent.com/71362691/154204120-2ba45a8b-536c-40fc-a26a-35d2f1f8eb92.png)

**Comment by Foaloke** [comment]
We isolated the issue in a brand new project, and tried on the updated version of VSCode Teams Toolkit.

We confirm the issue doesn't appear on latest version, and also we noticed in case of issues the manifest validation gives more meaningful error messages now (thanks for that!).
