### ISSUE TITLE
Build Issue in VS2022.1 Preview 5 Teams Template

### ISSUE THREAD

**Issue by grumpykiwi** [OfficeDev/TeamsFx#3835]
**Describe the bug**
Created a brand new TeamsFX project using the latest build of VS2022 Pro 17.1.0 Preview 5. Does not compile.

**To Reproduce**
1. Go to Create New Project
2. Click on 'Microsoft Teams App -> Tabs
3. When project creation is complete, select Build Solution from Build menu.

**Expected behavior**
Project to build successfully. 22 errors instead.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11 Dev 22543.1000
 - Visual Studio 2022 Pro 17.1.0 Preview 5
 - TeamsFX 0.3.0-rc
 - TeamsFX.SimpleAuth 0.1.1
[Teams FX Build Errors.txt](https://github.com/OfficeDev/TeamsFx/files/8007112/Teams.FX.Build.Errors.txt)

Clicking on the first error brings up the file:

\interop\TeamsSDK\EnumDescriptionConverter.cs

It appears the error is on line 8. There should be a space between internal and class. Once I fix that, the program compiles and runs ok.

Thought y'all would like to know.

Cheers

**Comment by dilin-MS** [comment]
Add @JerryYangKai for more information.

**Comment by tecton** [comment]
Hi @grumpykiwi, thanks for the feedback! Sorry I cannot reproduce this bug in VS 2022 Pro 17.1.0 Preview 5. Our project template code doesn't include `internal` in the file `\interop\TeamsSDK\EnumDescriptionConverter.cs` on line 9. I guess the `internal` access modifier is automatically added by VS 2022.

I'll add the modifier to our template for a stable scaffolding process. Appreciate your help!

**Comment by grumpykiwi** [comment]
OK. Let me know if you want me to provide a zipped up solution folder or similar.

Thanks

**Comment by JerryYangKai** [comment]
@grumpykiwi  Hi, could you please provide a zip file including your solution for us to tracking this issue? Thanks.

**Comment by grumpykiwi** [comment]
Here you go. I pasted over the client ID, tenant ID, secret and deleted the bin & obj folders. Let me know if you need anything else.


Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

**Comment by JerryYangKai** [comment]
@grumpykiwi  Maybe Github ignore it, I could not find the zip file.

**Comment by grumpykiwi** [comment]
[MyTeamsApp11.zip](https://github.com/OfficeDev/TeamsFx/files/8029881/MyTeamsApp11.zip)

**Comment by grumpykiwi** [comment]
Trying again as a zip instead of a 7z.  Added to issue in github too.


Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

**Comment by JerryYangKai** [comment]
Like @tecton said, we are trying to improve the process of create project, in next release we will avoid this issue. Great thanks for reporting this bug.

**Comment by tecton** [comment]
Improved in #3896
