### ISSUE TITLE
bug report: Solution.FailedToExecuteTasks

### ISSUE THREAD

**Issue by Kensuke-Ito** [OfficeDev/TeamsFx#3974]
AadCreateAppError:Failed to create an app in Azure Active Directory. , Request failed with status code 503

**Comment by KennethBWSong** [comment]
Hi @Kensuke-Ito Thank you for reporting this issue! It seems that our toolkit use Microsoft Graph APIs to try to create Azure AD apps for you, and is getting 503 from Azure Active Directory. You can simply have a try with the following steps to see whether you can create an Azure AD app:
1. Go to [Azure Portal](https://ms.portal.azure.com/#home), login with the same M365 account you login in our toolkit and find "Azure Active Directory"
2. Go to "App Registration"
3. Click on "new registrations"
4. Fill in an app name and click on "Register"

If you can create an Azure AD app, you can go back to your project and provision again.
Please feel free to leave comment here if you meet with any problem.
