### ISSUE TITLE
Session Storage Error

### ISSUE THREAD

**Issue by grumpykiwi** [OfficeDev/TeamsFx#3986]
**Describe the bug**
All of a sudden seeing a new error when running Teams App from Visual Studio.

Microsoft.TeamsFx.ExceptionWithCode: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document. Error: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document. at Function.get (https://localhost:44350/_content/Microsoft.TeamsFx/teamsfx.js:15:4450) at He.getTokenCache (https://localhost:44350/_content/Microsoft.TeamsFx/teamsfx.js:15:81048) at He.<anonymous> (https://localhost:44350/_content/Microsoft.TeamsFx/teamsfx.js:15:77429) at Generator.next (<anonymous>) at a (https://localhost:44350/_content/Microsoft.TeamsFx/teamsfx.js:15:165) at Microsoft.TeamsFx.TeamsUserCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken) at TeamsStatusTabApp.Components.IndexBase.InitializeTeams() in D:\projects\TeamsStatusTabApp\TeamsStatusTabApp\Components\Index.razor.cs:line 110

Line 110 is my call to acquire a token

`Token = await teamsUserCredential.GetTokenAsync(new TokenRequestContext(new string[] { Scopes }), new System.Threading.CancellationToken());`

**To Reproduce**
Not sure how to reproduce. Error started happening all of a sudden after a few weeks of no work on the project,

**Expected behavior**
Should work as previous

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11
 - Version Build 22557 (Dev channel insider build)
 - Visual Studio 2019 16.11.10
 - Teams FX Toolkit 0.1.107.31731

**Additional context**
Have not found anything from searching around that would indicate where to start looking

**Comment by tecton** [comment]
Hi @grumpykiwi, as you are using Visual Studio 2019, the TeamsFx .NET SDK version is 0.1.0-rc if you haven't upgraded it.
It depends on the session storage of browser to store the access token.

From the error message you provided, could you please check the cookies settings of the browser?
You can visit `edge://settings/content/cookies` in Edge or `chrome://settings/content/cookies` in Chrome and check whether "Allow sites to save and read cookie data (recommended)" is enabled.

**Comment by grumpykiwi** [comment]
I am now receiving the following error when calling TeamsUserCredential.GetTokenAsync

Microsoft.TeamsFx.ExceptionWithCode
  HResult=0x80131500
  Message=Failed to get access token with error: 
  Source=Microsoft.TeamsFx
  StackTrace:
   at Microsoft.TeamsFx.TeamsUserCredential.GenerateAuthServerError(String content)
   at Microsoft.TeamsFx.TeamsUserCredential.<GetAndCacheAccessTokenFromSimpleAuthServer>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Microsoft.TeamsFx.TeamsUserCredential.<GetTokenAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at TeamsTestNet6.Components.IndexBase.<InitializeTeams>d__106.MoveNext() in D:\projects\TeamsTestNet6\TeamsTestNet6\Components\Index.razor.cs:line 119

  This exception was originally thrown at this call stack:
    [External Code]
    TeamsTestNet6.Components.IndexBase.InitializeTeams() in Index.razor.cs

This is my appsettings.json

{
	"AllowedHosts": "*",
	"CLIENT_ID": "<clientId>",
	"CLIENT_SECRET": "<secret>",
	"IDENTIFIER_URI": "api://teamstab.partnercomm.net/<clientId>",
	"TAB_APP_ENDPOINT": "https://teamstab.partnercomm.net/",
	"OAUTH_AUTHORITY": "https://login.microsoftonline.com/f2b31dc2-1677-463d-8cf1-2150d7ff1100",
	"AAD_METADATA_ADDRESS": "https://login.microsoftonline.com/f2b31dc2-1677-463d-8cf1-2150d7ff1100/v2.0/.well-known/openid-configuration",
	"ALLOWED_APP_IDS": "1fec8e78-bce4-4aaf-ab1b-5451cc387264;5e3ce6c0-2b1f-4285-8d4b-75ee78787346",
	"Scopes": "User.ReadWrite Presence.Read.All Group.Read.All GroupMember.Read.All Directory.Read.All",
	"GroupId": "<groupId",
	"DetailedErrors": true,
	"Logging": {
		"LogLevel": {
			"Default": "Information",
			"Microsoft": "Warning",
			"Microsoft.Hosting.Lifetime": "Information"
		}
	},
	"TeamsFx": {
		"Authentication": {
			"ClientId": "<clientId>",
			"SimpleAuthEndpoint": "https://teamstab.partnercomm.net/",
			"InitiateLoginEndpoint": "https://teamstab.partnercomm.net/auth-start.html"
		}
	},
	"MicrosoftGraph": {
		"MaxDegreeOfParallelism": 15,
		"Scopes": "APIConnectors.Read.All APIConnectors.ReadWrite.All Contacts.Read Directory.Read.All Directory.ReadWrite.All Group.Read.All Group.ReadWrite.All GroupMember.Read.All GroupMember.ReadWrite.All MailboxSettings.Read openid Presence.Read Presence.Read.All PrivilegedAccess.Read.AzureADGroup profile Tasks.ReadWrite TeamsAppInstallation.ReadForChat TeamsAppInstallation.ReadForTeam TeamsAppInstallation.ReadForUser TeamsAppInstallation.ReadWriteForChat TeamsAppInstallation.ReadWriteForTeam TeamsAppInstallation.ReadWriteForUser TeamsAppInstallation.ReadWriteSelfForChat TeamsAppInstallation.ReadWriteSelfForTeam TeamsAppInstallation.ReadWriteSelfForUser User.Read User.Read.All User.ReadWrite User.ReadWrite.All email",
		"BaseUrl": "https://graph.microsoft.com/v1.0",
		"BaseUrlBeta": "https://graph.microsoft.com/beta",
		"PublishNoteUrl": "https://presence.teams.microsoft.com/v1/",
		"GroupsQueryString": "members?$count=true&$top=200&$select=givenName,surname,displayName,id,officeLocation,jobTitle,mobilePhone,businessPhones,faxNumber,homePhone,city,state,userPrincipalName",
		"ColumnList": "givenName,surname,displayName,id,officeLocation,jobTitle,mobilePhone,businessPhones,faxNumber,homePhone,city,state,userPrincipalName"
	}
}

This app is built in Visual Studio 2022 Preview 1.0 Version 17.2.0 with Teams FX toolkit 0.1.160.49857

The previous error was fixed by using a different client Id. No idea why that cleared that error

Thanks

**Comment by grumpykiwi** [comment]
App will run with client id of aa682e29-5c6e-4554-be16-455fb05f97f9 but fails with client id 7dec84d2-d53e-4ed0-8271-cbb672e25431. I dont see anything between the 2 app registrations that would make a significant difference.

**Comment by tecton** [comment]
The error means that HTTP request from TeamsFx SDK to SimpleAuth library fails but have no HTTP content.
It looks like you have changed the configuration to customized values.
`CLIENT_ID`, `CLIENT_SECRET`, `IDENTIFIER_URI` etc. are used by SimpleAuth library. It's also related to the AAD app configurations. E.g. missing "CLIENT_ID" will cause the error.

Could you please share the changes of app settings or reproducing steps?
Or you can capture the HTTP request to see if it's an unauthorized response from SimpleAuth.

**Comment by grumpykiwi** [comment]
I used the client id etc from an AAD app registration that I knew worked. I found out there was a piece I had missed. The ID field from the manifest.json was wrong. I managed to find this and update manifest in the broken project plus update the launchsettings.json launch url to get it all working.

I think it would be a great idea to document the different parts of a configuration, where they come from and how they relate to each other. Currently it is a real guessing game as the error messages are not very helpful. A diagram would be great too. Also document what parts are grabbed from where during the publish phase.


Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

**Comment by tecton** [comment]
This is a very good advice and appreciate your help! Some of tasks / libraries are behind the scene and we are simplifying these settings as well as providing documentation about how to customize it.

**Comment by grumpykiwi** [comment]
Hi

From a personal perspective I would like more information on what these tasks are doing. I am not a fan of the black box approach. I think this would help a lot with troubleshooting also. Surfacing more meaningful errors would help as well. Would be happy to get on another call with John miller etc to discuss.

Cheers


Mark

Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

________________________________
