### ISSUE TITLE
new bug report: Task 'frontend npm install' failed

### ISSUE THREAD

**Issue by AnandS6** [OfficeDev/TeamsFx#3993]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**Additional context**

**Error detail**
{
    "logFile": "C:\\Users\\AnandS6\\AppData\\Roaming\\npm-cache\\_logs\\2022-02-21T07_27_54_978Z-debug.log",
    "timestamp": "2022-02-21T07:27:54.978Z",
    "nodeVersion": "v14.18.1",
    "npmVersion": "v6.14.15",
    "cwd": "C:\\Users\\AnandS6\\Documents\\MyCodes\\wishes-app\\Code\\Dev\\tabs",
    "exitCode": 1,
    "errorMessage": [
        "3898 error code EINTEGRITY",
        "3899 error errno EINTEGRITY",
        "3900 error Invalid response body while trying to fetch https://registry.npmjs.org/ms: Integrity verification failed for sha512-Bo1zuwd83jE5XqiQUoKT1vh Q091sifXNZJRBO1RcrA3UyQDFOJ0Vi0uqIRACxcWPN2iXR aJ2ftxx7ddNSBtg== (C:\\Users\\AnandS6\\AppData\\Roaming\\npm-cache\\_cacache\\content-v2\\sha512\\06\\8d\\73bb077cde31395ea890528293d6f87e434f75b227d735925104ed5172b03753240314e274562d2ea884400b17163cdda25d1f9a2767edc71edd74d481b6)"
    ]
}

**Comment by kuojianlu** [comment]
@AnandS6 Please follow the steps below which may solve this issue:
1. Run `npm cache clear --force`
2. Remove `tabs/package-lock.json` and `tabs/node_modules`
3. F5 again
