### ISSUE TITLE
TeamsFx Tab app deployment approach to scale the app to be deployed across multiple tenant without going for CICD or Teams toolkit

### ISSUE THREAD

**Issue by v-royavinash** [OfficeDev/TeamsFx#4003]
We are developing MS teams tabs app for OfficeDev which can be deployed by our customer across multiple tenant. The deployment approach we have is,

1. Create the App registration manually.
2. Provision the TeamsFx resources by the ARM template.
3. Deploy the TeamsFx app to App service or static website Azure storage.

The problem is the TeamsFx app has dependency on the environment variable which includes 

- REACT_APP_CLIENT_ID
- REACT_APP_FUNC_ENDPOINT
- REACT_APP_START_LOGIN_PAGE_URL
- REACT_APP_TEAMSFX_ENDPOINT 

For our case these values will be provided by the customer when they will be deploying the app to their tenant. 

Is there any way to deploy the app through ARM template? Also could you please suggest the approach to deploy the TeamFx app in such a way that the client Id can be provided by individual customers
while they are deploying the app to their specific tenant and then build gets generated for deployment?

You can reach out to me at **_v-royavinash@microsoft.com_** for further details over MS Teams.

**Comment by sffamily** [comment]
Hi v-royavinash, I've pinged your on Teams to learn about your questions. Sounds like you won't have access to the client's cloud resources for provision.

**Comment by adashen** [comment]
Close here as we have the solve the issue through arm script
