### ISSUE TITLE
bug report: Solution.FailedToExecuteTasks

### ISSUE THREAD

**Issue by ron-dev-chowis** [OfficeDev/TeamsFx#4024]
PreconditionError:'graph token' is missing. Suggestions: Please retry the current step.

**Comment by xiaolang124** [comment]
Have you signed in to M365 account? You can open Teams toolkit treeView and click ```Sign in to M365``` button and continue.
![image](https://user-images.githubusercontent.com/13211513/155641470-de413505-a549-44b1-884e-9e7c3b80021f.png)
