### ISSUE TITLE
OBO flow is very slow with Azure functions back end

### ISSUE THREAD

**Issue by AnthonyPhan** [OfficeDev/TeamsFx#4049]
**Describe the bug**
Teamsfx provides 2 different methods for making graph calls form a MS Teams application (Authorization Code Flow with PKCE and On Behalf of Flow). When using the Authorization Code Flow client side the data is returned from Microsoft graph in milliseconds. When using the On behalf of flow with function apps back end it take 3-4 seconds to return the same data. This time delay when using OBO flow make the app experience very poor for end users, especially when many apps will need to make multiple graphs calls.

Is there a reason for the drastic performance issues with the OBO flow?

**To Reproduce**
1. Simply open the "Hello-world-with-back-end-example"
2. test getting the user data using the interactive Authorisation button, this will return the user profile instantly
3. Click the "Call Function Apps" button. This will take 3-4 seconds to respond

**Expected behavior**
The function apps OBO flow should only add a few milliseconds more than the Authorization Code flow. 

**Screenshots**
Note the GIF below is sped up... the Function app call was 4 seconds.
![functionapps](https://user-images.githubusercontent.com/12785492/155865025-ca291298-e3d5-4a64-8a29-147346f83cdc.gif)

**Additional context**
Our app currently will make a graph call to get the users teams and then make a a graph call for each team to return its corresponding channels. This process can take minutes with the current performance of the OBO flow. This can be improved with concurrent calls but its still too slow with the current implementation.

**Comment by blackchoey** [comment]
Hi @AnthonyPhan thanks for contacting us.
When you call the API for the first time, Azure Functions "cold starts" the server, which initializes everything. This takes extra time and resulted in long latency on first API call. You can refer this blog for more details: https://azure.microsoft.com/en-us/blog/understanding-serverless-cold-start/

Can you click "Call Azure Function" button multiple times and see whether the performance gets better? My experiment shows:
1. Call Microsoft Graph `/me` API from browser takes 436 ms
2. Call `/getUserProfile` API via "Call Azure Function" for the first time takes 3.01 s
3. Call `/getUserProfile` API via "Call Azure Function" for the second time takes 700 ms (includes time for OBO flow, Microsoft Graph API call, other http related processing in Azure Functions)
