### ISSUE TITLE
VS 2022 Support

### ISSUE THREAD

**Issue by WhitWaldo** [OfficeDev/TeamsFx#4187]
**Is your feature request related to a problem? Please describe.**
The Teams Toolkit is currently only available (in preview) in VS 2019. I do almost all my work in the newer VS 2022 at this point and this is the only reason I still have VS 2019 installed now. Searching for it in the extensions manager within VS 2022 yields no results.

**Describe the solution you'd like**
I'd like to see the preview support extended to VS 2022.

**Describe alternatives you've considered**
Currently using VS 2019.

**Additional context**
It's a pretty simple request, so I'll leave it at this.

**Comment by therealjohn** [comment]
@WhitWaldo 

Thanks for reaching out and sorry for the confusion. For VS 2022, we've bundled the Teams Toolkit extension as part of the ASP.NET and web development working in the Visual Studio Installer. 

You can find it as an individual component that is optional to install. It's currently available in VS Preview 17.1 P1. However, I recommend waiting until 17.1 P2 is available (planned for this week) which fixes some common issues we're seeing in P1. 

![image](https://user-images.githubusercontent.com/1501196/158184064-65b2775d-ecec-4b7c-9b03-0302acadea88.png)

**Comment by WhitWaldo** [comment]
@therealjohn Personally, I think that's a better distribution channel than an extension and I'm all for it... except for the dependency on VS Preview. Any guesses when I'll be able to use it in VS 2022 stable?

**Comment by therealjohn** [comment]
@WhitWaldo As soon as the current 17.1 Preview ships to stable. Unfortunately, I don't have a date on that. I'd expect something in the next few months.

**Comment by WhitWaldo** [comment]
@therealjohn Looking forward to it! Thanks!
