### ISSUE TITLE
isInTeams state always returns true 

### ISSUE THREAD

**Issue by AnthonyPhan** [OfficeDev/TeamsFx#4206]
**Describe the bug**
The isInTeams state always return true even when the react app is not embedded in teams

**To Reproduce**
Add the following line to your app and notice how it will always return true..
```
const { isInTeams } = useTeamsFx();
```

**Expected behavior**
- When embedded in teams this should return true
- When outside of teams it should return false

**Comment by SLdragon** [comment]
Hi, @AnthonyPhan , here is the logic to check whether in teams we're using.
https://github.com/wictorwilen/msteams-react-base-component/blob/master/src/useTeams.ts#L18

It cannot 100% make sure that the code is running inside Teams.

Here is the related discussion in teams library repo about the check, and you can choose the right one you want to use:
https://github.com/OfficeDev/microsoft-teams-library-js/issues/310
