### ISSUE TITLE
Support node.js v16 (LTS) and v17 (latest)

### ISSUE THREAD

**Issue by formulahendry** [OfficeDev/TeamsFx#4223]
Currently in VS Code, when 'F5' to debug a Teams Project, it says only support node v10, v12, v14.

![image](https://user-images.githubusercontent.com/1050213/158146408-d477101b-f926-447a-9c7c-03e2b7c7aa29.png)

However, per https://nodejs.org/en/, current LTS of Node.js is already v16.

![image](https://user-images.githubusercontent.com/1050213/158145935-cba0c5ce-0364-4327-a15b-d074a8414705.png)

![image](https://user-images.githubusercontent.com/1050213/158146756-ec7f0d10-ebc0-408a-81bb-afc28c504c07.png)

Please help support LTS version. Thanks!

**Comment by meifans** [comment]
Hi @formulahendry, thanks for your advice.

 The supported node.js version of Teams Toolkit are as follows:
| app \ version| 10 | 12 | 14 | 16|  
| -- | -- | -- | -- | -- |
| Tab | √ | √ |  √ |  √ | 
| Function | √ |  √ |  √ |  × | 
| SPFx | √ |  √ |  √ |  × | 

We've been thinking about supporting node.js 16 (17), but there are several limitations: 

- SPFx SDK : node.js 16 is not supported.
- Azure Functions Core Tools 4.x : support level to node.js 16 is **Preview**.  And node.js (10/12) are not supported.
- Breaking changes between Azure Functions Core Tools 4.x and 3.x : [refer link](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=in-process%2Cv4&pivots=programming-language-csharp#migrating-from-3x-to-4x)

Azure Functions Core Tools: Languages by runtime version
![image](https://user-images.githubusercontent.com/12523371/158351959-c364dd1c-492d-45ee-b20c-0c92d4bbbd70.png)

For these reasons, we can't support node.js 16 or above for Function app and SPFx app, at least so far.
