### ISSUE TITLE
'IsInTeams' does not recognized from ios and android teams app - dotnet-sdk

### ISSUE THREAD

**Issue by georgemichailou** [OfficeDev/TeamsFx#4365]
**Describe the bug**
When I run my app from android or ios teams application the IsInTeams method returns false and GetUserInfo is not working.

`        protected override string ModulePath => "./js/TeamsJsBlazorInterop.js";
`

`export function inTeams() {
    var microsoftTeamsLib = microsoftTeams || window["microsoftTeams"];
    return window.self !== window.top && microsoftTeamsLib !== undefined;
}`

```
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);

        if (firstRender)
        {
            isInTeams = await MicrosoftTeams.IsInTeams();

            if (isInTeams)
            {
                var user = await teamsUserCredential.GetUserInfoAsync();
                userName = user.DisplayName;
                preferredUserName = user.PreferredUserName;
            }
            else
            {
                errorMessage = "Not running in Microsoft Teams.";
            }

            isLoading = false;
            StateHasChanged();
        }
    }
```

**VS Information*
Version Visual Studio Enterprise 2022
Microsoft Teams development tools

![image](https://user-images.githubusercontent.com/14372162/159651029-0c70fb1c-7ddc-4b02-beec-18d43c771c27.png)

**Comment by tecton** [comment]
Hi @georgemichailou, thanks for reporting this issue.
Please replace the `inTeams` function in `js/TeamsJsBlazorInterop.js` with the following snippet:
```typescript
export function inTeams() {
    if (
        (window.parent === window.self && window.nativeInterface) ||
        window.navigator.userAgent.includes("Teams/") ||
        window.name === "embedded-page-container" ||
        window.name === "extension-tab-frame"
    ) {
        return true;
    }
    return false;
}
```

**Comment by georgemichailou** [comment]
Thanks !
