### ISSUE TITLE
Teams Package Build Failure During Provision

### ISSUE THREAD

**Issue by MuyangAmigo** [OfficeDev/TeamsFx#4407]
Hi guys. I'm trying to add provisioning to our pipeline and it is mostly working, but I'm hitting the following error which is causing the teamsfx provision command to fail:

```
TeamsPackageBuildError: Validation error: 
251 /developer/websiteUrl must match pattern "^[Hh][Tt][Tt][Pp][Ss]?://"
252 at Function.UserError (/home/mct/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:4807482)
253 at AppStudioPlugin.buildTeamsPackage (/home/mct/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:4738081)
254 at async AppStudioPlugin.postProvision (/home/mct/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:4734772)
255 at async Object.configureResourceAdapter (/home/mct/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:5392419)
256 at async AppStudioPluginV2.configureResource (/home/mct/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:4818749)
257 at async Promise.all (index 2)
258 at async Object.executeConcurrently (/home/mct/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:5675068)
259 at async TeamsAppSolutionV2.provisionResource [as provisionResources] (/home/mct/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:5714720)
260 at async FxCore.provisionResourcesV2 (/home/mct/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:4133055)
261 at async FxCore.<anonymous> (/home/mct/node_modules/@microsoft/teamsfx-cli/lib/index.js:2:4186268)
```

The websiteUrl configured in config.[env].json definitely does match that regex:

```
   "manifest": {
        "developerName": "Metaswitch",
        "websiteUrl": "https://contoso.com",

```

We have seen that error running this from VS Code as well, but we can usually fix it by just saving the config.[env].json file again and re-running. I've retried the CI job multiple times but still no luck. Can you help?

**Comment by jtgs** [comment]
This is happening in CI with the latest version of teamsfx-cli (0.12.1) on a node:lts container. It's also happened intermittently running Teams Toolkit v3.6.0 in VS Code, connected to the same node:lts container. I don't think we've seen it running Teams Toolkit directly in Windows.

**Comment by eriolchan** [comment]
I guess the reason why you want to edit ```config.[env].json``` is because you need to setup custom domain for customer and attempt to update this value in config file. Is my assumption correct?

If that's true, I think the correct way is to edit file ```templates/appPackage/manifest.remote.template.json```, and update the value of ```websiteUrl``` from ```"{{{state.fx-resource-frontend-hosting.endpoint}}}"``` to ```"{{config.manifest.websiteUrl}}"``` for your case.
```
"developer": {
   "websiteUrl": "{{{state.fx-resource-frontend-hosting.endpoint}}}"
}
```

By this way, Teams Toolkit will automatically retrieve websiteUrl value which is defined in ```config.[env].json``` for the final Teams manifest file. You can find more underlying details of ```teamsfx provision``` and possible customization from this document https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/provision#customization-scenarios
