### ISSUE TITLE
Deploy app registration & Teams App as a Guest user in another tenant

### ISSUE THREAD

**Issue by msekkappan** [OfficeDev/TeamsFx#4494]
**Describe the bug**
Added O365 & Azure account to the account tab with guest user access to Teams.  The guest user has owner privileges to Azure 
resource group.

**To Reproduce**
1. Click "provision in the cloud"
2. Notice that the registration is created in the main tenant, not the tenant where the guest user resides
3. Click "Zip Teams metadata package", teams package is pointing to the registration under the main tenant. 

**Expected behavior**
Ability to choose where the registration needs to be created.

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - Windows 11
 - Version 11

**CLI Information (please complete the following information):**

**Additional context**
Would like to provision as a guest user in O365 tenants

**Comment by KennethBWSong** [comment]
Hi @msekkappan Thank you for using our toolkit. To better understand your problem, we need some more context.
1. Which account do you login with your guest account? M365 or Azure?
2. Which account you want to have the ability to choose where the registration needs to be created?
