### ISSUE TITLE
bug report: unknown.Error

### ISSUE THREAD

**Issue by sivateja1995** [OfficeDev/TeamsFx#4617]
EPERM: operation not permitted, open '\\wsl$<REDACTED: user-file-path>'

stack:
Error: EPERM: operation not permitted, open '\\wsl$<REDACTED: user-file-path>'

**Comment by adashen** [comment]
Hi @sivateja1995 , thanks for reporting the issue. Can you help to provide the repro steps and more console logs?

**Comment by adashen** [comment]
Hi @sivateja1995  seems the detail info is not attached. Can you help to re-post the detail?
