### ISSUE TITLE
Vulnerabilities in the packages of TeamsFx tab project

### ISSUE THREAD

**Issue by amitkh22** [OfficeDev/TeamsFx#4630]
**Describe the bug**
When we create the project for TeamsFx tabs, there are  multiple vulnerabilities in the NPM packages. We were able to remove some of the vulnerabilities but updating remaining packages results in breaking the solution. We are mainly trying to remove High and Critical vulnerabilities. Below are some of the packages which have critical/high vulnerabilities. 

> immer
> glob-parent
> underscore
> node-forge
> ansi-html

Above packages are part of "react-scripts" module.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version: - 3.7.0

**Comment by eriolchan** [comment]
@amitkh22 Thanks for reporting this issue, and we are fixing it and release a new version in May. The fix solution is to upgrade react-scripts package from 4.x to 5.0.

**Comment by amitkh22** [comment]
@eriolchan I tried to update the "react-scripts" module from 4.x to 5.0 but that results in breaking other modules. Are there any other packages/ modules that I need to update with it?

**Comment by hund030** [comment]
@amitkh22 I update `react-scripts` and when executing `react-scripts start` or `react-scripts build`, I get some warnings saying `Failed to parse source map from teamsfx-react`.
To work around these warnings, just add `GENERATE_SOURCEMAP=false` before start or build script:
```
"scripts": {
    "start": "GENERATE_SOURCEMAP=false react-scripts start",
    "build": "GENERATE_SOURCEMAP=false react-scripts build",
    ...
```
I did not get any error/warning from opentelemetry. Could you share more details about the errors/warnings you met?

**Comment by v-ashrirao** [comment]
@hund030, Thank you for the response. 
All vulnerabilities are fixed after updating react-scripts version to 5.0.0

**Comment by eriolchan** [comment]
Close this issue since latest Teams Toolkit has upgrade react-scripts to 5.0
