### ISSUE TITLE
How to deploy TeamsFx solution to the AzureGovernment tenant

### ISSUE THREAD

**Issue by sagar-malpure** [OfficeDev/TeamsFx#4666]
Hello Team,

we are trying to deploy [TeamsFx](https://github.com/OfficeDev/TeamsFx-Samples/tree/v2) samples to the AzureGovernment tenant.
we followed this approach - https://github.com/OfficeDev/TeamsFx/blob/dev/docs/cli/user-manual.md#e2e-collaboration-work-flow-in-cli but not working for Azure government (GCC/GCC-H).

Please suggest.

**Comment by sffamily** [comment]
@sagar-malpure Do you refer to government tenant on regular Azure or government cloud? which step it was not working with Azure Government cloud? the Azure login step? or add collaborator step? As government cloud has more stringent permissions, we need to know the exact step and if possible the error messages that you can capture, for us to analyze it and help troubleshoot. If it is government tenant on Azure, you may need to double check the permissions you have for that tenant.
