### ISSUE TITLE
@microsoft/teamsfx - The TeamsFx class will not receive a token if read access to Azure Active Directory is not given.

### ISSUE THREAD

**Issue by tobim-dev** [OfficeDev/TeamsFx#4668]
**Describe the bug**
The TeamsFx class cannot get any token and runs into endless loop when locally started via `teamfx preview --local` and with read access to Azure Active Directory. 

**To Reproduce**
1. Configure the Azure ADs User Settings to have the option "Restrict access to Azure AD administration portal" activated
2. Manually create a app registration and configure it according to the demands of teamFx
4. Use a tenants' user that has no read access to the Azure Directory. Login in via teamfx-cli
5. Try using the TeamFX class to obtain a token within the React application
7. See browser log message `@microsoft/teamsfx : Info - Create teams user credential` followed by `@microsoft/teamsfx : Verbose - Validate authentication configuration`. The application runs into an endless loop. 

**Expected behavior**
A token is successfully obtained. 

**Screenshots**
![Screenshot 1](https://user-images.githubusercontent.com/15176413/163212545-18353c47-dc76-4930-99ba-31c936719f79.png)

Code used to obtain a token: 
```typescript
import { AxiosRequestConfig } from 'axios';
import { TeamsFx } from '@microsoft/teamsfx';

export const getAuthorizationHeaders = async (): Promise<AxiosRequestConfig> => {
  const teamsfx = new TeamsFx();
  const credentials = teamsfx.getCredential();
  const accessToken = await credentials.getToken('https://graph.microsoft.com/User.Read');

  return {
    headers: {
      Authorization: `Bearer ${accessToken.token}`,
    },
  };
};
```

We also tried it with an empty scope. 

**CLI Information**
 - OS: MacOS 12.3.1
 - @microsoft/teamsfx-cli version 0.11.1
 - @microsoft/teamsfx version 0.6.0

Thank you in advance for your help!

**Comment by tecton** [comment]
Hi @tobim-dev, have you consented the tenant user in step 3 to use the AAD app? If not, `credentials.getToken()` will throw an error: `ErrorWithCode.UiRequiredError: Failed to get access token cache silently, please login first: you need login first before get access token.`

I tried to reproduce this bug following your steps.
In step 2, I assume that your configured AAD app is similar to auto-generated one by Teams Toolkit.
And I updated the code in `Welcome.tsx` to:
```typescript
const { loading, data, error } = useData(async () => {
  if (teamsfx) {
    try {
      const credentials = teamsfx.getCredential();
      const accessToken = await credentials.getToken('https://graph.microsoft.com/User.Read');
      console.log('accessToken: ' + accessToken?.token);
    } catch (e) {
      console.log(e);
    }
    const userInfo = await teamsfx.getUserInfo();
    return userInfo;
  }
});
```
The messages in console are like:
```
[Fri, 15 Apr 2022 06:11:46 GMT] : @microsoft/teamsfx : Info - Get access token with scopes: User.Read
useTeamsFx.ts:55 [Fri, 15 Apr 2022 06:11:46 GMT] : @microsoft/teamsfx : Verbose - Get SSO token from memory cache
useTeamsFx.ts:55 [Fri, 15 Apr 2022 06:11:46 GMT] : @microsoft/teamsfx : Verbose - Failed to call acquireTokenSilent. Reason: no_account_error: No account object provided to acquireTokenSilent and no active account has been set. Please call setActiveAccount or provide an account on the request.. 
useTeamsFx.ts:55 [Fri, 15 Apr 2022 06:11:46 GMT] : @microsoft/teamsfx : Info - Get access token with scopes: https://graph.microsoft.com/User.Read
useTeamsFx.ts:55 [Fri, 15 Apr 2022 06:11:46 GMT] : @microsoft/teamsfx : Verbose - Failed to call acquireTokenSilent. Reason: no_account_error: No account object provided to acquireTokenSilent and no active account has been set. Please call setActiveAccount or provide an account on the request.. 
browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
useTeamsFx.ts:55 [Fri, 15 Apr 2022 06:11:48 GMT] : @microsoft/teamsfx : Verbose - Failed to call ssoSilent. Reason: consent_required: AADSTS65001: The user or administrator has not consented to use the application with ID '48083a97-72e4-46ee-af10-2a27123a0f9d' named 'aadError'. Send an interactive authorization request for this user and resource.
Trace ID: 318d7b6f-dfb5-42a0-94f0-d095e1901c00
Correlation ID: 2c8c601a-091c-4ed0-a2df-737201f14816
Timestamp: 2022-04-15 06:11:47Z. 
useTeamsFx.ts:55 [Fri, 15 Apr 2022 06:11:48 GMT] : @microsoft/teamsfx : Error - Failed to get access token cache silently, please login first: you need login first before get access token.
useTeamsFx.ts:55 [Fri, 15 Apr 2022 06:11:48 GMT] : @microsoft/teamsfx : Verbose - Failed to call ssoSilent. Reason: consent_required: AADSTS65001: The user or administrator has not consented to use the application with ID '48083a97-72e4-46ee-af10-2a27123a0f9d' named 'aadError'. Send an interactive authorization request for this user and resource.
Trace ID: 4c7683a3-0350-41fe-b912-a92b0b881a00
Correlation ID: 6958d3ef-8f0e-4983-b422-cf8a2c11b2be
Timestamp: 2022-04-15 06:11:47Z. 
useTeamsFx.ts:55 [Fri, 15 Apr 2022 06:11:48 GMT] : @microsoft/teamsfx : Error - Failed to get access token cache silently, please login first: you need login first before get access token.
Welcome.tsx:48 ErrorWithCode.UiRequiredError: Failed to get access token cache silently, please login first: you need login first before get access token.
    at TeamsUserCredential.getToken (teamsUserCredential.browser.ts:248:1)
    at async Welcome.tsx:45:1
useTeamsFx.ts:55 [Fri, 15 Apr 2022 06:11:48 GMT] : @microsoft/teamsfx : Info - Get basic user info from SSO token
useTeamsFx.ts:55 [Fri, 15 Apr 2022 06:11:48 GMT] : @microsoft/teamsfx : Verbose - Get SSO token from memory cache
```

**Comment by tobim-dev** [comment]
Hi @tecton, 

thanks for reproducing the error. We gave our app registration admin consent for the Graph API scope "User.Read". 

Regarding your assumption for step 2: Yes, we manually configured the AAD app as it would be auto-generated via the teamsfx-CLI, which included for us: 
* Setting the redirect urls in the Authentication blade
* Create a secret named `default` in the Certificate & Secret blade
* Add an `idtyp` claim in the Token configuration
* Configure the `User.Read` Permission including Admin Consent in the API Permissions blade
* Define a new api scope "access_as_user" on "api://localhost/CLIENT-APP-ID/access_as_user" within the Expose an API blade
* Add all 6 Client Ids in the Authorized Client Section within the Expose an API blade

As the user has no read access to the Azure AD, the `teamfx preview --local` command takes also a long time to start, as it always try to read the app registration first (which it can't), then gives some instructions on how to check the AAD app registration and then starts anyway.

**Comment by tecton** [comment]
Hi @tobim-dev,

I've tried again but failed to reproduce the bug. SDK and CLI versions are matched. Here's my steps:
1. Using Teams Toolkit to scaffold a Tab app.
2. Add the code to retrieve access token in previous comment.
3. Click F5 or run `teamsfx preview --local` to start for the first time and stop it. (This is to generate the AAD app)
4. Go to Azure Portal and login as tenant admin.
5. Remove read-only tenant user from owner list and add admin account as owner.
6. Grant admin consent for permission `User.Read`.
7. Run `teamsfx preview --local` again and it takes a long time because the login user didn't have permission to update AAD app.
    - Failed in step: Update permission for Azure AD app.
    - Failed in step: Update redirect uri for Azure AD app.
    - Failed in step: Update application id uri for Azure AD app.
8. Check the console output of browser and I can see the access token.

Your configuration steps look good to me. So, I'm not sure whether there's any steps missed when using an existing AAD app. Also involve @blackchoey to check the steps.
