### ISSUE TITLE
Protecting the clientSecret?

### ISSUE THREAD

**Issue by AndrewCraswell** [OfficeDev/TeamsFx#4736]
**Describe the bug**
It seems like the AAD `clientSecret` is being stored in the `localSettings.json` file, along with the `clientId`. This raises a lot of questions about security. Is this safe to be checked into source control? Or should every developer maintain their own file which never gets checked in?

What are the risks associated with having this secret value viewable in the repo? Is there any way to exclude it, or rely on a KeyVault value?

**Similar issues:**
https://github.com/OfficeDev/TeamsFx/issues/3330 -- Obtain Client Secret From Key Vault

**Comment by formulahendry** [comment]
Hi @AndrewCraswell , for the `clientSecret` in `localSettings.json` file, it is an encrypted value stating with `crypto_`. It is **NOT recommended** to check this file into source control.  Developer need to maintain their own file which never gets checked in.

In addition, you could try the experimental features for Unify Conigs:
![image](https://user-images.githubusercontent.com/1050213/164393857-816dd8f1-1e3e-40f5-b4ef-8b2139c1de13.png)

With that, secret is separated form other settings. It is stored in a separate `local.userdata` file:
![image](https://user-images.githubusercontent.com/1050213/164394337-436eb581-51f9-4578-8ef5-db9a8cbb8c24.png)

Let me know if you have any other question.

**Comment by AndrewCraswell** [comment]
@formulahendry Thanks for the clarification, this makes more sense to me. But does this mean that every developer who works on the app gets a unique client is generated? And if this is the case, when we need to authorize an SSO token with our own APIs, what is the best way to do that? I feel like with so many clientIds we will need to constantly amend our API. Are there any samples we should look at?

**Comment by formulahendry** [comment]
- For local debug: Yes, every developer who works on the app gets a unique client.
- For app deployed to Azure: there is a feature to let multiple developers to share on Azure AD App. You could follow the doc and have a try: https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-collaboration?cid=kerryherger

**Comment by AndrewCraswell** [comment]
Based on the samples, I understand how the SSO token can get authorized for MS Graph, but I guess I'm not really understanding how to authorize against our own microservices since we can't predict the clientIds for local testing. Any samples or docs around this aspect you can point me to?

**Comment by formulahendry** [comment]
@AndrewCraswell Maybe you could try this document: https://github.com/OfficeDev/TeamsFx/wiki/%5BDocument%5D-Connect-to-an-API-(Preview-Feature), (Note: you need use Teams Toolkit with latest pre-release version: https://github.com/OfficeDev/TeamsFx/releases )

**Comment by formulahendry** [comment]
BTW, in case you do not want to hard code the client id, you could use below code to get current client id:
```
teamsfx.getConfig('clientId')
```

**Comment by AndrewCraswell** [comment]
> @AndrewCraswell Maybe you could try this document: https://github.com/OfficeDev/TeamsFx/wiki/%5BDocument%5D-Connect-to-an-API-(Preview-Feature), (Note: you need use Teams Toolkit with latest pre-release version: https://github.com/OfficeDev/TeamsFx/releases )

I'm trying this, but am unable to find the `Enable GA Preview Features` setting that is mentioned. I'm using the Teams Toolkit extension version `3.7.0`.

I also noticed that [this](https://github.com/OfficeDev/TeamsFx/wiki/Enable-Preview-Features-in-Teams-Toolkit) Wiki entry references the same process for enabling the preview features, but it refers to the setting as the `Insider Preview` checkbox.

Any suggestions on what I might be doing wrong?

**Comment by formulahendry** [comment]
Please download and install the pre-release vsix from: https://github.com/OfficeDev/TeamsFx/releases/tag/vscode-extension-3.7.1-beta.08b0a4e6b.0

![image](https://user-images.githubusercontent.com/1050213/164650037-96071bf5-8f8a-4129-a7cb-5eb5602369ee.png)


> > @AndrewCraswell Maybe you could try this document: https://github.com/OfficeDev/TeamsFx/wiki/%5BDocument%5D-Connect-to-an-API-(Preview-Feature), (Note: you need use Teams Toolkit with latest pre-release version: https://github.com/OfficeDev/TeamsFx/releases )
> 
> I'm trying this, but am unable to find the `Enable GA Preview Features` setting that is mentioned. I'm using the Teams Toolkit extension version `3.7.0`.
> 
> I also noticed that [this](https://github.com/OfficeDev/TeamsFx/wiki/Enable-Preview-Features-in-Teams-Toolkit) Wiki entry references the same process for enabling the preview features, but it refers to the setting as the `Insider Preview` checkbox.
> 
> ![image](https://user-images.githubusercontent.com/1908292/164607130-20bca711-7eab-433a-b142-6bea8f0cae60.png)
> 
> Any suggestions on what I might be doing wrong?

**Comment by formulahendry** [comment]
> Thanks, this is very helpful.
> 
> One thing I'll note, as I am experimenting with the Unify Configs option. This is what I get after enabling the feature:
> 
> ![image](https://user-images.githubusercontent.com/1908292/164537651-758b5382-5f37-48cf-b903-dce1ac3d6de9.png)
> 
> The last 3 exclusions are added to the gitignore, but this is not the folder I store my projects in. I believe these should have been relative paths? The way these are added, my secret is not ignored by Git, and at danger of someone checking them in

oh, that might be a bug, Please help create a separate issue with detailed repo steps, so that our team member could follow up on this issue. Thanks!

**Comment by AndrewCraswell** [comment]
Will do. Thanks for the help, I'm considering this issue closed. :)
