### ISSUE TITLE
"TypeError: Cannot read properties of undefined" in in-meeting-app sample

### ISSUE THREAD

**Issue by Bravo555** [OfficeDev/TeamsFx#4830]
**Describe the bug**
I am following the In-meeting App sample. After following the instructions in `README.md` file of this section, specifically `Try this sample` section, I'm now trying to test the in-meeting app as described in `Use the app in Teams` section.

I can add the application to my meeting:
![image](https://user-images.githubusercontent.com/10912424/164987011-0f512dfe-ab8b-4ffc-a7bb-2c1e17dc2839.png)

However, when I open the created meeting tab, the following message appears:
![image](https://user-images.githubusercontent.com/10912424/164987056-14099db7-a8c9-418b-8bbc-ae69e33c9bf9.png)

The node application in the `bot` directory of the sample, returns a following output and exits:
```
PS C:\Users\Marcel\TeamsApps\in-meeting-app\bot> npm run start:local

> api-server@0.0.1 start:local
> cross-env NODE_ENV=development.local node ./index.js

API server is listening on port 5000
C:\Users\Marcel\TeamsApps\in-meeting-app\bot\node_modules\botbuilder\lib\botFrameworkAdapter.js:197
            const connectorClient = this.createConnectorClientInternal(reference.serviceUrl, credentials);
                                                                                 ^

TypeError: Cannot read properties of undefined (reading 'serviceUrl')
    at BotFrameworkAdapter.<anonymous> (C:\Users\Marcel\TeamsApps\in-meeting-app\bot\node_modules\botbuilder\lib\botFrameworkAdapter.js:197:82)
    at Generator.next (<anonymous>)
    at C:\Users\Marcel\TeamsApps\in-meeting-app\bot\node_modules\botbuilder\lib\botFrameworkAdapter.js:15:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Marcel\TeamsApps\in-meeting-app\bot\node_modules\botbuilder\lib\botFrameworkAdapter.js:11:12)
    at BotFrameworkAdapter.continueConversation (C:\Users\Marcel\TeamsApps\in-meeting-app\bot\node_modules\botbuilder\lib\botFrameworkAdapter.js:170:16)
    at C:\Users\Marcel\TeamsApps\in-meeting-app\bot\index.js:144:13
    at Layer.handle [as handle_request] (C:\Users\Marcel\TeamsApps\in-meeting-app\bot\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Marcel\TeamsApps\in-meeting-app\bot\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Marcel\TeamsApps\in-meeting-app\bot\node_modules\express\lib\router\route.js:112:3)
```

And the frontend tab server, returns this message, but doesn't exit:
```
Compiled successfully!

You can now view microsoft-teams-ext in the browser.

  Local:            https://localhost:3000
  On Your Network:  https://192.168.1.2:3000

Note that the development build is not optimized.
To create a production build, use npm run build.

Proxy error: Could not proxy request /getParticipantInfo?ssoToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6ImpTMVhvMU9XRGpfNTJ2YndHTmd2UU8yVnpNYyJ9.eyJhdWQiOiI3MmMzY2ZhNS0zZjlkLTRkYTctYTVhYS00MTA1ZWI2NDJiNjAiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vZThmMDNhNDAtZWY5NC00MDNlLTg2ZDYtNGM1MDRlMDI1YmUzL3YyLjAiLCJpYXQiOjE2NTA4MTY2NDcsIm5iZiI6MTY1MDgxNjY0NywiZXhwIjoxNjUwODI0MzkzLCJhaW8iOiJBVlFBcS84VEFBQUFlbUdrRElaTVdVelR2VmhZSVU5Rkp3bUZLdEl0SDlua3hUYWllTTZpTEZxZk5VZk8xSmdUajduL0pFcHhQdEJEUit4MDNsQkVPM3VVMjF2RGR6VGcwc3lKdjBoc3V3Ump5bWlDM2M4VlFZWT0iLCJhenAiOiIxZmVjOGU3OC1iY2U0LTRhYWYtYWIxYi01NDUxY2MzODcyNjQiLCJhenBhY3IiOiIwIiwibmFtZSI6Ik1hcmNlbCBHdXppayIsIm9pZCI6ImY0NjBkM2E1LTA0NzktNDEwMC05NDc2LTk0YmQ2ZWUyY2U3ZCIsInByZWZlcnJlZF91c2VybmFtZSI6IkJyYXZvNTU1QDVic3pwNC5vbm1pY3Jvc29mdC5jb20iLCJyaCI6IjAuQVU4QVFEcnc2SlR2UGtDRzFreFFUZ0piNDZYUHczS2RQNmROcGFwQkJldGtLMkJQQUlFLiIsInNjcCI6ImFjY2Vzc19hc191c2VyIiwic3ViIjoienhFU29lbl9ET0ZpcVZEQlFNTWI4aWNWdjA5Qk1XUlZhaHZqZVB2SEprTSIsInRpZCI6ImU4ZjAzYTQwLWVmOTQtNDAzZS04NmQ2LTRjNTA0ZTAyNWJlMyIsInV0aSI6Ik1MX3Vval93MlVlWWUyTW56MW1iQUEiLCJ2ZXIiOiIyLjAifQ.itTB3QypBl4Tsx-cjBcNr73ulwKxSCaS79d2_yU0uzlLuuZcZIyoISgG_eeSGG8WXAvOOTkHWoE9dndALol-VEn4RZTwz6JE54CD0YMBwwIfik97hcYIsivRvwF8WOvhu2ap8AxmreGiApS8xfvYmXkM553JRAVwytTDacEEH_XtLo4H2o0TZ-00RN_ZeONBU7COS3BdVdkEIaQZJ7lEM4XoyTVl3Q_Pk7eRuUrG64F4WGmFqOW9Ng3ycXNJE744-sjNuu9a9orhl3Wai46a4fw9dQLTrKs6UElIevPFemAB5HietsN2k3fb73uvzQyJRTwfncP_Aup8dnRmzKTQTw&conversationId=19:meeting_MDhlM2QxMDItZmVmMS00Y2ZlLTg4OTEtMzI0ZDExNzljMjVm@thread.v2&aadObjectId=f460d3a5-0479-4100-9476-94bd6ee2ce7d&meetingId=MCMxOTptZWV0aW5nX01EaGxNMlF4TURJdFptVm1NUzAwWTJabExUZzRPVEV0TXpJMFpERXhOemxqTWpWbUB0aHJlYWQudjIjMA== from 7fae-188-122-20-104.eu.ngrok.io to http://localhost:5000/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
```

I tried restarting both servers, but the issue remains.

I encountered the issue on Node v16.14.2, but also tried on Node v14, which `README.md` says is supported. The issue happens all the same, just the behaviour is slightly different - process doesn't exit and additionally prints:

```
(node:7790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

The first time that I had tried to add the sample app to a meeting, I had an error in my configuration with ngrok (specifically, I had erroneously configured it to proxy only HTTP traffic and it returned error when the HTTPS request of the Teams app came in), which resulted in the SSO authentication process failing. I suspect that the failed state of authentication maybe got saved somewhere and are the cause of subsequent failures.

However, I think the error reporting in this case needs to be improved, as the stacktrace doesn't seem to contain any relevant information as to why the request failed.

**To Reproduce**
1. Create a bot how described in `in-meeting-tab` sample
2. Add the bot to a planned or in-progress meeting.
3. The message appears
4. The `bot` node app prints stacktrace and crashes (on Node 14 it doesn't crash).

**Expected behavior**
The app should gracefully handle the error and print relevant information about why the request failed, exiting only if necessary.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Version: 3.7.0

**CLI Information (please complete the following information):**
 - OS: Windows 10 Pro 21H2
 - Version: node v16.14.2

**Comment by JerryYangKai** [comment]
@Bravo555  Hi! This in-meeting app is archived in the lastest version. If you want to try an Hello world in-meeting app in Teams, please upgrade the Teams Toolkit to the lastest version. The sample is named My First Meeting app in the sample gallary.

As for this sample, thanks for reporting the issue. We will fixed it and it will release in the furture.

**Comment by Bravo555** [comment]
Thank you for the response, I was able to run the updated demo very quickly. Less code and configuration is a welcome change as well. My original problem is resolved, so the issue can be closed, but I have some feedback regarding the README of the updated sample:
- ngrok is no longer necessary, but it's still mentioned in the README to add the ngrok URL to the manifest, I was a little bit confused about that
- there are some minor grammar errors in the README
