### ISSUE TITLE
Error after upgrading to TeamsToolkit 3.8.0

### ISSUE THREAD

**Issue by ichivers** [OfficeDev/TeamsFx#4857]
**Describe the bug**
After upgrading to 3.8.0 I can no longer debug existing app:
[Error] - code:Solution.LocalBotEndpointNotConfigured, message: Local bot endpoint is not configured. Set "fx-resource-local-debug.localBotEndpoint" in ".fx/default.user.data" and try again.

**To Reproduce**
Create a new Teams App using the Teams Toolkit with tab & bot, select Typescript for language, enter an application name.  Attempt to debug the new app, fails with [Error] - code:Solution.LocalBotEndpointNotConfigured, message: Local bot endpoint is not configured. Set "fx-resource-local-debug.localBotEndpoint" in ".fx/default.user.data" and try again.

**Expected behavior**
Should be able to debug just as before the upgrade to 3.8.0

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: MacOS 12.3.1
 - TeamsToolkit 3.8.0
 - Visual Studio Code 1.66 (March 2022)

**CLI Information (please complete the following information):**
 - OS: MacOS 12.3.1
 - TeamsFX 0.14.0

**Additional context**
I don't have a .fx/default.user.data file, tried creating one but still same error

**Comment by xiaolang124** [comment]
@ichivers Thanks for reporting this issue. Can you look at your Vs Code settings->Extensions->Teams Toolkit->Prerequisite Check->Ensure Ngrok is installed and started? If this is not selected, select this, and reload VsCode and try to do local debug again.
![image](https://user-images.githubusercontent.com/13211513/165330157-9b44bca6-7ef8-4bd6-bff5-40f163da1e29.png)

If you want to use your own bot endpoint to do local debug, you can follow this doc.
https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/debug-local#customize-debug-settings

**Comment by ichivers** [comment]
@xiaolang124 I didn't have that checked as I run ngrok manully.  When I do check it and try to debug I get a message saying "Failed to install ngrok@4.2.2. Install ngrok@4.2.2 manually." with options to "Cancel" or "Learn more", clicking Cancel stops the debug.  I installed ngrok as a homebrew cask, ngrok version 2.3.40.  This is why I had the option disabled, I couldn't figure out why Teams Toolkit couldn't find ngrok.  Here's a copy of the output:

Info 2022-04-27T08:01:46.839Z: Downloading and installing ngrok@4.2.2.
Debug 2022-04-27T08:01:46.840Z: Running command: "npm install ngrok@4.2.2 --prefix /Users/ianchivers/.fx/bin/ngrok --no-audit", options = '{"cwd":"/var/folders/tn/ks3l5_xx5679kmmnwfw4dtw00000gp/T","shell":false,"timeout":300000}'
Debug 2022-04-27T08:01:49.653Z: Command finished with outputs, cmdOutputIncludingStderr: 'npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 53 packages in 3s

7 packages are looking for funding
  run `npm fund` for details
'
Debug 2022-04-27T08:01:49.653Z: Finished running command: "npm install ngrok@4.2.2 --prefix /Users/ianchivers/.fx/bin/ngrok --no-audit".
Debug 2022-04-27T08:01:49.655Z: Running command: "ngrok version", options = '{"cwd":"/var/folders/tn/ks3l5_xx5679kmmnwfw4dtw00000gp/T","shell":true,"env":{"PATH":"/Users/ianchivers/.fx/bin/ngrok/node_modules/ngrok/bin"}}'
Debug 2022-04-27T08:01:49.660Z: Command finished with outputs, cmdOutputIncludingStderr: ''
Debug 2022-04-27T08:01:49.660Z: Failed to run command: "ngrok version", code: "null",
                            output: "", error: ""
[2022-04-27T08:01:49.716Z] [Error] - Failed to install 'ngrok', error = 'Error: Failed to install ngrok@4.2.2. Install ngrok@4.2.2 manually.'
[2022-04-27T08:01:49.723Z] [Error] - Failed to install ngrok@4.2.2. Install ngrok@4.2.2 manually., error = Error: Failed to install ngrok@4.2.2. Install ngrok@4.2.2 manually.

**Comment by xiaolang124** [comment]
Sorry for you inconvenience. We will check ngrok install problem. There is a work around way to use your own ngrok. Unselect `Ensure Ngrok is installed and started` and reload VsCode.
Use `ngrok http 3978` to create a tunnel for your local bot. And copy this https URL.
![image](https://user-images.githubusercontent.com/13211513/165480544-aa82f2d5-da2d-41d2-94e5-f2b2c0c4a0ee.png)

Put this URL in your ` .fx/configs/config.local.json` bot->siteEndpoint
![image](https://user-images.githubusercontent.com/13211513/165480773-0a3b6128-a852-4b4e-b027-ad4269096683.png)

Then try to do local debug. Please let me know if you have any questions.

**Comment by ichivers** [comment]
Thank you @xiaolang124, updating the config.local.json with the siteEndpoint works!
