### ISSUE TITLE
TeamsFx token generation is failing in Android

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/TeamsFx#4859]
TeamsFx [sample app](https://github.com/OfficeDev/TeamsFx-Samples/tree/ga/hello-world-tab) is deployed. Tab app is loading fine. If we click on "Authorize" button, consent popup opens and popup will close after consent. And then profile details are showing in tab. It is working fine Desktop Teams/ Web teams/ iOS as well.
But it is failing in Android mobile. Once popup closed, following error message is showing:
Unhandled Rejection(ErrorWithCode. InvalidResponse): Failed to parse response to Json

Issue is consistently reproducible in other apps as well. 

**To Reproduce**
1. Deploy following app: https://github.com/OfficeDev/TeamsFx-Samples/tree/ga/hello-world-tab
2. Once app installed for user, open app in android teams
3. Click on "Authrorize" and provide consent in popup
4. You will see error after popup closes.

**Expected behavior**
User profile details like name, profile pic should be shown in tab

**Screenshots**
[Attached recording](https://msteamspoc-my.sharepoint.com/:f:/g/personal/johndoe_msteamspoc_onmicrosoft_com/Ekg1ae69jwREkrCLFi9O3KUBklXNIt8WMLRNPddYDEIDLw?e=ZNirNd)

**Additional context**
[Attached recording](https://msteamspoc-my.sharepoint.com/:f:/g/personal/johndoe_msteamspoc_onmicrosoft_com/Ekg1ae69jwREkrCLFi9O3KUBklXNIt8WMLRNPddYDEIDLw?e=ZNirNd)

**Comment by formulahendry** [comment]
Fix is merged in `ga` branch: https://github.com/OfficeDev/TeamsFx/pull/4910
Will close this issue once there is an available SDK in https://www.npmjs.com/package/@microsoft/teamsfx

**Comment by formulahendry** [comment]
Hi @SubbaReddi , this issue has been fixed. And this fix is available in the beta version of the `@microsoft/teamsfx` SDK: https://www.npmjs.com/package/@microsoft/teamsfx/v/0.7.1-beta.c23501411.0

You could try this beta version in you Teams app.
