### ISSUE TITLE
Teams Toolkit does not respect option to skip npm install

### ISSUE THREAD

**Issue by AndrewCraswell** [OfficeDev/TeamsFx#4877]
**Describe the bug**
When hitting `F5`, Teams Toolkit will automatically execute `npm install`. Our project uses Yarn, so we disabled the "Automatic Npm Install" setting in the VS Code settings page. However, if no `tabs\node_modules` folder exists, this option is no longer being respected and anytime we attempt to run the app it will force npm install.

Beyond this issue, it shouldn't be assumed that everyone is using Npm for package management. At Microsoft it's common to use `Yarn`, `pnpm`, or even `midgard-yarn-strict`. Therefore, the assumption that Npm is compatible with a project is not true for many apps. Any scenario where Npm is forced to run represents a breaking issue.

**Expected behavior**
Toggling off the "Automatic Npm Install" checkbox should not cause `npm install` script to execute after hitting `F5` to debug the app. Even in the scenario that the dependencies were never installed.

**Reproduction steps**

1. Create a new Teams Toolkit project
2. Open the project in VS Code
3. Disable the `automaticNpmInstall` setting
4. Use `F5` to execute the app. Note that the npm packages are still installed
5. After the dependencies are installed, close VS Code and reopen the projec
6. Use `F5` to execute the app. Notice now that dependencies are detect, and no installation occurs
7. Close VS Code. Rename the `<root>\tabs\node_modules` folder to `backup_modules`
8. Launch VS Code again and use `F5` to run the app. Note that the npm package installation is executed again

**Screenshots**
![image](https://user-images.githubusercontent.com/1908292/165652197-d53afaaa-3cb2-4271-8eed-bf02d4ee06cb.png)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11
 - Version 3.8.0

**Comment by aruray-ms** [comment]
Hi @AndrewCraswell, the solution to this is to use the latest version of the teamsfx-cli 0.14.0 and above. that gives you the option to have custom install commands. `install:teamsfx`

using npm 
```json
"scripts": {
    "dev:teamsfx": "env-cmd --silent -f .env.teamsfx.local npm run start",
    "start": "react-scripts start",
    "install:teamsfx": "npm install --legacy-peer-deps",
    "build": "react-scripts build",
    "eject": "react-scripts eject",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```
using yarn
```json
"scripts": {
    ...
    "install:teamsfx": "yarn",
   ...
  }

**Comment by AndrewCraswell** [comment]
Ah, that's pretty cool. I generated a fresh project with Teams Toolkit just now and I can see the new `install:teamsfx` script in the `package.json`. I verified I've got `teamsfx-cli` `0.14.0` and the extension version `3.8.0`. But even still, when I hit `F5` to debug, npm is executed instead.

![image](https://user-images.githubusercontent.com/1908292/165695703-1d28b526-f6c0-4492-906f-c2b94c475ad5.png)

I thought maybe the console output was misleading, and really it was executing my `yarn install`. But unfortunately I see a `package-lock.json` file generated instead of a `yarn.lock` file.

**Comment by kuojianlu** [comment]
Hi @AndrewCraswell, the `Automatic Npm Install` setting means automatically execute npm install command for a new created project. That is to say, if you turn on this setting, after creating a new project, Teams Toolkit will automatically execute npm install command to install the dependencies. This setting does not affect the behavior of F5. Sorry for the confusion.

During F5, Teams Toolkit will detect whether the dependencies are installed. If not Teams Toolkit will execute npm install command to install the dependencies. If the dependencies are already installed, Teams Toolkit will skip executing npm install command. Currently, Teams Toolkit does not respect the `install:teamsfx` script during F5, but just hard codes the install command as `npm install --no-audit`.

Thank you for reporting this issue! We may consider to fix it.

**Comment by AndrewCraswell** [comment]
Thanks for the explanation. In this scenario, I have unchecked the box, yet the install is still occuring :/

**Comment by kuojianlu** [comment]
> Thanks for the explanation. In this scenario, I have unchecked the box, yet the install is still occuring :/
> 
> It appears the checkbox does not have any effect

The `Automatic Npm Install` setting **only affects the behavior of creating a new project**. If you uncheck this setting, Teams Toolkit will not execute npm install command automatically after you create a new project. But if you check this setting, Teams Toolkit will execute npm install command automatically after you create a new project. **This setting have no effect on the behavior of F5**.

**Comment by AndrewCraswell** [comment]
Ah, thanks for the clarification. This fits my experience. Unfortunately this does create an awkward scenario that every dev on our team has encountered so far. After launching the project and attempting to run it, they get an `npm install` executed when our app uses Yarn. I've had to jump on calls and help explain to everyone that they need to delete the `node_modules` and make sure to run `yarn install` before attempting to use Teams Toolkit with the project.

At the very least, I think the wording should be rewritten in the settings because it's a bit misleading.

**Comment by AndrewCraswell** [comment]
As for the other issue of hardcoding of the `npm install --no-audit`, are there plans to respect the `install:teamsfx` script, or something similar?

**Comment by kuojianlu** [comment]
@AndrewCraswell Sorry for the convenience. Yes, we are considering to respect `install:teamsfx` script rather than the hard-coded npm install command. Thanks for your feedback!

**Comment by kuojianlu** [comment]
This issue is solved in latest version of Teams Toolkit.
