### ISSUE TITLE
new bug report: Task 'spfx npm install' failed

### ISSUE THREAD

**Issue by Sekhno** [OfficeDev/TeamsFx#4895]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**Additional context**

**Error detail**
{
    "logFile": "/Users/dmitrysekhno/.npm/_logs/2022-04-28T13_03_26_506Z-debug.log",
    "timestamp": "2022-04-28T13:03:26.506Z",
    "nodeVersion": "v14.19.1",
    "npmVersion": "v6.14.16",
    "cwd": "/Users/dmitrysekhno/TeamsApps/todo-list-SPFx/SPFx",
    "exitCode": 1,
    "errorMessage": [
        "2375 error code ELIFECYCLE",
        "2376 error errno 1",
        "2377 error node-sass@4.14.1 postinstall: `node scripts/build.js`",
        "2377 error Exit status 1",
        "2378 error Failed at the node-sass@4.14.1 postinstall script.",
        "2378 error This is probably not a problem with npm. There is likely additional logging output above."
    ]
}

**Comment by HuihuiWu-Microsoft** [comment]
Hi @Sekhno , did you run the 'spfx npm install' task from a fresh start? If you already have node_modules installed, please try to remove node_modules folder and try again.
