### ISSUE TITLE
bug report: SPFx.DependencyInstallFailed

### ISSUE THREAD

**Issue by Ashailu** [OfficeDev/TeamsFx#4906]
Failed to install package sharepoint generator. Learn how to remediate in the [output](command:fx-extension.showOutputChannel).

stack:
DependencyInstallFailed: Failed to install package sharepoint generator. Learn how to remediate in the [output](command:fx-extension.showOutputChannel).
	at Object.DependencyInstallError (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:6484490)
	at SPFxPluginImpl.postScaffold (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:6489807)
	at processTicksAndRejections (node:<REDACTED: user-file-path>:96:5)
	at async SpfxPlugin.runWithErrorHandling (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:6486893)
	at async SpfxPlugin.postScaffold (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:6486121)
	at async Object.scaffoldSourceCodeAdapter (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:6601503)
	at async SpfxPluginV2.scaffoldSourceCode (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:6518030)
	at async TeamsAppSolutionV2.scaffoldSourceCode (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:6980879)
	at async FxCore.createProjectV2 (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:5077669)
	at async FxCore.<anonymous> (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:5214610)
	at async FxCore.exports.ProjectSettingsWriterMW (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:5269585)
	at async FxCore.exports.ContextInjectorMW (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:5202937)
	at async FxCore.exports.QuestionModelMW (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:5275797)
	at async FxCore.exports.ErrorHandlerMW (<REDACTED: user-file-path> <REDACTED: user-file-path>:2:5217928)

**Comment by HuihuiWu-Microsoft** [comment]
Hi @Ashailu , can you help attach the error logs in output window?

**Comment by Ashailu** [comment]
[SPFx.DependencyInstallFailed]: Failed to install package sharepoint generator. Learn how to remediate in the [output](command:fx-extension.showOutputChannel).

[Error] - Failed to execute npm install @***@***.***

________________________________

**Comment by HuihuiWu-Microsoft** [comment]
Hi @Ashailu , there should be detailed logs about the error in this pattern: Failed to install  sharepoint generator, error = '${error}'. Could you help check and paste  that?

Package installation fail could be due to multiple reasons. You can check your npm(should be v6.x) and Node.js version( should be v12.x or v14.x). If lyou're using the right version, you could go to HOME\.fx\bin\spfx\node_modules\@microsoft and delete the @microsoft folder and try again.

**Comment by Ashailu** [comment]
Hi,

Yes, my npm is v8.x and node is v17.x and that could be the reason.

Thanks for the follow up.
________________________________

**Comment by HuihuiWu-Microsoft** [comment]
> Hi, Yes, my npm is v8.x and node is v17.x and that could be the reason. Thanks for the follow up.
> […](#)
> ________________________________ From: HuihuiWu-Microsoft ***@***.***> Sent: Friday, May 6, 2022 8:26 PM To: OfficeDev/TeamsFx ***@***.***> Cc: Ashailu ***@***.***>; Mention ***@***.***> Subject: Re: [OfficeDev/TeamsFx] bug report: SPFx.DependencyInstallFailed (Issue #4906) Hi @Ashailu<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAshailu&data=05%7C01%7C%7C33ad8df092a74fb2a0e908da2fc898ab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637874835837992508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YlAKYb0lLZtp%2BBiTl1k%2Fo0LdCz4dsNQCvQrBM22SMXc%3D&reserved=0> , there should be detailed logs about the error in this pattern: Failed to install sharepoint generator, error = '${error}'. Could you help check and paste that? Package installation fail could be due to multiple reasons. You can check your npm(should be v6.x) and Node.js version( should be v12.x or v14.x). If lyou're using the right version, you could go to ***@***.*** and delete the @microsoft<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft&data=05%7C01%7C%7C33ad8df092a74fb2a0e908da2fc898ab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637874835837992508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IISJp0pw7a4g0E1eBCnyaa3nKIKWwMhdX%2FtC7e0jKo0%3D&reserved=0> folder and try again. — Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2FTeamsFx%2Fissues%2F4906%23issuecomment-1120102621&data=05%7C01%7C%7C33ad8df092a74fb2a0e908da2fc898ab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637874835837992508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=MXAa5A%2FeFRU3bh%2BrAbot0qQV6JNFPc9KMAPTNcenGzg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO27GYEQCWXBLUNUEAM3TO3VIXBD5ANCNFSM5UXUFPOA&data=05%7C01%7C%7C33ad8df092a74fb2a0e908da2fc898ab%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637874835837992508%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0kDxKH97RsZNzBuVJNunxUd6QmdbAIei%2B30ES9NDBXg%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.***>

Hi @Ashailu , you can install supported version for SPFx(https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-nodejs) and try again. I'll close this issue if you don't have other problems.
