### ISSUE TITLE
Can not aquire token via teamsfx.getCredential().getToken();

### ISSUE THREAD

**Issue by hsteweri** [OfficeDev/TeamsFx#4907]
**Describe the bug**
I am trying to run the sample "[graph-connector-app](https://github.com/OfficeDev/TeamsFx-Samples/tree/ga/graph-connector-app)", but this also happens without using a sample.

When I hit F5 and the app opens it is trying to execute the following code in tabs\src\components\sample\lib\useLogin.ts :
`await teamsfx.getCredential().getToken(scopes);`
This outputs the following console messages but then hangs with an never ending loading-circle and the function never finishes. The tab never displays anything.
`[Tue, 03 May 2022 12:44:02 GMT] : @microsoft/teamsfx : Info - Create teams user credential
tabs/src/components/sample/lib/useTeamsFx.ts:14`
`[Tue, 03 May 2022 12:44:02 GMT] : @microsoft/teamsfx : Verbose - Validate authentication configuration
tabs/src/components/sample/lib/useTeamsFx.ts:14`
`[Tue, 03 May 2022 12:44:02 GMT] : @microsoft/teamsfx : Info - Create teams user credential
tabs/src/components/sample/lib/useTeamsFx.ts:14`
`[Tue, 03 May 2022 12:44:02 GMT] : @microsoft/teamsfx : Verbose - Validate authentication configuration
tabs/src/components/sample/lib/useTeamsFx.ts:14`
`[Tue, 03 May 2022 12:44:02 GMT] : @microsoft/teamsfx : Info - Get basic user info from SSO token`

**To Reproduce**
1. Clone sample "[graph-connector-app](https://github.com/OfficeDev/TeamsFx-Samples/tree/ga/graph-connector-app)"
2. Set breakpoints in tabs\src\components\sample\lib\useLogin.ts , lines 8,9
3. Hit F5 and let it install/provision/add the app.
4. Watch it hit breakpoint on `await teamsfx.getCredential().getToken(scopes);` but after that running into an endless loop/hang.

**Expected behavior**
Should get a token or an error message at that point.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11
 - Teams Tookit v3.8.0

**Comment by hsteweri** [comment]
Kind of found it myself. If I remove the breakpoint on line 8 (`await teamsfx.getCredential().getToken(scopes);`) the code runs without problems to line 9 and token is aquired. Never seen that before. Anyone can shed some light on why the breakpoint is causing this behaviour?

**Comment by tecton** [comment]
Hi @hsteweri, I think it's related to the Teams JS SDK API `authentication.getAuthToken()` ([link](https://docs.microsoft.com/en-us/javascript/api/@microsoft/teams-js/microsoftteams.authentication?view=msteams-client-js-latest#@microsoft-teams-js-microsoftteams-authentication-getauthtoken)) that returns authentication token. It hangs when breakpoint is enabled.

**Comment by haidv1992** [comment]
You nead config add authentication 
Like this it worked
![image](https://github.com/OfficeDev/TeamsFx/assets/86423592/a7ab8283-5256-41d2-81da-b7a8203da114)
