### ISSUE TITLE
Deploy to the cloud - FE.NoStorageError : undefined

### ISSUE THREAD

**Issue by Jose-BFreitas** [OfficeDev/TeamsFx#4921]
When clicking on Deploy to the cloud, it starts, it fails and I get the following error:
code:FE.NoStorageError, message: undefined Suggestions: Run 'Provision Resource' again.

Before getting the error, de messages I get that indicate the fail problem are the following:
[Info] - [Teams Toolkit] Deployment start.
[Info] - Running fx-resource-frontend-hosting concurrently
[Info] - [fx-resource-frontend-hosting] Pre-deploying 'Tab Frontend'.
[Info] - [Teams Toolkit] Execute Task summary----------------------------
[Info] - fx-resource-frontend-hosting-deploy......................... [failed]
[Info] - [Teams Toolkit] Task overall result.........................[failed]
[Info] - fail to deploy 'app' to the cloud!
[Info] - [core] finish task:deployArtifactsV2 , time: 1676 ms

Also a doubt, Provision Resource a app that is already deployed will mess with something? Or will everything keep normal?

**Comment by hund030** [comment]
Re-provision an app will not mess anything. You can safely do it.
For NoStorageError, it means Teams Toolkit failed to find your Azure Storage Account to deploy. You could check if you login with correct Azure account.
Or you cloud find your Azure Storage Account id in .fx/states/state.{env name}.json and confirm it exists.
```
{
    "fx-resource-frontend-hosting": {
        "storageResourceId": "/subscriptions/xxxx/resourceGroups/xxxx-dev-rg/providers/Microsoft.Storage/storageAccounts/xxxx"
    }
}
```

**Comment by nellyk** [comment]
I'm getting the same issue using the teams vscode extension when i try to deploy.( i used vscode to provision the environment) The storage account exists in azure.
I'll try to manually deploy it

**Comment by eriolchan** [comment]
@nellyk did you succeed in manually deployment?

**Comment by nellyk** [comment]
@eriolchan i re tried after a couple of days and it worked. Might it be an issue worth investigating though, I'm happy to retry the steps to see if i can replicate it
