### ISSUE TITLE
teamsfx manifest update => API.EmptyOptionError

### ISSUE THREAD

**Issue by dluc** [OfficeDev/TeamsFx#4971]
**Describe the bug**
1. `git clone git@github.com:pnp/teams-dev-samples.git`
2. `cd teams-dev-samples/samples/tab-move-your-filters/`
3. `teamsfx manifest update`
4. Command fails without clear action

![image](https://user-images.githubusercontent.com/371009/167706513-99cfe3fa-75e2-46ca-9422-4f96da607bbf.png)

**CLI Information:**
 - OS: macOS 12.3.1
 - Node.js: v14.19.2
 - Bash: 5.1.16(1)-release (x86_64-apple-darwin21.1.0)

**Comment by xiaolang124** [comment]
Thanks for sharing this question with us.
Are you trying to update samples to support teams-toolkit? For this problem, the project is missing an environment file. You can add a `dev` environment like this one.
https://github.com/OfficeDev/TeamsFx-Samples/blob/ga/hello-world-tab/.fx/configs/config.dev.json

**Comment by dluc** [comment]
hi @xiaolang124, with many sample online I've noticed VS Code doing a manifest upgrade, so I started running the `teamsfx upgrade` command manually when I clone repos, just to be sure they are up to date. 

Looks like the command fails for this repo (which I do not own). 
VS Code is able to upgrade the project without errors instead:

![image](https://user-images.githubusercontent.com/371009/167911707-8a18e623-75a6-456f-b78e-9b3abcf78696.png)
![image](https://user-images.githubusercontent.com/371009/167911748-7b6b904d-80b4-4617-b888-ff084cfeba26.png)

Is VS Code doing something different?

**Comment by xiaolang124** [comment]
`teamsfx manifest update` means synchronize manifest changes to Teams. This requires at least one already provisioned environment.
When VsCode opens the project, the `upgrade` button only triggers upgrade logic. But in CLI, `teamsfx manifest update` command will trigger upgrade and update remote Teams manifest. The upgrade project was successful, but the update remote Teams manifest failed.

**Comment by dluc** [comment]
When I clone the repo and launch VS Code for the first there is no provisioned environment, and I immediately get this prompt:

![image](https://user-images.githubusercontent.com/371009/168130261-5ae8618f-6106-4cb4-bb38-fbf50adfc01d.png)

Is it possible to do this project upgrade from command line?

**Comment by xiaolang124** [comment]
For now, we do not have a single upgrade command in CLI, we can only upgrade projects during normal `Teamsfx command`.
