### ISSUE TITLE
Proactive message issue in bot adaptive card on Action.Submit button click

### ISSUE THREAD

**Issue by RamPrasathBGSW** [OfficeDev/TeamsFx#5082]
Proactive message issue in bot adaptive card on Action.Submit button click

We are posting adaptive card to teams channel from bot through graph api. We need to send proactive message back to bot when user clicks on Submit button in the adaptive card posted in the teams channel. 
 
Submit button syntax in adaptive card :
 
{
      "type": "Action.Submit",
      "title": "Click me for messageBack",
      "data": {
        "msteams": {
            "type": "messageBack",
            "displayText": "Maintenance Request",
            "text": "Maintenance Request",
            "value": "{\"bfKey\": \"bfVal\", \"conflictKey\": \"from value\"}"
        }
      }
    }

But the submit button is not getting invoked when user clicks and we are getting below error.

[AdaptiveCardScreenshot.zip](https://github.com/OfficeDev/TeamsFx/files/8715466/AdaptiveCardScreenshot.zip)

**Comment by dooriya** [comment]
@RamPrasathBGSW Thanks for reporting this! 
Looks like this issue is more related to Teams platform not the toolkit, and I see there is a similar issue opened in https://github.com/MicrosoftDocs/msteams-docs/issues/780, is that solution can solve your problem?
