### ISSUE TITLE
Prerequisite check stalling after adding notification only bot

### ISSUE THREAD

**Issue by mattgillam** [OfficeDev/TeamsFx#5218]
**Describe the bug**
After adding a notification bot using "Add Features" and attempting a local debug run, the prerequisite check hangs on "Checking and installing NPM packages for tab app (react-based) ...". I waited more than 10 minutes, several times.

The app is an existing and functioning app using React based personal tabs.

When I revert to the master branch which does not have the notification bot changes present, the app loads and runs as expected and all prerequisite checks succeed.

**Expected behavior**
Prerequisite check should pass.

**Screenshots**
Start up stalls here, I gave up after 20 minutes.

![image](https://user-images.githubusercontent.com/379568/171401391-09d66c06-ea16-4433-ac16-a8be19001ffe.png)

**VS Code Extension Information (please complete the following information):**
 - OS: macOS
 - Version TeamsToolkit 4.0.0

**CLI Information (please complete the following information):**

Not using CLI, running in VS Code Mac 1.67.2

**Comment by kuojianlu** [comment]
@mattgillam Could you please open "Terminal" to see the installing process? I guess it hangs because installing NPM packages is still running.

**Comment by mattgillam** [comment]
Thank you @kuojianlu - I think everything needed was installed and didn't notice any warnings in Terminal. However I since moved on to using a different method to add the bot than Teams Toolkit, so I'm closing this.

Thanks.
