### ISSUE TITLE
Add documentation for `activeResourcePlugins`

### ISSUE THREAD

**Issue by AndrewCraswell** [OfficeDev/TeamsFx#5220]
**Is your feature request related to a problem? Please describe.**

Our app which uses Teams Toolkit and Teamsfx is using a very limited set of features from the Toolkit. Primarily, we just want to be able to debug the app within the Teams for Web, and the Toolkit makes that easy. However, we have our own First Party AAD, manage our own CI/CD, and deploy to our own CDN.

What we'd like to know, is which aspects of Teams Toolkit we can disable. I suspect we can modify the `projectSettings.json` file and remove some of the `activeResourcePlugins`, but I haven't been able to locate any documentation on what each of these do, and what removing them might affect.

![image](https://user-images.githubusercontent.com/1908292/171505357-87027991-8347-4c47-b08d-df8441af133b.png)

**Describe the solution you'd like**

I think some documentation on managing the resource plugins would be helpful. And a description of several common scenarios for teams who might already manage their own resources, and want to "opt-in" to Toolkit features selectively. This would be a big help for those of us with established apps trying to get on board with the Toolkit.

**Describe alternatives you've considered**

At the moment, we are hardcoding our values in the `manifest.template.json` such as the AAD ClientId, and `webApplicationInfo`. In the `.fx/configs/config.{env}.json` files we are putting our existing `teamsAppId`, and the hosted CDN `domain`. This works, and we just ignore all the `.fx/states/*` state and userdata files that are generated. We also ignore the `aad.template.json` file which recently started being generated.

Ideally, these files wouldn't be generated at all though.

**Comment by MuyangAmigo** [comment]
Closing as outdated. Starting with Teams Toolkit v5, we don't have removed `projectSettings.json` file along with `activeResourcePlugins`.
