### ISSUE TITLE
Invalid meeting id

### ISSUE THREAD

**Issue by Githamza** [OfficeDev/TeamsFx#5243]
I would like to retrieve meeting infos using the react TeamsFx library

this is how I do :

```

const meetingInfos = (graph: Client)=> {
    return new Promise((resolve,reject)=>{
        microsoftTeams.getContext( async context=>{
            console.log("contexxt",context);
            let meeting;
            const meetingId= atob(context.meetingId || '') 
            try {
            meeting = await graph.api(`/me/onlineMeetings/${context.chatId}`).get();
                console.log("meeeting",meeting);
                resolve(meeting);
            } catch (error) {
                console.error("reject error",error);
                reject(error);
            }
            console.log(meeting);

        })
    })
}
```

I tried also to convert context.meetingIdto b64 but I get same error ( I figured out that chatId encoded to b64 = meetingId )

Actually I'm getting this error:

**"Invalid meeting id 19:meeting_MzU0MzFhYTQtNjlmOS00NGI4LTg1MTYtMGI3ZTkwOWYwMzk4@thread.v2."**

How to get the correct meeting id ?

**Comment by JerryYangKai** [comment]
Hi @Githamza ,  I have checked the graph API and could you please follow this way to get the infos.
`GET /me/onlineMeetings/{meetingId}` 
I found you make this request using the chatId, I am not sure if it will works.

**Comment by Githamza** [comment]
I also used meetingId , I get  `"Meeting Id is corrupted."`

MeetingId is b64 encoded : "MCMxOTptZWV0aW5nX016VTBNekZoWVRRdE5qbG1PUzAwTkdJNExUZzFNVFl0TUdJM1pUa3dPV1l3TXprNEB0aHJlYWQudjIjMA=="

So I decoded it using `atob()`

I get : `"0#19:meeting_MzU0MzFhYTQtNjlmOS00NGI4LTg1MTYtMGI3ZTkwOWYwMzk4@thread.v2#0"` ( equal to #0#${chatId}#0 )

I tried this value I get same error.

**Comment by JerryYangKai** [comment]
@Githamza  
I think in this page it may help you about this 
https://github.com/microsoftgraph/microsoft-graph-docs/issues/11696
