### ISSUE TITLE
First run failed for a new project setup via Teams Toolkit extension

### ISSUE THREAD

**Issue by shubham-betterworks** [OfficeDev/TeamsFx#5261]
**Describe the bug**
Hi, I followed the [Get Started for messaging extension](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?tabs=vscode%2Cvsc%2Cvcode%2Cviscode) to create a new teams app but failed to run it locally

**To Reproduce**
Follow the steps as stated in the [document](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?tabs=vscode%2Cvsc%2Cvcode%2Cviscode)

**Expected behavior**
All dependencies are installed and the user is asked to add the app to their Microsoft Teams account.

**Actual behavior**
Prerequisite checks can't find node which is already installed on the system via nvm.

**Screenshots**
<img width="1458" alt="Screenshot 2022-06-09 at 2 58 52 PM" src="https://user-images.githubusercontent.com/80667102/172814799-2841a26d-3654-46f7-9f5f-3619959b06a9.png">

**VS Code Extension Information (please complete the following information):**
 - OS: MacOS
 - Version: 4.0.0

**CLI Information (please complete the following information):**
 - OS: MacOS
 - Version: 1.0.0

**Additional context**
I tried running the same app using CLI `teamsfx preview --local` and it is working as expected but not with `F5` from VSCode.

**Comment by meifans** [comment]
Hi @shubham-betterworks , can you restart all the Visual Studio Code instances and try to debug again?
So VSCode can read the **latest PATH** on your MacOS.

Let me know if you have any questions :)

**Comment by shubham-betterworks** [comment]
Hi @meifans 

It worked. Thanks for helping out.
