### ISSUE TITLE
Debugging local teams app not possible

### ISSUE THREAD

**Issue by CIPSoftware** [OfficeDev/TeamsFx#5277]
**Describe the bug**
We are developing a teams Tab app with Visual Studio Preview 2022 and Teams Toolkit. This worked perfectly until last week. After running into the issue with the development of our app, I created a new app just to make sure we have a clean start. 
The issue is that it is not possible anymore to debug / run a local app within teams. The response is : the app cannot be found or you do not have access to it. This happens with our app but also with a clean template generated with Visual Studio from the toolkit.

Possible cause 
I have noticed a http 500 error from https://teams.microsoft.com/api/appstudio/appdefinitions/{appid}/manifest?tenantId={tenantid}

When starting the session within teams the given api call is done to retrieve the manifest. As this request fails I am assuming this will result in the given message within teams; the application (manifest) cannot be found. The Developer Portal within teams shows the app so the app is registered within App Studio environment. I chacked the app ID and this corresponds to the id within the code.

**To Reproduce**
1. Go to 'Visual Studio 2022 Preview'
2. Click on 'Create a new Project'
3. Select 'Microsoft Teams App'
4. Project -> Teams Toolkit -> Configure Micrososft Teams App (runs without issues)
5. Start the project from Visual Studio

**Expected behavior**
I would axpect to get the steps to install the app and add a tab to teams.

**Screenshots**
Response from teams web after running the app
![afbeelding](https://user-images.githubusercontent.com/4321350/173300894-1f1045f2-bdd8-44e8-823c-d051a994caf0.png)

Error 500 from Developer Tools 
![afbeelding](https://user-images.githubusercontent.com/4321350/173301978-520c70e2-7f6b-4ca6-8b5d-6c934f81e3c2.png)

Registration of the app within Developer Portal 
![afbeelding](https://user-images.githubusercontent.com/4321350/173303787-f1ed3a3c-fb4c-4edd-8eb5-48880d3e926d.png)

Log from Teams Toolkit after running : Configure Microsoft Teams App:
[core] start task:localDebugV2 , API v3: false
[core] success to acquire lock for task localDebugV2  on: D:\projecten\cip\MyTeamsApp2\MyTeamsApp2\.fx
[core] success to get questions for localDebugV2
Running fx-resource-frontend-hosting concurrently
Running fx-resource-aad-app-for-teams concurrently
[AAD App Registration] Start to local debug
Running fx-resource-local-debug concurrently
[AAD App Registration] Successfully parsed permissions.
[AAD App Registration] Successfully updated permission for Azure AD app.
[AAD App Registration] Successfully local debug
[Teams Toolkit] Execute Task summary----------------------------
fx-resource-frontend-hosting-provisionLocalResource......... [ok]
fx-resource-aad-app-for-teams-provisionLocalResource........ [ok]
fx-resource-local-debug-provisionLocalResource.............. [ok]
[Teams Toolkit] Task overall result.........................[ok]
[AAD App Registration] Successfully created application id uri for Azure AD app.
Running fx-resource-frontend-hosting concurrently
Running fx-resource-aad-app-for-teams concurrently
[AAD App Registration] Start to post local debug
Running fx-resource-local-debug concurrently
Running fx-resource-appstudio concurrently
[AAD App Registration] Successfully updated redirect uri for Azure AD app.
[AAD App Registration] Successfully updated application id uri for Azure AD app.
[AAD App Registration] Successfully post local debug
Uploading icon for teams 858d3a36-c635-409f-9138-dc52374aae56
successfully uploaded two icons
[Teams Toolkit] Execute Task summary----------------------------
fx-resource-frontend-hosting-configureLocalResource......... [ok]
fx-resource-aad-app-for-teams-configureLocalResource........ [ok]
fx-resource-local-debug-configureLocalResource.............. [ok]
fx-resource-appstudio-configureLocalResource................ [ok]
[Teams Toolkit] Task overall result.........................[ok]
[core] persist local settings config file: D:\projecten\cip\MyTeamsApp2\MyTeamsApp2/.fx/configs/localSettings.json
[core] persist project setting file: D:\projecten\cip\MyTeamsApp2\MyTeamsApp2\.fx\configs\projectSettings.json
[core] lock released on D:\projecten\cip\MyTeamsApp2\MyTeamsApp2\.fx
[core] finish task:localDebugV2 , time: 5024 ms

**VS Code Extension Information (please complete the following information):**
- Visual Studio Preview 2022
 - OS: Windows 10
 - Version: latest version teams toolkit

**Additional context**

**Comment by nliu-ms** [comment]
Thanks @CIPSoftware for reporting this bug. 

Can you please try to open this Teams app in Developer Portal, and click `Preview in Teams`, and check if you meet the same error as well? Or it works?
![image](https://user-images.githubusercontent.com/71362691/173729539-3d5115ca-d0fb-416d-b018-560e92d389ad.png)

And I'd like to know if your M365 account has been invited to another tenant as the guest user? Thanks!

**Comment by CIPSoftware** [comment]
Hi @nliu-ms,

thanks for your help. Please find below the answers to your questions.

Within the desktop version of teams, I am getting the below message after pressing Preview in Teams

![afbeelding](https://user-images.githubusercontent.com/4321350/173823059-313d7b01-9b92-4750-9592-45cc9b88e1b7.png)

Within the browser version of teams, the given app is missing in the Developer Portal - Apps but visible within the desktop version.

Web :
 
![afbeelding](https://user-images.githubusercontent.com/4321350/173823530-7352e307-f58d-434b-8292-3cb45126bedf.png)

Desktop :

![afbeelding](https://user-images.githubusercontent.com/4321350/173823814-25239f39-d8cc-4227-b9d6-4382f56b1ba4.png)

Within Developer Portal -> App Studio, the app is visible in both situations. The App ID corresponds to the App id within the local json so it is pointing to the same app.

My account is invited to another tenant as a guest user. But the active 'environment' is the one I am developing in. To be sure : you mean this option ?

![afbeelding](https://user-images.githubusercontent.com/4321350/173825770-67a16bef-deb9-422c-9953-ef798ca007c3.png)

Please let me know if you need any additional information.

**Comment by nliu-ms** [comment]
Thanks @CIPSoftware , I was thinking if your account has some special settings like invited as the guest user. But we find more tenants meeting the same error as you, so reported this issue to service team. Will let you know the updates. Sorry for the inconvenience!

**Comment by jackpoz** [comment]
Hi, we are developing a Teams personal app, last week everything worked fine but since yesterday we are experiencing the same issue as the one reported here. We are using M365 Developer tenants

**Comment by mrrobertsson** [comment]
Hello, I am experiencing the same issue as mentioned by @CIPSoftware and @jackpoz.

I have tried using different tenants without any luck.

**Comment by rnag** [comment]
Sorry I think I opened duplicate issue on this, but I also receiving same end error in teams window in browser. 

This is what I have tried so far:
1. Downgrade Teams Toolkit extension to v4.0.0: Uninstall (dropdown) -> Install another version -> Select v4.0.0
2. Reload VS Code
3. Sign out of MS account in Teams Toolkit
4. Exit VS code completely
5. Get rid of all VS code related cache (Mac):
```sh
rm -rf ~/Library/Application\ Support/Code/Cache/*
rm -rf ~/Library/Application\ Support/Code/CachedData/*
rm -rf ~/Library/Application\ Support/Code/CachedExtensionVSIXs
```
6. Restart VS code
7. Deploy locally via F5
8. Sign in to MS account via Teams Toolkit
9. Still running into same error even with Toolkit v4.0.1, as also indicated in comments above.

**Comment by nliu-ms** [comment]
Thanks @rnag , the failure should come from an API with 500 error: https://teams.microsoft.com/api/appstudio/appdefinitions/{appid}/manifest

So it's not about Teams Toolkit version, or downloading the js.map file. 

Can you please check from browser developer tool -> Network to see if you meet this API failure as well?

**Comment by mrrobertsson** [comment]
I am currently using a workaround that seems to be working, at least for me. 

What I have done is the following (Important that its the local version you deploy):
1. Build the local project from VSCode
    - Run `teamsfx package` from root folder.
    - Run `gulp bundle --ship && gulp package-solution --ship` from SPFx folder
2. Upload the .sppkg application (`..YourTeamsApp\SPFx\sharepoint\solution\my-app.sppkg`) to Sharepoint Apps (Sharepoint administrator -> Manage Apps) (e.g. https://yourtenantname.sharepoint.com/sites/appcatalog/_layouts/15/tenantAppCatalog.aspx/manageApps)
![image](https://user-images.githubusercontent.com/16357010/174257703-5ce41038-9021-48c7-a8c3-40a1625ff022.png)
4. Add the manifest and images to Apps in [Teams Administrator Manage Apps](https://admin.teams.microsoft.com/policies/manage-apps). Found under `YourTeamsApp\build\appPackage\appPackage.local.json`, make sure its the local. Not sure if other environments works.
![image](https://user-images.githubusercontent.com/16357010/174256501-18c5c149-74fd-47b9-ab30-a29246bffdbd.png)
5. Start debugging locally from VSCode and you will be met with this message:
![image](https://user-images.githubusercontent.com/16357010/174258010-9f7b8c8e-0736-4f4a-9b30-2fae519cb0cb.png)
6. Close the message and navigate to `Apps` -> `Built for your org` and you should be met with this view:
![image](https://user-images.githubusercontent.com/16357010/174258249-aa1380bc-73f8-412f-b5a2-c98501e22e54.png)
7. Select the `MyApp-local-debug` -> `Open`
8. Now you will be prompt to `Allow debug scripts?` as you normally would when debugging, click `Load debug scripts`.
9. It should now be working as expected and you edit your local code and then reload the teams app in the browser.

This is what worked for me and hopefully it will help someone else!

**Comment by zhenjiao-ms** [comment]
The issue is caused by the API failures in Teams dev portal, now they are actively working on the investigations of this issue. We will share when there is any updates from their side.

**Comment by rnag** [comment]
@nliu-ms ah yes, looks like you are totally right, when I go into Network tab in chrome dev tools, I also see a 500 error when requesting `https://teams.microsoft.com/api/appstudio/appdefinitions/{appid}/manifest?tenantId={tenantId}`.

**Comment by zhenjiao-ms** [comment]
We got the update from Teams dev portal that the issue has been mitigated and I have verified it in my machine. @jackpoz @CIPSoftware @rnag @mrrobertsson, feel free to let us know if you still see any issue.

**Comment by CIPSoftware** [comment]
@zhenjiao-ms I have just verified the fix using our test application and it works.

Thanks for your help.

**Comment by jackpoz** [comment]
@zhenjiao-ms thanks, now it works for me too 🚀
