### ISSUE TITLE
bug report: AppStudioPlugin.LocalAppIdCreateFailed

### ISSUE THREAD

**Issue by jk-msft** [OfficeDev/TeamsFx#5289]
I got the following error while going through [this doc](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-msgext?tabs=vscode%2Cvsc%2Cvcode%2Cviscode&tutorial-step=2).

When I was performing step 8 under `Create your message extension project workspace`, and ran Debug (Edge) in VSCode, I got the error below.

Failed to create local debug teams app in app studio, due to 503, Failed to create teams app in app studio, due to Error, Request failed with status code 503 data: "<!DOCTYPE html PUBLIC '<REDACTED: user-file-path><REDACTED: user-file-path>/DTD XHTML 1.0 <REDACTED: user-file-path>/EN' 'http:/<REDACTED: user-file-path>'><html xmlns='http:/<REDACTED: user-file-path>'><head><meta content='<REDACTED: user-file-path>

**Comment by nliu-ms** [comment]
Thanks @jk-msft , can you please try again? It might be an intermittent server error.

**Comment by jk-msft** [comment]
@nliu-ms , I don't see the issue anymore. Feel from to resolve it.

**Comment by nliu-ms** [comment]
Great, thanks!
