### ISSUE TITLE
Error when installing custom app from Teams

### ISSUE THREAD

**Issue by tcorvazier** [OfficeDev/TeamsFx#5314]
**Describe the bug**
After publishing my Teams app in my organization from Teams Tookit 4.0.1 in VS code, I get "Please check the values of authorization.permissions.resourceSpecific." when installing the teams app.

**To Reproduce**
Add the following in the Teams app manifest:
`"authorization": {
        "permissions": {
            "resourceSpecific": [
                {
                    "type": "Application",
                    "name": "Calls.Initiate.All"
                }
            ]
        }
    }`
Publish the app in your organization with Teams Toolkit.
Install the app in Teams.

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/22908717/174495323-0ddb9dea-3823-4382-8648-6c5e8cae8218.png)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version 4.0.1

**Comment by SLdragon** [comment]
@tcorvazier , from [resource-specific-consent](https://docs.microsoft.com/en-us/microsoftteams/platform/graph-api/rsc/resource-specific-consent)  doc, there is no permission "Calls.Initiate.All" available, maybe your can use another permission and try again.

Another tip is that authorization is supported for manifest version 1.12, so if you're using an old Teams Client, this may be not supported, you can update your Teams client and try again.

**Comment by tcorvazier** [comment]
ok it seems I should have added the permission in aad.template.json instead indeed
