### ISSUE TITLE
When depolying to the cloud the notification dialog is empty

### ISSUE THREAD

**Issue by LeHailender** [OfficeDev/TeamsFx#5352]
When I select the "Deploy to Cloud" option, the content of the notification dialog is blank

<img width="304" alt="image" src="https://user-images.githubusercontent.com/85994794/174987812-30534f84-1833-44d0-9313-15a59ee0204c.png">

**To Reproduce**
1. Go to 'Deploy to cloud'
<img width="282" alt="image" src="https://user-images.githubusercontent.com/85994794/174988393-2743737b-b2c1-4760-86d4-1ff0be56fe9f.png">
2. Then an empty dialog opens

**Expected behavior**
A message should appear in the dialog

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11
 - Version Teams Toolkit 4.0.1 

**Additional context**
The Teams Toolkit appears in German although all other options of VS Code appear in English
<img width="431" alt="image" src="https://user-images.githubusercontent.com/85994794/174989960-1bca83b3-c405-40e4-aeee-fc0b80b74be2.png">

**Comment by HuihuiWu-Microsoft** [comment]
Hi @LeHailender ,  this has been fixed in our latest code and you can try next release to verify. 
![image](https://user-images.githubusercontent.com/73154171/176101604-3f1032bf-1654-4580-a4d0-689f178f23cb.png)
