### ISSUE TITLE
How to debug without ngrok

### ISSUE THREAD

**Issue by air-ball** [OfficeDev/TeamsFx#5405]
Hi Team,

If we are in the company's internal network, the external network cannot directly access our local area (Tools like ngrok are not allowed), how can we debug the robot?

Thanks in advance,
Klay

**Comment by kuojianlu** [comment]
Please see this [help doc](https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/localdebug-help.md#what-to-do-if-i-want-to-use-my-own-tunneling-service-instead-of-the-built-in-one-for-bot-or-messaging-extension) for the details.

**Comment by air-ball** [comment]
> 
Hi Kuojian,

Thanks for your information.

But I means if we can not forwarding localhost address to public address, can we still do local debug?

**Comment by kuojianlu** [comment]
No. Public address is required for debugging bot app locally.

**Comment by air-ball** [comment]
Got it, Thanks kuojian.
