### ISSUE TITLE
Bot not receiving all channel messages

### ISSUE THREAD

**Issue by tcorvazier** [OfficeDev/TeamsFx#5465]
**Describe the bug**
Bot not receiving all channel messages (unless it's explicity mentioned) despite having the ChannelMessage.Read.Group RSC permission

**To Reproduce**
Add the following configuration in Teams app manifest:
`  "authorization": {
        "permissions": {
            "resourceSpecific": [
                {
                    "type": "Application",
                    "name": "ChannelMessage.Read.Group"
                }
            ]
        }
    }`

**Expected behavior**
As described in https://docs.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/channel-messages-with-rsc?tabs=dotnet bot should receive all messages, even when not mentioned

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11
 - Version 4.0.1

**Additional context**
My application registration doesn't have publisher verification yet, could that explain the issue?
My Azure active directory setup does have "Allow group owner consent for all group owners" selected

**Comment by blackchoey** [comment]
Hi @tcorvazier thanks for reaching us. I have created another issue at https://github.com/MicrosoftDocs/msteams-docs/issues/6397 which can better help on your question. Let's continue the discussions there.

**Comment by blackchoey** [comment]
@tcorvazier as we got a solution from the msteams-docs issue I created for you, I will close this issue. If you have any further questions, please post to that issue.
