### ISSUE TITLE
Error Deploying to the Cloud in Visual Studio v17.3.0

### ISSUE THREAD

**Issue by robertstewartnz** [OfficeDev/TeamsFx#5466]
This was working fine, and now it is broken. I get the following error every time I try to deploy. Nothing in the config seems to have changed from when it worked.

As a side note the deploy from VS seems very fragile. What are the recommend steps to deploy a production app to Azure? All the authentication is set up correctly because the app is working I just can't deploy the latest "Blazor" app code.

Is there a way to copy a blazor package up to Azure that can by pass this issue?

Error below:

[core] finish task:deployArtifactsV2 , time: 950 ms
{
  "errorType": "SystemError",
  "source": "FE",
  "name": "UnhandledError",
  "message": "Unhandled error.",
  "stack": "UnhandledError: Unhandled error.\n    at Function.SystemError (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at FrontendPlugin.runWithErrorHandling (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async Object.deployAdapter (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FrontendPluginV2.deploy (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async Promise.all (index 0)\n    at async Object.executeConcurrently (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async TeamsAppSolutionV2.deploy (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FxCore.deployArtifactsV2 (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FxCore.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FxCore.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)",
  "innerError": {
    "errno": -4058,
    "code": "ENOENT",
    "syscall": "open",
    "path": "C:\\xxxxxxxxx.csproj"
  },
  "userData": null,
  "timestamp": "2022-07-06T20:34:52.101Z",
  "displayMessage": "Unhandled error.",
  "helpLink": null,
  "issueLink": "https://github.com/OfficeDev/TeamsFx/issues/new"
}

**Comment by JerryYangKai** [comment]
Hi @robertstewartnz !  Thanks for reporting this bug.
Could you please re-deploy this project, and paste all the output log instead of the result, for us to tracking this issue?

**Comment by robertstewartnz** [comment]
Hi Jerry,

Thanks for getting back to me.

I managed to deploy my code by using the standard publish profiles using a Zip Deploy. I also manually created a new AAD app registration to go with it. That seems like a much better way to deploy and I can now easily target multiple deployment environments. It may be worth you guys doing an article on this approach to help others.

Even when the Teams Toolkit “Deploy to cloud” was working it was unclear how to target the deployment to multiple environments and there didn’t seem to be any configuration for naming conventions so I ended up with ugly names auto generated in Azure. Are there plans to update the Teams toolkit tooling for this?

Cheers
-Rob

**Comment by JerryYangKai** [comment]
@robertstewartnz  Great to hear that this issue is not blocking you any more. Your idea is valuable to us, what we are working on is make the operation open and clear to our user!

**Comment by JerryYangKai** [comment]
@therealjohn  Here's some idea from our user.

**Comment by therealjohn** [comment]
@robertstewartnz Yes, we want to improve this area of the toolkit and/or better integrate with existing VS features. I'd love to connect with you directly and briefly chat about this so I can capture the right details. 

Would you be willing to setup a time to chat with me about this?

**Comment by robertstewartnz** [comment]
Hi Guys,

Another note on this. I’m building a SaaS app for Teams that needs to be multi-tenant. I managed to get it working in multiple tenants but it broke all the MS Graph api calls unless it was running in the original tenant. After a lot of troubleshooting including a bunch of different code attempts I got it working by setting tenantId to “common” in the state.dev.json file.

This file isn’t even included in the project and I had to go digging in the .fx hidden folder for it.

Is this correct or is there another way I should be doing this?

Would be great if this was pulled out into app settings and some guidance give around multi-tenant support.

***@***.***

Cheers
-Rob

**Comment by KennethBWSong** [comment]
Hi @robertstewartnz Thanks for reporting this issue. Currently multi-tenant is not officially supported for .Net projects. We have already added this into our backlog and will let you know when we have any update.

**Comment by KennethBWSong** [comment]
@robertstewartnz We now have a tutorial for enable multi-tenant in node projects [here](https://github.com/OfficeDev/TeamsFx/wiki/Multi-tenancy-Support-for-Azure-AD-app#update-your-project). Updating tenant id in state.${env}.json file is a workaround to enable multi-tenant, and we will keep improving our product to provide an easier way to enable multi tenant.

**Comment by robertstewartnz** [comment]
Sure, that would be great. I'm in New Zealand gmt+12. Flick me some options for next week.

Cheers
Rob

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
