### ISSUE TITLE
Team dev newbie seeing: "Error while reading manifest.json: "manifestVersion" is required"

### ISSUE THREAD

**Issue by MuyangAmigo** [OfficeDev/TeamsFx#5507]
I am using Team Toolkit for Visual Studio installed in VS 2019 and I am seeing this error when I launch the debugger (i.e., F5) which is targeting our Microsoft Teams tenant: "Error while reading manifest.json: "manifestVersion" is required".  

I checked and I do see the “upload a custom app” menu option in Temas which the doc says indicates I have enough permission to test a Teams app in a Tab.  

Any idea why I am getting this error and what to do to fix it?  I am hoping I don’t have to create an environment to do the testing.

**Comment by nliu-ms** [comment]
@MuyangAmigo  does your manifest contains "manifestVersion"?
![image](https://user-images.githubusercontent.com/71362691/178878311-8b03205e-f148-4e19-94a9-7c5c54dfc6dc.png)

**Comment by nliu-ms** [comment]
@MuyangAmigo As Teams Toolkit for VS 2019 is deprecated and no longer maintained. I will close this issue.
