### ISSUE TITLE
Supports different manifest template for one project

### ISSUE THREAD

**Issue by nliu-ms** [OfficeDev/TeamsFx#5590]
**Is your feature request related to a problem? Please describe.**
Is it possible to have multiple manifest templates per Teams Tookit app? I want to have apps with and without offer specified, and with different sets of tabs for a single ASP.NET app. How to achieve that?

**Describe the solution you'd like**
User can define manifest template path for each environment. If it is not defined for an environment, Teams Toolkit will use the default one.

**Additional context**
Multi-env seems good for this scenario. But here user wants to customize not only the value of a tab url, but the number of tabs differ from each env. Which cannot be customized by a simple config.

**Comment by nliu-ms** [comment]
https://stackoverflow.com/questions/73058178/multiple-manifest-templates-per-teams-tookit-app

**Comment by MuyangAmigo** [comment]
Thanks for reaching out to us! We will consider this in future Teams Toolkit feature planning, and now right please consider using different code branch to manage different manifest settings.

**Comment by MuyangAmigo** [comment]
Closing this request is outdated.
