### ISSUE TITLE
Data required: validDomain

### ISSUE THREAD

**Issue by nakul91** [OfficeDev/TeamsFx#5598]
As I am trying to add a provision in the cloud using the VS  getting below error

_**code:AppStudioPlugin.GetRemoteConfigFailed, message: Missing configuration data for manifest. Data required: validDomain You must run 'Provision in the cloud' first to fill out certain fields in the manifest. Click Get Help to learn more about why you need to provision.**_

below is the JSON file 

{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.11/MicrosoftTeams.schema.json",
  "accentColor": "#FFFFFF",
  "bots": [
  ],
  "composeExtensions": [
  ],
  "configurableTabs": [
  ],
  "description": {
      "full": "Full description of {{config.manifest.appName.short}}",
      "short": "Short description of {{config.manifest.appName.short}}"
  },
  "developer": {
      "name": "Teams App, Inc.",
      "privacyUrl": "{{{state.fx-resource-frontend-hosting.endpoint}}}{{{state.fx-resource-frontend-hosting.indexPath}}}/privacy",
      "termsOfUseUrl": "{{{state.fx-resource-frontend-hosting.endpoint}}}{{{state.fx-resource-frontend-hosting.indexPath}}}/termsofuse",
      "websiteUrl": "{{{state.fx-resource-frontend-hosting.endpoint}}}"
  },
  "icons": {
      "color": "resources/color.png",
      "outline": "resources/outline.png"
  },
  "id": "{{state.fx-resource-appstudio.teamsAppId}}",
  "manifestVersion": "1.11",
  "name": {
      "full": "{{config.manifest.appName.full}}",
      "short": "{{config.manifest.appName.short}}"
  },
  "packageName": "com.microsoft.teams.extension",
  "permissions": [
      "identity",
      "messageTeamMembers"
  ],
  "staticTabs": [
      {
          "contentUrl": "{{{state.fx-resource-frontend-hosting.endpoint}}}{{{state.fx-resource-frontend-hosting.indexPath}}}/tab",
          "entityId": "index",
          "name": "Personal Tab",
          "scopes": [
              "personal"
          ],
          "websiteUrl": "{{{state.fx-resource-frontend-hosting.endpoint}}}{{{state.fx-resource-frontend-hosting.indexPath}}}/tab"
      }
  ],
  "validDomains": [
    "xyz.co",
    "app.xyz.co"
  ],
  "version": "1.0.0",
  "webApplicationInfo": {
      "id": "{{state.fx-resource-aad-app-for-teams.clientId}}",
      "resource": "{{{state.fx-resource-aad-app-for-teams.applicationIdUris}}}"
  }
}

**Comment by nliu-ms** [comment]
Thanks @nakul91 for reporting this issue? Can you please provide your Visual Studio and Teams Toolkit version? Thanks!

**Comment by nakul91** [comment]
**VS Version: 1.59.1 (Universal)**
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Darwin x64 21.4.0
**Teams Toolkit v3.7.0**

**Comment by nakul91** [comment]
Hey @nliu-ms  It worked thanks a lot for the help 👏

**Comment by nliu-ms** [comment]
That is awesome!

**Comment by SkyAdam** [comment]
Hey we have the same error but adding "validDomains": "xyzdd.com" to state dont help

**Comment by nliu-ms** [comment]
Hey @SkyAdam , I noticed that your added key is "validDomains" instead of "validDomain". Can you please check if it is the case, thanks!
