### ISSUE TITLE
bug report: SPFx.NpmVersionNotSupported

### ISSUE THREAD

**Issue by jsabety** [OfficeDev/TeamsFx#5600]
NPM version v8 is not supported for SPFx v14. Check <REDACTED: user-file-path> for more details.

stack:
NpmVersionNotSupported: NPM version v8 is not supported for SPFx v14. Check <REDACTED: user-file-path> for more details.
    at Object.NpmVersionNotSupportedError (<REDACTED: user-file-path>:2:6653734)
    at Object.func (<REDACTED: user-file-path>:2:6684644)

**Comment by HuihuiWu-Microsoft** [comment]
Hi @jsabety , NPM v8 is not supported by SPFx v1.14. You can check https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility for more details.
