### ISSUE TITLE
Created new VS2022 project with Teams toolkit bot project, hit F5 stuck at MS Teams web UI with spinner icon

### ISSUE THREAD

**Issue by frankchen76** [OfficeDev/TeamsFx#5608]
**Describe the bug**
When I used VS2022 with MS Team toolkit to create a bot application, after I hit F5, the browser showed my MS Teams with a spinner and there is nothing display except the spinner. I found out the AAD apps were created in my AAD and MS Teams bot was created on MS Teams developer portal and endpoint was configured to my ngrok. however, the MS Teams web page stuck at spinner. 

**To Reproduce**
1. Create a MS Teams app with a bot
2. run my ngrok to monitor 2544 port
![image](https://user-images.githubusercontent.com/9618662/180634268-ec85b864-7b16-4672-a44d-75776d281032.png)

3. click Project > Teams Toolkit > Configure Microsoft Teams app menu to configure the AAD App and Bot
4. hit F5. 
5. the code was compiled successfully and a debug console showed up
![image](https://user-images.githubusercontent.com/9618662/180634116-47143c06-7b3d-47a0-8369-5370ec684631.png)
![image](https://user-images.githubusercontent.com/9618662/180634121-66c99f98-fe1f-49e4-a183-f2caf0dca300.png)
![image](https://user-images.githubusercontent.com/9618662/180634125-24a93dbb-d3f7-44cc-8827-48bce3a2ec5e.png)

6. the ms team web interface was opened from browser, but stuck at spinner when sideload
![image](https://user-images.githubusercontent.com/9618662/180634128-a3753947-35f9-4eb6-b8a3-a70a66aa4731.png)

**Expected behavior**
we should be able to see MS Teams add app dialog to allow us to add app

**Screenshots**

**Visual Studio 2022 Information (please complete the following information):**
 - OS: Windows 11
 - Visual Studio 2022 Version 17.2.6
 - Teams Toolkit: 0.2.46.31854
 - .NET 6

**Comment by frankchen76** [comment]
couple things I also found out that: 

- I don't see "deploy" option is checked when I checked the solution property->project configuration. does that mean the app was delivered to MS Team?
![image](https://user-images.githubusercontent.com/9618662/180849854-15beda70-75b6-45f1-834a-23dc8bce00b6.png)

- the debug output also showed the below error message. 
![image](https://user-images.githubusercontent.com/9618662/180850066-a7d664f8-0453-466a-8519-57aff379c7ec.png)

any updates for this issue?

**Comment by nliu-ms** [comment]
Sorry for the inconvenience @frankchen76 , the problem may come from the failure of `Configure Microsoft Teams app `. Besides AAD and bot, this step will create a Teams app as well. So the failure of this step may be the root cause.
![image](https://user-images.githubusercontent.com/71362691/180944052-2800c8f6-58d7-4218-b4e6-59917b8a4aef.png)

And I highly doubt it is related to a known backend service outage, see https://github.com/OfficeDev/TeamsFx/issues/5610. This issue has been mitigated now. Can you please try again and check if you're still meeting this problem? Thanks!

**Comment by frankchen76** [comment]
@nliu-ms thanks for your note. I was aware the service outage which you mentioned and believe it might be associated with that. when I rerun everything, it actually worked. 
a side question, I felt about the Team toolkit (both vscode and vs one) wrapped up a lot of provisioning processes. do you recommend any documents which I can understand what exactly those processes are? I recalled previously when we created bot based on Azure Bot service, even though I had to provisioning AAD app and azure resources and did a lot of configurations, I knew where I should check if there were any errors. Now when something happened, I don't know what those processes missed and where to check. :-) Thanks

**Comment by nliu-ms** [comment]
That's great! Can you please check this doc: https://docs.microsoft.com/en-us/microsoftteams/platform/toolkit/provision , which describes what resources are provisioned by Teams Toolkit. And under {project root}/templates/azure, there are some bicep files providing some clues. Thanks!
