### ISSUE TITLE
teamsFx.login() popup consent shows white screen and freez.

### ISSUE THREAD

**Issue by anoopgcmz** [OfficeDev/TeamsFx#5609]
**Describe the bug**
To get access to Graph api we use teamsFx sdk. The popup for obtaining user consent is freezed and no data is shown. The re-direct URL is shown as "/blank-auth-end.html" which was not defined. This issue is only for MS Teams desktop applications. In browser It is working fine.
Due to this issue we are not able to access the graph api.

**Code we use**
`const teamsfx = new TeamsFx();
  const scope = ["User.ReadBasic.All", "Team.ReadBasic.All", "Channel.ReadBasic.All", "User.Read"];
  await teamsfx.login(scope);
  // Initialize Graph Toolkit TeamsFx provider
  const provider = new TeamsFxProvider(teamsfx, scope);
  Providers.globalProvider = provider;
  Providers.globalProvider.setState(ProviderState.SignedIn);`

**Expected behavior**
Popup should automatically close and receive the token, although the admin grants the permissions

**Screenshots**

![freez image](https://user-images.githubusercontent.com/7369440/180635584-dc4e1534-6e63-4abe-9b20-3526954f6b69.PNG)

**Comment by KennethBWSong** [comment]
@anoopgcmz Thank you for reporting this issue! Seems you are hosting this page on Azure Webapp. You may need to config the initiateLoginEndpoint [here](https://github.com/OfficeDev/TeamsFx/tree/dev/packages/sdk#invoke-graph-api-on-behalf-of-teams-user-user-identity). Would you please check whether the initiateLoginEndpoint is config correctly?

**Comment by anoopgcmz** [comment]
@KennethBWSong Thank you for the support. Some users only report this issue. we haven't configured initiateLoginEndpoint .

**Comment by KennethBWSong** [comment]
@anoopgcmz We will keep tracking this issue in email. Thanks!

**Comment by AnthonyPhan** [comment]
Hi, we are experiencing the same issue. Also hosting our app on Azure Web App. Is it possible to provide some of the details form the email support here for the community?

**Comment by anoopgcmz** [comment]
@AnthonyPhan  This issue is not yet resolved. Communication is going on. once we resolve this issue, I will update the solution here

**Comment by AnthonyPhan** [comment]
We have found that this issue happens to users running outdated versions of teams that may predate Teamsfx. For example the user running version 1.4 below experiences the issue. Did you come to the same conclusion @anoopgcmz 

![image](https://user-images.githubusercontent.com/12785492/192529541-62401de4-1a30-4505-b353-623e4ab00916.png)

**Comment by Anandks1993** [comment]
Hi @AnthonyPhan, We are also facing this issue right now, any update on this issue? 

We are hosting the app in Azure Web App and now if we open the app it is saying `blank-auth-end.html` file is not found.

**Comment by AnthonyPhan** [comment]
No update on this on our end. Based on our application insight we belive this is an on-going issue affecting a large number of our users.

> We are hosting the app in Azure Web App and now if we open the app it is saying blank-auth-end.html file is not found.

This sounds like a separate issue.

**Comment by anoopgcmz** [comment]
@AnthonyPhan still now no update. we updated the teamsFx version, but still in some scenarios we are facing this issue

**Comment by stefan-at-ilionx** [comment]
We're also getting this error, but only on devices running MacOS. We also tried several solutions as described in https://github.com/OfficeDev/teams-toolkit/issues/10379, but no dice.
