### ISSUE TITLE
Cannot Run Teams Toolkit 4.0.2 Local Debug with Mac M1

### ISSUE THREAD

**Issue by mike-bell-gettogetherai** [OfficeDev/TeamsFx#5619]
I am suddenly getting issues (after the most recent Teams Toolkit upgrade) for testing local apps, both on bot and tabs. After 5+ hours of attempting to reinstall / clear everything, I'm finally posting here...

Note: I'm running on a Mac M1 with node 14.19.1 and have seen similar issues reported by others with Mac M1. 

The bot is now failing to run due to the error below: 

```
"UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 401 ERROR
 Error: Unauthorized. Invalid AppId passed on token: <my bot ID>"
```

I can manually update the line below...

```
    const adapter = new BotFrameworkAdapter({
      appId: process.env.BOT_ID,
      appPassword: process.env.BOT_PASSWORD,
    });
```

so that it has the registered ID and Password in the portal (though I've never had to do that before), but then I still have another issue...

The tab is now failing due to: 

`Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/data-resolvers-user-preferences-c06303c3f2b26931.js: Unexpected 503 response from https://local.teams.office.com/sourcemaps/hashed-assets/data-resolvers-user-preferences-c06303c3f2b26931.js.map: connect ECONNREFUSED 0.0.0.0:443`

None of my team members are having this issue and I've ensured our code is the exact same other than our app / bot registrations. 

Reverting to Teams Toolkit 4.0.0 fixes the issue with no other changes.

**Comment by XiaofuHuang** [comment]
> I am suddenly getting issues (after the most recent Teams Toolkit upgrade) for testing local apps, both on bot and tabs. After 5+ hours of attempting to reinstall / clear everything, I'm finally posting here...
> 
> Note: I'm running on a Mac M1 with node 14.19.1 and have seen similar issues reported by others with Mac M1.
> 
> The bot is now failing to run due to the error below:
> 
> ```
> "UnhandledPromiseRejectionWarning: Error: BotFrameworkAdapter.processActivity(): 401 ERROR
>  Error: Unauthorized. Invalid AppId passed on token: <my bot ID>"
> ```
> 
> I can manually update the line below...
> 
> ```
>     const adapter = new BotFrameworkAdapter({
>       appId: process.env.BOT_ID,
>       appPassword: process.env.BOT_PASSWORD,
>     });
> ```
> 
> so that it has the registered ID and Password in the portal (though I've never had to do that before), but then I still have another issue...
> 
> The tab is now failing due to:
> 
> `Could not read source map for https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/data-resolvers-user-preferences-c06303c3f2b26931.js: Unexpected 503 response from https://local.teams.office.com/sourcemaps/hashed-assets/data-resolvers-user-preferences-c06303c3f2b26931.js.map: connect ECONNREFUSED 0.0.0.0:443`
> 
> None of my team members are having this issue and I've ensured our code is the exact same other than our app / bot registrations.
> 
> Reverting to Teams Toolkit 4.0.0 fixes the issue with no other changes.

Hi @mike-bell-gettogetherai, thank you for your reporting. We can't reproduce the bot bug on m1. Would you like to provide more information about it? (e.g. the screenshot, .fx/configs/projectSettings.json, ./bot/.env.teamsfx.local)

For the tab error message, if it is shown in the debug console, you can ignore it, because it is an error thrown by the teams webside, and it does not affect the display of the tab content.

**Comment by mike-bell-gettogetherai** [comment]
This issue is still present, including with 4.0.3. The highest I can upgrade without breaking is 4.0.1. 

If it would be helpful, I can record a video demo. 

If you'd like the files mentioned, then can I please email somewhere directly since there may be some compromising information included in those?

**Comment by XiaofuHuang** [comment]
> 

@mike-bell-gettogetherai Thanks so much! The demo & project files are very important for us to improve the experience of the Teams Toolkit. Can we keep in touch at ttkfeedback@microsoft.com?

**Comment by scottrpoulin** [comment]
Any Updates on this? I get this in the debug console. Currently using 4.18.0
