### ISSUE TITLE
bug report: AppStudioPlugin.LocalAppIdUpdateFailed

### ISSUE THREAD

**Issue by nickolitesla** [OfficeDev/TeamsFx#5626]
Failed to update local debug Teams app in Developer Portal, due to API call to Developer Portal failed: Error, Request failed with status code 503, API name: get-app, X-Correlation-ID: undefined. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "<!DOCTYPE html PUBLIC '<REDACTED: user-file-path><REDACTED: user-file-path>/DTD XHTML 1.0 <REDACTED: user-file-path>/EN' 'http:/<REDACTED: user-file-path>'><html xmlns='http:/<REDACTED: user-file-path>'><head><meta content='<REDACTED: user-file-path>

**Comment by nliu-ms** [comment]
Thanks @nickolitesla , this one is duplicate with https://github.com/OfficeDev/TeamsFx/issues/5627, so will close this one.
