### ISSUE TITLE
Service unavailable with error code 503 when launching debug

### ISSUE THREAD

**Issue by SpicyNoodless** [OfficeDev/TeamsFx#5627]
Service unavailable with error code 503 when launching debug, it works good yesterday, and I didn't change any of my codes.

More info
<img width="1443" alt="image" src="https://user-images.githubusercontent.com/76025453/181140085-761940df-0cf8-409e-a812-e3eaa4c3fbb9.png">

App Studio in Teams is unavailable also
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/76025453/181140231-c04b246d-cb0c-441a-848f-4fe68a820bd3.png">

App that already deployed can be launch successfully, so I think this should an App Studio service issue, creating a bug to track.

Is it possible to skip the phase that communicate with App Studio service when launching local debug?

**Comment by nliu-ms** [comment]
@SpicyNoodless  Thanks for reporting this bug! From the telemetry the error rate is about 50%, so maybe you can retry several times. We reported this issue to Developer Portal team.

**Comment by nliu-ms** [comment]
The issue is caused by some unhealthy Teams Developer Portal clusters. We have filed a ticket to them and they are actively investigating it. We will inform you once we get any updates.

**Comment by SpicyNoodless** [comment]
Seems partially recovered, run successfully just now.

**Comment by nliu-ms** [comment]
Thanks @SpicyNoodless , the unhealthy clusters have been deployed again. This issue should have been mitigated now, I've monitored the logs that no error in 1 hour.
