### ISSUE TITLE
TeamsFx dotnet-sdk package - ConversationBot: Issue processing Action.Submit action from AdaptiveCard sent as respone from CommandHandler

### ISSUE THREAD

**Issue by abbasl7** [OfficeDev/TeamsFx#5648]
**Describe the bug**

I'm trying to use TeamsFx dotnet-sdk and facing issue using CommandHandlers.
The ConversationBot does work and I do get responses. But, when I send an adaptiveCard as response and when user performs Action.Submit on the Card, the response doesn't get posted to IBot implementation for processing Activity. It simplys looks for CommandHandler and throws an exception saying RegEx match not found.

**To Reproduce**
1. Add Microsoft.TeamsFx package to an existing Bot
2. Create a CommandHandler class which sends an AdaptiveCard with Action.Submit component
3. Register it and the Conversation with command-response feature enabled in Startup.cs
4. Run the Bot and invoke Command. In the received Adaptive Card, click on submit button
5. AdapterWithErrorHandler throws error.

**Expected behavior**
Action.Submit should be sent to ActivityHandler so that it can be processed

**StackTrace**
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Text.RegularExpressions.ThrowHelper.ThrowArgumentNullException(ExceptionArgument arg)
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at Microsoft.TeamsFx.Conversation.CommandResponseMiddleware.ShouldTrigger(String input, IEnumerable`1 triggerPatterns)
   at Microsoft.TeamsFx.Conversation.CommandResponseMiddleware.OnTurnAsync(ITurnContext turnContext, NextDelegate next, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.MiddlewareSet.ReceiveActivityWithStatusAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)
   at Microsoft.Bot.Builder.BotAdapter.RunPipelineAsync(ITurnContext turnContext, BotCallbackHandler callback, CancellationToken cancellationToken)

**Package Used:**
- TeamsFx dotnet-sdk from nuget

**Comment by dooriya** [comment]
Thanks @abbasl7! Can you try to use the [adaptive card universal action](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/universal-actions-for-adaptive-cards/overview?tabs=mobile) (`Action.Execute`) instead of `Action.Submit`, which is replacement of the old `Action.Submit` and is a unified action model across platforms.

And then you should be able to catch the invoke activity in your own `ActivityHandler` when end-user clicks the button. For example:
```csharp
public class TeamsBot : ActivityHandler
    {
        //public Task OnTurnAsync(ITurnContext turnContext, CancellationToken cancellationToken = default) =>
        //    Task.CompletedTask;

        protected override async Task<InvokeResponse> OnInvokeActivityAsync(ITurnContext<IInvokeActivity> turnContext, CancellationToken cancellationToken)
        {
            // Handle card action
            if (turnContext.Activity.Name == "adaptiveCard/action")
            {
                // Handle your action response
                var cardJson = await File.ReadAllTextAsync("Resources/ActionResponseCard.json", cancellationToken).ConfigureAwait(false);
                var response = JObject.Parse(cardJson);
                var adaptiveCardResponse = new AdaptiveCardInvokeResponse()
                {
                    StatusCode = 200,
                    Type = "application/vnd.microsoft.card.adaptive",
                    Value = response
                };

                return CreateInvokeResponse(adaptiveCardResponse);
            }

            return CreateInvokeResponse(null);
        }
    }
```

**Comment by abbasl7** [comment]
Thanks for the response, @dooriya ! I'll certainly give it a try and let you know.
Meanwhile, I've a related question. Since you suggested to use Action.Execute, I'm willing to take it a step further and use Sequential Workflow, which offers a lot more cleaner workflow.
Now, my question is this:
IMO, CommandHandlers are more like direct/alternate paths to specific actions so that user don't have to remember what to type. As a side effect, It helps to keep the code in the bot class clutter free (which is a relief to me, as a developer!). But, if I go through this Sequential Workflow, I'll have to send the first card through CommandHandler and all further Action.Execute actions have to be handled in my ActivityHandler Bot. Am I correct? Or is there still a way, which I don't see, to handle all Action.Execute actions within the CommandHandler itself?

**Comment by dooriya** [comment]
@abbasl7 Thanks for the valuable feedback! Your understand is correct that you'll need to use your `ActivityHandler` Bot to handle the subsequent actions in a sequential workflow scenario with **current** conversation bot SDK.

But to continue improve the dev experience for bot development, we're now looking into supporting workflow handling with our simplified SDK. Once this is supported in our SDK, then you don't need to have your `ActivityHandler` bot to handle the actions, both the initial command response and the card action responses should be able to handled in our conversation bot SDK.

**Comment by abbasl7** [comment]
Very glad to hear that you're looking into it! I'll be very much waiting to see that released soon. I understand you can't commit when it will be available, but any tentative timeline that you can share? Like weeks or months away so that I can plan accordingly?
You don't know how much relieved I was to see this _dotnet-sdk_ available via nuget. I was struggling with Teams Toolkit for VisualStudio for the past 2 months. I still don't understand why it doesn't support adding "Teams features" after a project is created using it, when it's VS Code counterpart can do that. I don't mind using VS Code too, but it doesn't support C#.
I was very much disappoint for a while to see that C# developers don't get as much love as TypeScript/JavaScript developers.

**Comment by abbasl7** [comment]
Closing this for now, since a workaround is available.

**Comment by MuyangAmigo** [comment]
Hey @abbasl7, thanks for your interest in our upcoming work. We are planning to ship out support building workflow style bot application around October this year. We'd love your feedback when we release it, so please stay tunned.
