### ISSUE TITLE
bug report: SPFx.NodeVersionNotSupported

### ISSUE THREAD

**Issue by dracs516** [OfficeDev/TeamsFx#5658]
Node.js version v18 is not supported for SPFx v14. Check <REDACTED: user-file-path> for more details.

stack:
NodeVersionNotSupported: Node.js version v18 is not supported for SPFx v14. Check <REDACTED: user-file-path> for more details.
    at Object.NodeVersionNotSupportedError (<REDACTED: user-file-path>:2:6727190)
    at Object.func (<REDACTED: user-file-path>:2:6751348)
    at processTicksAndRejections (node:<REDACTED: user-file-path>:96:5)

**Comment by HuihuiWu-Microsoft** [comment]
Hi @dracs516 , it's expected behavior that Node.js v18 is not supported for SPFx v1.14.0. You can check https://docs.microsoft.com/en-us/sharepoint/dev/spfx/compatibility#spfx-development-environment-compatibility for more details.
