### ISSUE TITLE
Empty SSO token returned by TeamsUserCredential

### ISSUE THREAD

**Issue by AndrewCraswell** [OfficeDev/TeamsFx#5672]
**Describe the bug**
Our SSO Tab app uses `TeamsUserCredential` to get the user's SSO token. This works when running the app using Teams Toolkit, the token is returned for the user. Our custom First Party App AAD instance has been configured for SSO, and we use the same ClientId for all our test environments in all tenants. However, when we deploy the app to our Teams org, suddenly the SSO token (which is returned by `TeamsUserCredential`) is an empty string.

When debugging the TeamsFx code, we're hitting this code block on line 107 of the `teamsUserCredential.browser.ts` file:
https://github.com/OfficeDev/TeamsFx/blob/c326d0a30d9e58219f401cb25d6dfb9f78249a5a/packages/sdk/src/credential/teamsUserCredential.browser.ts#L106-L112

It seems like the Teams SDK `authenticate()` method is calling the success callback, but the resulting token is just an empty string. I can see that the TeamsFx code is handling this scenario and throwing an error. But it's not clear to me what would cause someone to encounter this in the first place. Unfortunately, my research hasn't turned up any helpful materials.

Since the code works fine when running the app locally, or when previewing the app via the Teams Developer Portal, I think we can rule out AAD settings. Since the same Manifest and app package is being used, I feel like that can be ruled out as well.

I suspect this isn't an issue with TeamsFx, since the SDK is just calling the Teams SDK. But does somebody on the team maybe have some guidance on what we might be doing wrong? Or what might cause this particular scenario? The fact that an error case is being thrown here leaves me hopeful that someone has dealt with this before :)

**Additional context**
This question was also filed in the Teams Developer Questions team, under the Authentication channel:
https://teams.microsoft.com/l/message/19:17162c6217f74e329f06316033d1185b@thread.skype/1659389672553?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=e6142543-e676-4276-8555-6232b0e3a89f&parentMessageId=1659389672553&teamName=Teams%20Developer%20Questions&channelName=Authentication&createdTime=1659389672553

**Expected behavior**
A non-empty SSO token should be returned by the `TeamsUserCredential` class.

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10

**CLI Information (please complete the following information):**
 - OS: Windows 10
 - Version: ^1.0.0

**Comment by blackchoey** [comment]
Thank you for contacting us. As synced in another thread, since the token is returned by Teams client, please try to switch Teams client rings to public to see whether this issue still exists.

**Comment by AndrewCraswell** [comment]
Thanks for taking the time to sync with us offline. Since we've identified that it seems the TeamsFx library is behaving correctly, I opened a similar ticket on the teams-js Github. Hopefully they will have some ideas :)
https://github.com/OfficeDev/microsoft-teams-library-js/issues/1290
