### ISSUE TITLE
"Object reference not set to an instance of an object" error during provision

### ISSUE THREAD

**Issue by blackchoey** [OfficeDev/TeamsFx#5759]
When your project contains Azure App Service, you may encounter "Object reference not set to an instance of an object".

Please apply this workaround when you meet this error:
1. Search Microsoft.Web/serverfarms in all bicep files in your project
2. Add properties: {} to the resource definition. Here is an example:
![image](https://user-images.githubusercontent.com/16605901/186344753-efc14760-fb1b-4f67-9d8d-6539209e44c2.png)
3. Provision again

We're actively working with Azure team to fix this issue.

**Comment by dozer75** [comment]
This is a critical, it messes up our `serverfarm` based templates so I REALLY hope you fix it soon since this has worked earlier and causes a bit havoc in various CI/CD routines.

**Comment by blackchoey** [comment]
@dozer75 this is an issue in Azure App Service so we're not able to fix it in the tooling. The good news is related fix is being deployed but it still takes some time to apply to all Azure regions.
You can follow the workaround to update your templates to unblock your CI/CD.

**Comment by blackchoey** [comment]
The issue has been fixed in App Service. Closing this issue.
