### ISSUE TITLE
M365 Pre-requisite account sign on?

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/TeamsFx#5795]
Trying to build some sample apps. I have an M365 tenant & Dev Program account, etc. In Visual Studio Code, when I try to run the source, it hangs when trying to sign in. Under accounts, no accounts are shown. How is sign on handled from within VS Code? It isn't clear...

**Comment by xiaolang124** [comment]
Sorry for your inconvenience. In normal case, click `Sign in to M365` or `Sign in to Azure` will open a login web page for you to login. This will happen when you try to local debug without user login. Have you encountered any problem opening the login page or cannot login via login page?

![image](https://user-images.githubusercontent.com/13211513/185018460-c599e479-a6b3-4e10-af63-a86c95710b3e.png)

**Comment by elthombre** [comment]
Hi, yes, I was able to correct this. It was opening a browser page but directing to it. It was hidden. Consequently, VS Code would just hang. Once I found out what was happening, I changed my default browser which had inadvertently been altered from Chrome to Opera. It then began working correctly.

**Comment by adashen** [comment]
Close as the issue has been solved.
