### ISSUE TITLE
[Login] Failed to retrieve token silently: endpoints_resolution_error

### ISSUE THREAD

**Issue by elthombre** [OfficeDev/TeamsFx#5830]
Trying to get a sample app up and running in Teams. Receiving the following error:

[Error] - [Login] Failed to retrieve token silently: endpoints_resolution_error: Error: could not resolve endpoints. Please check network and try again. Detail: ClientConfigurationError: untrusted_authority: The provided authority is not a trusted authority. Please include this authority in the knownAuthorities config parameter.

**Comment by blackchoey** [comment]
@elthombre can you share which sample are you trying?

**Comment by elthombre** [comment]
https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-javascript

**Comment by elthombre** [comment]
I also have the following book:

https://link.springer.com/book/10.1007/978-1-4842-6364-8

with source here:

https://github.com/Apress/pro-microsoft-teams-dev

**Comment by blackchoey** [comment]
@elthombre Can you share where did you get the error message? I tried the sample and didn't met errors. Since the sample you shared does not include login related logic, I guesses the error is not happened in the tab app.

**Comment by elthombre** [comment]
It never gets to run the app. It uploads but does not load correctly. Appears to be something in setting up the environment. There are many moving parts and 3rd party tools.

**Comment by blackchoey** [comment]
Can you share Teams Toolkit's log in VS Code output channel, as well as some error message or screenshot for `It uploads but does not load correctly` you mentioned earlier? We will troubleshoot further with these information.
