### ISSUE TITLE
Custom app in Teams desktop client 

### ISSUE THREAD

**Issue by Arthurqin20227** [OfficeDev/TeamsFx#5841]
Hi Team,

We have a custom app, and we encounter an issue. We find that in one of our devices, we cannot access to the backend page of the app. Authentication not pop out. However, in other device, with the same app, same Teams desktop version, and same code, authentication windows can pop out.

**To Reproduce**
1. Go to test channel, click the tab( app already pin on the channel tab)
2. Waiting for authentication windows pop out but it didn't. Just blank screen.

**Expected behavior**
an Authentication windows will pop out like below
![image](https://user-images.githubusercontent.com/110021957/185363686-5a235b15-3b86-459a-bff8-37f371878130.png)

When we check the Develop tools in Teams desktop client for this app, we can see error report in Console:
Refused to display 'https://login.microsoftonline.com' in a frame i-frame-container.htm...Invalidation=true:1 because it set 'X-Frame-Options' to 'deny'

![image](https://user-images.githubusercontent.com/110021957/185365224-b0e2b4e4-e010-45bf-bb1b-85ed3b2a64f9.png)

For SSO code part 
![image](https://user-images.githubusercontent.com/110021957/185365985-13196cb9-776a-4ee4-af3d-1ac8d6f886be.png)

Does anyone have any idea about why this issue only happen on one single device? Any reply will be appreaciated~

**Comment by KennethBWSong** [comment]
Hi @Arthurqin20227 thank you for reporting this issue.
This error will occur when you are trying to render the login page in iframe. It seems that you are using teams js sdk, it would be better to raise an issue in this [repo](https://github.com/OfficeDev/microsoft-teams-library-js).
I also want to confirm that are you using our TeamsFx sdk in our project?

**Comment by Arthurqin20227** [comment]
Hi @KennethBWSong  thank you for you reply~~

Sure I will discuss in your provided link and create a new thread~

Btw, I'm not sure whether we are using TeamsFx sdk since I'm not developer of this app. Sorry about that
