### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by ThomasPe** [OfficeDev/TeamsFx#5910]
I'm wondering if there are any release notes for the packages that are being released? Under releases I don't even see all packages, am I looking in the wrong place?
Microsoft Graph Tookit for example is doing a great job here: https://github.com/microsoftgraph/microsoft-graph-toolkit/releases

**Comment by wenytang-ms** [comment]
what's a good idea, thank you for your kind reminder @ThomasPe 
At present, the release notes/changelogs of our products are list as follows:
|package |Doc |
|----|----|
|teams-vscode-extension|[WHATISNEW](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/vscode-extension/WHATISNEW.md)|
|teams-vscode-extension|[CHANGELOG](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/vscode-extension/CHANGELOG.md)|
|@microsoft/temasfx|[CHANGELOG](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/sdk/CHANGELOG.md)|
|@microsoft/teamsfx-react|[CHANGELOG](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/sdk-react/package.json)|
|Microsoft.Azure.WebJobs.Extensions.TeamsFx|[CHANGELOG](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/function-extension/CHANGLOG.md)|

In the future, we will add these release notes to the GitHub release page.

**Comment by ThomasPe** [comment]
thanks, this already helps a lot.

**Comment by adashen** [comment]
Close as the issue is resolved
