### ISSUE TITLE
referer policy "strict-origin-when-cross-origin" causing HTTP request failures in our Tab TeamsFx app

### ISSUE THREAD

**Issue by RobertMcAuley** [OfficeDev/TeamsFx#5912]
**Is your feature request related to a problem? Please describe.**
We built a TeamsFx tab application in Microsoft Teams, and we noticed that it was working fine in MS Teams version 1.5.00.17261 (for Mac) but failed in MS Teams version 1.5.00.21551 (for Mac).

Upon further investigation, we noticed one of our HTTP requests was failing on version 1.5.00.21551, and using the Dev tools we discovered a different referer policy was being applied to web requests (1.5.00.17261 used "no-referrer-when-downgrade", and 1.5.00.21551 and upward uses "strict-origin-when-cross-origin"). 

To give a bit of background, our tab app embeds an IFrame with a certain domain that we've whitelisted (the app Manifest.json has a section for validDomains and the IFrame's domain is listed within). The domain within our IFrame then makes a few calls to log in and authenticate the user, and all calls are made to that same domain we've whitelisted, so there shouldn't be any cross origin violations. With the new "strict-origin-when-cross-origin" policy being applied to our HTTP requests, the login calls fail, and we can't proceed.

**Describe the solution you'd like**
It was clear that with the old referer policy "no-referrer-when-downgrade" our authentication calls were successful, and I'm wondering if there's a way to either revert to that policy in a newer version of MS Teams or to specify what policy we'd like to employ at the tab application level. 

**Describe alternatives you've considered**
We've attempted to specify the referer-policy at the IFrame level, but that didn't work. It seems that the policy is being enforced at a higher level than what we have access to within the application ecosystem. 

**Additional context**
No additional context at this time.

**Comment by blackchoey** [comment]
@RobertMcAuley can you share following information with us?
1. Is your app working fine in Teams Web Client? What's the referer policy in this case?
2. Which identity provider are you using to log in users? Is it AAD or something else?
3. What's the error message for the login call?
4. How do you make http requests in your iFrame?

By the way, you can refer this blog for the impact of changing `no-referrer-when-downgrade` to `strict-origin-when-cross-origin`:https://developer.chrome.com/blog/referrer-policy-new-chrome-default/#whats-the-impact. Based on the blog, seems there's no CORS related impact with the header change. You may take further investigation on how the login calls fail.

**Comment by RobertMcAuley** [comment]
hi @blackchoey , thank you for the quick reply. 

Here are the answers to your questions:

1. I tested the app in both Chrome and Firefox and it appears to also fail there. I did see that the `strict-origin-when-cross-origin` is also present in those browsers.
2. It is something else, we do not authenticate with AAD. 
3. There isn't an error message, but I inspected the http request being made from our app and there is no response. My suspicion is that it is being blocked. Since the referer policy changed between versions of microsoft teams and nothing else changed from our end, the referer policy was the prime suspect.
4. In our tab application, we create an iFrame element and point its src to our server (the server is located at a different host and port). The server sends some html/javascript to the iFrame, and we use the embedded html page to log in (http login request is being sent by the html page to the same domain).

Thank you for the reference page for the impact of the referer-policy. We may have to investigate why our login fails with the new policy. 

I don't suppose there is a way for us to configure the policy during TeamsFx app development, or in MS Teams itself (either desktop or browser)? We're confident that the old policy worked for us, but the reason is unknown. It would be great if we could go back to the old policy in the meantime to get the app working again. Thanks in advance

**Comment by Atila027** [comment]
I have just faced such problem, but I can not find the solution easily.
Currently I am working on meteor project

**Comment by blackchoey** [comment]
@Atila027 Please refer https://developer.chrome.com/blog/referrer-policy-new-chrome-default/#whats-the-impact, the impact is on server-side logging and analytics. You can refer following code snippet (based on fetch) to set this policy if you need:
```
fetch('your-url', {referrerPolicy: 'no-referrer-when-downgrade'})
```

**Comment by Atila027** [comment]
________________________________
