### ISSUE TITLE
Local Debug with Visual Studio Code fails for Teams App with Localization in Manifest

### ISSUE THREAD

**Issue by jensker** [OfficeDev/TeamsFx#5940]
**Describe the bug**
I added localizationInfo to manifest.json of my teams app. When I try to locally debug the app, teams denies to load the package with error message: "Fehler beim Lesen von manifest.json: The file could not be parsed as a JSON object.

When I try to upload the local package manually, everything works as expected.

**To Reproduce**

1. Local debug teams app with manifest and localization -> Error
2. Validate local package in Teams Developer Tools -> Success
3. Manually upload local app package to Teams and install app -> Success
4. Zip metadata to the cloud -> Success
5. Deploy to cloud -> Success
6. Remote debug teams app with manifest and localization -> Success

**Expected behavior**

I want to be able to locally debug the app package with localization without having to manully install the app package.

**Screenshots**

![image](https://user-images.githubusercontent.com/81486634/187176753-bb4e0d7e-c5a8-4f14-bd54-5beefd44971d.png)

Manifest.template.json:
   "localizationInfo": {
        "defaultLanguageTag": "en",
        "additionalLanguages": [
         {
          "languageTag": "de",
          "file": "resources/de.json"
         }
        ]
    },

de.json:
{
    "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.12/MicrosoftTeams.Localization.schema.json",
    "name.short": "Name App",
    "name.full": "Name App",
    "description.short": "Description Short Deutsch",
    "description.full": "Description Long Deutsch",
    "staticTabs[0].name": "Home"
  }

Loading app locally to Teams:

![image](https://user-images.githubusercontent.com/81486634/187179498-c1ee7c67-9def-4043-9e2c-80a1118957d1.png)

Error message: Fehler beim Lesen von manifest.json: The file could not be parsed as a JSON object.

Networking analysis:

![image](https://user-images.githubusercontent.com/81486634/187179919-5603337b-6c20-466a-a466-e90338164c1c.png)

Checking the same package with teams developer tools:

![image](https://user-images.githubusercontent.com/81486634/187240837-be2592a5-0092-4861-b05e-3b005124c683.png)

![image](https://user-images.githubusercontent.com/81486634/187241014-e4d1629b-d811-46ee-8ad7-19dc1c5bc1d1.png)

Manually uploading the local package with localization is fine:

![image](https://user-images.githubusercontent.com/81486634/187241237-b9a27f0f-bb9b-4665-a15c-0a702b1c5705.png)

![image](https://user-images.githubusercontent.com/81486634/187241406-431c7dbf-9361-4fda-a508-6b19cba82d35.png)

The localization json is available in local zip package. Also local manifest look fine.

**VS Code Extension Information (please complete the following information):**
 - Teams Toolkit v4.0.5
 - Windows 10

**CLI Information (please complete the following information):**

**Additional context**

**Comment by nliu-ms** [comment]
Hey @jensker , thanks for your useful information. I will take a look and get back to you.

**Comment by nliu-ms** [comment]
Hey @jensker , sorry for the late reply. With some investigation I believe it might be a bug from server side. There are 2 options as the workaround:
1) You can use Teams Toolkit v4.0.2 (it uses different APIs so the localization file will be uploaded correctly)
2) You can still use Teams Toolkit v4.0.5, but please define more than one language in your manifest.template.json file.

```
"localizationInfo": {
        "defaultLanguageTag": "en",
        "additionalLanguages": [
            {
                "languageTag": "de",
                "file": "resources/de.json"
            },
            {
                "languageTag": "en",
                "file": "resources/en.json"
            }
        ]
    }
```
Please let me know if it works for you, thanks!

**Comment by jensker** [comment]
@nliu-ms : Sorry for the late reply. I was busy with deploying of the app in the AppSource store. Nevertheless, the workaround works pretty well. Thank you very much! This makes development much easier again.

**Comment by Steffi3rd** [comment]
Hi, 

I have the same problem, even with Teams Toolkit v4.0.2 or 4.0.5.
❌ **Erreur lors de la lecture du manifest.json: The file could not be parsed as a JSON object.**

I have 2 lang (`en` and `fr`)

I just update to the latest v4.1.1, but same problem.

Here is my `manifest.template.json`.
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.14/MicrosoftTeams.schema.json",
  "manifestVersion": "1.14",
  "version": "1.3.4",
  "id": "{{state.fx-resource-appstudio.teamsAppId}}",
  "packageName": "com.microsoft.teams.extension",
  "localizationInfo": {
    "defaultLanguageTag": "fr",
    "additionalLanguages": [
      {
        "languageTag": "en",
        "file": "resources/en.json"
      },
      {
        "languageTag": "fr",
        "file": "resources/fr.json"
      }
    ]
  },
  ...
}
```

And each i18n file : 

`resources/fr.json`
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.14/MicrosoftTeams.Localization.schema.json",
  "name.short": "FR",
  "name.full": "FR",
  "description.short": "FR",
  "description.full": "FR",
  "staticTabs[0].name": "FR",
}
```

`resources/en.json`
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.14/MicrosoftTeams.Localization.schema.json",
  "name.short": "EN",
  "name.full": "EN",
  "description.short": "EN",
  "description.full": "EN",
  "staticTabs[0].name": "EN",
}
```

Is there another fix for this bug?

**Comment by jensker** [comment]
@Steffi3rd: Hey! The workaround is still working for me (I just double-checked a few minutes ago).

Teams Toolkit v.4.0.5
In the manifest, I am using v1.12:

manifest.template.json: 
"$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
"manifestVersion": "1.12",

en.json:
"$schema": "https://developer.microsoft.com/json-schemas/teams/v1.12/MicrosoftTeams.Localization.schema.json",

In manifest.template.json, I also use name and description:

    "name": {
        "short": "{{config.manifest.appName.short}}",
        "full": "{{config.manifest.appName.full}}"
    },
    "description": {
        "short": "BLA",
        "full": "BLA BLA"
    },

Do you also have name and description in your manifest.template.json? The values will be overwritten, but still, they need to exist.

Did you double check that after start of debugging manifest.dev.json is generated correctly? You find these in your project under build\appPackage.

Hope that helps. 

Best regards,

Jens

**Comment by jensker** [comment]
@Steffi3rd : One addition:

In resource json, I don't have a comma at the end! Maybe the parser is confused by the comma?

{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.14/MicrosoftTeams.Localization.schema.json",
  "name.short": "EN",
  "name.full": "EN",
  "description.short": "EN",
  "description.full": "EN",
  "staticTabs[0].name": "EN"**,**  <- I mean this comma
}

**Comment by Steffi3rd** [comment]
@jensker Yes, i have all that. 

I just check with : https://dev.teams.microsoft.com/appvalidation.html

And it seems that my localization en.json and fr.json is missing inside the zip appPackage.production.zip... 
Only icons are uploaded to the zip 

<img width="1031" alt="Capture d’écran 2022-11-04 à 11 58 12" src="https://user-images.githubusercontent.com/814410/199956815-c533894d-c27e-4e02-a45e-7dbe65ace76e.png">

**Comment by jensker** [comment]
@Steffi3rd : Maybe deleting everything in this folder helps?
![image](https://user-images.githubusercontent.com/81486634/199957855-40955354-31c7-4ec8-bfba-526dac54112a.png)

This way, you force Teams Toolkit to actively rebuild manifest json for local, production etc.

**Comment by jensker** [comment]
@Steffi3rd : Also my template folder looks like this:
![image](https://user-images.githubusercontent.com/81486634/199958108-1e2676f6-1f42-4c3c-8a44-97fcb6bff856.png)

I did not do anything special. Files in resources folders are zipped automatically by Teams Toolkit.

**Comment by Steffi3rd** [comment]
Structure is same as you. but [localization].json is not zipped... only icons 🤔

<img width="267" alt="Capture d’écran 2022-11-04 à 12 12 38" src="https://user-images.githubusercontent.com/814410/199959504-b4376149-74b3-4ed0-9513-0cc6ac0b6b58.png">

**Comment by Steffi3rd** [comment]
We see a lot of differences in the Microsoft documentation from one page to another... (Example: Use v1.8 here, use v.1.12 there, 1.13 overthere etc) It's quite complicated to find your way around when you have a bug. Fortunately StackOverflow or people like @jensker are there to help us here.

About additionalLanguages, some indicates `resources/en.json` instead `en.json`
Do you have to add the `defaultLanguage` in `additionalLanguages`? If not where TeamsTooltik found the file himself?

Anyway, thanks @jensker, it works now!!! 🎉

Below the complete solution (for me):
 
- Downgrade to : Teams Toolkit `v4.0.5 `
- Use `v1.12` in manifest.template.json
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
  "manifestVersion": "1.12",
   ...
}
```

- Use `v1.12` in `en.json` and `fr.json`
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.12/MicrosoftTeams.Localization.schema.json",
  ...
}
```
- Put localization files in folder `appPackage/resources` not directly in `appPackage`.
- Finally add `additionalLanguages` with all languages in `localizationInfo`
```
  "localizationInfo": {
    "defaultLanguageTag": "fr",
    "additionalLanguages": [
      {
        "languageTag": "fr",
        "file": "resources/fr.json"
      },
      {
        "languageTag": "en",
        "file": "resources/en.json"
      }
    ]
  },
```

Hope that bug will fix in the last version of TeamTooltik 🤞

**Comment by Steffi3rd** [comment]
We see a lot of differences in the Microsoft documentation from one page to another... (Example: Use v1.8 here, use v.1.12 there, 1.13 overthere etc) It's quite complicated to find your way around when you have a bug. Fortunately StackOverflow or people like @jensker are there to help us here.

About additionalLanguages, some indicates resources/en.json instead en.json
Do you have to add the defaultLanguage in additionalLanguages? If not where TeamsTooltik found the file himself?

Anyway, thanks @jensker, it works now!!! 🎉

Below the complete solution (for me):

Downgrade to : Teams Toolkit v4.0.5
Use v1.12 in manifest.template.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
  "manifestVersion": "1.12",
   ...
}
Use v1.12 in en.json and fr.json
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.12/MicrosoftTeams.Localization.schema.json",
  ...
}
Put localization files in folder appPackage/resources not directly in appPackage.
Finally add additionalLanguages with all languages in localizationInfo
  "localizationInfo": {
    "defaultLanguageTag": "fr",
    "additionalLanguages": [
      {
        "languageTag": "fr",
        "file": "resources/fr.json"
      },
      {
        "languageTag": "en",
        "file": "resources/en.json"
      }
    ]
  },
Hope that bug will fix in the last version of TeamToolkit 🤞

<img width="757" alt="Capture d’écran 2022-11-04 à 12 49 01" src="https://user-images.githubusercontent.com/814410/199965695-38f51691-c01a-439e-8e21-dd9699f9281b.png">

**Comment by Steffi3rd** [comment]
We see a lot of differences in the Microsoft documentation from one page to another... (Example: Use v1.8 here, use v.1.12 there, 1.13 overthere etc) It's quite complicated to find your way around when you have a bug. Fortunately StackOverflow or people like @jensker are there to help us here.

About additionalLanguages, some indicates resources/en.json instead en.json
Do you have to add the defaultLanguage in additionalLanguages? If not where TeamsTooltik found the file himself?

Anyway, thanks @jensker, it works now!!! 🎉

Below the complete solution (for me):

- Downgrade to : Teams Toolkit **v4.0.5**
- Use **v1.12** in `manifest.template.json`
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.12/MicrosoftTeams.schema.json",
  "manifestVersion": "1.12",
   ...
}
```
- Use **v1.12** in `en.json` and `fr.json`
```
{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.12/MicrosoftTeams.Localization.schema.json",
  ...
}
```
- Put localization files in folder `appPackage/resources` not directly in `appPackage`.
- Finally add `additionalLanguages` with all languages in `localizationInfo`
```
{
   ...
  "localizationInfo": {
    "defaultLanguageTag": "fr",
    "additionalLanguages": [
      {
        "languageTag": "fr",
        "file": "resources/fr.json"
      },
      {
        "languageTag": "en",
        "file": "resources/en.json"
      }
    ]
  },
  ...
}
```
Hope that bug will fix in the last version of TeamToolkit 🤞

<img width="757" alt="Capture d’écran 2022-11-04 à 12 49 01" src="https://user-images.githubusercontent.com/814410/199965695-38f51691-c01a-439e-8e21-dd9699f9281b.png">

**Comment by nliu-ms** [comment]
Thank you so much @jensker and @Steffi3rd, I'm so glad that you finally made it!

Sorry for the inconvenience brought to you. With information you provided, that is a bug of Teams Toolkit. During some code migration, the logic of zipping localization file has been removed. So when you downgrade to previous version it works. 

Sorry again! I will fix it ASAP.

**Comment by nliu-ms** [comment]
Hey @jensker , this issue has been fixed and deployed to PROD, there is no need to define at least 2 languages anymore. I will close this issue. Please let me know if you still meet the bug, thanks!
