### ISSUE TITLE
Can't acquire SSO token for full trust apps

### ISSUE THREAD

**Issue by AndrewCraswell** [OfficeDev/TeamsFx#5978]
**Describe the bug**
The `TeamsUserCredential` is failing to return a valid SSO token when calling the `getSSOToken()` function. Our app is a Full Trust app, and when running in Ring 0, we've only been able to retrieve empty tokens (""). With further investigation, we believe the issue is caused here:
https://github.com/OfficeDev/TeamsFx/blob/dev/packages/sdk/src/credential/teamsUserCredential.browser.ts#L336

When `getSSOToken()` calls the `getAuthToken()` method from teams-js, an empty array of resources are being passed. Our thought was that this is sufficient, since our app manifest defines the resource needed (`api://{domain}/{clientId}`). However, it appears that Full Trust apps will not attempt to locate the resource from the manifest, and instead checks what resources are passed to the `getAuthToken()` function. We were able to find this line in the docs:

![image](https://user-images.githubusercontent.com/1908292/187781634-1db23fac-2a39-4c54-86c8-dcdd2809b5e9.png)

We only encountered this behavior after deploying the Full Trust app to Ring 0. Sideloaded apps still appear to be able to find the resource defined in the manifest. Unfortunately, since the `resources` argument is not exposed through the `getSSOToken()` function, we had to clone the `teamsfx` SDK library and make the change and bundle it directly into our app code to verify that passing the proper resource would resolve the issue.

A deeper investigation into the Teams Client code determined that Full Trust apps also require the resource to be expressed as `https://{domain}/{clientId}` rather than using the `api://` scheme. I haven't been able to find any documentation that describes this, so it was a complete surprise.

**Expected behavior**

1. Provide a mechanism for developers to pass the `resources` parameter to the `getSSOToken()` function to unblock Full Trust apps, and enable us to properly fetch SSO tokens.

2. Some documentation should probably be updated to identify that Full Trust apps need to define the resource using the `https://` schema rather than `api://`. I'm not really sure which team should do that, but it probably fits better here:
https://docs.microsoft.com/en-us/microsoftteams/platform/tabs/how-to/authentication/tab-sso-manifest

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version: 4.0.5

**CLI Information (please complete the following information):**
 - OS: Windows
 - Version: ^1.0.0

**Additional context**

This issue is related to this bug I filed some time back:
https://github.com/OfficeDev/TeamsFx/issues/5672

At that time, it seemed TeamsFx was invoking the teams-js SDK correctly. If it's helpful, happy to setup a meeting between our dev team members who performed the research on this issue to add any additional clarity we can.

**Comment by SLdragon** [comment]
Thanks for the feedback, we will discuss it in the meeting~

**Comment by SLdragon** [comment]
Here is the PR to address this issue:
https://github.com/OfficeDev/TeamsFx/pull/6019

**Comment by SLdragon** [comment]
Keep this open since we can track whether teamsjs sdk docs is ready
