### ISSUE TITLE
replyUrlsWithType not correctly deployed [VS Code Teams Toolkit v4.0.5]

### ISSUE THREAD

**Issue by jensker** [OfficeDev/TeamsFx#5997]
**Describe the bug**
In the aad.template.json file, the following parts are not transfered to aad.dev.json (or any other environment):

"replyUrlsWithType": [
		{
			"url": "msal{{state.fx-resource-aad-app-for-teams.clientId}}://auth",
			"type": "InstalledClient"
		},
...
]

**To Reproduce**
1. Enhance aad.dev.json with code from above.
2. Debug or deploy
3. Check aad.dev.json (or your environment)

**Expected behavior**

I expect the url also to be available in aad.dev.json. After deployment, I have to think of manually checking azure portal and add missing url manually. 

Thank you for checking!

**Screenshots**

aad.template.json:
![image](https://user-images.githubusercontent.com/81486634/187932693-8333454a-b994-4eb6-8478-eae4f19cc769.png)

aad.dev.json:
![image](https://user-images.githubusercontent.com/81486634/187932843-68a3de04-cc26-4bf9-a248-fb4c0a11c957.png)

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by SLdragon** [comment]
Hi, @jensker , thanks for reporting this issue.
Seems it is a bug that redirect URL of installedClient type can only start with https://, we will try to fix this bug, and when it ready, will let you know

**Comment by jensker** [comment]
Thank you for considering my defect.

**Comment by SLdragon** [comment]
Hi, @jensker , this bug has been fixed and merged into dev branch, and now it supports redirect URL with custom schema, you can try the latest VSCode Teams Toolkit extension from our daily release page tomorrow: https://github.com/OfficeDev/TeamsFx/releases

**Comment by SLdragon** [comment]
Since the issue has been fixed, I will close it, and if you have any other questions or suggestions, feel free to contact us, thank you!
