### ISSUE TITLE
SDK initialization times out using @microsoft/teamsfx

### ISSUE THREAD

**Issue by mballav** [OfficeDev/TeamsFx#5998]
**Describe the bug**
SDK initialization times out using @microsoft/teamsfx

**To Reproduce**
Please see "Additional Context"

**Expected behavior**
It should return a token.

**VS Code Extension Information (please complete the following information):**
 - OS: macOS
 - Version 12.0.1

**Additional context**
I created a Teams tab application by customizing the SSO react app sample from the Teams toolkit. The application redirects the user to our website (inside one of the tabs). I can grab the id-token in react (```teamsfx.getCredentials().getToken("")```) and pass it to our web application via a query parameter. 

This id-token is validated and then passed around to various microservices that comprise our backend.

This part works well, but then, we had the need to refresh the token. So, we decided for the web application (written in Angular) to fetch the token using @microsoft/teamsfx and @microsoft/teams-js npm packages.

While I am not certain if that is the way to go, when I execute the following code inside an angular service, it throws the "<b>SDK initialization timed out</b>" error.

```
    try {
      const teamsFx: TeamsFx = new TeamsFx(IdentityType.User, {         
        "clientId": "ee89fb47-a378-4096-b893-**********",
        "objectId": "df568fe9-3d33-4b22-94fc-**********",
        "oauth2PermissionScopeId": "4ce5bb24-585a-40d3-9891-************",
        "tenantId": "5d65ee67-1073-4979-884c-**************",
        "oauthHost": "https://login.microsoftonline.com",
        "oauthAuthority": "https://login.microsoftonline.com/5d65ee67-1073-4979-884c-****************",
        "applicationIdUris": "api://localhost/ee89fb47-a378-4096-b893-***************",
        "frontendEndpoint": "https://localhost",
        "initiateLoginEndpoint": "https://localhost:8101"
      });

      const creds = await teamsFx.getCredential().getToken('https://graph.microsoft.com/User.Read');
      const token = creds?.token;

      console.log("New Token: ", token);

      const expirationTimestamp = creds?.expiresOnTimestamp;
      this.scheduleRefresh(expirationTimestamp);
      this.tokenRefreshed.next({ token: token, expiresOnTimestamp: expirationTimestamp });
    }
    catch (error) {
      console.error("Error in getNewTeamsToken(): ", error);
    }
```

Am I missing anything here, or is the approach itself wrong? Please advise.

Btw, Here is the version information about the installed npm packages:
-     "@microsoft/teams-js": "^2.2.0",
-     "@microsoft/teamsfx": "^1.1.1",
-     "@azure/msal-browser": "^2.28.1"

**Comment by yiqing-zhao** [comment]
Hello @mballav, "SDK initialization timed out" error is reported by teams-js library, and when the initialize function of teams-js runs more than 5s, it will throw the timeout error. I am not able to reproduce the error from my side. However, @microsoft/teamsfx@1.1.1 requires @microsoft/teams-js@1.9.0 as peer dependency. Could you please provide more context about the code usage so that I can reproduce the error?

**Comment by mballav** [comment]
Hi @yiqing-zhao, Two questions:
- Can this timeout be increased via configuration?
- I have a hunch that my "initiateLoginEndpoint" value is incorrect. I could not find it inside my Teams App's config files. I copied the rest of the parameters from one of the config files. Could you please tell me what should be "initiateLoginEndpoint"'s value and why it is not necessary to specify inside the react-app, and why it is compulsory to provide a value for it when using the teamsfx package in angular?

Thanks a lot in advance!

**Comment by yiqing-zhao** [comment]
Hi @mballav, for the first question, I'm afraid the time cannot be increased, see the source code [here](https://github.com/OfficeDev/microsoft-teams-library-js/blob/5bbc69cd8addc10adc569e4f652573c3141367ff/packages/teams-js/src/public/app.ts#L535). 

For the second question, TeamsFx reads the value of `initiateLoginEndpoint` by using [loadFromEnv()](https://github.com/OfficeDev/TeamsFx/blob/46663f250eb40b4bc31a6c8968bd833919e476da/packages/sdk/src/core/teamsfx.browser.ts#L49). Typically, if you scaffold a teams tab app with Teams Toolkit, and do local debug (F5), you will find the value of `initiateLoginEndpoint` in `./tabs/.env.teamsfx.local` file as `REACT_APP_START_LOGIN_PAGE_URL=https://localhost:53000/auth-start.html`. The `auth-start.html` and `auth-end.html` refers to `auth-start.html` and `auth-end.html` under `./tabs/public`. 

`initiateLoginEndpoint` is required for SSO. If you did not specify it from the manual configuration, the react app will read from the environment variable (Teams Toolkit will scaffold `.env.teamsfx.local` for the user during local debug, which includes `REACT_APP_START_LOGIN_PAGE_URL` if SSO is enabled). If neither manual configuration nor the environment variable is provided, TeamsFx will throw an error.

**Comment by mballav** [comment]
Thanks, @yiqing-zhao for the clarification. I updated the ```initiateLoginEndpoint``` and tried the code out. Unfortunately, It still throws the same error. Could you try out my code sample at your end?

**Comment by yiqing-zhao** [comment]
Hi @mballav, could you check if you are running your code in teams? This might cause the timeout issue. Another reason might be due to debug session, in which the code gets stuck at some point. Could you please provide a detailed version of error message? The code looks good from my side.

I would also suggest changing the version of Teams JS or TeamsFx. Since TeamsFx@1.x lists Teams-JS@1.x as peer dependency. If you prefer to use Teams-JS@2.x, you could use TeamsFx@2.0.0-beta.0.
