### ISSUE TITLE
Deploy Teams App in Azure Tenant which not equals users (aad app) tenant

### ISSUE THREAD

**Issue by toellbe** [OfficeDev/TeamsFx#6009]
I wanted to deploy Teams app in an Azure tenant that is different from the tenant of the AAD App. 

I registered the AAD app manually in the user tenant and adjusted the config.dev.json as described at https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/using-existing-aad.md.

`"auth": {
  "objectId": **Object ID**,
  "clientId": **Application (client) ID**,
  "clientSecret": {{ $env.AAD_APP_CLIENT_SECRET }},
  (optional) "accessAsUserScopeId": **Access As User Scope ID**
}`

But now I get the error message that the AAD app cannot be found in the tenant of the Azure resources. How or where can I explicitly specify the tenant of the AAD app?

`[Error] - code:aad.AadGetAppError, message: Failed to get AAD app with Object Id "xxxxxx-xxxxxxx-xxxxxx" in tenant "xxxxxx-xxxxxxx-xxxxxx". Please make sure the object id is valid, or delete 'objectId' under fx-resource-aad-app-for-teams in state.dev.json and try again. Detailed error: Request failed with status code 404. Reason: Resource 'xxxxxx-xxxxxxx-xxxxxx' does not exist or one of its queried reference-property objects are not present.`

**Comment by KennethBWSong** [comment]
Hi @toellbe Thank you for reporting this issue. Now Teams Toolkit will create/update AAD app with the M365 account you are using in the tool. When providing existing AAD app, Teams Toolkit will look for the app in the same tenant as your M365 account and will throw the above error if no app with the object id exists. Please make sure that the M365 account you login is under the same tenant as the AAD app you provided.
