### ISSUE TITLE
Microsft Graph (sendactivitynotification) not working for seding the specific user

### ISSUE THREAD

**Issue by hiennguyen2018** [OfficeDev/TeamsFx#6067]
Hi Team,

I got the following error when I create a new task in the Team and send activity notification to the assigned user, but I can send  successfully activity notification for the Channel.

 _"message": "Application with AAD App Id '{AppId}' is not authorized to generate custom text notifications about '/beta/teams/{TeamId}/Microsoft.Teams.GraphSvc.sendActivityNotification' to the recipient. Ensure that the expected Teams app is installed in the target scope (user, team, or chat).",_

**To Reproduce**
1. Create the Custom App
2. Config for the App
3. Use Postman to send activity notification

<img width="335" alt="Permission-01" src="https://user-images.githubusercontent.com/44386157/189301410-96c306ec-c486-4bb1-a845-8a8056bedc72.png">

Use Postman to send activity notification for user-> get error above
<img width="517" alt="Send-User-01" src="https://user-images.githubusercontent.com/44386157/189301791-0d8c1b36-dde7-4f9c-85cb-c3fc12306f51.png">

Use Postman to send activity notification for channel -> successfull
<img width="679" alt="Send-Channel-01" src="https://user-images.githubusercontent.com/44386157/189301909-e36b79fb-95ab-4ac9-92b2-0afd9bdcbbd8.png">

Scopes in Manifest file
<img width="863" alt="Manifest-01" src="https://user-images.githubusercontent.com/44386157/189302164-5b63ca60-4920-4428-8ee9-8a2d988caa25.png">

Thank you for you reviewing.

**Comment by ChoOo7** [comment]
Please, can you share what was the problem please ?
