### ISSUE TITLE
Feedback Email Address does not work

### ISSUE THREAD

**Issue by ThomasPe** [OfficeDev/TeamsFx#6232]
**Describe the bug**
I just wanted to let you know that the feedback email address ttkfeedback@microsoft.com in the readme does not accept emails from presumably outside Microsoft. I sent an email from my @outlook.com address wanting to thank the team as I've finished my first app with your toolkit, but it got rejected immediately. Thought you might want to know. :)

**Comment by sffamily** [comment]
We've updated the setting to confirm it can now take external emails. It may take a while to take effect.

@ThomasPe please wait a little and give it a try. Let us know if it gets rejected again.

**Comment by ThomasPe** [comment]
Seems to still get rejected. And the error response includes the email addresses where it should have been redirected. 🧐

**Comment by ThomasPe** [comment]
FYI email still returns an error for two redirect addresses, one is I assume @pierceboggan.
