### ISSUE TITLE
teamsfx.login popup blank

### ISSUE THREAD

**Issue by AnthonyPhan** [OfficeDev/TeamsFx#6255]
**Describe the bug**
When calling the teamsfx.login() button the login button will sometimes appear blank for some Teams users. 
Very much like #5609 

**To Reproduce**
The issue is hard to reproduce but common among a large user base. 

**Expected behavior**
The login popup should display a login or consent window.

**Additional context**
This occurs for probably 30% of our users but we are unable to reproduce it. User have screen shared with us and shown us the blank popup. When the popup is closed an error message of "Consend cancelled" is thrown.

**Comment by KennethBWSong** [comment]
Hi @AnthonyPhan Thank you for using our toolkit! Would you please follow the [instruction](https://github.com/OfficeDev/TeamsFx/tree/dev/packages/fx-core/templates/plugins/resource/aad/auth/bot#login-page-does-not-pop-up-after-clicking-continue) first to see whether your problem can be fixed?
