### ISSUE TITLE
Visual Studio 2022 Teams Toolkit - Are the docs there (yet)?

### ISSUE THREAD

**Issue by Expecho** [OfficeDev/TeamsFx#6440]
I've installed the Visual Studio 2022 Teams Toolkit with the plan to write a bot using C#. So far so good, the template gets me up and running quickly. In my bot I want to use Microsoft Graph to fetch calendar data for the logged in user using the toolkit as it promises to make it easy to address such a scenario.

But now it seems examples are not really geared towards the use of the VS 2022 Teams Toolkit with C#.  

- The [docs](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/add-single-sign-on) regarding SSO only mention the VS Code toolkit or the javascript/TS based cli.
- There are pointer to the Bot Framework examples at https://github.com/microsoft/BotBuilder-Samples but they don't use the Teams Toolkit.

Are there any C# docs/samples that explain how to use the Teams Toolkit for VS 2022 for access the graph api using a bot?

**Comment by KennethBWSong** [comment]
Hi @Expecho Thank you for using our toolkit. Support on adding SSO to VS projects is now under preview and will release on VS 17.4. 
To better help you with this issue, we want to first confirm the version of your Visual Studio. Would you please go to 'Help' and click on `About Microsoft Visual Studio` and check your version like below?
![image](https://user-images.githubusercontent.com/63089166/197146737-8dd423b6-6f1e-4c41-8d0c-fde9c5b7c7bd.png)

**Comment by KennethBWSong** [comment]
@Expecho Sure, you can go [here](https://visualstudio.microsoft.com/en-us/vs/preview/#download-preview) to get the latest preview version for VS.

After installing, you can open your project and simply right click on your project, choose `Teams Toolkit`, and select `Add authentication code` to enable SSO in your project.
![image](https://user-images.githubusercontent.com/63089166/197150367-67c7ae15-6d90-41fa-9b7c-3700e3a4ff40.png)
You can refer to the [README for bot](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/fx-core/templates/plugins/resource/aad/auth/bot/README.txt) for detailed info. We will also automatically open this Readme when the command successfully run.
