### ISSUE TITLE
Bug report: not able to start debugging app

### ISSUE THREAD

**Issue by Kolinas** [OfficeDev/TeamsFx#6443]
**Describe the bug**

I've installed the Visual Studio Teams Toolkit to run and debug the existing app. But when I try to run the application build fails with the message "Failed to npm install for frontend" and with the following error: "[Error] - code:Ext.PrerequisitesValidationError, message: Prerequisites Check Failed. If you wish to bypass checking and installing any prerequisites, you can disable them in Visual Studio Code settings. Please check the output panel to see the details."
Any suggestions on how to fix this issue?
Thanks in advance.

**Expected behavior**
I should be able to start debugging the application

**Screenshots**
![image](https://user-images.githubusercontent.com/45821242/197149703-5cd6e8d4-2cf2-4a8a-85b1-92af562885dc.png)

**VS Code Extension Information (please complete the following information):**
 - OS:  Windows 10 
 - Version 22

**CLI Information (please complete the following information):**
 - OS: Windows 10 
 - Version: ![image](https://user-images.githubusercontent.com/45821242/197150159-c84f8fa6-2acc-4f8e-adda-832de161f430.png)

**Comment by kuojianlu** [comment]
@Kolinas This error message shows that `npm install` failed for tab app. You can check `TERMINAL` window to see the error details of `npm install` command.

**Comment by Kolinas** [comment]
> @Kolinas This error message shows that `npm install` failed for tab app. You can check `TERMINAL` window to see the error details of `npm install` command.

Run of "npm install" separately works without any problems

**Comment by kuojianlu** [comment]
@Kolinas If so, you can unblock debugging by commenting `validate local prerequisites` task from `Pre Debug Check & Start All` in `.vscode/tasks.json` then try to debug again.
![image](https://user-images.githubusercontent.com/37978464/197667575-b8710feb-3e0d-4421-9a68-b2086949beff.png)
