### ISSUE TITLE
security issue: @microsoft/teamsfx-cli depends on adal-node which depends on xmldom version with security vulnerability

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/TeamsFx#6485]
see: https://github.com/Azure/ms-rest-nodeauth/issues/146#issuecomment-1280211322

**Comment by Alive-Fish** [comment]
Hi @JensMadsen, thanks for reporting it. I have checked the [package-lock.json](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/cli/package-lock.json) in the source code and cannot find the `adal-node` dependency.

Do you mean the latest published [@microsoft/teamsfx-cli](https://www.npmjs.com/package/@microsoft/teamsfx-cli)? If yes, I will reply to you when the new version has been published.

**Comment by JensMadsen** [comment]
Hi @Alive-Fish. You are right. Sorry about the noise. I was told by your colleagues to report it here but it turns out that it is the package that uses an old version see https://github.com/OfficeDev/Office-Addin-Scripts/blob/e9cd6b6456c7b79621e5d4c07206e6cc1ab47df9/packages/office-addin-dev-settings/package.json#L25. Sorry about the noise and sorry for not checking it properly! I close the issue
