### ISSUE TITLE
bug report: SPFx.SPFxScaffoldError

### ISSUE THREAD

**Issue by hoangtd1706** [OfficeDev/TeamsFx#6623]
Failed to run command: "yo <REDACTED: user-file-path>@<REDACTED: user-file-path> --skip-install true --component-type webpart --component-name helloworld --environment spo --skip-feature-deployment true --is-domain-isolated false --framework react --solution-name Ecoba Approval", code: "1",
                            output: "", error: "<REDACTED: user-file-path>:27
	const [name, version] = nameMap.get(release)

**Comment by HuihuiWu-Microsoft** [comment]
Hi @hoangtd1706 , this should be the same issue with https://github.com/yeoman/yo/issues/75 if you're using latest macOS version. 
To make it work, you can downgrade to legacy version. We'll fix the issue once yo released the fix build.

**Comment by HuihuiWu-Microsoft** [comment]
Hi @hoangtd1706, this has been fixed in https://github.com/OfficeDev/TeamsFx/pull/7283. Please help verify and feel free to reopen if you still have the issue.

**Comment by hoangtd1706** [comment]
Thanks for the support! 🥳
