### ISSUE TITLE
{{$env.MA_VARIABLE}} empty

### ISSUE THREAD

**Issue by Steffi3rd** [OfficeDev/TeamsFx#6640]
**Describe the bug**
I'm trying to use a custom environnement variable for each environnment. 

**To Reproduce**
1. I created` .env.production` with a FOO=bar in root folder next to `.fx` folder
2. Then use it in my files (`manifest.template.json` and `aad.template.json`) like this {{$env.FOO}} (Example found here : https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code#referencing-environment-variables-in-parameter-files)
3. Then build 
4. The value is empty on build in `manifest.json`

**Expected behavior**
{{$env.FOO}} should not be empty. It should be filled like {{state.___}} and {{config.___}} do.

**Comment by nliu-ms** [comment]
Hey @Steffi3rd , currently only parameter files supports .env customization. To customize `manifest.template.json` and `aad.template.json`, we suggest to use {{config.xx}}, as described in this doc: https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview-and-customize-app-manifest?pivots=visual-studio-code#customize-your-teams-app-manifest

We will have a new version which supports environment variables, will be released at the end of this year. Hope it helps!

**Comment by Steffi3rd** [comment]
@nliu-ms Thanks for you reply.

I tried but I have this error

**Comment by nliu-ms** [comment]
This issue can be released now as Teams Toolkit v5.0.0 will support .env files.
