### ISSUE TITLE
sideloading check failed

### ISSUE THREAD

**Issue by thanhnguyen0504** [OfficeDev/TeamsFx#6724]
Today, when I sign-in to Teams Tookit, I received the message: sideloading check failed
![image](https://user-images.githubusercontent.com/56904041/200800937-5c026aac-2863-4117-9d00-e5e6767e47d3.png)

Base on the document : https://learn.microsoft.com/en-us/microsoftteams/platform/m365-apps/prerequisites#prepare-a-developer-tenant-for-testing

I checked and found that the Upload custom apps was enabled:
![image](https://user-images.githubusercontent.com/56904041/200802976-d43dc022-0277-482f-a3ab-33619870eec9.png)

When I tried to start the application locally. There's an error occurred:

[AppStudioPlugin.DeveloperPortalAPIFailed]: API call to Developer Portal failed: Error, Request failed with status code 503, Request path: POST /api/appdefinitions/v2/import?teamstoolkit=true&overwriteIfAppAlreadyExists=false, X-Correlation-ID: undefined. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: "<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'><html xmlns='http://www.w3.org/1999/xhtml'><head><meta content='text/html; charset=utf-8' http-equiv='content-type'/><style type='text/css'>body {{font-family:Arial; margin-left:40px; }}img  {{ border:0 none; }}#content {{ margin-left: auto; margin-right: auto }}#message h2 {{ font-size: 20px; font-weight: normal; color: #000000; margin: 34px 0px 0px 0px }}#message p  {{ font-size: 13px; color: #000000; margin: 7px 0px 0px0px}}#errorref {{ font-size: 11px; color: #737373; margin-top: 41px }}</style><title>{0}</title></head><body><div id='content'><div id='message'><h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p></div><div id='errorref'><span>Ref A: 630A1476D62543F2BDE259D995380605 Ref B: SGN30EDGE0513 Ref C: 2022-11-09T09:24:53Z</span></div></div></body></html>"

The issue blocked my team. Please support to solve the issue.

**Comment by nliu-ms** [comment]
Hey @thanhnguyen0504 , this issue has same root cause with https://github.com/OfficeDev/TeamsFx/issues/6723. And this issue should have been mitigated now. Please let me know if you still meet this error.
