### ISSUE TITLE
Import Custom App Fails to add Enterprise App registration - app fails to run

### ISSUE THREAD

**Issue by bemokraig** [OfficeDev/TeamsFx#6751]
**Describe the bug**
In the past week roughly deployment of a custom app to a test tenant / teams failed and continues to fail today.  The app fails to initialize.  It does not register an enterprise app in the tenant.

This has nothing to do with any code in the app but seems to be init.  Web Sockets are enabled.

**To Reproduce**

Create a new Teams App Tab from Visual Studio 2022 template
Deploy
Go to test tenant Admin.Teams...
Upload new App
Go to Teams
Add new App
Blazor Error (reload) appears
Browser Console shows0.2-angular-jquery.min-14969ec.js:114 
        
       2022-11-10T13:50:21.858Z AUTHMSAL: Event: adal:tokenRenewFailure, code: invalid_resource|AADSTS500011: The resource principal named api://<app service>.azurewebsites.net/<id> was not found in the tenant named BEMO Sandbox. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
action: resourceDisabled

Check for Enterprise App - none exists

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by bemokraig** [comment]
Repro'd with two tenants not associated with our tenant so not a local issue.

**Comment by KennethBWSong** [comment]
Hi @bemokraig Thank you for using our Toolkit. I want to ask a few questions to help us better understand your problem.
1. Which version of VS are you using now? You can go to 'help' -> 'About Visual Studio' to check your version.
2. Would you please check whether Azure AD app is successfully created when provision? You can go to `.fx/states/state.{env}.json` and find related info in 'fx-resource-aad-app-for-teams'

**Comment by bemokraig** [comment]
Thanks for the reply.  This is a very critical issue for me as I am unable to test deployment to customer tenants and am approaching a release date.  We are a Microsoft MSP reseller.

2 Versions Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.3.6
Version 17.4

There is a problem in the Admin.Teams Manage Apps area.
My app checks for consent required (as do a templates) and that worked until this last week.
That stopped working, the app never runs because the Enterprise App is not registered.

I saw new documentation saying the Teams Admin had to approve in Admin.Teams so I attempted to do that but it has never worked.  Granting Permissions fails.

I have tried this with different source tenants and customer tenants.

Repro Steps

Create a new Teams App from Tab Template.
It is built, provisioned and deployed to Tenant A, it runs just fine

It is uploaded to Tenant B via Admin.Teams Manage Apps Upload app

I click on Permissions and Grant Admin permissions
              I used to get a generic failure message (something went wrong)
              Now I get this during the login process
              Request Id: 2628e14c-ab77-4657-8422-074580311800
Correlation Id: 00000000-0000-0000-0000-000000000000
Timestamp: 2022-11-15T16:26:53Z
Message: AADSTS90015: Requested query string is too long.


Test Tenant
***@***.***


Kraig Rury | Principal Software Development Manager
Microsoft Alumni
|425.616.0802

**Comment by KennethBWSong** [comment]
@bemokraig Do you mean that your app works well in the tenant same as your M365 account and just fail in other tenants?
In this scenario, you need to follow the [steps](https://github.com/OfficeDev/TeamsFx/wiki/Multi-tenancy-Support-for-Azure-AD-app) to use multi-tenant AAD app.

**Comment by bemokraig** [comment]
This has resolved the issue, I re-provisioned the app and did not manually update it.  Thanks for the help.
