### ISSUE TITLE
Port 53000 already in use

### ISSUE THREAD

**Issue by jerome-pialot** [OfficeDev/TeamsFx#6894]
I sometimes encounter a blocking issue while trying to launch my application in debugguing mode with vs code, where prerequisits check locks on "port 53000 already in use".
I find no process using tcp port 53000.

Looking onto all forum and discussions, i found a solution that works for me: reset NAT windows service 

>net stop winnat
>net start winnat

**Comment by kuojianlu** [comment]
@jerome-pialot From your solution, I guess the port 53000 has been already used by winnat. Actually, you can use another port instead of 53000 in Teams Toolkit to solve "Port 53000 already in use". Follow the steps:
1. Update the port in `baseUrl` arg in "Set up Tab" task in `.vscode/tasks.json`, e.g., using **53001**:
```json
{
    "label": "Set up Tab",
    "type": "teamsfx",
    "command": "debug-set-up-tab",
    "args": {
        "baseUrl": "https://localhost:53001"
    }
},
```
2. Update the `ports` arg in `Validate & Install prerequisites` task in `.vscode/tasks.json`, e.g., using **53001**:
```json
{
    "label": "Validate & Install prerequisites",
    "type": "teamsfx",
    "command": "debug-check-prerequisites",
    "args": {
        "prerequisites": [
            "nodejs",
            "m365Account",
            "devCert",
            "ports"
        ],
        "ports": [
            53001 // tab service port
        ]
    }
},
```
3. F5 again.

**Comment by jerome-pialot** [comment]
Hello, 
Thank you for the information. I think it could help.
The only process that is using port 53000 on my PC is VS Code with Teams Fx extension.
I guess there is quite something wrong sometimes when we stop PC without ending the debug session...with winnat.
So perhaps something to investigate.

**Comment by kuojianlu** [comment]
@jerome-pialot Can you always reproduce this issue if you stop PC without ending the debug session? Normally, when we stop PC, the VS Code will be closed, and the running tasks will be terminated, then the port will be released. It is strange that the port is still occupied after PC is restarted.

**Comment by jerome-pialot** [comment]
To be honest I don't know about the exact scenario, but my feeling is that is linked to exit from VS Code without ending correctly the debugguing session.
The point is that I encountered this issue several times, and it's very annoying because there is no much information about how to deactivate checks with Teams Fx and/or how to configure the default listening port (until now :-)). .. and I was very very upset because of that: don't be able to debug because of already used port that, in fact, is not used.

**Comment by kuojianlu** [comment]
@jerome-pialot Sorry for the inconvenience :(. If you do not need the ports checking logic, you can remove `ports` from `Validate & Install prerequisites` task, like
```json
{
    "label": "Validate & Install prerequisites",
    "type": "teamsfx",
    "command": "debug-check-prerequisites",
    "args": {
        "prerequisites": [
            "nodejs",
            "m365Account",
            "devCert"
        ],
},
```
Then Teams Toolkit will not block the debugging even if the ports are already used. (See https://github.com/OfficeDev/TeamsFx/wiki/%7BDebug%7D-Teams-Toolkit-VS-Code-Tasks to know more about how to customize the `tasks.json`)

Close this issue as this case is very corner and can be solved with the above solutions. Feel free to let me know if you have any other questions.

**Comment by gen-ass** [comment]
@jerome-pialot your option still works best to reset the port: 
**net stop winnat
net start winnat**

**Comment by kale1d0code** [comment]
I have this problem.
When ever attempting to run a test,
it will lock the previous port and open another
