### ISSUE TITLE
teams calling graph api working in webapp but not in desktop

### ISSUE THREAD

**Issue by Githamza** [OfficeDev/TeamsFx#6974]
The sso is working well , 
but when I call graph api using :

```
export default function meetingInfos(graph: Client): Promise<IMeetingInfos> {
  alert("graph" + JSON.stringify(graph));
  return new Promise((resolve, reject) => {
    try {
      microsoftTeams.getContext(async (context) => {
        try {
          let meeting;
          try {
            meeting = await graph.api(`/chats/${context.chatId}`).get();
          } catch (error) {
            alert("alert:****" + error);
          }
          alert(" meeting infos" + meeting);
          const meetingInfos = await graph
            .api(
              `https://graph.microsoft.com/beta/me/onlineMeetings?$filter=joinWebUrl eq '${meeting.onlineMeetingInfo.joinWebUrl}'`
            )
            .get();
          console.log(meetingInfos);

          resolve(meetingInfos);
        } catch (error) {
          alert(error);
          reject(error);
        }
      });
    } catch (error) {
      console.error(" error", error);
    }
  });
```

I get error 
`alert:****Error: Failed to get access token cache silently, please login first: you need login first before get access token.`

When I login on web app with the same user the api call works well

I tried to logout then login in the desktop app : no fix
Remove cache : `rm -r ~/Library/Application\ Support/Microsoft/Teams`

Uninstall teams et reinstall it : nothing.

In app registration tab I have theses authorized apps ids : 

```
4345a7b9-9a63-4910-a426-35363201d503
4765445b-32c6-49b0-83e6-1d93765276ca
0ec893e0-5785-4de6-99da-4ed124e5296c
bc59ab01-8403-45c6-8796-ac3ef710b3e3
00000002-0000-0ff1-ce00-000000000000
d3590ed6-52b3-4102-aeff-aad2292ab01c
5e3ce6c0-2b1f-4285-8d4b-75ee78787346
1fec8e78-bce4-4aaf-ab1b-5451cc387264
```

**Comment by blackchoey** [comment]
@Githamza can you create a new `SSO-enabled tab` project and see whether the project can successfully call Graph API (the code calls Graph API to show your profile) in desktop app?

`Failed to get access token cache silently` message means the SDK failed to acquire a cache in browser's session storage and also cannot login the user silently. Here's the logic FYI: https://github.com/OfficeDev/TeamsFx/blob/dev/packages/sdk/src/credential/teamsUserCredential.browser.ts#L208-L272

**Comment by tnsholding** [comment]
Facing the exact same issue. 

Any update on cause or resolution?

**Comment by blackchoey** [comment]
@tnsholding can you create a new `SSO-enabled tab` project and see whether the project works?

This error means the app cannot login users silently, so you need to write some code to login users in this case.

**Comment by Githamza** [comment]
Thanks for the reply , I'll try to Crete another project . 

What I don't understand is that on localhost usegraph hook is able to get the token silently and I get my data, 
It does not work only when I deploy on dev environment. 
I have debugged the user-browser.ts ( not sure about the name ) and I notice that account variable is null ( getaccount function return null ) I feel that the problem is that data is not getting set on session storage .

**Comment by Githamza** [comment]
I notice that 

  const account = this.msalInstance!.getAccountByUsername(this.loginHint!);

Returns null , 

But in localhost it returns the profile object

**Comment by Githamza** [comment]
Update : 
Actually on dev environment it's working ( on web browser ,I haven't assigned and consent the permission for the dev env azure app) 
But in desktop app I have always the same problem: can't get token silently

**Comment by blackchoey** [comment]
Can you share whether `SSO-enabled tab` works in your desktop? I wasn't able to repro this issue in my side. If you could provide some repro steps, that would be helpful.

For your finding that `this.msalInstance!.getAccountByUsername(this.loginHint!);` returns null, we're working with MSAL to figure out the root cause, you can watch this issue for updates: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5617

By the way, it's suggested to add login logic when this kind of error happens. Because there may be many reasons that prevents the code to get token silently (e.g. cached token expired and cannot silent login the account). This should be able to workaround your issue.

**Comment by tnsholding** [comment]
Seems the same as the issue I reported(?):
https://github.com/OfficeDev/TeamsFx/issues/7808

Even when granting admin consent, the desktop app does NOT allow to get a token, but the browser version does.
