### ISSUE TITLE
Can't launch Custom meeting app in teams web version

### ISSUE THREAD

**Issue by Githamza** [OfficeDev/TeamsFx#6975]
I have added my custom app to a meeting 

When I launch the meeting in desktop app I get the app icon

<img width="430" alt="image" src="https://user-images.githubusercontent.com/11578288/203757368-a86b7afc-8338-49f6-8c4d-07a4dbaafed0.png">

but when I use the web app in chrome or edge : 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/11578288/203757534-408e2d00-dbab-4959-903d-78a6814faf3e.png">

I don't find the app Icon and I can't add one .

I'm using the same user in both cases

That was working days ago ...

**Comment by jidddddd** [comment]
The browser client currently doesn't have the add app button, but we are actively working on improving the meeting app debugging experience.
