### ISSUE TITLE
Developer section doesn't change in manifest file

### ISSUE THREAD

**Issue by biogenez** [OfficeDev/TeamsFx#6986]
**Describe the bug**
Developer section didn't changed in the environment manifest file

**To Reproduce**
1. Create new teams app with bot
2. Open file: manifest.template.json
3. Change any information in the "developer" section (e.g. name, websiteUrl etc.)
4. Save file
5. Press F5. 
6. Open generated file /build/appPackage/manifest.local.json
7. Check developer section. Changes from step 3 are not applied.

**Expected behavior**
Developer section in the generated file (manifest.local.json) should be changed according to the data from manifest.template.json file

**Screenshots**
<img width="1861" alt="image" src="https://user-images.githubusercontent.com/4600781/203947439-96a088dd-a258-495d-9744-9fe86b97536b.png">

**VS Code Extension Information (please complete the following information):**
 - OS: OSX (Ventura 13.0.1)
 - Version: v4.1.3

**Comment by nliu-ms** [comment]
Hey @biogenez , sorry for the inconvenience. You're right, the issue has been fixed but not released. We will have a release around middle of December. Thanks!

**Comment by nliu-ms** [comment]
The fix has been released in v4.2.0, so close this issue. Thank you.
