### ISSUE TITLE
 Microsoft.Bot.Builder.Integration.AspNet.Core not found

### ISSUE THREAD

**Issue by AlperSL** [OfficeDev/TeamsFx#6987]
**Describe the bug**
I am following the steps to create a sample Message Extension using Visual Studio 2022. 
Several packages are not found. 

Error	NU1101	Unable to find package Microsoft.Bot.Builder.Integration.AspNet.Core. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages	MyTeamsApp3	
Error	NU1101	Unable to find package Microsoft.Bot.Builder. No packages exist with this id in source(s): Microsoft Visual Studio 
Error	NU1101	Unable to find package Microsoft.AspNetCore.Authentication.JwtBearer. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages	MyTeamsApp3	

**To Reproduce**
1. After completing the "Prepare App Dependencies" step in the tutorial.
2. Click on F5

**Expected behavior**
It should continue debugging. 

**Screenshots**
I am seeing this errors. 
Error	NU1101	Unable to find package Microsoft.Bot.Builder.Integration.AspNet.Core. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages	MyTeamsApp3	
Error	NU1101	Unable to find package Microsoft.Bot.Builder. No packages exist with this id in source(s): Microsoft Visual Studio 
Error	NU1101	Unable to find package Microsoft.AspNetCore.Authentication.JwtBearer. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages	MyTeamsApp3	

**VS Code Extension Information (please complete the following information):**
 - OS: Windows11

**Additional context**

**Comment by JerryYangKai** [comment]
Hi @AlperSL, I suggest adding a nuget.config file to the solution directory, it will resolve the issue.
The content is

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
