### ISSUE TITLE
Teams toolkit try to get the first HTTPS URL from http://127.0.0.1:4040 and failed.

### ISSUE THREAD

**Issue by ITAndy23** [OfficeDev/TeamsFx#7053]
**Describe the bug**
Failed to start local tunnel service.
Failed to find the tunnel endpoint. Teams toolkit try to get the first HTTPS URL from http://127.0.0.1:4040 and failed.

**To Reproduce**
1. Go to 'Teams Toolkit extension'
2. Click on 'Create a new Teams app'
3. Select 'Initiate sequential workflows'
4. Select 'typescript'
5. Select folder
6. Enter app name
7. Wait for Scaffolding to complete
8.  Press F5 to begin debug mode

**Expected behavior**
The bot should open up in debug mode per this video:
https://www.youtube.com/watch?v=rQIXOo0BevM&t=300s

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version 21H2
Visual Studio Code: 1.73.1

**CLI Information (please complete the following information):**

**Additional context**
Error in VS Code Terminal:
Starting local tunnel service.

C:\Users\user\.fx\bin\ngrok\node_modules\ngrok\bin\ngrok http 3978 --log=stdout --log-format=logfmt

t=2022-12-01T09:47:26-0500 lvl=info msg="no configuration paths supplied"
t=2022-12-01T09:47:26-0500 lvl=info msg="ignoring default config path, could not stat it" path=C:\\Users\\user/.ngrok2/ngrok.yml err="CreateFile C:\\Users\\user/.ngrok2/ngrok.yml: The system cannot find the path specified."
t=2022-12-01T09:47:26-0500 lvl=info msg="starting web service" obj=web addr=127.0.0.1:4040
t=2022-12-01T09:47:26-0500 lvl=eror msg="failed to reconnect session" obj=csess id=81d11d8b3835 err="dial tcp: lookup tunnel.us.ngrok.com: no such host"
t=2022-12-01T09:47:26-0500 lvl=eror msg="failed to reconnect session" obj=csess id=81d11d8b3835 err="dial tcp: lookup tunnel.us.ngrok.com: no such host"
t=2022-12-01T09:47:35-0500 lvl=info msg=start pg=/ id=97352b6f8293b8d4
t=2022-12-01T09:47:35-0500 lvl=info msg=end pg=/ id=97352b6f8293b8d4 status=302 dur=1.0118ms
t=2022-12-01T09:47:35-0500 lvl=info msg=start pg=/inspect/http id=63d6f4b9a8bb191f
t=2022-12-01T09:47:35-0500 lvl=info msg=end pg=/inspect/http id=63d6f4b9a8bb191f status=200 dur=0s
t=2022-12-01T09:47:37-0500 lvl=eror msg="failed to reconnect session" obj=csess id=81d11d8b3835 err="read tcp 10.64.101.46:56978->3.133.228.214:443: i/o timeout"
t=2022-12-01T09:47:45-0500 lvl=info msg=start pg=/ id=05ca0c982c920970
t=2022-12-01T09:47:45-0500 lvl=info msg=end pg=/ id=05ca0c982c920970 status=302 dur=0s
t=2022-12-01T09:47:45-0500 lvl=info msg=start pg=/inspect/http id=0e1cbd4b2d5b954f
t=2022-12-01T09:47:45-0500 lvl=info msg=end pg=/inspect/http id=0e1cbd4b2d5b954f status=200 dur=538.5µs
t=2022-12-01T09:47:48-0500 lvl=eror msg="failed to reconnect session" obj=csess id=81d11d8b3835 err="read tcp 10.64.101.46:56988->3.20.27.198:443: i/o timeout"
t=2022-12-01T09:47:50-0500 lvl=eror msg="failed to reconnect session" obj=csess id=81d11d8b3835 err="resolved tunnel.us.ngrok.com has no records"
t=2022-12-01T09:47:53-0500 lvl=eror msg="failed to reconnect session" obj=csess id=81d11d8b3835 err="dial tcp: lookup tunnel.us.ngrok.com: no such host"
t=2022-12-01T09:47:55-0500 lvl=info msg=start pg=/ id=e55f24cbd18916e3
t=2022-12-01T09:47:55-0500 lvl=info msg=end pg=/ id=e55f24cbd18916e3 status=302 dur=1.0002ms
t=2022-12-01T09:47:55-0500 lvl=info msg=start pg=/inspect/http id=dfafd0f599d057f5
t=2022-12-01T09:47:55-0500 lvl=info msg=end pg=/inspect/http id=dfafd0f599d057f5 status=200 dur=0s
t=2022-12-01T09:48:05-0500 lvl=info msg=start pg=/ id=fb60f33afe4d5438
t=2022-12-01T09:48:05-0500 lvl=info msg=end pg=/ id=fb60f33afe4d5438 status=302 dur=0s
t=2022-12-01T09:48:05-0500 lvl=info msg=start pg=/inspect/http id=85f34d777aa3163c
t=2022-12-01T09:48:05-0500 lvl=info msg=end pg=/inspect/http id=85f34d777aa3163c status=200 dur=0s
t=2022-12-01T09:48:07-0500 lvl=eror msg="failed to reconnect session" obj=csess id=81d11d8b3835 err="read tcp 10.64.101.46:57041->3.136.132.147:443: i/o timeout"
t=2022-12-01T09:48:15-0500 lvl=info msg=start pg=/ id=1cfcceef9024c4e5
t=2022-12-01T09:48:15-0500 lvl=info msg=end pg=/ id=1cfcceef9024c4e5 status=302 dur=0s
t=2022-12-01T09:48:15-0500 lvl=info msg=start pg=/inspect/http id=d32bebc867499298
t=2022-12-01T09:48:15-0500 lvl=info msg=end pg=/inspect/http id=d32bebc867499298 status=200 dur=0s
t=2022-12-01T09:48:22-0500 lvl=eror msg="failed to reconnect session" obj=csess id=81d11d8b3835 err="read tcp 10.64.101.46:57060->3.20.27.198:443: i/o timeout"
t=2022-12-01T09:48:25-0500 lvl=info msg=start pg=/ id=5cb279bf15aae6eb
t=2022-12-01T09:48:25-0500 lvl=info msg=end pg=/ id=5cb279bf15aae6eb status=302 dur=0s
t=2022-12-01T09:48:25-0500 lvl=info msg=start pg=/inspect/http id=bf4f9cffd1c13f95
t=2022-12-01T09:48:25-0500 lvl=info msg=end pg=/inspect/http id=bf4f9cffd1c13f95 status=200 dur=0s

Failed to start local tunnel service.
Failed to find the tunnel endpoint. Teams toolkit try to get the first HTTPS URL from http://127.0.0.1:4040 and failed.

 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by Jerry069** [comment]
Facing the same issue

**Comment by XiaofuHuang** [comment]
> Facing the same issue

Could you solve this problem through the solution in the [link](https://github.com/inconshreveable/ngrok/issues/484) above (using 127.0.0.1 instead of localhost / close your VPN / update hosts file)

**Comment by Aravindtammireddy** [comment]
It looks like the webpage at https://localhost:53000/index.html#/tab might be having issues, or it may have moved permanently to a new web address.
I am trying to port my other project into microsoft teams and everything is going well expect for when the path was opened in teams app in "https" secured mode. Can you provide reason and measures for this .
