### ISSUE TITLE
Update React and React Router dependencies in TS templates

### ISSUE THREAD

**Issue by BOLT04** [OfficeDev/TeamsFx#7100]
**Is your feature request related to a problem? Please describe.**
I recently used this vs code extension, but the generated starter template had an older React version ( `^16.14.0`) and other outdated dependencies. For example:

https://github.com/OfficeDev/TeamsFx/blob/328d16af9c330f97bd8c7b01923323d6949d1177/templates/tab/ts/default/package.json#L15

**Describe the solution you'd like**
To update `react`, `react-router` dependency versions on the TS templates available on this repository.

**Additional context**
By upgrading to the latest versions of these packages, we can leverage new React 18 concurrent features, and just stay up to date.

I believe this change would only apply to **new apps** using these templates.

**Comment by BOLT04** [comment]
hi @adashen, is this already in progress?
I could submit a PR and help out on some of the templates, and jumpstart this work.

Let me know if it's up for grabs 👍

**Comment by huimiu** [comment]
Hi @BOLT04, sorry for the late reply.

Sure, this is a very good suggestion, we are doing some verification work and will release it as soon as possible if it is ok.

**Comment by BOLT04** [comment]
awesome @huimiu 👍 👍 , that sounds great 😃.
If there is anything I can help let me know, and I can open a PR 👍

**Comment by BOLT04** [comment]
hi @huimiu, just pinging to know if there is something I can help with on this issue, and perhaps open a PR 🙂 ?

**Comment by huimiu** [comment]
Hi @BOLT04, we are already working on it, and it is expected to be released around mid-March. 
If it is ready, I will let you know in time, thanks for your attention.

**Comment by MuyangAmigo** [comment]
Hey @BOLT04 , We have released a new alpha version of teamsfx-react that supports React 18: @microsoft/teamsfx-react": "^3.0.0-alpha. Stable version will come soon, stay tuned.

**Comment by huimiu** [comment]
Hi @BOLT04, we have released a stable version of the [SDK](https://www.npmjs.com/package/@microsoft/teamsfx-react) to support React 18, and all our templates have also been upgraded to React 18.

https://github.com/OfficeDev/TeamsFx/blob/dev/templates/ts/dashboard-tab/package.json.tpl#L15

Therefore, I am closing this issue for now. If you have any other questions, please feel free to contact us. Thank you!
