### ISSUE TITLE
Recover values from /tabs/env.teamsfx.ENV in a working Environment

### ISSUE THREAD

**Issue by Leviani** [OfficeDev/TeamsFx#7164]
After creating a teams Application with the Teams Toolkit, a bunch of Environment related settings files are created.
One of them being /tabs/env.teamsfx.ENV.
(Others are .fx/configs/config.ENV.json and .fx/states/state.ENV.json)

We did create several Stages (Dev / Int / Prod) and deployed the App into them.

Through an unfortunate event, we lost those Settings Files used for the different stages.
Now we need to read the current values for the Prod Environment, to be able to fix some issues for the App and re-Deploy it into Production.

We did search for a place to find the values inside the Tenant, once the App was deployed but didn't find them at all.
The App underneath the storage Account, its pages in the Container and the Static Website are all visible, but none of those show the values we are looking for.

Is there a way to recover those stage specific values from an Environment once the App has been installed, like you can read the Application settings of any installed Function App under Settings -> Configuration ?

**Comment by hund030** [comment]
@Leviani 
Storage Account host a static website. The env states are compiled into the app so you can try finding the compiled JavaScript file in your $web container. Download the file and search for your client id in it.

Here are the steps:
1. Open Azure portal and find the Storage Account. Download static/js/main.03b3675c.js from $web container.
2. Open the file any editor and search for the env name. For example, REACT_APP_CLIENT_ID.
3. You should find something as below:
```
REACT_APP_CLIENT_ID:"xxxxx-xxxxxx",REACT_APP_START_LOGIN_PAGE_URL:"auth-start.html"}
```

**Comment by hund030** [comment]
> Perfect, thank you very much. In my case it was named main.cf....chunk.js
> 
> Now that I found those, is it possible to just update the values in the js file and re-upload it (and restart the App / resolve any caching issues), or is there more to it if I want to change those values ?

I will recommend you recover the env files and re-build the app rather than modify the built assets.
