### ISSUE TITLE
Adding a notification indicator on the app icon

### ISSUE THREAD

**Issue by acomvan** [OfficeDev/TeamsFx#7180]
Is it possible to show a notification bubble on the application icon? I am developing a Teams Application, where there are messages that can be read by the user. And I want to show an unread messages indicator on the app icon like it is currently for the Chat application of Microsoft Teams. 
I am aware, that I could use the Activity tab or a bot to achieve some kind of notification but I want a static indicator for the amount of unread messages and not only a one time notification.

**Comment by jidddddd** [comment]
Hi @acomvan, currently there's no feature in Teams Toolkit to add a notification bubble. Thanks for raising this question, it is not on our current roadmap but we will keep it in mind for future improvements.
