### ISSUE TITLE
Bug report: Why doesn't the bot program run locally?

### ISSUE THREAD

**Issue by tuxxon** [OfficeDev/TeamsFx#7184]
**Describe the bug**
My bot program was running locally until last week (2022-12-09 Friday, KST). 
But, Today the same bot program is not running even locally.
I want to know why.

Could you please let me know why?

**To Reproduce**
1. click F5  (in WSL-ubuntu22 on windows 10) 

**Expected behavior**
Working normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/7301022/206899849-cfc52414-7228-4921-8aed-e4f26b0e8ec4.png)

**VS Code Extension Information (please complete the following information):**
 - OS:  Teams Toolkit on WSL2-ubuntu22- windows10
 - Version v4.1.3

**CLI Information (please complete the following information):**
 - OS: VSCode on  WSL2-ubuntu22- windows10 ,  node 16.13.1
 - Version 1.73.1
 
**Additional context**
```
(Totally 5 steps) Teams Toolkit is setting up bot for debugging.

(1/5) Registering the AAD app which is required to create the bot ...
(2/5) Registering the bot in Bot Framework Portal ...

Summary:

√ Skip registering AAD app but use the existing AAD app from args: 1b874558-27b9-49e4-b818-39c85c3b9c3f

× AlreadyCreatedBotNotExist: Could not get bot with id 1b874558-27b9-49e4-b818-39c85c3b9c3f which was created before. 
This could happen if the bot was created by another account. Visit https://aka.ms/teamsfx-switch-account-or-subscription-help to learn more.

Visit https://aka.ms/teamsfx-debug-set-up-bot-task to learn more about 'Set up bot' task.

[2022-12-11T10:13:50.875Z] [Error] - code:Ext.SetUpBotError, message: Set up bot task failed. Please check the output panel to see the details.
```

**Comment by quinndumala** [comment]
I'm getting this same error on my Teams Toolkit bot app as well. It was running completely fine last week but it now fails with that message when I try to debug.

**Comment by mikepepping** [comment]
Posting to help gain traction, same problem occurring for my team as well, was working Friday 9th Dec, this morning, no bueno.  Mac Ventura, node 16 lts.

**Comment by lucianchen** [comment]
Getting this same error from Friday afternoon, affecting local testing now, in teams dev portal cannot retrieve correct bot info, tried add bot from there also no luck.
Provisioning directly against Azure seems working though.
 
![image](https://user-images.githubusercontent.com/994255/206949167-48025c0a-7931-447a-b5ea-2984aa26b066.png)

**Comment by AChaoZJU** [comment]
Hi @lucianchen 
How can we provision directly against Azure? Is there any difference between provisioning directly against Azure and the normal workflow?
Thanks in advance.

**Comment by IvanJobs** [comment]
Hi All, After some investigations and verifications, It seems there's some live-site issues related to the underlying API of creating bot registration on bot framework portal. We're actively connecting with the corresponding team to handle this issue, please stay tunned, thanks.

To workaround this issue, you can apply the existing bot flow.
1. Use this link https://dev.botframework.com/bots/new to create bot registration for local debug manually
2. Update the corresponding BOT_ID, BOT_PASSWORD in project file by following this guide https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/bot-help.md#how-to-reuse-existing-aad-in-toolkit-v2.
3. Hit local debug's `F5` again, TTK will respect the existing bot.

**Comment by xlb233** [comment]
> Hi All, After some investigations and verifications, It seems there's some live-site issues related to the underlying API of creating bot registration on bot framework portal. We're actively connecting with the corresponding team to handle this issue, please stay tunned, thanks.
> 
> To workaround this issue, you can apply the existing bot flow.
> 
> 1. Use this link https://dev.botframework.com/bots/new to create bot registration for local debug manually
> 2. Update the corresponding BOT_ID, BOT_PASSWORD in project file by following this guide https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/bot-help.md#how-to-reuse-existing-aad-in-toolkit-v2.
> 3. Hit local debug's `F5` again, TTK will respect the existing bot.

There seem to be some issues within the bot registration workflow. This workaround doesn't work for me.
![image](https://user-images.githubusercontent.com/17999749/206972938-6ffc4343-3ac1-46f5-8a27-f8aba11d7477.png)

**Comment by IvanJobs** [comment]
> > Hi All, After some investigations and verifications, It seems there's some live-site issues related to the underlying API of creating bot registration on bot framework portal. We're actively connecting with the corresponding team to handle this issue, please stay tunned, thanks.
> > To workaround this issue, you can apply the existing bot flow.
> > 
> > 1. Use this link https://dev.botframework.com/bots/new to create bot registration for local debug manually
> > 2. Update the corresponding BOT_ID, BOT_PASSWORD in project file by following this guide https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/bot-help.md#how-to-reuse-existing-aad-in-toolkit-v2.
> > 3. Hit local debug's `F5` again, TTK will respect the existing bot.
> 
> There seem to be some issues within the bot registration workflow. This workaround doesn't work for me. ![image](https://user-images.githubusercontent.com/17999749/206972938-6ffc4343-3ac1-46f5-8a27-f8aba11d7477.png)

Hi @xlb233, Thanks for the quick feedback. 
It seems you used the Developer Portal for Teams to create a new bot. Unfortunately, Developer Portal for Teams may have the same issue. Can you try using BotFramework Portal (https://dev.botframework.com/bots/new) instead as I mentioned in the previous comment? Thanks.

**Comment by wangrenhang** [comment]
Hi @IvanJobs, I just follow your workaround but still cannot proceed debugging locally
<img width="1223" alt="Screen Shot 2022-12-12 at 15 06 55" src="https://user-images.githubusercontent.com/42313666/206982210-03cfb520-dfeb-4aeb-8b19-70eeee0a1d1f.png">

**Comment by IvanJobs** [comment]
> Hi @IvanJobs, I just follow your workaround but still cannot proceed debugging locally <img alt="Screen Shot 2022-12-12 at 15 06 55" width="1223" src="https://user-images.githubusercontent.com/42313666/206982210-03cfb520-dfeb-4aeb-8b19-70eeee0a1d1f.png">

It looks like there's another underlying API of Getting Bot Registation was impacted which makes the reusing existing bot flow no working anymore. Thanks for your feedback. Stay tunned - I will give updates as long as the  server side API issue was fixed.

**Comment by IvanJobs** [comment]
> Hi @IvanJobs, I just follow your workaround but still cannot proceed debugging locally <img alt="Screen Shot 2022-12-12 at 15 06 55" width="1223" src="https://user-images.githubusercontent.com/42313666/206982210-03cfb520-dfeb-4aeb-8b19-70eeee0a1d1f.png">

It looks like there's another underlying API of Getting Bot Registation was also impacted which makes the reusing existing bot flow no working anymore. Thanks for your feedback. Stay tunned - I will give updates as long as the  server side API issue was fixed.

**Comment by sohamzycus** [comment]
Team, when are we expecting a resolution on this issue. Workaround doesn't work and our development process is totally stuck. Looking for fast resolution and/or any working work around, please.

**Comment by hidn** [comment]
Hi @IvanJobs ,

Tried the workaround to manually create the app registration and Bot. Unfortunately while it appears that the task did pickup the app id, it still returned ProvisionError.

Was provisioning the bot in local environment for this first time. Not sure if this is the same issue as others, or a different one.

```
Summary:

√ Forwarding ngrok URL https://3f01-115-199-179-165.ngrok.io to http://localhost:3978

Visit https://aka.ms/teamsfx-local-tunnel-task to learn more about 'Start local tunnel' task.

[2022-12-12T09:10:31.467Z] [Info] - Started local tunnel service in 1.61 seconds.
[2022-12-12T09:10:31.508Z] [Info] - Running 'Set up bot' Visual Studio Code task.

(Totally 5 steps) Teams Toolkit is setting up bot for debugging.

(1/5) Registering the AAD app which is required to create the bot ...
(2/5) Registering the bot in Bot Framework Portal ...

Summary:

√ Skip registering AAD app but use the existing AAD app from args: ef37b9d4-c1e2-4ab0-b6d1-484f64b73a93

× ProvisionError: Failed to provision Developer Portal bot registration.

Visit https://aka.ms/teamsfx-debug-set-up-bot-task to learn more about 'Set up bot' task.

[2022-12-12T09:13:22.309Z] [Error] - code:Ext.SetUpBotError, message: Set up bot task failed. Please check the output panel to see the details.
```

**Comment by Ericvf** [comment]
Any progress on this? We are trying to develop an application but its impossible at the moment.

**Comment by YutongTie-MSFT** [comment]
Hello @IvanJobs 

I have seen two more threads about this issue for your reference -
https://learn.microsoft.com/en-us/answers/questions/1124839/error-occurs-when-fetching-bot.html?childToView=1125743#answer-1125743
https://learn.microsoft.com/en-us/answers/questions/1125281/teams-developer-portal-can39t-fetch-bot-error.html?childToView=1125771#answer-1125771

I posted your solution in both threads, please let us know once this issue has been fixed. Thank you.

**Comment by Ericvf** [comment]
@YutongTie-MSFT 

Thanks! These steps do work for me now:

1. Clean solution
2. Restart VS
3. `Update` the `Messaging endpoint` in the [Botframework portal](https://dev.botframework.com/bots) to my `local ngrok` url
4. `Remove` `<ProjectCapability Include="TeamsFx" />` from the `.csproj`
5. `Add` the following section to my _config.local.json_

```
"bot": {
    "appId": "<bot-id>",
    "appPassword": "<bot-secret>"
  }
```

**Comment by Ericvf** [comment]
NOTE

The solution above does not correctly provision a new TeamApp package (manifest) to Teams. That means that your ngrok.io urls will not be updated in the manifest.json. For our Teams task modules we require the ngrok url to be present as **validDomains** in the manifest. 

If you also need to upload a new TeamsApp manifest:

1. `Add` `<ProjectCapability Include="TeamsFx" />` back to the project
2. Use `Project > Teams Toolkit > Zip App Package > For Local`
3. Upload the `~\build/appPackage/appPackage.local.zip` file to the [Teams Admin portal](https://admin.teams.microsoft.com/policies/manage-apps)
4. Install the app

**Comment by IvanJobs** [comment]
> > Hi @lucianchen How can we provision directly against Azure? Is there any difference between provisioning directly against Azure and the normal workflow? Thanks in advance.
> 
> First click provision in the cloud, then use provisioned debugging option <img alt="image" width="344" src="https://user-images.githubusercontent.com/994255/207067959-8c5879cb-7ea2-435c-94e9-5a126c9432ec.png">
> 
> @IvanJobs Is there a way to check the console logs from somewhere in Azure console since the local debugging is not working yet? Many thanks!

@lucianchen You can check Azure App Service's application log stream on Azure portal instead. Check https://learn.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs.

**Comment by lucianchen** [comment]
> > > Hi @lucianchen How can we provision directly against Azure? Is there any difference between provisioning directly against Azure and the normal workflow? Thanks in advance.
> > 
> > 
> > First click provision in the cloud, then use provisioned debugging option <img alt="image" width="344" src="https://user-images.githubusercontent.com/994255/207067959-8c5879cb-7ea2-435c-94e9-5a126c9432ec.png">
> > @IvanJobs Is there a way to check the console logs from somewhere in Azure console since the local debugging is not working yet? Many thanks!
> 
> @lucianchen You can check Azure App Service's application log stream on Azure portal instead. Check https://learn.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs.

Thanks, figured it out later🙏

**Comment by IvanJobs** [comment]
@kuojianlu will give a working workaround for this server-side api issue soon. The basic logic is to remove steps of calling those APIs from local debug, and provide guide to do those steps manually. 
Sorry for the inconvenience, and please stay tunned. @lucianchen @Ericvf @YutongTie-MSFT @hidn @sohamzycus @wangrenhang @xlb233 @quinndumala @tuxxon

**Comment by kuojianlu** [comment]
Hi all, here is a workaround for VS Code:
1. In `.vscode/tasks.json`, remove "Set up bot" from the "dependsOn" field of "Start Teams App Locally" task.
2. From command palette, run "Tasks: Run Task" and select "Start local tunnel". Then open "Start local tunnel" terminal, you can see the forwarding url like "https://f633-2404-f801-9000-18-6fec-00-26d.ngrok.io".
3. Create an AAD app with your M365 account. Create a client secret and copy the secret value which will be used later.
4. Create a bot in https://dev.botframework.com/bots/new with your M365 account. Set the messaging endpoint using the above forwarding url like "https://f633-2404-f801-9000-18-6fec-00-26d.ngrok.io/api/messages". After the bot is created, configure Microsoft Teams channel.
5. In `templates/appPackage/manifest.template.json`, update `botId` to the AAD app client id; update `validDomains` to the domain of the above forwarding url like "f633-2404-f801-9000-18-6fec-00-26d.ngrok.io".
6. In `bot/.env.teamsfx.local`, update "BOT_ID" to the AAD app client id; update BOT_PASSWORD to the AAD app client secret.
7. F5.

**Comment by quinndumala** [comment]
> Hi all, here is a workaround for VS Code:
> 
> 1. In `.vscode/tasks.json`, remove "Set up bot" from the "dependsOn" field of "Start Teams App Locally" task.
> 2. From command palette, run "Tasks: Run Task" and select "Start local tunnel". Then open "Start local tunnel" terminal, you can see the forwarding url like "https://f633-2404-f801-9000-18-6fec-00-26d.ngrok.io".
> 3. Create an AAD app with your M365 account. Create a client secret and copy the secret value which will be used later.
> 4. Create a bot in https://dev.botframework.com/bots/new with your M365 account. Set the messaging endpoint using the above forwarding url like "https://f633-2404-f801-9000-18-6fec-00-26d.ngrok.io/api/messages". After the bot is created, configure Microsoft Teams channel.
> 5. In `templates/appPackage/manifest.template.json`, update `botId` to the AAD app client id; update `validDomains` to the domain of the above forwarding url like "f633-2404-f801-9000-18-6fec-00-26d.ngrok.io".
> 6. In `bot/.env.teamsfx.local`, update "BOT_ID" to the AAD app client id; update BOT_PASSWORD to the AAD app client secret.
> 7. F5.

Didn't work for me, unfortunately. I'm getting the following error:
```× GetLocalDebugConfigFailed: Missing configuration data for manifest. You may need to run 'debug' first. Data required: state.teams-bot.botId,state.teams-bot.domain.```

**Comment by kuojianlu** [comment]
@quinndumala Have you done the step 5?

> 5. In templates/appPackage/manifest.template.json, update botId to the AAD app client id; update validDomains to the domain of the above forwarding url like "f633-2404-f801-9000-18-6fec-00-26d.ngrok.io".
For example:
```
{
    ...
    "bots": [
        {
            "botId": "5800acec-8e11-4407-8430-04d7610e0236",
            ...
        }
    ]
    ...
    "validDomains": [
        "911f-2404-f801-9000-1a-6fea-00-26d.ngrok.io"
    ]
    ...
}
```

**Comment by Priyanka-Diligent** [comment]
> 3\. Create an AAD app with your M365 account.

Create an AAD app with your M365 account.
How to create an AAD app with your M365 account?
Can somebody please help me.

**Comment by kuojianlu** [comment]
@Priyanka-Diligent 
1. Open https://portal.azure.com/#view/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/~/Overview, login with your M365 account.
2. Click "App registrations" from left side bar, then click "New registration".

**Comment by mtr1920** [comment]
Working Now

**Comment by IvanJobs** [comment]
Hi All, 
### The server side API issue was **resolved** around two hours ago. 
I did a quick check, and the local debug experience of TTK was working good now. 
Can you help verify this in your convenience and give back some feedbacks here? Thanks.
@lucianchen @Ericvf @YutongTie-MSFT @hidn @sohamzycus @wangrenhang @xlb233 @quinndumala @tuxxon

**Comment by YutongTie-MSFT** [comment]
Thanks for posting the fix confirmation!
@IvanJobs Working for me now.

**Comment by quinndumala** [comment]
it's working for me now too. Thank you @IvanJobs!

**Comment by Ericvf** [comment]
Thanks all, problems here resolved as well

**Comment by tuxxon** [comment]
Thanks all for posing the fix. 
It's working for me.
