### ISSUE TITLE
Resolve code 404 ('blank tabs') on Deployment - config options?

### ISSUE THREAD

**Issue by mattgillam** [OfficeDev/TeamsFx#7243]
**Is your feature request related to a problem? Please describe.**

My app is multi-tenant, deployed using Toolkit to Azure Storage, with CDN and a Custom Domain activated. It works fine. In use from several sites in Europe, US and Asia.

Users intermittently report "blank tabs" when I deploy updates. The tab menu (from the Manifest) its correct but the core content area is plain grey.

This is very hard to reproduce reliably but I believe it's because their client locally caches index.html but not the app's .js or .css files.

On deployment the js and css files get new names and the previous version is deleted. This means the cached index.html is referring to unavailable source files, the request 404s and the user sees a blank tab until, some time, their index.html gets updated.

**Describe the solution you'd like**
A way to resolve above please. For instance a way to prevent caching of index.html, or require matching local caching of source and css to match a index.html.

**Describe alternatives you've considered**
I've already moved from another CDN - didn't help.

Thank you.

**Comment by sffamily** [comment]
@mattgillam Thank you for sharing your issue, and your proposal to mitigate this. We will bring your case for an internal discussion and see whether we can do something quick to improve this. will reply here if we have more updates.

**Comment by sffamily** [comment]
After some internal investigation, the caching seems happen at CDN level. We don't have clear way on how to disable caching on CDN, but found a previous question on Stackoverflow: https://stackoverflow.com/questions/61557904/how-to-stop-index-html-being-cached-by-azure-cdn

**Comment by mattgillam** [comment]
Thank you @sffamily I will test this and report back.
