### ISSUE TITLE
bug report: Login.LoginCacheError

### ISSUE THREAD

**Issue by nmPascal** [OfficeDev/TeamsFx#7270]
Failed to get login account token from cache. You could try signing out and signing back in to your Azure Account using Teams Toolkit tree view or command palette

stack:
LoginCacheError: Failed to get login account token from cache. You could try signing out and signing back in to your Azure Account using Teams Toolkit tree view or command palette
    at TeamsFxTokenCredential.<anonymous> (<REDACTED: user-file-path>:8:6816672)
    at Generator.throw (<anonymous>)
    at rejected (<REDACTED: user-file-path>:8:6814769)

**Comment by xiaolang124** [comment]
Hi, thanks for reporting this issue.
Will logging out and logging in solve the problem? If this cannot solve this, which version is your `Azure Account Extension`?

**Comment by akai-nu** [comment]
This work. Thank you

**Comment by adashen** [comment]
close as the issue is resolved.
