### ISSUE TITLE
Missing deploy teams app manifest option

### ISSUE THREAD

**Issue by amansani15** [OfficeDev/TeamsFx#7410]
**Describe the bug**
I am trying to deploy only the manifest file without provisioning the entire application and I don't see the option of **Deploy teams app manifest** either in command palette or by right clicking on manifest.template.json file. In the the below link, it shows what I am looking for under **Sync local changes to developer portal** section.

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/teamsfx-preview-and-customize-app-manifest?pivots=visual-studio-code

**Expected behavior**
Looking to deploy only the manifest file. If I do the provisioning just to deploy the manifest file, then the domain and endpoints are getting replaced in the state.dev.json.

**Screenshots**
![image](https://user-images.githubusercontent.com/62998123/210839633-1aee1982-c675-47d0-9bf7-91fc4b09b394.png)

![image](https://user-images.githubusercontent.com/62998123/210839519-e45f29b3-c445-4e1c-b14c-e49c2daf77b9.png)

**VS Code Extension Information (please complete the following information):**
OS: Windows 10 Pro
VS Code Version 1.72.0
Teams tool kit version: V4.2.1

Any inputs are highly appreciated, thank you

**Comment by nliu-ms** [comment]
Hey @amansani15 , sorry for the inconvenience, there were some refactors so the name has been changed. Can you please find the following command from command palette? This should be identical with the command described in the doc.
![image](https://user-images.githubusercontent.com/71362691/211258634-ef396a8c-f1af-469c-a959-e041bea7de40.png)

Please let me know if it works for you. Thanks!

**Comment by amansani15** [comment]
I can see the **Update Teams app** option and when I selected that, it did apply all the manifest file changes to the developer portal. Thank you. 

Do you have any idea how to not update the domain and the endpoint in the manifest while doing provisioning?

**Comment by nliu-ms** [comment]
@amansani15 Glad to hear that. Can you please share the validDomain section in your manifest.template.json file? And the expected value/actual value synced to Developer Portal. Then I can have some investigation. Thanks!

**Comment by amansani15** [comment]
Sure. Here are the details in the state.dev.json and in the manifest.template.json

**state.dev.json:**
"fx-resource-frontend-hosting": {
        "indexPath": "/index.html#",
        "domain": "testCDN.azureedge.net",
        "endpoint": "https://testCDN.azureedge.net",
        "storageResourceId": "storageresourcelocation"
},

**manifest.template.json:**
"staticTabs": [
    {
      "entityId": "test",
      "name": "test1",
      "contentUrl": "{{{state.fx-resource-frontend-hosting.endpoint}}}{{{state.fx-resource-frontend-hosting.indexPath}}}/test",
      "websiteUrl": "{{{state.fx-resource-frontend-hosting.endpoint}}}{{{state.fx-resource-frontend-hosting.indexPath}}}/test",
      "scopes": ["personal"]
    },

whenever I provision the resources, the domain and the endpoint in the state.dev.json are replaced with the below values and the manifest.template.json reads these values from the json and generates related values in the manifest.dev.json.

**state.dev.json:**
"fx-resource-frontend-hosting": {
        "indexPath": "/index.html#",
        "domain": "test86597tab.blob.core.windows.net",
        "endpoint": "https://test86597tab.blob.core.windows.net",
        "storageResourceId": "storageresourcelocation"
},

I want the domain and the endpoint values in state.dev.json need to be remain same(which is cdn domain and endpoint) even after provisioning the resources step.

**Comment by nliu-ms** [comment]
@amansani15 Thanks for your information. As the values are auto-generated during provision, though you manually update the *state.dev.json* file, it doesn't work. But I think you can add your customization value to config file. E.g.

**config.dev.json**:
Add the CDN domain and value to config file
```
{
    "$schema": "https://aka.ms/teamsfx-env-config-schema",
    "description": "You can customize the TeamsFx config for different environments. Visit https://aka.ms/teamsfx-env-config to learn more about this.",
    "manifest": {
        "appName": {
            "short": "tab0110",
            "full": "Full name for tab0110"
        },
        "description": {
            "short": "Short description of tab0110",
            "full": "Full description of tab0110"
        },
        "icons": {
            "color": "resources/color.png",
            "outline": "resources/outline.png"
        },
        "tab": {
            "domain": "testCDN.azureedge.net",
            "endpoint": "https://testCDN.azureedge.net"
        }
    }
}
```

**manifest.template.json**
Update placeholders in staticTabs and validDomains section.
```
    "staticTabs": [
        {
            "entityId": "test",
            "name": "test1",
            "contentUrl": "{{{config.manifest.tab.endpoint}}}{{{state.fx-resource-frontend-hosting.indexPath}}}/tab",
            "websiteUrl": "{{{config.manifest.tab.endpoint}}}{{{state.fx-resource-frontend-hosting.indexPath}}}/tab",
            "scopes": [
                "personal"
            ]
        }
    ],
    "validDomains": [
        "{{config.manifest.tab.domain}}"
    ]
```
Provision again, and the values provided in config file will be used:
![image](https://user-images.githubusercontent.com/71362691/211702959-a73cbaad-82f8-4ea6-a972-e4f20bf3331e.png)

Please let me know if this solution works for you, thanks!

**Comment by amansani15** [comment]
Everything looks good except the state.dev.json still getting modified with the below values:

"fx-resource-frontend-hosting": {
        "indexPath": "/index.html#",
        "domain": "test86597tab.z9.web.core.windows.net",
        "endpoint": "https://test86597tab.z9.web.core.windows.net",
        "storageResourceId": "storagelocation"
    },

Can't we stop updating these values?

**Comment by nliu-ms** [comment]
The `state.dev.json` will be updated and overwritten every time `provision` executed, so I'm afraid this cannot be avoided right now. But I'm trying to understand your scenario. If the values in manifest are correct, as the `config.dev.json` will not be updated, why keeping `state.dev.json` not updated is required? 
cc our PM @jidddddd

**Comment by amansani15** [comment]
To maintain the consistency in the code to have the same domain and endpoint in all the places in the project. So that we don't get confused in the future.

**Comment by jidddddd** [comment]
Hi @amansani15, there's a release coming with features that'll help resolve your issue, I'll ping back here once it's available.

**Comment by amansani15** [comment]
Great, thank you.

**Comment by nliu-ms** [comment]
Close this issue as it has been resolved. And the doc will be updated soon.
