### ISSUE TITLE
can not receive message

### ISSUE THREAD

**Issue by 86driver** [OfficeDev/TeamsFx#7461]
**Describe the bug**
cannot receive resnponse after i send messgae to teams bot

**Comment by IvanJobs** [comment]
Hi @86driver, we've provided a document to guide you trouble-shooting the case here. Can you check this link and help yourself here  ? https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/bot-help.md#how-can-i-troubleshoot-issues-when-teams-bot-isnt-responding-on-azure

**Comment by 86driver** [comment]
> 

it works fine after a day, i don't know what happened

**Comment by 86driver** [comment]
> Hi @86driver, we've provided a document to guide you trouble-shooting the case here. Can you check this link and help yourself? https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/bot-help.md#how-can-i-troubleshoot-issues-when-teams-bot-isnt-responding-on-azure
> 
> If you still cannot make it work, please provide us with more info, thanks.

it works fine after a day, i don't know what happened

**Comment by 86driver** [comment]
the issue can be closed

**Comment by adashen** [comment]
close as it is resolved
