### ISSUE TITLE
"[Error] - code:Core.InvalidEnvConfigError, message: The configuration config.dev.json is invalid" when running a local debug from VSCode and using existing Azure AD app with env variables 

### ISSUE THREAD

**Issue by FranckyC** [OfficeDev/TeamsFx#7487]
**Context**

I've created a project from the _"Post messages to Teams"_ sample app from Teams Toolkit extension. I have the only two default environments **local** and **dev** defined. For both environments, I need to use existing Azure AD apps for the bot.

According to the [documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code#use-an-existing-azure-ad-app-for-your-bot), I've updated the `config.dev.json` and `config.local.json` files to use predefined `appId` and `appPassword` like this and using environment variables:

```json
{
    "$schema": "https://aka.ms/teamsfx-env-config-schema",
    "description": "You can customize the TeamsFx config for different environments. Visit https://aka.ms/teamsfx-env-config to learn more about this.",
    "manifest": {
        "appName": {
            "short": "My App",
            "full": "My App)"
        },
        "description": {
            "short": "...",
            "full": "..."
        },
        "icons": {
            "color": "resources/color.png",
            "outline": "resources/outline.png"
        }
    },
    "bot": {
        "appId": "{{$env.BOT_ID}}",
        "appPassword": "{{$env.BOT_PASSWORD}}"
    }
}
```

**Issues**

When deploying the `dev` environment from CI using TeamsFx CLI, I'm able to log/provision/deploy the solution correctly by setting environment variables dynamically using PowerShell Core like this:

```
$env:BOT_ID= <APP_ID>
$env:BOT_PASSWORD= <APP_SECRET>
```

However, when using the local debug configuration (F5 from VSCode), I'm not able to set the environment variables for `config.local.json` as I don't know where to define them. I tried an `.env` file in the workspace folder or add an `env` property in the `launch.json` file but they are not resolved:

![image](https://user-images.githubusercontent.com/5659122/211954077-a74f3ada-9780-4e99-81f5-ecd832657fcd.png)

If I put hard coded values in `config.local.json`. it seems to pass the validation but I get then the following error after the "Build and upload Teams manifest" task and the browser doesn't launch:

```
[Error] - code:Core.InvalidEnvConfigError, message: The configuration config.dev.json is invalid, details: [{"instancePath":"/bot/appId","schemaPath":"#/properties/bot/properties/appId/minLength","keyword":"minLength","params":{"limit":1},"message":"must NOT have fewer than 1 characters"}].
```

Removing the `bot` property from `config.dev.json` fixes the issue but I don't really understand why `config.dev.json` is involved when I run a local debug session.

As a workaround, I've ended up adding the bot `appId` and `appPassword` during CI by updating the json file but I have the feeling this is not the way is it is supposed to work.

Am I missing something in the documentation for the scenario where you need to use existing Azure AD apps?

Thanks!

**To Reproduce**
1. Create a project using "Post messages to Teams" sample starter from Teams Toolkit extension 4.2.1.
2. Register your own Azure AD app for default **dev** env.
3. Update the `config.dev.json` file to use your own `appId` and `appPassword` using env variables (ex `{{$env.BOT_ID}}`) according to https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/provision?pivots=visual-studio-code#use-an-existing-azure-ad-app-for-your-bot), 
4. Run a local debug session using F5
5. See `code:Core.InvalidEnvConfigError` for `config.dev.json` file

**Expected behavior**

Local debug should ignore the config.dev.json values as it is not the targeted env.

**Screenshots**

![image](https://user-images.githubusercontent.com/5659122/211953727-76872215-4f39-41b9-ba62-8675d7b5e6bd.png)

**VS Code Extension Information**
 - Version 4.2.1

**CLI Information**
 - OS: Windows 10
 - Version 1.21

**Comment by KennethBWSong** [comment]
Hi @FranckyC Thank you for using our toolkit! Teams Toolkit updated the logic for local debug after 4.1.0. If you are using Teams Toolkit >= 4.1.0, would you please try to follow this [doc](https://github.com/OfficeDev/TeamsFx/wiki/%7BDebug%7D-Teams-Toolkit-VS-Code-Tasks#set-up-bot) to use existing AAD app for bot? We also support referencing env in task.json.

**Comment by KennethBWSong** [comment]
Hi @FranckyC Here is an example on using env variables, and set `BOT_AAD_ID` and `BOT_AAD_PASSWORD` in your environment variables.
```
{
    // Register resources and prepare local launch information for Bot.
    // See https://aka.ms/teamsfx-debug-set-up-bot-task to know the details and how to customize the args.
    "label": "Set up bot",
    "type": "teamsfx",
    "command": "debug-set-up-bot",
    "args": {
        //// Enter your own bot information if using the existing bot. ////
        "botId": "${env:BOT_AAD_ID}",
        "botPassword": "${env:BOT_AAD_PASSWORD}", // use plain text or environment variable reference like ${env:BOT_PASSWORD}
        "botMessagingEndpoint": "/api/messages" // use your own routing "/any/path", or full URL "https://contoso.com/any/path"
    }
},
```

**Comment by FranckyC** [comment]
Thanks for the reply @KennethBWSong. Actually, I expected more an example about how to define them (i.e. the values) not how to reference them in `tasks.json` as it is literally explained in the file.

**Comment by KennethBWSong** [comment]
Hi @FranckyC You can try one of the following ways to set envs:
1. Open system properties, click on advanced, and add the environment variables
2. Open powershell, navigate to your project folder, set the environment variables and open vscode like:
![image](https://user-images.githubusercontent.com/63089166/212217859-74719400-9eb7-444a-8a8a-65820ec776e7.png)



cc @dooriya

**Comment by FranckyC** [comment]
I defined the variables at system level but doesn't work. Anyway it does not resolve the main issue with the `config.dev.json` file error during local debug. Any thoughts about the cause? Thanks!

**Comment by KennethBWSong** [comment]
Hi @FranckyC 
For first problem, you need to close all vscode sessions and restart the vscode again to make these changes take effect after defining these variables.
For your second question, do you mean you still get errors when using `task.json` to input the bot id and password?
