### ISSUE TITLE
Localization is not working for Teams tab app

### ISSUE THREAD

**Issue by SonOfJesseAsSnekithan** [OfficeDev/TeamsFx#7504]
**Describe the bug**
I have a teams tab app and added localization support as per the blazor localization documentation. When Settings in Team is changed to a different language, but cultural values in the cookies ( .AspNetCore.Culture) of my blazor app is not changed, Cookie values for the Microsoft Teams Client App is changed. When I tried to get the culture value from the Teams Context from CustomRequestCultureProvider, it is not allowed.  I am getting Exception that JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaSCript interop calls can only be performed during the OnAfterRenderAsync licecyle method.
**To Reproduce**
1. Build a Teams Tab App using the template provided by the Teams SDK
2. Make necessary changes to the app as per the documentation provided by msft for supporting localization and add necessary changes.
3. Run the app from VS 
4. CustomRequestCultureProvider could not return the culture

**Expected behavior**
Ther should be some way to get the culture info and save it as a cookie of the Blazor server app, so that CookieRequestCultureProvider can provide right culture details.

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**
 - OS: Window 11 and iOS Teams Client.
 - Version TeamsFX version 1.20

**Additional context**
For temporary workaround, singleton object is used in passing the teams culture to blazor server app, this works for Web client where reload tab option is used in reloading the tab with changed culture. In iOS teams client, there is no option for reload the tab which allows not able to provide localization.

**Comment by SonOfJesseAsSnekithan** [comment]
For temporary workaround, I have tried localstorage, cookies, and singleton object for passing the teams culture to blazor server app. Singleton object works for Web client where reload tab option is used in reloading the tab with changed culture. In iOS teams client, there is no option for reload the tab , so there is no way IStringLocalizer to return the correct strings.

**Comment by SonOfJesseAsSnekithan** [comment]
For a temporary workaround, I have tried local storage, cookies, and singleton object used in passing the team's culture to the blazer server app, this works for the Web client where reload tab option is used in reloading the tab with the changed culture. In the iOS teams client, there is no option for reloading the tab which results no way IStringLocalizer to provide localized string.

**Comment by chagong** [comment]
@SonOfJesseAsSnekithan can you follow this sample to localize your tab app?
https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/app-localization

Here is the tutorial: https://learn.microsoft.com/en-us/samples/officedev/microsoft-teams-samples/officedev-microsoft-teams-samples-app-localization-csharp/

**Comment by SonOfJesseAsSnekithan** [comment]
I have checked the sample, the sample includes ba ot and tab, so it sets the current culture from the turnContext.Activity.Locale.
Mine is a tab app I don't get the change, the only way I would get the locale is using the Teams JavaScript library.

**Comment by chagong** [comment]
Hi @SonOfJesseAsSnekithan, did you set your tab url as this:
"staticTabs": [
    {
      "entityId": "com.contoso.localization",
      "name": "English",
      "contentUrl": "<<Ngrok Url>>?culture={locale}",
      "scopes": [
        "personal"
      ]
    }
  ],

**Comment by SonOfJesseAsSnekithan** [comment]
Thanks for the details. I have made changes to the manifest as per your details, still it did not fix the problem when I change the language from Microsoft Teams, app title is changed from the manifest file, but content of my blazor app is not, if I click refresh, it renders correctly.
My teams app is a blazor web server and localization is done as per the following link ([![image](https://user-images.githubusercontent.com/5042316/215636043-51b430f8-f51d-4ac8-9198-2e3f8df06c73.png)]).

**Comment by chagong** [comment]
@SonOfJesseAsSnekithan are you able to share both (local and remote) your manifest snippet for the tabs?

**Comment by SonOfJesseAsSnekithan** [comment]
@chagong, it works now, thanks for the feedback. After changing the content-url as per your suggestion and using  default implementation of QueryStringRequestCultureProvider did not fix the problem, intermittently, tab was called without a culture query string, so it requires custom implementation of RequestCultureProvider returning the correct culture for the specific user.

**Comment by chagong** [comment]
Happy to hear, @SonOfJesseAsSnekithan. Thanks for the reply!
