### ISSUE TITLE
bug report: unknown.Error

### ISSUE THREAD

**Issue by Sairoj** [OfficeDev/TeamsFx#7512]
Lock is not <REDACTED: user-file-path> by you

stack:
Error: Lock is not <REDACTED: user-file-path> by you
    at <REDACTED: user-file-path>:8:4397068
    at LOOP (node:fs:2611:14)
    at processTicksAndRejections (node:<REDACTED: user-file-path>:78:11)

**Comment by adashen** [comment]
Hi @Sairoj  can you provide more info about the repro step and error messages?
