### ISSUE TITLE
VS TeamsFx Deploy not working with Asp 6.013 

### ISSUE THREAD

**Issue by bemokraig** [OfficeDev/TeamsFx#7553]
Confirmed no issues using ASP 6.011 that I have on VM

**Describe the bug**
Reset PC to recover from Patch Tuesday Defender disaster
Install Visual Studio with Teams
Create new Teams project
Prepare
Provision
Deploy
Deploy fails with errors

VS cannot find any of the runtime dependencies Asp.net or netcore

C:\Program Files\dotnet\sdk\7.0.102\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB3030: Could not copy the file
 "C:\Users\KraigRury\.nuget\packages\microsoft.netcore.app.runtime.win-x86\6.0.13\runtimes\win-x86\lib\net6.0\System.Threading.Tasks.Extensions.dll" because it was not found. [C:\Users\KraigRury\source\repos\MyTeamsApp7\MyTeamsApp7.csproj]

C:\Program Files\dotnet\sdk\7.0.102\Microsoft.Common.CurrentVersion.targets(4862,5): error MSB3030: Could not copy the file "C:\Users\KraigRury\.nuget\packages\microsoft.aspnetcore.app.runtime.win-x86\6.0.13\runtimes\win-x86\lib\net6.0\Microsoft.AspNetCore.Authentication.Cookies.dll" because it was not found. [C:\Users\KraigRury\source\repos\MyTeamsApp7\MyTeamsApp7.csproj]

In the VS project Dependencies
Microsoft.AspNetCore
File Version = 6.0.1322.58013
Path = C:\Program Files\dotnet\packs\Microsoft.AspNetCore.App.Ref\6.0.13\ref\net6.0\Microsoft.AspNetCore.dll

This path exists and contains the files.
Date modified: 12/1/22
Version matches

**Expected behavior**
Deploy should work

System Info
.Net Framework v 4.8.09032

<img width="676" alt="image" src="https://user-images.githubusercontent.com/67882884/212904961-3a583b97-bdd4-4db7-bc7e-654de81c2407.png">
<img width="651" alt="image" src="https://user-images.githubusercontent.com/67882884/212906328-c6896fe7-67c9-40df-8e3f-c5a160a3247f.png">

OS Win11 2261
Microsoft Visual Studio Enterprise 2022
Version 17.4.4
VisualStudio.17.Release/17.4.4+33213.308
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.4.326.54890
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.4.0-6.22608.27+af1e46ad38d900023f8b1a2839484e471ece1502
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22263.6
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Node.js Tools   1.5.40817.1 Commit Hash:66443775f9f3b1d8f8fee47af5002828b346688d
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.22263.6
Profiling support for Python projects.

Python with Pylance   17.0.22263.6
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.0.0.2246202+61cc048d36a3fc9246d2f04625988b19a18ab8f0
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.28050
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-6.22608.27+af1e46ad38d900023f8b1a2839484e471ece1502
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**********************

**Additional context**

**Comment by Siglud** [comment]
I think the cause of this error comes from the build process rather than the deployment process, please refer to [this link](https://stackoverflow.com/questions/61755681/errormsb3030could-not-copy-the-file-c-users-webapi3-obj-debug-netcoreapp) to solve it

**Comment by bemokraig** [comment]
You are correct, when I Reset my PC I kept my files which may have left a bad Nuget cache behind.  Thanks for the swift reply.
