### ISSUE TITLE
TeamsFX randomly (or not) does not resolve ARM? variables

### ISSUE THREAD

**Issue by bemokraig** [OfficeDev/TeamsFx#7554]
Teams Tab App

There is a problem resolving variables.  Two separate issues, both started occurring this year.

Seemingly random but for some apps permanently.  My real app is permanent so let me know if I can troubleshoot.
Our existing App and sometimes New Projects with no mods.

**1) Provision fails due to missing line for indexPath in state.local.json**

Missing configuration data for manifest
During Provision step: Missing configuration data for manifest. You may need to run 'Local debug' first. Data required: state.teams-tab.indexPath."
Cause: Unknown
Work-around Add indexPath to state.local.json
    "fx-resource-frontend-hosting": {
        "indexPath": "/",
        "endpoint": "[https://localhost:44302"](https://localhost:44302%22/),
        "domain": "localhost"
    }​​​​​​​
**2) App Crashes on Launch in Config.cs with error including the word oauthAuthority**

This problem has two known causes.
**1)  Failure to populate oauthAuthority variable in state.*.json**
For a while I could hard code this and it worked but then that stopped or it never worked except due to randomness
In .fx/states/state.local.json modify the    "fx-resource-aad-app-for-teams" section to include the value
       "oauthAuthority": "[https://login.microsoftonline.com/{tenantId / common}"]

**2) Failure to populate  variable config with OAuthAuthority
var config = builder.Configuration.Get<ConfigOptions>();
<img width="372" alt="image" src="https://user-images.githubusercontent.com/67882884/212925160-228188ba-c7df-44c1-958c-bcc6c2f008a7.png">

**Expected behavior**
For app to run with correct OAuthAuthority.  Even if it ran it's not picking up my settings for "common"

Microsoft Visual Studio Enterprise 2022
Version 17.4.4
VisualStudio.17.Release/17.4.4+33213.308
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.4.326.54890
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.4.0-6.22608.27+af1e46ad38d900023f8b1a2839484e471ece1502
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22263.6
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Node.js Tools   1.5.40817.1 Commit Hash:66443775f9f3b1d8f8fee47af5002828b346688d
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.22263.6
Profiling support for Python projects.

Python with Pylance   17.0.22263.6
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.0.0.2246202+61cc048d36a3fc9246d2f04625988b19a18ab8f0
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.28050
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.4.0-6.22608.27+af1e46ad38d900023f8b1a2839484e471ece1502
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by swatDong** [comment]
Hi @bemokraig, it looks like Teams Toolkit did not recognize your app's capability correctly, probably caused by missing value(s) in `.fx/configs/projectSettings.json`.

So,
- Is it convenient for you to share `.fx/configs/projectSettings.json`? (kindly remove sensitive data as your wish)
- Or, create new app and compare their projectSettings file to see if any difference.

BTW, make sure to run *Prepare Teams App Dependencies* before launching debug:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/7642967/213110682-65516c97-bf56-472e-9224-e147a03cc9e7.png">

Or, if all above do not work, just directly setting your configs to `appsettings.Development.json`:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/7642967/213111067-926cb9ff-b375-4123-a09a-01a8f546a79a.png">


(Adding @blackchoey as well on this AAD/SSO related issue)

**Comment by blackchoey** [comment]
@KennethBWSong for oauthAuthority issue
@hund030 for indexPath issue
Please take a look

**Comment by blackchoey** [comment]
@bemokraig You mentioned the issue also happens to new projects sometimes. Can you share the steps you take to debug new projects to help us troubleshooting?
