### ISSUE TITLE
TeamsFx Deploy Fails unless Teams Project has focus in Solution Viewer

### ISSUE THREAD

**Issue by bemokraig** [OfficeDev/TeamsFx#7555]
This seems new.  

Teams App project is set as startup project
Have focus in a file in the Teams project.
Teams Toolkit Deploy
Fails with error and suggestion
      "Please run failed command 'dotnet publish --output publish --configuration Release --runtime win-x86 --self-contained' in the folder: 'C:\\Users\\KraigRury\\source\\repos\\MyTeamsApp7'.",

Select the project in the Solution Viewer and Deploy
Success

Expect:  Deploy to use Startup Project to Deploy, remember Deploy can be run from Menu Project->Teams Toolkit as well as context menu on Project.  

Impact: Low but extremely annoying and time consuming

***********************************
{
  "errorType": "SystemError",
  "source": "FE",
  "name": "CommandExecutionError",
  "message": "Failed to run dotnet publish --output publish --configuration Release --runtime win-x86 --self-contained.",
  "stack": "CommandExecutionError: Failed to run dotnet publish --output publish --configuration Release --runtime win-x86 --self-contained.\n    at TabCodeProvider.doBlazorBuild (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async TabCodeProvider.build (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async TabCodeProvider.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async TeamsTab.build (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async Object.thunk (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async Promise.all (index 0)\n    at async Object.executeConcurrently (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async TeamsfxCore.deploy (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async TeamsfxCore.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)",
  "innerError": {
    "name": "CommandExecutionError",
    "details": [
      "Failed to run dotnet publish --output publish --configuration Release --runtime win-x86 --self-contained.",
      "Failed to run dotnet publish --output publish --configuration Release --runtime win-x86 --self-contained."
    ],
    "suggestions": [
      "Please run failed command 'dotnet publish --output publish --configuration Release --runtime win-x86 --self-contained' in the folder: 'C:\\Users\\KraigRury\\source\\repos\\MyTeamsApp7'.",
      "Please check the command output and try to fix it.",
      "Please retry the current step."
    ],
    "errorType": "User",
    "innerError": {
      "killed": false,
      "code": 1,
      "signal": null,
      "cmd": "dotnet publish --output publish --configuration Release --runtime win-x86 --self-contained"
    }
  },
  "userData": null,
  "timestamp": "2023-01-17T14:34:42.437Z",
  "displayMessage": null,
  "helpLink": null,
  "issueLink": null
}

**Comment by Alive-Fish** [comment]
@bemokraig Sorry for any inconvenience. Last week we were in holiday so give the delay response.

Could you tell me which extension version you have used to run "Teams Toolkit Deploy"? You can find it from "Extensions -> Manage Extensions -> Installed -> Teams Toolkit" and see the "Version" on the right.

Also, we have added the context menu as well as "Project -> Teams Toolkit" in the latest stable (17.4.4) and preview versions of Visual Studio (17.5.0 Preview 2). You can see the screenshots as below:

"Teams Toolkit" Context Menu in the stable (17.4.4) Visual Studio:
![image](https://user-images.githubusercontent.com/15262146/215235584-deeab761-9915-4ffb-a41a-09eba62e8409.png)
