### ISSUE TITLE
UpdateAadAppError: Failed to update application in Azure Active Directory. Please make sure 'templates/appPackage/aad.template.json' is valid: Request failed with status code 404

### ISSUE THREAD

**Issue by karlrez** [OfficeDev/TeamsFx#7563]
**Describe the bug**
Setting up existing AAD app fails

**To Reproduce**
1. Go to .vscode/tasks.json:
2. Update values (asterisked out for screenshot):
![image](https://user-images.githubusercontent.com/47090434/213289153-b91c16c3-b690-4e5a-b555-6a30bdc0e4c5.png)

3. See error:
![image](https://user-images.githubusercontent.com/47090434/213289264-5344cec1-24a4-4b96-858e-3b3eb306e4c0.png)

**Expected behavior**
Should be able to add existing AAD app registration

**VS Code Extension Information (please complete the following information):**
 - OS: [Windows 10]
 - Version [latest]

**CLI Information (please complete the following information):**
 - OS: [Windows 10]
 - Version [latest]

**Comment by KennethBWSong** [comment]
Hi @karlrez Thank you for using our Toolkit. Teams Toolkit will try to update your Azure AD app according to `templates/appPackages/aad.template.json` to make sure SSO works properly. Would you please first check whether this file exists in your project?

**Comment by karlrez** [comment]
Hi @KennethBWSong, the file exists with default values from the [sample code](https://github.com/OfficeDev/TeamsFx-Samples). We ran into this error after we modified the values in the screenshot above in tasks.json.

**Comment by KennethBWSong** [comment]
Hi @karlrez One potential reason is that your existing Azure AD app is configured with `oauth2Permissions`. Would you please try the following steps to update your existing Azure AD app?
1. Go to [Azure Portal](https://ms.portal.azure.com/#home), click on `Azure Active Directory`, click on `App registrations
` and find your existing Azure AD app
2. Click `Manifest` and find `oauth2Permissions`, if there is an object like following image, please update value of 'isEnabled' to `false`. If this permission is required for you, you can copy the object (with `isEnabled` = true) and paste into `oauth2Permissions` in `templates/appPackages/aad.template.json`.
3. Try local debug again
![image](https://user-images.githubusercontent.com/63089166/213608080-574251fa-22d4-44fd-a686-259fbc7a2f54.png)

**Comment by karlrez** [comment]
Hi @KennethBWSong, thanks for your help, that worked out for us.
Another question, do you know if we are able to self host a teams app? If you have a link to any documentation, it would be greatly appreciated.

**Comment by KennethBWSong** [comment]
Hi @karlrez I am quite clear what do you mean by self host a teams app. Would you please give us more info about what you want?

**Comment by karlrez** [comment]
@KennethBWSong do we have the option to deploy a teams app on a local machine or is it only Azure?

**Comment by KennethBWSong** [comment]
@karlrez For now we only have local-debug for running an app on a local machine. In the near future, we will provide more flexibility in customization, and you can then deploy your app anywhere you want, e.g. on your local machine. Thank you for your advice!
cc @adashen

**Comment by karlrez** [comment]
@KennethBWSong ok good to know, thanks for your help!

**Comment by Tuan-TIT** [comment]
Hi @KennethBWSong , I have same issue
I have been added `aad.template.json `into `templates/appPackages`. copy `id `of `oauth2Permissions` into `accessAsUserScopeId` in tasks.json

![image](https://user-images.githubusercontent.com/22438257/219316693-abf905c5-c4cd-4c87-81a0-c77e169e9533.png)

and I got an error when I debug in visual code 
![image](https://user-images.githubusercontent.com/22438257/219316921-7d5eafc1-1a28-4f9c-bafd-03c1bd78ce2e.png)

**Comment by KennethBWSong** [comment]
Hi @Tuan-TIT Thank you for using our Toolkit. This error occurs usually when failed to update your Azure AD app using Graph api. Would you please first make sure that your M365 account has the permission to update your app and all the values in `tasks.json` is correctly set. If this problem persists, would you please share your `aad.template.json` and manifest of your Azure AD app with us?
