### ISSUE TITLE
Authorisation failed in teams tab for (external) users added as quest to a team.

### ISSUE THREAD

**Issue by d-soratus** [OfficeDev/TeamsFx#7577]
When people are added as a quest to a team, and try to use a custom app (tab), they will not receive a valid token because the app is not installed in the quest's tenant.

**To Reproduce**
The OAuthAuthority property in the TeamsFx settings for the app, running in the hosts tenant is 
"OAuthAuthority": "https://login.microsoftonline.com/common"
this configuration is used in the startup of the app.

**Expected behavior**
Since the OAuthAuthority is set to /common we assume that the token is retrieved from the quests tenant. but the app isn't installed there. So the quest will not receive a valid token.

When we change the configuration to: "OAuthAuthority": "https://login.microsoftonline.com/<tenantId>", the quest receives a valid token and it works fine. 

**Additional context**
Since we initialized the app with OAuthAuthority is /common we want to be able to change the OAuthAuthority for quests.

**Comment by KennethBWSong** [comment]
Hi @d-soratus Thank you for using our toolkit. You can refer to this [wiki](https://github.com/OfficeDev/TeamsFx/wiki/Multi-tenancy-Support-for-Azure-AD-app) for multi tenancy support. Note that you need to use your Custom Domain or create an Azure CDN for your Tab app.

**Comment by d-soratus** [comment]
Dear Bowen,

Thank you for your email.
We are using TeamFx in our blazor app via .nuget
The solution mentioned in the wiki is to change aad.manifest.json, but we can’t find this file.
We make use of the configuration for teamsfx in our appSettings.json like:
"TeamsFx": {
    "Authentication": {
      …
      “OAuthAuthority”

Is it possible to add set the signInAudience to AzureADMultipleOrgs here as well?

Kind Regards,

[https://docs.google.com/uc?export=download&id=1MHhLQdn-iH9yvwCcEA6whkaNkX5OBo-w&revid=0B4PWnDuEuSZ5OW04KzJ4L2E0TWtBUlp1aFN5WWlkK0FiRUI0PQ]

Dennis Verhamme, MSc
Co-founder
+31 (0) 6 1832 7607 | ***@***.******@***.***> | www.soratus.com<http://www.soratus.com/> | KvK: 68752326

***@***.***<https://umbiko.app/>
Kijk op umbiko.app<https://umbiko.app/> voor meer informatie

**Comment by KennethBWSong** [comment]
Hi @d-soratus You can find your AAD manifest under `Templates/appPackage` in latest VS as shown below:
![image](https://user-images.githubusercontent.com/63089166/214992155-52618550-f856-4cf0-ba20-42ff4b76032f.png)
Changing `appSettings.json` won't help in your scenario since you need to update your AAD app.
