### ISSUE TITLE
Support for AAD B2C

### ISSUE THREAD

**Issue by remirobichet** [OfficeDev/TeamsFx#7578]
I went through many documentations and I still don't know if my use case is correct.

I have an existing AAD B2C tenant and I want to create a Teams Tab SSO application with TeamsFx (and with Teams Toolkit VSCode extension *which has great DX btw*).

I haven't found any tutorial/issue/roadmap indication except this issue https://github.com/MicrosoftDocs/msteams-docs/issues/7361 and this tutorial about AAD https://github.com/OfficeDev/TeamsFx/blob/dev/docs/fx-core/using-existing-aad.md

Do you have any informations on this ?

**Comment by remirobichet** [comment]
I haven't understand the Teams Tab SSO/AAD connection properly.
I'll dig deeper before opening an issue.

**Comment by chulla** [comment]
I have the same problem.

I have a tenant with Azure B2C and I want to create a tab app in Teams.

How can I use Azure B2C with SSO with the Teams app?

There is no customer registration section into Azure B2C panel 

Some example ? Thank you
