### ISSUE TITLE
Manifest validation error due to schema change

### ISSUE THREAD

**Issue by nliu-ms** [OfficeDev/TeamsFx#7737]
**Describe the bug**
The released manifest schema has been changed, e.g. https://developer.microsoft.com/en-us/json-schemas/teams/v1.14/MicrosoftTeams.schema.json

Keys ```groupchat``` has been updated to ```groupChat```.

You may meet validation error like below:
![image](https://user-images.githubusercontent.com/71362691/217988571-c18bdbdb-140a-43fe-a1d8-8cf52225a7fe.png)

We already posted this change to Teams Developer Portal team. For the workaound, please manually update your manifest.template.json or manifest.json, update ```groupchat``` to ```groupChat```. Sorry for the inconvenience.

**Comment by bgerm** [comment]
I too am receiving validations errors now.  The 1.9 schema has unexpectedly changed.  A few days ago it was `groupchat` and now it's `groupChat`.  

Old schema here:
https://web.archive.org/web/20211018043706/https://developer.microsoft.com/en-us/json-schemas/teams/v1.9/MicrosoftTeams.schema.json

**Comment by nliu-ms** [comment]
The manifest schema change has been reverted. Will close this issue.
