### ISSUE TITLE
"Something went wrong" at local debug attempt.

### ISSUE THREAD

**Issue by mattgillam** [OfficeDev/TeamsFx#7766]
**Describe the bug**

I unexpectedly see the below on a local debug attempt, on multiple project copies that previously worked perfectly.

<img width="646" alt="Screenshot 2023-02-13 at 09 16 30" src="https://user-images.githubusercontent.com/379568/218420334-c6a6e59a-56ac-48b9-8d09-8739c56d8d52.png">

The referred error message is "Error while reading manifest.json: The file could not be found in the app package."

I unpacked build/appPackage/appPackage.local.json (which is timestamped for my deployment attempt), it does contain manifest.json, I see no obvious issue.

I noticed #7737 so updated templates/appPackage/manifest.template.json to change 'group chat' to 'groupChat'. I subsequently removed the configurableTabs array that referenced groupChat - neither of these changes corrected the issue.

I also noticed #7608 - my app had groupChat in the manifest, now removed in attempt to mitigate this, but didn't use it.

**VS Code Extension Information (please complete the following information):**
 - OS: MacOs 13.1
 - Teams Toolkit Version 4.2.2

**CLI Information (please complete the following information):**
from where?

Thank you for your help.

**Comment by nliu-ms** [comment]
Hey @mattgillam , this is a known issue about bot app. Please see https://github.com/OfficeDev/TeamsFx/issues/7608. Please check the Teams channel in your bot framework, update it until the healthy status is correct. Then it should work.

Please let me know if this is your case and if the workaround works for you. Thanks!

**Comment by mattgillam** [comment]
Thank you @nliu-ms I did all the following but am still seeing the error:

* my app doesn't use any bots, though there was a reference to 'groupchat' scope in the manifest. I fixed the case to 'grpoupChat', that had no benefit, then I removed the reference from the manifest, still no difference.
* I deleted all bots from the tenant - firstly in dev.teams.micrsosft.com then the matching App Registrations in Azure Portal - except one bot that is in use by a different application to the app that I can't now run. In botframework.com that is marked as 'Running'. #7608 mentions 'healthy' status, I don't see 'healthy', only 'Running'.

So I'm still stuck, I now can't run the dev version of my app that was working perfectly, so progress on client required features, that I have a timetable to deploy this week, is stopped. Frustrating.

Do you have any other suggestions please?

Thank you.

**Comment by mattgillam** [comment]
Here's the change I made to manifest template

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/379568/218704137-cca30402-16ab-428e-b504-537940f0e61a.png">

**Comment by mattgillam** [comment]
and this is the bot's status, though as the app doesn't use it I'm am unsure how that can be relevant. 
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/379568/218749133-71bd83dd-cc2c-4ed5-a7ad-f043dcddb48c.png">

**Comment by nliu-ms** [comment]
Hey @mattgillam , we previously meet this error but usually retry can fix it. It should be some data syncing problem between Teams client and Teams Developer Portal. But from your description this error happening all the time. Can you please try to use another Teams app id as the workaround? E.g. remove the Teams app id from "state.dev.json" and provision again. Please let me know if this solution acceptable and if it works for you. Thanks!

**Comment by mattgillam** [comment]
fix for me seemed to be:
* in manifest template groupchat becomes groupChat
* in manifest template update manifestVersion to 1.13
* rename to a backup build/appPackage/aad.local.json, TeamsFx will make a new one
* rename to a backup .fx/states/state.local.json

run, a new app gets created in AAD/AppRegistrations, and a new Teams App in dev.teams.microsoft.com, new json files get created as above

if appropriate update backend to be authorised to accept connections from the new appId in aad.local.json

I've yet to try a deployment but local debug is now working.

**Comment by nliu-ms** [comment]
Thanks @mattgillam  for the detailed information. It's also similar to another issue: https://github.com/OfficeDev/TeamsFx/issues/7822. I will keep following.
