### ISSUE TITLE
By default, per-user files and properties are committed to git in TTK generated project

### ISSUE THREAD

**Issue by BobGerman** [OfficeDev/TeamsFx#7780]
**Describe the bug**
I discovered these based on feedback from @HuihuiWu-Microsoft when I submitted a TeamsFx sample. 3 issues were flagged in my PR and I believe these are due to TeamsFx - 2 were caused by the generated .gitignore and the 3rd was caused by mixing local-only data (projectId) into the projectSettings.json file.

**To Reproduce**
1. Generate a Teams app (used the Meetings app sample)
2. Use the dev environment in addition to the local environment
3. Modify the app and commit your changes
4. The following issues occur during the commit:
    a. Only the config file for the local environment is checked in (due to .gitignore rules)
    b. The state files are included for all but the local environment (due to .gitignore rules)
    c. The project ID is stored in the projectSettings.json file; @HuihuiWu-Microsoft advised this should not be committed to the repository    
    
**Expected behavior**
 - When the project changes are committed, the config files should be included (I assume this is true due to @HuihuiWu-Microsoft's comments?) - This can be fixed by removing .fx/configs/config.local.json from .gitignore
 - When the project changes are comitted, no state files should be included - This can be fixed by changing .fx/states/state.local.json to .fx/states/state.*.json in .gitignore
 - When the project changes are committed, no per-user data should be included - This could be fixed by moving the projectId out of projectSettings.json and into a file that is excluded in .gitignore

** Additional details **
See [TeamsFx-Samples PR #638](https://github.com/OfficeDev/TeamsFx-Samples/pull/638)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10
 - OS Version 10.0.19045
 - TTK Version: 4.2.2 - Feb 7, 2023

Thanks!

**Comment by HuihuiWu-Microsoft** [comment]
This should not be TTK bug. See https://github.com/OfficeDev/TeamsFx-Samples/pull/638/files/d29f63f3bd67eef8c7b2f4596d1546750e7d71cc..c5812d75ca9ae6e7cafddc832d90c93d33c1753c#r1106860266 for more details.

**Comment by HuihuiWu-Microsoft** [comment]
@BobGerman, I'll close the bug since we've clarified the sample scenario. Feel free to reopen if you still have other problems.
