### ISSUE TITLE
TeamsFX: Provision broken with DeveloperPortalAPIFailed error if manifest.template.json includes empty meetingExtensionDefinition

### ISSUE THREAD

**Issue by bemokraig** [OfficeDev/TeamsFx#7795]
Very recently provision stopped working with a typically obscure error that suggested the problem could be temporary and no path to resolution.

A tiny scrap of information led me to look at my manifest.  The error included the word MeetingExtensionDefinition.  In my manifest I had an empty placeholder.  I deleted the placeholder and voila it worked again.

This placeholder has been present forever and was empty and until now caused no issues.

I have resolved this issue for myself but offer this as a warning to others.

**To Reproduce**
Have a manifest with this object included
  "meetingExtensionDefinition": {
    "scenes": []
  }
**Expected behavior**
Prepare should work as it has in the past.

** Error Message **execute [AppManifest.provision] failed!
{
  "errorType": "SystemError",
  "source": "AppStudioPlugin",
  "name": "DeveloperPortalAPIFailed",
  "message": "API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: 6e86ce60-d46f-49a8-8161-7210f03603bf. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: \"Error mapping types.\\r\\n\\r\\nMapping types:\\r\\nApplicationManifest -> AppDefinition\\r\\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\\r\\n\\r\\nType Map configuration:\\r\\nApplicationManifest -> AppDefinition\\r\\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\\r\\n\\r\\nDestination Member:\\r\\nMeetingExtensionDefinition\\r\\n\"",
  "stack": "DeveloperPortalAPIFailed: API call to Developer Portal failed: Error, Request failed with status code 422, API name: create-app, X-Correlation-ID: 6e86ce60-d46f-49a8-8161-7210f03603bf. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: \"Error mapping types.\\r\\n\\r\\nMapping types:\\r\\nApplicationManifest -> AppDefinition\\r\\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\\r\\n\\r\\nType Map configuration:\\r\\nApplicationManifest -> AppDefinition\\r\\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\\r\\n\\r\\nDestination Member:\\r\\nMeetingExtensionDefinition\\r\\n\"\n    at Function.SystemError (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at wrapException (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at Object.importApp (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Object.createTeamsApp (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async AppManifest.provision (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async AppManifest.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async TeamsfxCore.provision (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async TeamsfxCore.<anonymous> (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)\n    at async FxCore.provisionResourcesV3 (C:\\snapshot\\TeamsFx\\packages\\server\\lib\\index.js)",
  "innerError": null,
  "userData": null,
  "timestamp": "2023-02-13T21:17:09.305Z",
  "displayMessage": "API call to Developer Portal failed: Error, Request failed with status code 422, Request path: POST /api/appdefinitions/v2/import?teamstoolkit=true&overwriteIfAppAlreadyExists=false, X-Correlation-ID: 6e86ce60-d46f-49a8-8161-7210f03603bf. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: \"Error mapping types.\\r\\n\\r\\nMapping types:\\r\\nApplicationManifest -> AppDefinition\\r\\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\\r\\n\\r\\nType Map configuration:\\r\\nApplicationManifest -> AppDefinition\\r\\nAppStudio.API.Models.ApplicationManifest -> AppStudio.API.Models.AppDefinition\\r\\n\\r\\nDestination Member:\\r\\nMeetingExtensionDefinition\\r\\n\"",
  "helpLink": null,

**Comment by Githamza** [comment]
any updates ?
