### ISSUE TITLE
Issue on mobile client - API calls returns status cancelled

### ISSUE THREAD

**Issue by karlrez** [OfficeDev/TeamsFx#7813]
**Describe the bug**
I have a Teams Tab app which serves as another front end for our application (I will call it App 1) and we just use the client id for App 1 to authenticate. This works fine on Teams desktop and web, but on teams mobile (Android) I can successfully obtain a bearer token, but the rest of the api calls return status cancelled.

After following the sample SSO example, were there any additional steps required for mobile? Any suggestions would be greatly appreciated. 

**To Reproduce**
1. Go to teams app on mobile 
2. Sign in
3. All further api calls return status cancelled

**Expected behavior**
App should successfully call api

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: [Windows]
 - Version [latest]

**CLI Information (please complete the following information):**
 - OS: [Windows]
 - Version [latest]

**Additional context**

**Comment by KennethBWSong** [comment]
@karlrez Thank you for using our Toolkit! To help us trouble shooting your problem, we want to learn more about it:
1. Would you please give us a simple sample (not your business code) on how you implement the authorization in your Teams app?
2. You said you can obtain a token on mobile. Is this token SSO token or Access Token? Can you try to use other tools (like Postman) to call your api with this token?

**Comment by karlrez** [comment]
Hi @KennethBWSong below is my implementation of how I obtain the bearer access token. While debugging the mobile app, I am able to see the call to graph api does return the token, and I can then use that token in Postman to make calls to our api. However in teams mobile app the same api calls return status cancelled. 

LoginForm.jsx
```
const { teamsUserCredential } = useContext(TeamsFxContext);
   const { loading, error, data, reload } = useGraphWithCredential(
   
   async (graph, teamsUserCredential, scope) => {
     const provider = new TeamsFxProvider(teamsUserCredential, scope);
     Providers.globalProvider = provider;
     Providers.globalProvider.setState(ProviderState.SignedIn);

    if (teamsUserCredential.ssoToken === null) {
      setTeamsLoginError(true); // flag to switch to web auth flow
    }

    if (error) {
      setTeamsLoginError(true);
    }
  },

   { scope: ["User.Read"], credential: teamsUserCredential }
  );

  // for web auth flow
  const onClick = async () = {
    await login(instance)
  }
```

App.jsx
```
const { theme, themeString, teamsUserCredential, error, loading } =
  useTeamsUserCredential({
    initiateLoginEndpoint:
    "https://{teams app site name}.web.core.windows.net/auth-start.html",
    clientId: "{client id for App 1}", // not the teams app client id
  });

const {
  instance,
  accounts,
} = useMsal();

// SSO auth flow
if (!teamsLoginError) {
  let newAccessToken;
  try {
    newAccessToken = await teamsUserCredential.getToken(
    "api://{client id for App 1}/access_as_user"
    );
  } catch (error) {
      console.log("error getting token");
    }

  const token = `Bearer ${newAccessToken.token}`;
}

// auth flow for web clients
else {
  const accessTokenRequest = {
      scopes: ["api://{client id for App 1}/access_as_user"],
      account: accounts[0],
    };

    instance
      .acquireTokenSilent(accessTokenRequest)
      .then(async (accessTokenResponse) => {
        let newAccessToken = accessTokenResponse.accessToken;
        const token = `Bearer ${newAccessToken}`;
}
```

**Comment by KennethBWSong** [comment]
Hi @karlrez Since access token is successfully obtained and you can call your api successfully with Postman, I think this error may be caused by your code to call your api. Would you please give us some sample on you call the api in your Teams app?

**Comment by karlrez** [comment]
This is how it looks:

helper.js
```
  // Helper methods for http requests
  GET: async function (accessToken, url) {
    let requestOptions = {
      method: "GET",
      headers: {
        Authorization: accessToken,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    };

    let res;

    try {
      const data = await fetch(url, requestOptions).catch(function (err) {
        console.log(err);
      });
      res = await data.json();
    } catch (err) {
      console.log(`error on GET at ${url}`);
    }
    return res;
  },
};
```

App.js
```
let apiRequest = await helper.GET(accessToken, url);
```

This does work on the desktop client and web client, but unfortunately I do not have access to see the logs on the server side for why I am recieving api response cancelled on mobile.

**Comment by KennethBWSong** [comment]
Hi @karlrez I use the same code to use access token to call Graph API("https://graph.microsoft.com/v1.0/me") and the app works well on IOS. I will later have a try on Android , and would you please also have a try to call other API (such as the API above) to see whether the bug comes from your source code or your backend service?

**Comment by karlrez** [comment]
Hi @KennethBWSong thank you for the suggestions, I am able to call that Graph API you mentioned. 

When I call our internal api it shows as preflight and then shows as cancelled with these headers:
![image](https://user-images.githubusercontent.com/47090434/221679937-120ccf13-1f56-4180-ac0a-c52476cf7194.png)

I also tested with another test api and these are the headers on a successful call:
![image](https://user-images.githubusercontent.com/47090434/221681598-d34c7a1c-0c87-47db-aa3e-c36731b5ebe5.png)

From this, do you see any reason as to why our requests are getting canceled? Our api is not logging any CORS errors and I cant find any trace of our requests even reaching the server.

**Comment by KennethBWSong** [comment]
@karlrez Sorry I don't have much info about how your server works. Maybe you can try this [question](https://stackoverflow.com/questions/2896623/how-to-prevent-my-site-page-to-be-loaded-via-3rd-party-site-frame-of-iframe/2896705#2896705)?

**Comment by karlrez** [comment]
@KennethBWSong Thank you for the suggestion, but I wasn't able to resolve the issue with calling our api. Do you know of any other differences between teams mobile and desktop client?

**Comment by Sa-So** [comment]
As this issue has been marked completed can I know how was this issue resolved ? I am currently facing a similar issue

**Comment by karlrez** [comment]
@Sa-So This ended up being an issue with our ssl cert on the server. Was missing the ca-bundle file, so adding that in resolved the issue.
