### ISSUE TITLE
Teams toolkit 4.2.2. and 4.2.3 problem

### ISSUE THREAD

**Issue by mstefanec77** [OfficeDev/TeamsFx#7822]
Type: <b>Bug</b>

When debugging MS teams bot following message apears in the browser running MS Teams: 

Error while reading manifest.json: The file could not be found in the app package.

Debugging can not start as app can not be added to MS Teams

Extension version: 4.2.3
VS Code version: Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf, 2023-02-08T21:32:34.589Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.59GB (3.89GB free)|
|Process Argv|--crash-reporter-id 8377359f-694e-4591-97ac-806c37bc4b4f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30662994
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30662992
f6dab269:30613381
pythonsymbol12cf:30657549
a9j8j154:30646983
vsctsb:30662444

```

</details>

**Comment by nliu-ms** [comment]
Hey @mstefanec77 , thank you for reporting this bug. It might be an intermittent error from server side.

1) Can you find this app from Teams Developer Portal? https://dev.teams.microsoft.com/
2) If you can find the app, can you please check if manifest can be found from Teams Developer Portal?
![image](https://user-images.githubusercontent.com/71362691/220273820-67fcce99-336d-4e3c-8829-090d8f9b328f.png)
3) If manifest can be found, can you please try to Preview the app from Teams Developer Portal to see if it works?
![image](https://user-images.githubusercontent.com/71362691/220273680-2626a55d-1163-4c15-960a-49922f9a621c.png)

If you can find the app, the manifest can be found from Teams Developer Portal, and when you Preview in Teams from Teams Developer Portal it still meet the same error. You may need to use another Teams app id as the workaround. 

Please let me know your execution result, then I can collect more information and report this to Teams Developer Portal team. Thank you!

**Comment by mstefanec77** [comment]
Answer to all your questions is yes. I can find the app, see its manifest and preview it is Teams.
But I still can not debug it with Visual Studio code and TeamsToolkit.

This problem I have only with TeamsToolkit 4.2.2 and 4.2.3. When I downgrade to 4.2.1 everything in working normal and I can debug the bot I wrote without any problems.

**Comment by nliu-ms** [comment]
@mstefanec77 Thanks for your quick reply. Would you mind providing your zip app package to me to reproduce the error? Or providing more detailed repro steps. I'm trying to reproduce the error. Thank you.

**Comment by mstefanec77** [comment]
App package attached. Bot was developed and tested using TeamsToolkit 4.2.1. Debugging from the MS Visual Studio code was started and executed without any problems, both in Edge and Chrome. 
Update to TeamsToolkit 4.2.3 happened automatically. After the update I could not debug the app due to the reported error. When I roll back version of TeamsToolkit to 4.2.1. I can again debug the app without any problems. Same issue I have with 4.2.2. So I would say problem appeared somewhere in 4.2.2. and was propagated to 4.2.3.

[appPackage.local.zip](https://github.com/OfficeDev/TeamsFx/files/10802208/appPackage.local.zip)

**Comment by nliu-ms** [comment]
Thanks @mstefanec77 , it's very helpful. I will investigate more and get back to you.

**Comment by nliu-ms** [comment]
With some investigation, the issue may come from the icons or translation file is on a different regional endpoint vs the manifest. We started to use regional endpoint from 4.2.2 version.

Next time when you meet this error again, can you please go to [Teams Developer Portal](https://dev.teams.microsoft.com/apps), find your app and check if icons exist in app package to check if it is the case. As suggested from Teams Developer Portal team, a simple mitigation is re-upload icons from Teams Developer Portal.
![image](https://user-images.githubusercontent.com/71362691/222615631-f4a9189f-0515-4219-a8b7-4e116ddaee0b.png)

**Comment by mstefanec77** [comment]
Hi. I see TeamsToolkit 4.2.4 is out. This issue does not exist any lonfer in 4.2.4. Everything is working as before, without any modifications from my side.

**Comment by nliu-ms** [comment]
Thanks @mstefanec77 for the updates! I will close this issue has it has been mitigated.
