### ISSUE TITLE
Microsoft Teams Extension receives an ConsentFailed error when tryin to start authentication in Microsoft Teams Desktop

### ISSUE THREAD

**Issue by JonatanMedinilla** [OfficeDev/TeamsFx#7823]
**Describe the bug**
I have an app in meeting extension that requires the consent of the user to get access to an API. When the app starts the authentication flow, Teams shows the consent popup but the extension doesn't wait for the _appAuthWindow_(popup) notification and immediately gets a ConsentFailed error message saying `Consent failed for the scope api://<valid-domain>/<app-id/.default`. 

**Error stack trace**
`"ErrorWithCode.ConsentFailed: Consent failed for the scope api://<valid-domain>/<app-id/.default with error: 
    at TeamsUserCredential.login (https://6754-190-55-159-5.ngrok.io/static/js/bundle.js:89159:13)
    at async TeamsFx.login (https://6754-190-55-159-5.ngrok.io/static/js/bundle.js:89965:5)
    at async login (https://6754-190-55-159-5.ngrok.io/static/js/bundle.js:1737:3)
    at async https://6754-190-55-159-5.ngrok.io/static/js/bundle.js:1030:17"`

Despite the error, the user is able to give consent through the consent popup, but he must close the meeting side panel and open it again to be able to use the extension.

However, this error doesn't happen when I try the same flow using the Microsoft Teams Web client.

**Expected behavior**
After calling teamsFx.login(scopes), the meeting extension should wait for the popup consent notification.

**Screenshots**

**Example of consent scenario in Microsoft Teams Desktop client**
![image](https://user-images.githubusercontent.com/23441277/219696140-c94cf716-a928-4e1d-9fc0-f9fae12df8e3.png)

**Example of consent scenario in Microsoft Teams Web client**
![image](https://user-images.githubusercontent.com/23441277/219696000-e8997102-ef04-4773-a3fc-1d9922c70242.png)

**Additional context**
Despite using TeamsFX to create the extension, we are using ngrok to run the extension locally because the app registrations were created in Tenant A and we are running the extension in Tenant B.

As mentioned before, this works well in Teams Web client.

OS: Windows 11
Microsoft Teams Version 1.6.00.1381 (64-bit).
@microsoft/teamsfx: 2.0.0
@microsoft/teams-js: 2.7.1
@azure/msal-browser: 2.25.0 (as recommended in this [issue](https://github.com/OfficeDev/TeamsFx/issues/7532)

**Comment by KennethBWSong** [comment]
Hi @JonatanMedinilla Thank you for using our Toolkit! I can reproduce this bug. We will investigate this bug and reach out to you as soon as we find any solution.

**Comment by KennethBWSong** [comment]
Hi @JonatanMedinilla I create an [issue](https://github.com/OfficeDev/microsoft-teams-library-js/issues/1601) in Teams SDK repo, and will update here if we have any update.

**Comment by adashen** [comment]
Close here and track in the upstream issue
