### ISSUE TITLE
Need a way to detect mobile devices due to unique Teams UserAgent.

### ISSUE THREAD

**Issue by wrharper-AASP** [OfficeDev/TeamsFx#7865]
**Is your feature request related to a problem? Please describe.**
I need to load a different version of the app with a completely different layout if it is a mobile device.

**Describe the solution you'd like**
Need something like:
```
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        await base.OnAfterRenderAsync(firstRender);

        if (firstRender)
        {
if (await MicrosoftTeams.DeviceType == DeviceType.Mobile)
        stuff goes here
else
        different stuff goes here
```

**Describe alternatives you've considered**
I am currently using a javascript window size detection method and when the height is greater than the width, it is mobile, but as you can probably tell, this comes with possible downsides.
Normally, you would target the useragent like this: https://www.syncfusion.com/faq/blazor/javascript-interop/how-do-you-detect-whether-a-page-is-loaded-in-mobile-or-on-desktop#:~:text=There%20is%20no%20direct%20way,include%20the%20isDevice%20method%20call.

**Comment by davrous** [comment]
Hello @wrharper-AASP , a Teams app built with the Teams Toolkit is still a web app so the classical patterns to manage mobiles are the same. You can either use CSS and Media Queries to modify the layout for small devices or test the navigator.userAgent like in the article you've shared. The property will be properly filled even if a Teams app. Did you have an issue using this approach?

**Comment by AASPLLC** [comment]
The navigator.useragent from my experience just says it's Teams. It doesn't help in indicating if it's mobile? That's the part that is an issue since it is a Teams User Agent and not a normal browser agent.

**Comment by wrharper-AASP** [comment]
I found keyword "TeamsMobile-Android", just need IOS, MAC, and how to determine Linux. I'm also afraid of how reliable this is. Will it be TeamsMobile-Android across "all" versions of the Android OS? At this point, it isn't an issue with TeamsFx I guess and more of an issue with Teams itself.
