### ISSUE TITLE
VS Samples aren't initating pop-up when I clicked 'prepare teams app dependencies'

### ISSUE THREAD

**Issue by aycabas** [OfficeDev/TeamsFx#7896]
**Describe the bug**
Teams Toolkit Visual Studio samples in the TeamsFx-samples repo aren't initiating pop-up when I clicked "prepare teams app dependencies" before running the app.

**To Reproduce**
 I forked the repo > opened the repo folder on my desktop > found the project I'd like to run (One Productivity Hub .NET Core) > double-clicked on the .csproj file to open the project in VS > right-clicked to the project to select Teams Toolkit and then Prepare teams app dependencies > no pop-up, no action

**Expected behavior**
app doesn't run because app dependencies weren't prepared

**VS Extension Information:**
 - OS: Windows 11
 - Visual Studio 2022 v17.5.0
 - Teams Toolkit v17.5.92

**Comment by Alive-Fish** [comment]
Hi @aycabas, thanks for reporting this issue. I found that this template has no `projectId` in the `.fx/configs/projectSettings.json`. You can generate a GUID through `Tools -> Create GUID` and set it into the file. Also, this has been fixed in the 17.6 Preview 2 (which will be ship on March 14th).
