### ISSUE TITLE
Adopt `dotenv over` env-cmd

### ISSUE THREAD

**Issue by AbhijithGanesh** [OfficeDev/TeamsFx#7904]
## Is your feature request related to a problem? Please describe.

It isn't a problem per se but it uses an old package that hasn't been updated in 3 years

### Usage of dotenv

Most samples donot involve the usage of environment variables so no special provisioning is usually done, but in some cases like [this](https://github.com/OfficeDev/TeamsFx-Samples/blob/v1.1.0/bot-sso/bot/package.json), `env-cmd` is used as a package to handle environment variables. Usually [dotenv](https://www.npmjs.com/package/dotenv) is used. Can we migrate from env-cmd to dotenv?

**Comment by AbhijithGanesh** [comment]
@jayzhang @adashen Can I work on the patch as well ! It is not a major issue.

**Comment by swatDong** [comment]
@AbhijithGanesh Thanks for the feedback. Per my understand, `dotenv` is more like a runtime package that needs to be called from source code, so should be a dependency. However, `env-cmd` can be called via CLI (e.g., from NPM script), so could be just a dev dependency.

Could you please share more about how `env-cmd` blocks your scenario? Or, would [dotenv-cli](https://www.npmjs.com/package/dotenv-cli) be an alternative since it's newer than `env-cmd` and also CLI compatible?

**Comment by AbhijithGanesh** [comment]
@swatDong, that does make sense but unfortunately, env-cmd doesn't work with this case.

Let us say my Windows Account home folder is like this
`C:\Users\Rick and Morty`
Now, that space between `Rick` and `and` causes trouble for the node CLI to understand, that is why I felt `dotenv` will be a better alternative. When `npm run` is called, the file will be executed and it will still load the environment values. All that needs to be done is it should be imported accordingly!

**Comment by AbhijithGanesh** [comment]
Also, one can include the `.env` in the main file!

**Comment by swatDong** [comment]
@AbhijithGanesh Yep, agree that `dotenv` can handle more scenarios such as special path and multiple `.env` files. And the current samples do not have any limitation on using `dotenv`.

However, for the default generated samples, still need a CLI-compatible way, to provide a unified solution as simple as possible. Points are:
- `.env.teamsfx.local` is an env file which not only targets on runtime, but also can work on build time or pack time.
- A CLI-compatible way can load any environment variables before running npm script
- There're also some frontend samples (e.g., [tabs](https://github.com/OfficeDev/TeamsFx-Samples/blob/v1.1.0/hello-world-tab/tabs/package.json)) which cannot use `dotenv` in its React code

If it's really a problem that `env-cmd` is a bit older, may consider `dotenv-cli`, or adding doc/comment for the `dotenv` alternative. But for the default generated code, I prefer dependencies as less as possible.

**Comment by AbhijithGanesh** [comment]
Actually considering the use case, we can use `dotenv` as a default solution and `dotenv-cli` wherever it's specifically required

**Comment by swatDong** [comment]
Thanks for the case and suggestion, I've created our backlog item to track, to replace `env-cmd` with newer package and see if could directly use `dotenv`.

**Comment by AbhijithGanesh** [comment]
Is it possible for me to send in the patch?

**Comment by swatDong** [comment]
Welcome to contribute. And if contributing to the [samples](https://github.com/OfficeDev/TeamsFx-Samples), please base on the `dev` branch.
