### ISSUE TITLE
Ampersands not showing correctly in appName and appDescription in manifest

### ISSUE THREAD

**Issue by joshua-d-brown** [OfficeDev/TeamsFx#8049]
**Describe the bug**
When there is a & in the app name or app description properties in the config JSON, it gets rendered as `&amp;` in the manifest.

**To Reproduce**
1. Put text containing & in the "short" or "full" values for the "appName" or "appDescription" properties in a config JSON file
2. Zip the Teams metadata package or preview the manifest from the file view.
3. View the generated manifest file.

**Expected behavior**
Expected behavior: The name of the app would appear with &, for example, "Stop & Think".
Actual behavior: The name of the app appears with `&amp;`, for example, "Stop `&amp;` Think".

**VS Code Extension Information (please complete the following information):**
 - OS: macOS Ventura
 - Version 4.2.4

**Comment by nliu-ms** [comment]
Hey @joshua-d-brown , the templates are rendered with [mustache.js](https://github.com/janl/mustache.js), and it's HTML-escaped by default. You can use triple {} to avoid this error. E.g. in manifest:

```
"name": {
      "short": "{{{config.manifest.appName.short}}}",
      "full": "{{{config.manifest.description.short}}}"
},
```
Please let me know if it works for you, thanks!

**Comment by joshua-d-brown** [comment]
That worked, thank you. I had no idea about the mustache templating.
