### ISSUE TITLE
Error with components in Tab template

### ISSUE THREAD

**Issue by AbhijithGanesh** [OfficeDev/TeamsFx#8063]
**Describe the bug**
The components donot compile on TypeScript

**To Reproduce**
1. Go to this [link](https://github.com/OfficeDev/TeamsFx/blob/dev/templates/tab/ts/m365/src/components/App.tsx)
2. Compile the code
3. Scroll down to [33-35](https://github.com/OfficeDev/TeamsFx/blob/e103494128dab61bbd369b6b9e9015ecc4b1892f/templates/tab/ts/m365/src/components/App.tsx#L33-L36)
4. See Error

![image](https://user-images.githubusercontent.com/67182544/225380657-5ccbb401-5a92-492e-bad0-2a031c06b039.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/67182544/225384694-991e6d43-92fe-4bc1-ae58-47344567f9ad.png)

**VS Code Extension Information (please complete the following information):**
 - OS: Fedora
 - Version 37
 

**Additional context**
![image](https://user-images.githubusercontent.com/67182544/225384590-7d037cc4-76f6-46e9-8ac7-f210e2338069.png)

**Comment by hund030** [comment]
@AbhijithGanesh Do you start your web app by the command `npm run dev:teamsfx` or through F5 in VS Code?  [sample](https://github.com/OfficeDev/TeamsFx/blob/dev/templates/tab/ts/m365/package.json#L30).
And could you please check your .env.teamsfx.local file, if these environment variable are set
```
REACT_APP_START_LOGIN_PAGE_URL=
REACT_APP_CLIENT_ID=
```
If no, please ensure you successfully run F5 in VS Code.

**Comment by AbhijithGanesh** [comment]
I did

**Comment by hund030** [comment]
@AbhijithGanesh Seems there are type pacakge conflicts in your project. You can first try adding typeRoot config in your tsconfig.json file.
```
{
  "compilerOptions": {
    ...
    "typeRoots": ["./node_modules/@types"]
  }
}
```
If it doesn't work, could you provide your node and npm version for further investigation?
