### ISSUE TITLE
Error with another Example

### ISSUE THREAD

**Issue by AbhijithGanesh** [OfficeDev/TeamsFx#8064]
**Describe the bug**
The code just breaks when we try compiling!

**Expected behavior**
I expect the example to work smoothly!

**Screenshots**
![image](https://user-images.githubusercontent.com/67182544/225412272-88bbe33d-1cec-4aa6-8f35-b071e3e81fee.png)

**VS Code Extension Information (please complete the following information):**
 - OS: Fedora 
 - Version 37

**Comment by HuihuiWu-Microsoft** [comment]
Hi @AbhijithGanesh, as indicated in console log, your Node.js version is not supported to run Teams Toolkit. Please install supported version to run SPFx sample following https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-nodejs

**Comment by AbhijithGanesh** [comment]
> Hi @AbhijithGanesh, as indicated in console log, your Node.js version is not supported to run Teams Toolkit. Please install supported version to run SPFx sample following https://learn.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-nodejs

The version which got cropped off shows 16.14.0 if you can closely look

**Comment by HuihuiWu-Microsoft** [comment]
@AbhijithGanesh Yes, I can see that with really closely look. If you're using 16.14.0, everything should work fine. So your current problem should be: you have 16.14.0 installed but Teams Toolkit detected Node.js 18.12.1, right?

**Comment by AbhijithGanesh** [comment]
I'm closing this issue as I feel this has more to do with the ecosystem more than the codebase. Thanks. :)
