### ISSUE TITLE
VisualStudio: Support Graph SDK Version 5.2

### ISSUE THREAD

**Issue by thomyg** [OfficeDev/TeamsFx#8089]
Graph dotnet SDK 5.0 introduced some breaking changes in terms of authentication with missing interfaces and base classes when you try it with the latest TeamsFx version. Problem is the IAuthenticationProvider interface of MSGraphAuthProvider which isn't part of the SDK any more.

In order to "fix" that, you could remove the dependencies generated by MSGraphAuthProvider.cs by just deleting the class as such and update TeamsFx.cs by handing over the TokenCredential directly to the GraphServiceClient constructor. Plus, one needs to get rid of the authlogger of TeamsFx.cs as well, as it is based on MSGraphAuthProvider as a type. 

A working example with changes applied can be found at https://github.com/selectedtech/M365AIMate/blob/TeamsFxGraphSDK5/TeamsFx/TeamsFx.cs The branch "TeamsFxGraphSDK5" was created specifically to document this issue.

**Comment by yiqing-zhao** [comment]
Hi @thomyg,

Thank you for raising this issue and providing a working example of your solution. We appreciate your insight and feedback. We are currently investigating the compatibility of TeamsFx with Graph SDK Version 5.2 and will get back to you if we have any updates. Please stay tuned.

**Comment by Ericvf** [comment]
+1 for supporting the latest version (v5.5.0) of the Microsoft Graph package. We can update our app but it will not run. 

Why is the Microsoft.TeamsFx package not updated more frequently. The current release is months old...

**Comment by yiqing-zhao** [comment]
Hello @Ericvf, thanks for your comments. We are currently updating the TeamsFx package, and new version that supports Graph SDK 5.x will be released soon.

**Comment by Ericvf** [comment]
This is great, thanks for the response. My corporate client would like to know if you have a ETA for thie release? Just as an estimation, is there a public backlog/roadmap somewhere that could indicate this?

**Comment by yiqing-zhao** [comment]
@Ericvf, we are sorry but we don't have a public backlog. The ETA for SDK is before May. We will also update here once we release the SDK.

**Comment by yiqing-zhao** [comment]
Greetings @Ericvf and @thomyg, we are excited to announce the launch of TeamsFx 2.0.0. You can upgrade your existing project by following the steps [here](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/dotnet-sdk/README.md#upgrade-from-1xx-to-200). You can also check out this pull request (https://github.com/OfficeDev/TeamsFx/pull/8421) for more information. Please let us know if you encounter any problems, we appreciate your feedback!

**Comment by Ericvf** [comment]
Thanks a lot for the update, the migration to the latest version went quick and smoothly.
