### ISSUE TITLE
No targets under bot.notification.installations()

### ISSUE THREAD

**Issue by wangzelin007** [OfficeDev/TeamsFx#8112]
**Describe the bug**

Although I have installed this local teams bot to myself and a channel, the targets are still empty.

**To Reproduce**
1. create a new teams app with Teams Tookit
2. Press F5 to debug and preview Teams app
![image](https://user-images.githubusercontent.com/18628534/226559645-4dc2a030-f0e1-430a-89f0-58c1e3588ac1.png)

3. install local teams app to myself and a channel
![image](https://user-images.githubusercontent.com/18628534/226558938-6d662b07-c475-42da-899e-576c0a88abf6.png)
![image](https://user-images.githubusercontent.com/18628534/226559193-e3f15a07-27b5-4035-8b38-d38b712c0eb0.png)

4. get all target under bot.notification.installations()
```
const targets = await bot.notification.installations()
console.log(`Found ${targets.length} targets under ${JSON.stringify(targets)}`)
```
5. The targets are still empty.
![image](https://user-images.githubusercontent.com/18628534/226558842-6c39e978-314d-417f-b855-7e29821bbbd9.png)

**Expected behavior**
Can get two target, a personal target and a channel target.

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by qinezh** [comment]
Teams sends an event only at the first installation. If the bot app is already installed before your notification bot service is launched, the installation event, either didn't reach the bot service, or is omitted.

You can resolve this in the following ways:

- Send a message to your personal bot or mention your bot in group chat, or channel, which helps you to reach the bot service again with correct installation information.
- Uninstall the bot app from Teams then redebug or relaunch it. You can resend the installation event to bot service.

Notification target connections are stored in the persistence storage. If you're using the default local file storage, all installations are stored under `bot/.notification.localstore.json`, you could also check if the file is empty.

**Comment by wangzelin007** [comment]
Thanks for the help, after trying it, the problem has been solved
