### ISSUE TITLE
In local dev mode my app frequently does not load in browser, seeing Teams 'Apps' landing page

### ISSUE THREAD

**Issue by mattgillam** [OfficeDev/TeamsFx#8150]
**Describe the bug**

In local dev mode my app frequently does not load, browser shows only normal Teams entry page.

Other times the app loads perfectly.

I can't tell a difference between circumstances to reproduce. Sometimes successive attempts with no changes can load or fail.

**To Reproduce**

Intermittent but frequent fault, can't reproduce reliably.

** Screenshot **

Teams landing page, 'Apps' app.

**Expected behavior**

My app should reliably load in local dev mode.

**VS Code Extension Information (please complete the following information):**
 - OS: MacOS
 - Version 4.2.4

**CLI Information (please complete the following information):**
 - OS: MacOS
 - Version Azure CLI? 2.46.0

**Comment by kuojianlu** [comment]
Hi @mattgillam, thanks for reporting. This is a known issue of Teams web client. To mitigate this issue from Teams Toolkit side, when you encounter this issue again, you can copy the launch url from Teams Toolkit output channel in VS Code and manually open the launch url in your browser (that is to say, you do not need to stop F5 and retry F5, which is a little time-consuming).
![image](https://user-images.githubusercontent.com/37978464/228432317-558a6019-a6a5-4091-bbdf-9ee79dc6a777.png)

**Comment by mattgillam** [comment]
OK thanks. (yes it can be quite time consuming!0.
