### ISSUE TITLE
Unable to post to graph api SharePoint sites using application permission

### ISSUE THREAD

**Issue by ITAndy23** [OfficeDev/TeamsFx#8221]
**Describe the bug**
After scaffolding a SSO personal tab teamsfx project using Teamsfx toolkit. Users are unable to write to SharePoint list using the identity of the app registration. I gave the app registration 
Sites.ReadWrite.All. However, end users ended up getting access denied during POST operations. I switched to Delegated then i had to give users Contribute access to the site for it work. Also, had to expand permissions at the list's settings item-level permissions to Read all items and Create and edit all items so the graph calls would work. 
Is this normal or is this a bug

**To Reproduce**
1. Create a new project using personal tab SSO
2. Follow steps to deploy and publish
3. Add Sites.ReadWrite.All 
4. Add your code to POST to a SharePoint list
5. Users without access to the list will get access denied 

**Expected behavior**
Expect the application to write to the list under it's own identity using its permissions in the app registration vs attempting to use the user's identity. 

**Screenshots**

**VS Code Extension Information (please complete the following information):**
Windows 11
VS Code 1.76.2+
Teams Toolkit v4.2.4

**CLI Information (please complete the following information):**
TeamsFx Cli 1.2.2

**Additional context**

**Comment by KennethBWSong** [comment]
Hi @ITAndy23 Thank you for using our Toolkit. Would you please give us a simple sample (not your production code) on how your call SharePoint list API?

**Comment by ITAndy23** [comment]
Hi, i have a central service my GET/POST calls use. Essentially, the service looks like this:
@KennethBWSong 

*** Imports....
`import { createMicrosoftGraphClient, TeamsFx } from '@microsoft/teamsfx';`
other imports... ***

`someGetFunction = async(url:string)=>{`
    `const teamsfx = new TeamsFx();`
    `const graph = createMicrosoftGraphClient(teamsfx);`
    `const results = await graph.api(url).version('v1.0').get();`
    `return results`
`}
`
*** Skipped the try/catch and options block to focus on the core of the api call

**Comment by KennethBWSong** [comment]
Hi @ITAndy23 I am afraid that you are still using User Credential to call graph api with following code. Would you please have a try with code like below?
```
someGetFunction = async(url:string)=>{
  const teamsfx = new TeamsFx("Application");
  const graph = createMicrosoftGraphClient(teamsfx);
  const results = await graph.api(url).version('v1.0').get();
  return results
} 
```

**Comment by ITAndy23** [comment]
Hi @KennethBWSong, Only difference i see you in your response is specifying "Application" as parameter to TeamsFx. After trying that, i got typescript error: 
`Argument of type '"Application"' is not assignable to parameter of type 'IdentityType | undefined'.`

I imported IdentityType so now my import line looks like:
`import { createMicrosoftGraphClient, TeamsFx,IdentityType } from '@microsoft/teamsfx';`

Updated the teamsFx lines to look like the following:
`const teamsfx = new TeamsFx(IdentityType.App);`

Now I see the following error in dev tools and none of my graph calls load:
Uncaught (in promise) ErrorWithCode.IdentityTypeNotSupported: Application identity is not supported in TeamsFx
    at new TeamsFx (https://localhost:53000/static/js/bundle.js:216230:13)
    at getGraph (https://localhost:53000/static/js/bundle.js:6219:19)
    at requests (https://localhost:53000/static/js/bundle.js:4170:88)

FetchClient.ts:58          POST https://login.microsoftonline.com/b1fccc08-e170-4e18-a5d2-7a62fe61a082/oauth2/v2.0/token 400 (Bad Request)

I see the following on the network tab for token:
AADSTS65001: The user or administrator has not consented to use the application with ID 'AppId' named 'AppName'. Send an interactive authorization request for this user and resource.\r\nTrace ID: d6c9bfe0-6391-43c8-993f-3ed469dd0e00\r\nCorrelation ID: c778b803-58fc-4907-a6df-d265edda7768\r\nTimestamp: 2023-04-12 09:27:18Z

I reviewed the AppId in Azure and all permissions have been consented with Delegated(Is this the issue?)
![image](https://user-images.githubusercontent.com/5934563/231417597-7c6344c6-865b-4c33-996b-06263c5be9e6.png)

**Comment by ITAndy23** [comment]
@KennethBWSong 
Hi,
I granted app permission for Sites.ReadWrite.All:
![image](https://user-images.githubusercontent.com/5934563/231521664-a0899c39-66f3-435f-9513-55888df1b7a0.png)

I still see the same error in the console:
teamsfx.browser.ts:34 Uncaught (in promise) ErrorWithCode.IdentityTypeNotSupported: Application identity is not supported in TeamsFx
    at new TeamsFx (https://localhost:53000/static/js/bundle.js:216230:13)
    at getGraph (https://localhost:53000/static/js/bundle.js:6219:19)
    at getTeams (https://localhost:53000/static/js/bundle.js:3047:87)
    at https://localhost:53000/static/js/bundle.js:3062:7
    at commitHookEffectListMount (https://localhost:53000/static/js/bundle.js:296858:30)
    at commitPassiveHookEffects (https://localhost:53000/static/js/bundle.js:296890:15)
    at HTMLUnknownElement.callCallback (https://localhost:53000/static/js/bundle.js:279937:18)
    at Object.invokeGuardedCallbackDev (https://localhost:53000/static/js/bundle.js:279981:20)
    at invokeGuardedCallback (https://localhost:53000/static/js/bundle.js:280029:35)
    at flushPassiveEffectsImpl (https://localhost:53000/static/js/bundle.js:299520:13)

teamsfx.browser.ts:34 Uncaught (in promise) ErrorWithCode.IdentityTypeNotSupported: Application identity is not supported in TeamsFx
    at new TeamsFx (https://localhost:53000/static/js/bundle.js:216230:13)
    at getGraph (https://localhost:53000/static/js/bundle.js:6219:19)
    at requests (https://localhost:53000/static/js/bundle.js:4170:88)

I notice the constructor for teamsfx.browser.ts has the following:

`
this.identityType = identityType ?? IdentityType.User; 

    if (this.identityType !== IdentityType.User) {
      const errorMsg = formatString(
        ErrorMessage.IdentityTypeNotSupported,
        this.identityType.toString(),
        "TeamsFx"
      );
      internalLogger.error(errorMsg);
      throw new ErrorWithCode(errorMsg, ErrorCode.IdentityTypeNotSupported);
    }
`
If i'm reading it correctly it sounds like teamsfx is always expecting a user identity and not app

Thanks

**Comment by KennethBWSong** [comment]
> Hi, i have a central service my GET/POST calls use. Essentially, the service looks like this: @KennethBWSong
> 
> *** Imports.... `import { createMicrosoftGraphClient, TeamsFx } from '@microsoft/teamsfx';` other imports... ***
> 
> `someGetFunction = async(url:string)=>{` `const teamsfx = new TeamsFx();` `const graph = createMicrosoftGraphClient(teamsfx);` `const results = await graph.api(url).version('v1.0').get();` `return results` `} ` *** Skipped the try/catch and options block to focus on the core of the api call

Hi @ITAndy23 From you above message I thought you are implementing the code in your server side code, and [TeamsFx SDK](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/sdk/src/credential/appCredential.ts) only support using app credential from server side. However, the error message seems saying you are calling from frontend? Would you please clarify where do you implement the code to get access token?

**Comment by ITAndy23** [comment]
@KennethBWSong yes, this is all client-side code, react using typescript.
Apologies if I was unclear. I thought teamsfx could handle REST calls to graph under the identity of the app registration with the correct api permissions consented?

**Comment by ITAndy23** [comment]
Hi @KennethBWSong , sounds like this may not be an issue after all and instead a discussion. 
The security concern you mention sounds like what @waldekmastykarz has referred to on the community call videos. 
Do you have a sample or documentation you can point me to that shows how to use app identity for graph calls via Teams react app using node on Azure storage container?

Thanks

**Comment by KennethBWSong** [comment]
@ITAndy23 You can refer to this [sample](https://github.com/OfficeDev/TeamsFx-Samples/blob/1724fc3e6b508e12e1332dc207e4ad697a08605c/graph-connector-app/api/status/index.ts#L62) for calling Graph with app credential on server side.

**Comment by ITAndy23** [comment]
Thanks @KennethBWSong  I'll review the link you shared.
