### ISSUE TITLE
Can't sign to MS 365 on WSL2 : redirected to localhost 

### ISSUE THREAD

**Issue by TheUncharted** [OfficeDev/TeamsFx#8237]
**Describe the bug**
I'm on WSL2 + VS Code and I created a new project with a basic team app with the Hello World.
When I sign to my account I'm redirect to the localhost url and got a message : "This site can’t be reached,  
localhost refused to connect."

http://localhost:41653/?code= ...

**To Reproduce**
1. Go to "accounts" in side panel
2. Click on "Sign in to Microsoft 365"
3. Click "Sign in"
4. Fill your login/password
5. Redirected to the localhost

**Expected behavior**
Should be signed on VS Code on the account side panel

**VS Code Extension Information (please complete the following information):**
 - OS: WSL 2 + Ubuntu 20.04.6 LTS
 - Version 1.77

**Comment by xiaolang124** [comment]
Sorry for the inconvenience. Can you try these commands and see whether it can open localhost URL?
```
npx create-react-app my-app
cd my-app
npm start
```

Normally, WSL will allow connectivity to both the outside world as well as the Windows host. If you fail to open local URL, we may need to see why WSL does not build connection between outside and inside world.

**Comment by TheUncharted** [comment]
Hi
I did that and it works on this create-react-app and my other projects and I have no problems generally with my localhost for my backend/frontend projects
For information my .wslconfig is configured like that

```
[wsl2]
memory=16GB # Limits VM memory in WSL 2 to 16 GB
processors=2 # Makes the WSL 2 VM use two virtual processors
swap=0
localhostforwarding=true
```

**Comment by xiaolang124** [comment]
When you open M365 login URL, you will see `redirect_uri` part in your URL. Please try to ping this local URL with port and let us know the result. Thanks.
![image](https://user-images.githubusercontent.com/13211513/229462337-b5f332c4-1718-48e8-a988-16a99d4d7067.png)

Here’s an example command for pinging a specific port using telnet:
```
$ telnet <ip_address> <port_number>
$ telnet <domain_name> <port_number>
```

If you are using PowerShell, you can ping a specific port using the following command:
```
Test-NetConnection <address> -p <port_number>
```

**Comment by TheUncharted** [comment]
From the login i got this string

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=7ea7c24c-b1f6-4a20-9d11-9ae12e9e7ac0&scope=https://dev.teams.microsoft.com/AppDefinitions.ReadWrite%20openid%20profile%20offline_access&redirect_uri=http://localhost:37789&client-request-id=7aa58964..

On WSL it works

> telnet localhost 37789
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
^CConnection closed by foreign host.

On Powershell it seems to not working

> Test-NetConnection localhost -p 37789
> WARNING: TCP connect to (::1 : 37789) failed
> WARNING: TCP connect to (127.0.0.1 : 37789) failed
> 
> 
> ComputerName           : localhost
> RemoteAddress          : ::1
> RemotePort             : 37789
> InterfaceAlias         : Loopback Pseudo-Interface 1
> SourceAddress          : ::1
> PingSucceeded          : True
> PingReplyDetails (RTT) : 0 ms
> TcpTestSucceeded       : False

**Comment by xiaolang124** [comment]
That's strange. Usually, it can be accessed both in Windows and WSL. Have you tried restarting Windows or WSL to see if it resolves the issue?

**Comment by TheUncharted** [comment]
ok I solved the issue it was because the forwarding was not working. I dont know why since it works with normal react sites on differents ports
I had to do a Network System Reset as mentionned in this [issue](https://github.com/microsoft/WSL/issues/4636)

**Comment by xiaolang124** [comment]
Thanks for updating the information and sharing the solution.
