### ISSUE TITLE
Microsoft Teams Bot Template: The type or namespace name 'AuthenticationOptions' could not be found 

### ISSUE THREAD

**Issue by mercer2000** [OfficeDev/TeamsFx#8272]
**Describe the bug**
After creating a new Microsoft Teams app project using Visual Studio Microsoft Teams Toolkit, the code generated fails to build with the error  The type or namespace name 'AuthenticationOptions' could not be found 

**To Reproduce**
1. Create a new Visual Studio Project 
2. Select Microsoft Teams
3. Select Bot Workflow
4. Select Teams Toolkit, Prepare App 
5. Select Teams Toolkit, Add Authentication Code 

Follow the steps outlined int he readme.txt file that is added to the project after Adding Authentication Code. 

4. Update 'Program.cs'
    4.1 Find code: 'builder.Services.AddSingleton<BotFrameworkAuthentication, ConfigurationBotFrameworkAuthentication>();'
        and add the following code below:
        '''
        builder.Services.AddRazorPages();

        // Create the Bot Framework Adapter with error handling enabled.                                        
        builder.Services.AddSingleton<IBotFrameworkHttpAdapter, AdapterWithErrorHandler>();

        builder.Services.AddSingleton<IStorage, MemoryStorage>();
        // Create the Conversation state. (Used by the Dialog system itself.)
        builder.Services.AddSingleton<ConversationState>();

        // The Dialog that will be run by the bot.
        builder.Services.AddSingleton<SsoDialog>();

        // Create the bot as a transient. In this case the ASP Controller is expecting an IBot.
        builder.Services.AddTransient<IBot, TeamsSsoBot<SsoDialog>>();

        builder.Services.AddOptions<AuthenticationOptions>().Bind(builder.Configuration.GetSection("TeamsFx").GetSection(AuthenticationOptions.Authentication)).ValidateDataAnnotations();
        builder.Services.AddOptions<BotAuthenticationOptions>().Configure<IOptions<AuthenticationOptions>>((botAuthOption, authOptions) => {
            AuthenticationOptions authOptionsValue = authOptions.Value;
            botAuthOption.ClientId = authOptionsValue.ClientId;
            botAuthOption.ClientSecret = authOptionsValue.ClientSecret;
            botAuthOption.OAuthAuthority = authOptionsValue.OAuthAuthority;
            botAuthOption.ApplicationIdUri = authOptionsValue.ApplicationIdUri;
            botAuthOption.InitiateLoginEndpoint = authOptionsValue.Bot.InitiateLoginEndpoint;
        }).ValidateDataAnnotations();
        '''

<img width="924" alt="image" src="https://user-images.githubusercontent.com/18239028/229934365-3aa57fdb-a96a-4538-b18a-877073681283.png">

**Expected behavior**
The bot template to build without errors. 

**CLI Information (please complete the following information):**
 - OS:Windows 11
 - 

**Additional context**

**Comment by KennethBWSong** [comment]
Hi @mercer2000 Thank you for using our Toolkit. Would you please try to import `Microsoft.TeamsFx.Configuration` and `Microsoft.Bot.Builder` like following?
```
using Microsoft.TeamsFx.Configuration;
using Microsoft.Bot.Builder;
```

**Comment by mercer2000** [comment]
Adding the following two using statement fixed the issue:

using Microsoft.TeamsFx.Configuration;
using Microsoft.Extensions.Options;
________________________________

**Comment by adashen** [comment]
close as the issue is resolved
