### ISSUE TITLE
Failed to update application in Azure Active Directory. Please make sure 'templates/appPackage/aad.template.json' is valid: Request failed with status code 400 Detailed error: Request failed with status code 400. Reason: Values of identifierUris property must use a verified domain of the organization or its subdomain

### ISSUE THREAD

**Issue by christophemacabiau** [OfficeDev/TeamsFx#8275]
**Describe the bug**
When I try to re-provision my app on a new subscription, I get this error:
_Failed to update application in Azure Active Directory. Please make sure 'templates/appPackage/aad.template.json' is valid: Request failed with status code 400 Detailed error: Request failed with status code 400. Reason: Values of identifierUris property must use a verified domain of the organization or its subdomain: 'teamsprod49aa31tab.z28.web.core.windows.net'_
In my aad.template.json I have this line:
```json
"identifierUris": [
        "{{state.fx-resource-aad-app-for-teams.applicationIdUris}}"
    ]
```
and in my aad.production.json:
```json
    "identifierUris": [
        "api://teamsprod49aa31tab.z28.web.core.windows.net/00ebf757-b6af-441b-90eb-c626305dc5aa"
    ],
```

which seems correct.

**VS Code Extension Information (please complete the following information):**
 - OS: ubuntu
 - Version 4.2.4

**Comment by KennethBWSong** [comment]
Hi @christophemacabiau Thank you for using our Toolkit. This error occurs usually when you want to provision an multi-tenant Azure AD app (`signInAudience` set to `AzureADMultipleOrgs`). You can follow the steps in the [doc](https://github.com/OfficeDev/TeamsFx/wiki/Multi-tenancy-Support-for-Azure-AD-app) for multi-tenant support.

**Comment by KennethBWSong** [comment]
Hi @christophemacabiau Would you please make sure `signInAudience` is set to `AzureADMyOrg` in your `templates/appPackage/aad.manifest.json` file and try provision again?

**Comment by christophemacabiau** [comment]
Hi @KennethBWSong 
So I reprovisionned the application with  `signInAudience` set to `AzureADMyOrg`. It works.
Then I follow the doc:
2. My domain=teamsprodaf0cf3tab.z28.web.core.windows.net
3. My custom domain=azureprod.coachforeyes.com redirected to teamsprodaf0cf3tab.z28.web.core.windows.net
4. In the doc they ask to change `templates\azure\provision\azureStorageTab.bicep` but I don't have this file, instead I updated `endpoint` and `domain` in the file `templates/azure/provision/frontendHosting.bicep`:
```
output endpoint string = 'https://teamsprodaf0cf3tab.z28.web.core.windows.net'
output domain string = 'teamsprodaf0cf3tab.z28.web.core.windows.net'
```
then in `aad.template.json`: `signInAudience` set to `AzureADMultipleOrgs` and in `.fx/configs/azure.parameters.production.json`: "m365TenantId": "common".

And while reprovisioning I still get the same error:
_Failed to update application in Azure Active Directory. Please make sure 'templates/appPackage/aad.template.json' is valid: Request failed with status code 400 Detailed error: Request failed with status code 400. Reason: Values of identifierUris property must use a verified domain of the organization or its subdomain: 'teamsprodaf0cf3tab.z28.web.core.windows.net'_

Did I forget something?

**Comment by KennethBWSong** [comment]
Hi @christophemacabiau From the error message we can say that the custom domain is not correctly set in Teams Toolkit. Would you please make sure that these two lines are updated with your custom domain? For example
```
output endpoint string = 'https://azureprod.coachforeyes.com'
output domain string = 'azureprod.coachforeyes.com'
```

**Comment by christophemacabiau** [comment]
Hi @KennethBWSong, Thanks for your help.
Finally I created a whole new environment, and following your doc it worked. Something was wrong in the old .fx generated configuration I imagine.

Thank you!
