### ISSUE TITLE
Multi-tenant authentication suddenly failing with invalid issuer when acquiring token 

### ISSUE THREAD

**Issue by szekelydenisa** [OfficeDev/TeamsFx#8302]
**Describe the bug**
Following [the documentation](https://learn.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app), our team registered an application with Accounts in any organizational directory, in order to support multi-tenancy. 
Authenticating and acquiring tokens worked fine until one month ago, when we started to get 401 Unauthorized status code with error_description="The issuer 'https://login.microsoftonline.com/{tid}/v2.0' is invalid. 
Which kind of makes sense, as tid seems to be the current tenant id (which is an external tenant), instead of "common". 

I am trying to acquire the token using TeamsUserCredential:

`let errorMessage = "" as string;

  return credential.getToken(["Files.Read.All", "Files.ReadWrite.All", "User.Read"]).then(async function (authResponse) {
    return await processResponse(authResponse);
  }).catch(function (error) {
    errorMessage = error.toString();
    if (errorMessage && (errorMessage.includes('AADSTS65001') || errorMessage.includes('Get SSO token failed'))) {
      if (attempt === 0 && triggerAuthorization) {
        AuthorizeClipr();
      }
      return { auth: '', error: attempt > 0 ? 'failed' : 'authorize', status: 'consent' };
    } else if (errorMessage && errorMessage.includes('teams sdk timeout')) {
      return { auth: '', error: "The application must be running inside Microsoft Teams." };
    }
    return { auth: '', error: errorMessage };`

But what I noticed is that I never get to the point of calling credential.getToken .. as the authentication fails on /auth/token.

As I joined the project later, while navigating through the configs trying to solve the issue, I noticed the fx-resource-simple-auth plugin is it used, the app service configuration is set to multi-tenant, but the issuer that I test during the validation "/auth/token" always remains the same "https:/login.microsoftonline.com/tenantId" and causes the error I described above, blocking the user from using the application.

**To Reproduce**
Please checkout this loom in order to see how the issue is reproduced: https://www.loom.com/share/119f391f90cd41d0ac7ed902a437c471

**Expected behavior**
I would expect that fx-resource-simple-auth validates the issuer of different tenants with the service so that it uses the "common" multiplexer rather than the tenant's id.
I also would like to mention this was working, and it suddenly stopped working .. and no changes were done to the code or to the app configs.

**Screenshots**
Here is a loom video of the problem: https://www.loom.com/share/119f391f90cd41d0ac7ed902a437c471

**VS Code Extension Information (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.7.3

**CLI Information (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.7.3

**Additional context**
Dependecies:

"@microsoft/teams-js": "^1.6.0",
"@microsoft/teamsfx": "^0.1.0"
Using Teams Toolkit
v3.7.0

**Comment by KennethBWSong** [comment]
Hi @szekelydenisa Thank you for using our Toolkit! You can find solutions to support multi-tenant for Simple Auth in this [issue](https://github.com/OfficeDev/TeamsFx/issues/3101#issuecomment-993167250). Please check if this solution can help you.

**Comment by adashen** [comment]
Close as the issue is answered and there is no recent updates.
