### ISSUE TITLE
Bot cannot send notifications to users after a certain time

### ISSUE THREAD

**Issue by Steffi3rd** [OfficeDev/TeamsFx#8364]
**Describe the bug**
Hi! 👋

When I test the bot locally, I have no issues between bot and users.
I mean: Users still receive notifications from the bot (So I guess because users are always present in notification.localstore.json)

However, in production, users do receive notifications from the bot when they install the application. But after a certain time (how long?), the bot no longer finds the users and can no longer send notifications messages to them.

For the bot to be able to send new notification messages to users, the user must "respond" to the bot. And then it works again.

So I have 3 questions:

- After how long are users no longer taken into account by the bot?
- Is there a way to maintain the connection between the bot and the user (for example, until the user uninstalls the application?)
- If not, is there a way to modify/increase the time before the connection between the bot and the user is deleted?

Here are the links I found about notification storage but not implemented it yet:

- Use Azure Blob Storage to persist notification connections : [notification.localstore.json](https://github.com/OfficeDev/TeamsFx-Samples/blob/1e1c86c6f294012438474bb2f806e307d607c47b/adaptive-card-notification/README.md#optional-use-azure-blob-storage-to-persist-notification-connections)
- Add notification storage implementation sample : (https://github.com/OfficeDev/TeamsFx-Samples/commit/99eb772226a6c0603b4ed52788e660773e865a64) https://github.com/OfficeDev/TeamsFx-Samples/blob/ga/adaptive-card-notification/bot/src/storage/blobsStorage.ts

Last question : If we implemented notification.localstore.json ourself, where we can found it Azure please?

**To Reproduce**
- Deploy on production
- Install app
- Run notifications, it's ok : users receive
- Run notification days later, it's not ok, users don't receive anymore

**Expected behavior**
Bot should always find users and send notifications even a certain time

**VS Code Extension Information (please complete the following information):**
 - OS: MacOS
 - Version 12.3

**Comment by swatDong** [comment]
@Steffi3rd - do you mean that for both local and production, you are using the default file `.notification.localstore.json` to store the connection?
- In local, the file is written to you local file system so will be kept there until your manual deletion.
- In production, the file is written to Azure App Service's temp folder, so will be cleaned up after the app restarted or failover.

So it's recommended to use your own storage in production. The links you found do solve the problem - follow the sample and use Azure Blob Storage to persist connections.
To check your Azure Storage's content, you can go *Azure Portal* -> *your Storage Account* -> *Containers*, or use [Azure Storage Explorer](https://learn.microsoft.com/azure/vs-azure-tools-storage-manage-with-storage-explorer)

**Comment by Steffi3rd** [comment]
@swatDong yes! Currently we don't use any storage. So I guess it's the default.

**Comment by swatDong** [comment]
Sometimes the restart or failover is done by Azure automatically. It depends on your pricing tier and region.
One way to check that is using the advanced tools:
- Go to *https://{your-app-service-name}.scm.azurewebsites.net/*
- Open *Process explorer* tab
- (If Node.js project) Check the node process's start time

However, this can only help you check the restart, you still cannot prevent the issue.
So I would recommend to use your own persist storage in production.
