### ISSUE TITLE
TeamsFx doesn't support Microsoft Graph SDK v5.6.0.

### ISSUE THREAD

**Issue by robertstewartnz** [OfficeDev/TeamsFx#8388]
**Is your feature request related to a problem? Please describe.**
Just tried upgrading to the latest version of the Microsoft Graph SDK v5.6.0. It's all sweet except for Creating a new GraphServiceClient, as it no longer accepts the TeamsFx MsGraphAuthProvider class.

`var msGraphAuthProvider = new MsGraphAuthProvider(teamsUserCredential, scope);`
`var client = new GraphServiceClient(msGraphAuthProvider);`

no longer works.

**Describe the solution you'd like**
Some advice on how to use the updated Graph SDK with TeamsFx and specifically around configuring an auth provider that works with Teams.

**Describe alternatives you've considered**
Reviewed Microsoft documentation but it was unclear how to proceed.

**Comment by yiqing-zhao** [comment]
Same issue here: https://github.com/OfficeDev/TeamsFx/issues/8089. New version of dotnet SDK is estimated to be released before May.

**Comment by yiqing-zhao** [comment]
Hello @robertstewartnz, we are excited to announce the launch of TeamsFx 2.0.0. You can upgrade your existing project by following the steps [here](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/dotnet-sdk/README.md#upgrade-from-1xx-to-200). You can also check out this pull request (https://github.com/OfficeDev/TeamsFx/pull/8421) for more information. Please let us know if you encounter any problems, we appreciate your feedback!
