### ISSUE TITLE
publishing keeps making subdirectories. 

### ISSUE THREAD

**Issue by wrharper-AASP** [OfficeDev/TeamsFx#8405]
This screenshot pretty much says it all. Every time you do an Azure publish and it fails it seems to create more directories. It may still do it on success too, hard to tell. Also, the app keeps failing the deploy when I try to do it from another location, is this by design in some way?
![image](https://user-images.githubusercontent.com/117128832/232048903-9a483078-75e2-4a75-bcc1-27e9053dbf13.png)

**Comment by Alive-Fish** [comment]
@wrharper-AASP Sorry for any inconvenience. Could you tell us more information for troubleshooting?
* Visual Studio version (`17.3.x`/`17.4.x`/`17.5.x`/`17.6.x`)?
* Visual Studio channel (`Preview`/`GA` or other)?
* Which command do you use to do an Azure publish? (`Project -> Teams Toolkit -> Deploy to the Cloud` / `Right-click the project -> Publish` or other)
* If you don't mind, could you take a screenshot at the folder structure?

**Comment by wrharper-AASP** [comment]
this has happened on every update in visual studio at 17.3+
this is the official TeamsFx attached to the visual studio installer. The current GitHub says 1.2.1 for TeamsFx
Project -> Teams Toolkit -> Deploy to the Cloud is what I use.

![image](https://user-images.githubusercontent.com/117128832/232528532-7d4e7bb6-8b59-47db-ae4c-5f4d1f89096f.png)
![image](https://user-images.githubusercontent.com/117128832/232529062-5c244180-a1df-4520-a617-d7cba18fc6ba.png)

**Comment by Alive-Fish** [comment]
Thanks @wrharper-AASP, @hund030 and @Siglud will follow up this issue next.

**Comment by hund030** [comment]
@wrharper-AASP Thanks for reporting the issue. Teams Toolkit runs the build command before publishing, using the following command:
```
dotnet publish --output publish --configuration Release --runtime win-x86 --self-contained
```

According to the documentation, when specifying an output folder for the publish command, we should exclude that folder. 

To work around this issue, you can first remove both the publish folder and the bin folder from your project. Then, add the following line to a PropertyGroup:
`<DefaultItemExcludes>$(DefaultItemExcludes);publish/**</DefaultItemExcludes> `

You can find more information about the dotnet publish command and its options in this document: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#options

**Comment by hund030** [comment]
This issue will be fixed in 17.7.

**Comment by wrharper-AASP** [comment]
I have created a bat file to work around this for the time being. For whatever reason, this is still happening:

```
cd PATHTOPROJECT
RMDIR "publish" /S /Q
dotnet publish --output publish --configuration Release --runtime win-x86 --self-contained
pause
```

**Comment by hund030** [comment]
@wrharper-AASP Yes, we have resolved the issue in VS 17.7 which is currently in the preview channel. If you are using the stable channel (17.6), you may still be affected by the problem.
You can try installing the VS 17.7 preview using the VS installer, Or use a work around until the stable version is released. We anticipate that the stable version will be released soon.

**Comment by wrharper-AASP** [comment]
I was down for almost a whole month when Blazor broke from a "stable" release. I have to be careful on these decisions now....

**Comment by hund030** [comment]
@wrharper-AASP I think adding `<DefaultItemExcludes>$(DefaultItemExcludes);publish/**</DefaultItemExcludes>` to your .csproj file is a helpful solution that may mitigate the issue you're experiencing. Could you explain more details about how your Blazor app breaks?

**Comment by wrharper-AASP** [comment]
it happened to everyone, and it was a major outage on one of the Blazor versions. I'd have to go through a ton of issues to find it.

**Comment by wrharper-AASP** [comment]
ah, got lucky and found it towards the top:
https://github.com/dotnet/razor/issues/8718
It was originally about some kind of certain project they were using, but it ended up being an issue for everyone.

**Comment by hund030** [comment]
@wrharper-AASP It appears that you are suffering an issue related to Blazor framework. We suggest that you file an issue on Blazor's repository to ask for help. This repository is focused on Teams Toolkit and its associated projects, and we may not possess the expertise to address your concerns regarding the Blazor framework.

**Comment by wrharper-AASP** [comment]
That issue is fixed, the point is no one knew the issue was going to happen and everyone who upgraded to 16.2 went down for nearly a month unplanned. Microsoft fixed it in 16.3+, I'm just saying we need to take precautions when upgrading now.

**Comment by wrharper-AASP** [comment]
![image](https://github.com/OfficeDev/TeamsFx/assets/117128832/a9f47ea0-66fa-42d8-ab21-bd16a706fc32)

**Comment by wrharper-AASP** [comment]
![image](https://github.com/OfficeDev/TeamsFx/assets/117128832/bba2fb97-7256-43ee-96bc-f18283054dfd)

**Comment by hund030** [comment]
@wrharper-AASP It should be in PropertyGroup.
![image](https://github.com/OfficeDev/TeamsFx/assets/26134943/2bbcc7b1-02a8-474f-9a1a-f6bc313118bf)
