### ISSUE TITLE
login loop when I run debugger

### ISSUE THREAD

**Issue by Githamza** [OfficeDev/TeamsFx#8407]
**Describe the bug**
I'm trying to debug my teams app.

When I launch debugger I get the prompt window to login to azure .

When I log in  et get stuck in a login loop  and in the terminal I get this error message 

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/11578288/232218851-47140b34-0383-4e8a-9610-90d2ed50d26a.png">
I can't so launch my app in debugger mode.

I have tried to log in in the extension first but I get the prompt login screen.

here's a screen capture video

https://user-images.githubusercontent.com/11578288/232221123-9f8ee384-9a1a-4676-804b-47d754fbe243.mov

vscode version: 1.77.3
teams toolkit version : v4.99.2023032308

**Comment by xiaolang124** [comment]
Sorry for the inconvenience, have you tried to delete login cache in `/Users/hazahaddad/.fx/account` and run local debug? If not, you can try it and tell us the result.

**Comment by Githamza** [comment]
thanks that solved the issue

**Comment by adashen** [comment]
Close as the issue is resolved.
