### ISSUE TITLE
migrate from `@azure/core-http` to `@azure/core-auth`

### ISSUE THREAD

**Issue by jeremymeng** [OfficeDev/TeamsFx#8438]
we are planning to deprecate `@azure/core-http` in the near future.  It looks that the usage in this repo are all token credential related, and should be able to move to import from `@azure/core-auth` instead.

**Comment by SLdragon** [comment]
Seems we only use this dependency for some interfaces as below:
![image](https://user-images.githubusercontent.com/5545529/234153984-cbad289b-a80d-4d0b-88ec-bc462a4be91d.png)

So I think it is easy to update the dependency to use @azure/core-auth instead, and thanks for your information!

**Comment by SLdragon** [comment]
We have already migrate from @azure/core-http to @azure/core-auth in this PR: https://github.com/OfficeDev/TeamsFx/pull/8557, thanks for your help!
