### ISSUE TITLE
App package build files are saved to git

### ISSUE THREAD

**Issue by BobGerman** [OfficeDev/TeamsFx#8489]
**Describe the bug**

The **appPackage/build** folder contains manifest files that contain user-specific information such as Bot ID. Since these files are automatically built from other information, does it make sense to persist them to source control? As build artifacts, I suggest adding appPackage/build to .gitignore.

**To Reproduce**
1. Create a new project with Teams Toolkit v5
2. Build and publish the application
3. Commit the folder to github
4. You will find your local build files have been shared in github

**Expected behavior**
The local build files would not be shared in github. Other users would build their own version of these files, which would likely vary with different bot ID's, app ID's, etc.

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 10
 - Version 5.0 (April 18 release)

**Additional context**
attn/ @therealjohn - based on our Teams chat - thanks!

**Comment by nliu-ms** [comment]
Thanks for reporting this bug @BobGerman . You're right, we will update the .gitignore files in next release. Thank you!

**Comment by nliu-ms** [comment]
The fix has been merged and will be released in May, thank you so much for raising the issue.
