### ISSUE TITLE
Conditional Teams Tabs

### ISSUE THREAD

**Issue by wrharper-AASP** [OfficeDev/TeamsFx#8546]
Is it possible to have tabs show up despite what the manifest says? Can we add this as a feature? For example, what if you would like an admin panel tab that is only shown to certain users? It looks like the tabs will show up no matter what if you add it to manifest and there seems to be no way to add another one otherwise.

**Comment by MuyangAmigo** [comment]
@wrharper-AASP I'm checking this with other Microsoft team and will get back to you.

**Comment by MuyangAmigo** [comment]
Hey @wrharper-AASP , This is the response we got from Teams platform: 

> For personal tabs, the content URL is set directly in your Teams app manifest by the contentUrl property in the staticTabs array. Tab's content is the same for all users. There is no show or hide MS Teams tabs functionality implemented yet.

Unfortunately it's not something available today, but you can file a feature request through [Teams Feedback Portal](https://feedbackportal.microsoft.com/feedback/forum/ad198462-1c1c-ec11-b6e7-0022481f8472).

I'm closing this issue for now, please feel free to re-open if you need further assistance with Teams Toolkit.
