### ISSUE TITLE
bug report: teamsAppExtendToM365.UnhandledError

### ISSUE THREAD

**Issue by kamalshree** [OfficeDev/TeamsFx#8576]
An unexpected error has occurred while performing the <REDACTED: user-file-path> task. The reason for this error is: Unexpected token

**Comment by kuojianlu** [comment]
@kamalshree I cannot reproduce this error. Could you please share the reproducing steps and the `teamsApp/extendToM365` action in `teamsapp.local.yml`?
![image](https://user-images.githubusercontent.com/37978464/236367145-bc321bb6-6f0d-42a8-aa8d-e757ad3c05c7.png)
