### ISSUE TITLE
IndexedDB is not possible with the mobile version of Teams Applications

### ISSUE THREAD

**Issue by wrharper-AASP** [OfficeDev/TeamsFx#8583]
IndexedDB isn't possible on the phone, and I was using it with an encryption. What is the alternative for phones?
It looks like I'm not the only one with this issue either: https://techcommunity.microsoft.com/t5/microsoft-teams/indexeddb-is-not-working-in-the-android-app-for-teams/m-p/1359784

**Comment by MuyangAmigo** [comment]
Hey @wrharper-AASP Thanks for reporting the issue. We will reach out to SPFx team and get back to you as soon as we hear anything.

**Comment by MuyangAmigo** [comment]
Hey @wrharper-AASP Looks like `IndexDB` is supposed to work on Android - https://caniuse.com/?search=indexDB. We need to check with Teams platform if it's supported on Teams client.

**Comment by wrharper-AASP** [comment]
Yes, it works on browser in Android but not in the Teams app. Can we get this fixed? It is very important for performance. Especially on a phone.

**Comment by wrharper-AASP** [comment]
> Yes, it works on browser in Android but not in the Teams app. Can we get this fixed? It is very important for performance. Especially on a phone.

How could you test this? my only guess I can go on is the loading time.

**Comment by MuyangAmigo** [comment]
Hey @wrharper-AASP , unfortunately this isn't something directly related to Teams Toolkit so I wasn't able to give you answers right away. I'm still checking with the Teams platform team and not receiving a response yet. I would also suggest you to raise this issue in the [Teams developer community](https://techcommunity.microsoft.com/t5/teams-developer/bd-p/TeamsDeveloper)

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8817

**Comment by adashen** [comment]
Let's track in upstream repo https://github.com/MicrosoftDocs/msteams-docs/issues/8817 and close here.
