### ISSUE TITLE
Published version gets "reconnecting to server" periodically.

### ISSUE THREAD

**Issue by wrharper-AASP** [OfficeDev/TeamsFx#8615]
**Describe the bug**
There is some sort of failure that happens, and I cannot find the root cause. The app will randomly say it needs to reconnect to the server and fails as shown in the screenshot below.

**To Reproduce**
I'm not sure how to reproduce it, that is actually the issue. Can't find a root cause.

**Screenshots**
![image](https://user-images.githubusercontent.com/117128832/236453533-6f1a2f41-a4d5-4b5b-ae31-11c72d25c65d.png)

Payload:
id: PxDCODZhMpYf0qR_9sqegA
_: 1683287855066

This is .NET 6 Visual Studio 2022 and TeamsFx version 1.2.1

Does anyone know what could be causing this?

**Comment by JerryYangKai** [comment]
Thanks for reporting this, and I'd appreciate if you could provide more information for us to tracking this bug, for example the repro step.
Do not need much, just like 'using VS version 17.5.4' and 'create Tab project' then local debug, the error log will appear in output window.

**Comment by wrharper-AASP** [comment]
This is a tab project and happens when deploying as you mentioned.
VS version is 17.5.5
I have upgraded to TeamsFx 2.0, but this still appears to exist.

**Comment by JerryYangKai** [comment]
So, this app is running in Azure and in Teams you open this tab app and see the error which said reconnecting, right?
Could you please provide more screenshot, like when the app said "reconnecting to server", what's the Teams app looks like.

**Comment by wrharper-AASP** [comment]
It happens in the browser and teams. I use the browser at teams.microsoft.com so that I can use the dev tools to detect this error easier.
The reconnecting to server disappears pretty fast so it's a little hard to get a screenshot of it. It says something around "Attempting to reconnect, attempt 1 of 8" or maybe 1 of 6, something like that.
I cannot replicate the issue today. I'll re-open if it's still an issue and try to get more info.
