### ISSUE TITLE
TeamsFx desktop notification support.

### ISSUE THREAD

**Issue by Ouri028** [OfficeDev/TeamsFx#8630]
**Is your feature request related to a problem? Please describe.**
I have gone over examples and docs and it seems that TeamsFx does not support native desktop notifications, I am currently working on a chat based application that integrates with Teams and we require this feature to alert the user when they have a new message. I can also see this being a needed feature for many people.

**Describe the solution you'd like**
An available API that will allow TeamsFx to make full use of the native Electron notification system already available or allow an external application to send Teams notifications.

**Describe alternatives you've considered**
I have tried many different solution all boiling down to a common issue where the end user cannot send Teams notifications to themselves.

**Comment by MuyangAmigo** [comment]
Hey @Ouri028 Can you please elaborate what do you mean by `support native desktop notifications`? Are you trying to build an application that sends notifications to Teams user?

**Comment by Ouri028** [comment]
Hey @MuyangAmigo ,

That is correct, I would like to send notifications to Teams users such as the image below.

I will need to also be able to send this notification using the same user account that will receive the notification.

![image](https://github.com/OfficeDev/TeamsFx/assets/49057553/432446be-012a-4e42-9651-2f03462ce1f8)

**Comment by MuyangAmigo** [comment]
Hey @Ouri028 Thanks for explaining your use case. Does your requirement enforce that the notification is sent using a User's account? If so I would suggest you to open a feature request with [MS Graph APIs](https://github.com/microsoftgraph) as it's usually where this kind of APIs are exposed.

But honestly as far as I know, it might be pushed back as it could be dangerous to expose such APIs for app to send messages on behalf of user. (You might understand how dangerous that an app can send message on behalf of your identity.)

A more recommended way to send proactive messages (with native Teams conversation and desktop notifications) is that using a bot application to [send notifications to users](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams?tabs=ts%2Cjsts%2Cts4). 

Do hope those helps.

**Comment by Ouri028** [comment]
Thanks for all the info @MuyangAmigo, I really appreciate it, this ticket can be closed.
