### ISSUE TITLE
Tab + Outlook add-in does not run

### ISSUE THREAD

**Issue by rabwill** [OfficeDev/TeamsFx#8674]
Windows OS
Node 18
Teams Toolkit pre-release version.
Start with sample tab +outlook add in
F5 

Debugging is being started...
App type: desktop
Error: Unable to start debugging.
Error: Invalid filename
 *  Terminal will be reused by tasks, press any key to close it. 
 
in the add-in's package.json,  the path looks wrong in the scaffolded code. It should be `../appPackage/build/appPackage.local.zip` etc
Also in the preview version of manifest,

scope for configurable tabs throw error at `groupChat`. This may be a manifest bug but the sample needs update.

**Comment by 1yefuwang1** [comment]
@rabwill Thank you for reporting. It should be fixed by https://github.com/OfficeDev/TeamsFx-Samples/pull/903
