### ISSUE TITLE
Add deprecated to `bot-sso`

### ISSUE THREAD

**Issue by huzaifahj** [OfficeDev/TeamsFx#8690]
Add deprecated message to `bot-sso` sample directing users to https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/bot-sso instead

**Comment by adashen** [comment]
hi @huzaifahj  Thanks for reporting the issue. Can you elaborate more about which sample needs to be deprecated? (Then entry point of it) and which toolkit version are you using?
