### ISSUE TITLE
bug report: AppStudioPlugin.DeveloperPortalAPIFailed

### ISSUE THREAD

**Issue by Ullauri** [OfficeDev/TeamsFx#8735]
API call to Developer Portal failed: Error, Request failed with status code 400, API name: create-bot, X-Correlation-ID: a30f01c4-60dc-48b1-8c6d-969b05a2e253. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: {"errors":{"botId":["Error converting value \"ca79aa55-2459-4e16-964a-fd50f43da000CONFIG__MANIFEST__APPNAME__SHORT=<REDACTED: user-file-path>" to type 'System.Nullable`1[System.Guid]'. Path 'botId', line 1, position 100."]},"type":"https:/<REDACTED: user-file-path>

**Comment by HuihuiWu-Microsoft** [comment]
Hi @Ullauri, can you provide more info about this issue like what is the scenario when the issue happens and whether this is reproducible on your side?
