### ISSUE TITLE
bug report: teamsAppExtendToM365.UnhandledError

### ISSUE THREAD

**Issue by mibohlin** [OfficeDev/TeamsFx#8741]
An unexpected error has occurred while performing the <REDACTED: user-file-path> task. The reason for this error is: Unexpected token � in JSON at position 0. Welcome to report this issue by clicking on the provided "Issue Link", so that we can investigate and resolve the problem as soon as possible.

stack:
SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at ConvertTokenToJson (<REDACTED: user-file-path>:8:5763866)
    at CodeFlowLogin.<anonymous> (<REDACTED: user-file-path>:8:5756089)
    at Generator.next (<anonymous>)
    at fulfilled (<REDACTED: user-file-path>:8:5750045)

**Comment by kuojianlu** [comment]
@mibohlin Is "<REDACTED: user-file-path>" your manifest file path? This error is mainly because there are some special characters in this json file. You can double check this file and remove the special characters. From my experience, you can do that by copying the file content, deleting this file, re-creating this file and pasting the content.

**Comment by kuojianlu** [comment]
@mibohlin 
We are still investigating this error. Our initial conclusion is that this is a bug related to login. Followings are the workaround that may unblock you.

1. Sign out the M365 account, and then re-sign in. After that, retry F5.
2. If the above method cannot solve this error, comment out teamsApp/extendToM365 action in teamsapp.local.yml. After that, retry F5. (Please note that this workaround is not applicable to the scenario that you debug in Outlook or the Microsoft 365 app)
![image](https://github.com/OfficeDev/TeamsFx/assets/37978464/e56087fe-a5c1-4351-86cf-135d5c1a8c9a)

**Comment by kuojianlu** [comment]
PR to mitigate this issue: https://github.com/OfficeDev/TeamsFx/pull/8809
