### ISSUE TITLE
Separate deployment of Bot and Tab

### ISSUE THREAD

**Issue by IAM5K** [OfficeDev/TeamsFx#8745]
Project preface: I am developing a Bot that has tabs in it added as a feature
In Teams Toolkit version 4, 
On clicking on deployment we used to get an option to choose Bot or tabs but in the latest update we cannot choose among them and it automatically deploys both of them.

If it is possible to bring back the option to select which app I want to deploy, it will be really helpful as sometimes changes in bot are not in a state to be deployed but we have to deploy tabs as things need to run in parallel.

Cannot even generate Screenshots as those options are no more available.

**Comment by MuyangAmigo** [comment]
Hey @IAM5K, In the Teams Toolkit v5 we have changed fundamentally how we orchestrate the provision and deployment process. To ensure maximum flexibility and transparency, we have moved to use `teamsapp.yml` to control what and how the deployment process should take place. You can refer to: https://github.com/OfficeDev/TeamsFx/wiki/Available-actions-in-Teams-Toolkit for more details of customizing the deployment life cycle.

**Comment by IAM5K** [comment]
I have already checked the document but it no where specifies anything related to the raised isse.

**Comment by IAM5K** [comment]
Thanks for the details. I have cross-checked and now by modifying the file I am able to do separate deployments. But every time I have to modify `teamsapp.yml`. is there a way to get back to the UI mode or choose an option as we used to get earlier?

**Comment by therealjohn** [comment]
> Thanks for the details. I have cross-checked and now by modifying the file I am able to do separate deployments. But every time I have to modify `teamsapp.yml`. is there a way to get back to the UI mode or choose an option as we used to get earlier?

Can you share an example of what you did to deploy separately and have to modify the file every time?

**Comment by IAM5K** [comment]
To deploy the bot and tab separately through a manual process you can follow these:
- navigate to `teamsapp.yml`.
- Check for the attached snippet
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/69039b32-866d-4677-9814-450f6f2c3b7a)
- Comment out the code for Bot deployment. Here `147-157`
- Now go back to Teams Toolkit and hit deploy. It will deploy only tabs.
- For deployment of bot only disable the code for Tabs.
- For normal deployment (Bot and Tab both / all associated modules ) change back to default.

**Comment by MuyangAmigo** [comment]
@IAM5K Thanks for the information. We will discuss internally how we can better support this scenario, it might be either through allowing multiple yml files or conditional logics in the teamsapp.yml. Will get back to you on our plan.

**Comment by IAM5K** [comment]
Hi,
It has been 9 months, any update?

**Comment by MuyangAmigo** [comment]
Hey @IAM5K, unfortunately we didn't get enough similar requests to prioritize this feature request. We will get back to you if we have new inputs to prioritize this support. Apologies for the inconvinence.

**Comment by IAM5K** [comment]
We don't even have an option to have a bot with a tab. If there is any documentation please share

**Comment by jayzhang** [comment]
@IAM5K We are considering adding an optional input like 'config-file-path' in 'teamsapp deploy' CLI command that you can specify the yml file to run. Then you can split your deployment part into two different yaml files. Does this make sense for you?

**Comment by IAM5K** [comment]
Yeah that will help

**Comment by IAM5K** [comment]
@jayzhang is there a way how we can create a bot and then add a tab to it. Because we don't have any such options now.

**Comment by jayzhang** [comment]
@IAM5K Current version of TTK don't support doing this automatically, but you can follow the guide to add a tab mannually: https://github.com/OfficeDev/TeamsFx/wiki/How-to-configure-Tab-capability-within-your-Teams-app
