### ISSUE TITLE
Teams Toolkit v5.0.0 stuck in "Provisioning" state

### ISSUE THREAD

**Issue by senkwe** [OfficeDev/TeamsFx#8746]
**Description**
Just upgraded to v5.0.0 and all of a sudden I'm unable to debug my Teams Tab app. It's been stuck at the "provisioning" step forever.

2023-05-21T18:36:28.660Z] [Info] - Start to run command: "echo "::set-teamsfx-env PROVISIONOUTPUT__AZURESTORAGETABOUTPUT__DOMAIN=localhost:53000"; echo "::set-teamsfx-env PROVISIONOUTPUT__AZURESTORAGETABOUTPUT__ENDPOINT=https://localhost:53000"; echo "::set-teamsfx-env PROVISIONOUTPUT__AZURESTORAGETABOUTPUT__INDEXPATH=/index.html#";" on path: "C:\Experiments......".

**Expected behavior**
This worked fine with the previous version.

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/3192004/dc6a0237-7637-40f9-b468-9ad7ce2d02be)
**VS Code Extension Information (please complete the following information):**
 - OS: Windows 
 - Version 11

**Comment by xzf0587** [comment]
Hi @senkwe,
Thanks for reaching out.
The Teams Toolkit executes the "Provision" command based on the provision sector in "teamsapp.yml" in the project folder.
It seems the "teamsapp.yml" has been customized by adding a script action.
Could you help provide the content of "teamsapp.yml" to help our investigation?

**Comment by senkwe** [comment]
> Could you help provide the content of "teamsapp.yml" to help our investigation?

Sure. This is the content of my teamsapp.local.yml

\# yaml-language-server: $schema=https://aka.ms/teams-toolkit/1.0.0/yaml.schema.json
\# Visit https://aka.ms/teamsfx-v5.0-guide for details on this file
\# Visit https://aka.ms/teamsfx-actions for details on actions
version: 1.0.0

provision:
  \# Creates a new Azure Active Directory (AAD) app to authenticate users if
  \# the environment variable that stores clientId is empty
  - uses: aadApp/create
    with:
      \# Note: when you run aadApp/update, the AAD app name will be updated
      \# based on the definition in manifest. If you don't want to change the
      \# name, make sure the name in AAD manifest is the same with the name
      \# defined here.
      name: ${{CONFIG__MANIFEST__APPNAME__SHORT}}-aad
      \# If the value is false, the action will not generate client secret for you
      generateClientSecret: true
      \# Authenticate users with a Microsoft work or school account in your
      \# organization's Azure AD tenant (for example, single tenant).
      signInAudience: "AzureADMyOrg"
    \# Write the information of created resources into environment file for the
    \# specified environment variable(s).
    writeToEnvironmentFile:
      clientId: AAD_APP_CLIENT_ID
      \# Environment variable that starts with `SECRET_` will be stored to the
      \# .env.{envName}.user environment file
      clientSecret: SECRET_AAD_APP_CLIENT_SECRET
      objectId: AAD_APP_OBJECT_ID
      tenantId: AAD_APP_TENANT_ID
      authority: AAD_APP_OAUTH_AUTHORITY
      authorityHost: AAD_APP_OAUTH_AUTHORITY_HOST

  \# Creates a Teams app
  - uses: teamsApp/create
    with:
     \# Teams app name
      name: ${{CONFIG__MANIFEST__APPNAME__SHORT}}
    \# Write the information of created resources into environment file for
    \# the specified environment variable(s).
    writeToEnvironmentFile:
      teamsAppId: TEAMS_APP_ID

  - uses: script \# Set env for local launch
    with:
      run:
        echo "::set-teamsfx-env PROVISIONOUTPUT__AZURESTORAGETABOUTPUT__DOMAIN=localhost:53000";
        echo "::set-teamsfx-env PROVISIONOUTPUT__AZURESTORAGETABOUTPUT__ENDPOINT=https://localhost:53000";
        echo "::set-teamsfx-env PROVISIONOUTPUT__AZURESTORAGETABOUTPUT__INDEXPATH=/index.html#";

  \# Apply the AAD manifest to an existing AAD app. Will use the object id in
  \# manifest file to determine which AAD app to update.
  - uses: aadApp/update
    with:
     \# Relative path to this file. Environment variables in manifest will
      \# be replaced before apply to AAD app
      manifestPath: ./aad.manifest.json
      outputFilePath : ./build/aad.manifest.${{TEAMSFX_ENV}}.json

  \# Validate using manifest schema
  - uses: teamsApp/validateManifest
    with:
      \# Path to manifest template
      manifestPath: ./appPackage/manifest.json

  \# Build Teams app package with latest env value
  - uses: teamsApp/zipAppPackage
    with:
      \# Path to manifest template
      manifestPath: ./appPackage/manifest.json
      outputZipPath: ./build/appPackage/appPackage.${{TEAMSFX_ENV}}.zip
      outputJsonPath: ./build/appPackage/manifest.${{TEAMSFX_ENV}}.json

  \# Validate app package using validation rules
  - uses: teamsApp/validateAppPackage
    with:
     \# Relative path to this file. This is the path for built zip file.
      appPackagePath: ./build/appPackage/appPackage.${{TEAMSFX_ENV}}.zip

  \# Apply the Teams app manifest to an existing Teams app in
  \# Teams Developer Portal.
  \# Will use the app id in manifest file to determine which Teams app to update.
  - uses: teamsApp/update
    with:
      \# Relative path to this file. This is the path for built zip file.
      appPackagePath: ./build/appPackage/appPackage.${{TEAMSFX_ENV}}.zip

deploy:
  \# Generate runtime environment variables
  - uses: file/createOrUpdateEnvironmentFile
    with:
      target: ./tabs/.env.teamsfx.local
      envs:
        BROWSER: none
        HTTPS: true
        PORT: 53000
        SSL_CRT_FILE: ${{SSL_CRT_FILE}}
        SSL_KEY_FILE: ${{SSL_KEY_FILE}}

  \# Generate runtime environment variables
  - uses: file/createOrUpdateEnvironmentFile
    with:
      target: ./tabs/.env.teamsfx.local
      envs:
        REACT_APP_START_LOGIN_PAGE_URL: ${{PROVISIONOUTPUT__AZURESTORAGETABOUTPUT__ENDPOINT}}/auth-start.html
        REACT_APP_CLIENT_ID: ${{AAD_APP_CLIENT_ID}}

  \# Run npm command
  - uses: cli/runNpmCommand
    with:
      args: install --no-audit
      workingDirectory: ./tabs

**Comment by senkwe** [comment]
Thanks, I was able to get further after commenting this out. My env variables were already set correctly.
