### ISSUE TITLE
bug report: teamsapp.js example code does not wait for microsoftTeams.app.initialize to be completed

### ISSUE THREAD

**Issue by erinha** [OfficeDev/TeamsFx#8761]
In src/static/scripts/teamsapp.js (auto-generated code when you create a Basic Tab app), it calls the [initialize](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest#@microsoft-teams-js-initialize) method on the teamsjs library without waiting for it complete before making other teamsjs calls. This is a race condition. In order to have predictable behavior, it is required to wait until initialize completes before calling other teamsjs functions (either by using the callback parameter of the [deprecated version](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/?view=msteams-client-js-latest#@microsoft-teams-js-initialize) or waiting for the Promise to complete in the [current version](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teams-js/app?view=msteams-client-js-latest#@microsoft-teams-js-app-initialize)).

**Comment by hund030** [comment]
Thanks for the bug report. The fix has been merged.
