### ISSUE TITLE
Bot has no response after messaging in Teams

### ISSUE THREAD

**Issue by swatDong** [OfficeDev/TeamsFx#8778]
***For everyone's information, this is an upstream service issue and the engineering team is actively working on it.***

**Bot does not work**
My existing bot has no response after messaging it so I created a new one to test, but the newly create one fails on installation.

**To Reproduce**
**For existing project:**
1. Open project and F5
2. Wait for Teams Web Client launching in browser
3. Add the bot app
4. Chat with the bot
  <img width="382" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/7642967/c45c5045-ea1f-4044-9d57-76500c9a4a19">

5. There's no response and the breakpoint on `api/messages` is not hit
  <img width="448" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/7642967/c54e0fa2-7790-4e02-9eab-8ee9f073a84d">

<br/>
<br/>
<br/>

**For new project:**
1. Create new bot project and F5
2. Wait for Teams Web Client launching in browser
3. Add the bot app
4. Error occurs
  <img width="366" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/7642967/58df7224-6f59-49da-96d9-7ae8724eb55a">

**Expected behavior**
Both existing project and new project should work well (messaging bot and getting response)

**VS Code Extension Information (please complete the following information):**
Teams Toolkit V5.0.0

VSCode:
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by swatDong** [comment]
This is an upstream service issue and the engineering team is actively working on it.

**Comment by kimizhu** [comment]
The upstream team indicates this issue has been fixed, so close this issue for now.
