### ISSUE TITLE
bug report: Unable to start local tunneling service task. After updating to v5.0.0

### ISSUE THREAD

**Issue by rastym** [OfficeDev/TeamsFx#8786]
Right after updating the toolkit from v4 to v5 - we are not able to start our application locally.All the steps described in the **Preview upgradeReport.md** file were completed successfully. We face this  issue on linux/macOS. In case you need more information - just let me know, thanks.

**Screenshots**
![a](https://github.com/OfficeDev/TeamsFx/assets/33793538/5c48be28-9bbb-4ce3-8196-6c0b0ae612bd)
![image](https://github.com/OfficeDev/TeamsFx/assets/33793538/0a76355e-1b65-4269-869c-9f935d263067)

**Comment by xiaolang124** [comment]
Can you try to delete account cache in '/home/{user}/.fx/account and then reload VS Code to try again? This may be caused by token expired.

**Comment by rastym** [comment]
@xiaolang124  It helped, the issue can be closed, thanks!
