### ISSUE TITLE
Unable to start local tunneling service task. Unexpected token 'r', "r���tn�O�"... is not valid JSON

### ISSUE THREAD

**Issue by data-pirate** [OfficeDev/TeamsFx#8876]
While starting a new debug session I am getting this error. teams toolkit prompts me to sign into my Microsoft 365 account.
when i log in into my account it throws the error `Unable to start local tunneling service task. Unexpected token 'r', "r���tn�O�"... is not valid JSON`

**To Reproduce**
1. Go to Run and Debug
2. Click on Debug(chrome)
3. Sign in into you Microsoft account
4. Check terminal for error

**Expected behavior**
i want to start the development server but due to this bug i am not able to continue further

**Screenshots**
n/a

**VS Code Extension Information (please complete the following information):**
 - OS: Ubuntu 22.04

**CLI Information (please complete the following information):**
 - OS: ubuntu 22.04
 - Version 2

**Additional context**
i have two environments
1. local
2. production

i want to run local on running the debug command

**Comment by xiaolang124** [comment]
If you continue to encounter this problem, you can try logging in through the tree view first and then attempt local debugging again. This approach may help resolve any issues you are experiencing. We will fix this in the next version.

**Comment by data-pirate** [comment]
@macoo887 Thanks, this was helpful and it solved the problem
