### ISSUE TITLE
Not able to get choiceSet data from the adaptive card

### ISSUE THREAD

**Issue by data-pirate** [OfficeDev/TeamsFx#8877]
I am trying to get the send a choiceSet to the user which contains a list of all the items. I want to get the choice of the user when user clicks on the submit button. But the data object in the invokeValue comes as undefined.

here is the adaptive card that I am sending

```
{
    "type": "Input.ChoiceSet",
    "choices": [{
        "name": "choice1",
        "value": "1"
     },{
        "name": "choice2",
        "value": "2"
     }],
    "placeholder": "Select a team",
    "id": "teamId"
},
{
    "type": "ActionSet",
    "actions": [
    {
        "type": "Action.Execute",
        "title": "Submit",
        "verb": "teamForIncident",
        "fallback": "Action.Submit",
    }]
}
```

**To Reproduce**
1. create an adaptive card with the above components
2. send this card to Microsoft teams
3. select a choice and hit submit
4. check invokeValue.action.data in the bot

**Expected behavior**
I want to get the result of the selection of the user

**Screenshots**
n/a

**Additional context**
I am using Teams toolkit v4.4
adaptive card version 1.4

**Comment by therealjohn** [comment]
@data-pirate Can you include the snippet of code where you are reading `invokeValue.action.data`? Thanks!

**Comment by data-pirate** [comment]
```
async onAdaptiveCardInvoke(context, invokeValue) {
            const triggeredVerb = invokeValue.action.verb;
            const invokeData = invokeValue.action.data;
            if (triggeredVerb === "update") {
                const apiActions = new ApiActions(context.activity);
                const response = await apiActions.createNewIncidentTemplate(invokeData.teamId)

            }
```

here is the code snippet where I am extracting the invokeValue.action.data 

it throws error that I cannot read property of undefined

**Comment by ktkaushik** [comment]
Hi @therealjohn @adashen - any idea on what's going on? are we doing something wrong? It was working flawlessly just a week ago. No code changes and it breaks now.

**Comment by dooriya** [comment]
@ktkaushik @data-pirate 
According to the Adaptive Card schema definition, the `name` property should be `title` in your `Input.ChoiceSet` json definition. Update your card to below should work:
```json
    {
      "type": "Input.ChoiceSet",
      "choices": [{
          "title": "choice1",
          "value": "1"
       },{
          "title": "choice2",
          "value": "2"
       }],
      "placeholder": "Select a team",
      "id": "teamId"
    },
```

Here I can get the data back from `incokeValue`:
![image](https://github.com/OfficeDev/TeamsFx/assets/10163840/d4df4ef5-62e8-4574-b427-df14ab39acdb)

**Comment by data-pirate** [comment]
Hi @dooriya 

I tried changing the `name` property to `title` but it does not fix the issue. The issue is still the same the `invokeData` is received as undefined.

**Comment by dooriya** [comment]
Hi @data-pirate, 

Could you share the whole adaptive card JSON payload since I cannot repro it on my side?
From my understanding, [Bot Framework SDK](https://github.com/microsoft/botbuilder-js) will automatically fill in the `invokeData` if your card JSON is configured correctly (e.g. no schema error, the `id` property should be set for `Input.ChoiceSet`).  

Thanks!

**Comment by data-pirate** [comment]
@dooriya 

here is the adaptive card that i am sending
``` json
{
            "type": "AdaptiveCard",
            "body": [
                {
                    "type": "TextBlock",
                    "text": "Select a team you wish to create an incident",
                    "weight": "Bolder",
                    "size": "Small",
                    "style": "heading",
                    "wrap": true
                },
                {
                    "type": "Input.ChoiceSet",
                    "choices": [
                        {
                            "title": "Team 1",
                            "value": "team1"
                        },
                        {
                            "title": "Team 2",
                            "value": "team2"
                        }
                    ],
                    "placeholder": "Select a team",
                    "id": "teamId",
                },
                {
                    "type": "ActionSet",
                    "actions": [
                        {
                            "type": "Action.Execute",
                            "title": "Submit",
                            "verb": "teamForIncident",
                            "fallback": "Action.Submit",
                        }
                    ]
                }

            ],
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "version": "1.4"
        }
```

It was working perfectly a week ago. There is no code changes and it breaks now

**Comment by dooriya** [comment]
@data-pirate The above json is not a valid json, two trailing command need to be removed:
![image](https://github.com/OfficeDev/TeamsFx/assets/10163840/9566e09d-4446-405d-a8e3-350b785b2b52)

Can you fix it and re-run your app again?

**Comment by data-pirate** [comment]
@dooriya
Sorry for the confusion

it seems these trailing commas are added by mistake while copy pasting the JSON. In the actual json payload there is no trailing commas.

**Comment by data-pirate** [comment]
Hi there @dooriya 

Using the `invokeValue` solved the problem. Thank you so much for guiding us through.
