### ISSUE TITLE
bug report: coordinator. Error

### ISSUE THREAD

**Issue by sadalala** [OfficeDev/TeamsFx#8878]
EPERM: operation not permitted, mkdir 'c:\Program <REDACTED: user-file-path> <REDACTED: user-file-path>'

stack:
Error: EPERM: operation not permitted, mkdir 'c:\Program <REDACTED: user-file-path> <REDACTED: user-file-path>'

**Comment by therealjohn** [comment]
@sadalala What are the steps you took to get this issue? Can you include more details. Thanks!

**Comment by sadalala** [comment]
i just started the team tool kit in the visual code studio and waited for it to process and follow the steps. i am not sure if i did any mistakes

**Comment by tecton** [comment]
Hi @sadalala, if you met this error when you are creating new project, could you please share what's the workspace folder of your project? By default, it's under your home folder like "C:\Users\xxx\TeamsApps". If you haven't changed it, we'll further investigate the cause of this error.
