### ISSUE TITLE
Add features option is missing in Teams toolkit latest version 5.0

### ISSUE THREAD

**Issue by SubbaReddi** [OfficeDev/TeamsFx#8900]
**Describe the bug**
Add features option is missing in Teams toolkit latest version 5.0. It was there with 4.5.0 version.

**To Reproduce**
1. Add tab application using Teams toolkit 
2. Search for "Add features" option to add bot 

**Expected behavior**
Add features option should be displayed in left navigation-Teams toolkit section

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/69682598/e8bf7168-0af6-42da-b789-950dc3fe15df)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version 5.0

**Additional context**
vs code version: 1.78.2

**Comment by therealjohn** [comment]
@SubbaReddi Sorry for the confusion! In version 5, Add Features was replaced with new, updated How To guides. You can access them from VS Code using the command palette and searching for Teams: View How To:

![image](https://github.com/OfficeDev/TeamsFx/assets/1501196/2965ce45-9082-4a1d-bf38-7beed85c8800)

We're looking for more ways to improve how you can add, combine, and expand your app so please share any feedback you have.
