### ISSUE TITLE
How can we make our app multi tenant and successfully deploy & render content across multiple organization ?

### ISSUE THREAD

**Issue by IAM5K** [OfficeDev/TeamsFx#8915]
# **Problem statement:**

**Objective**: Publish a Microsoft Teams app with a chatbot and tabs integrated.

**Steps we did:** 
While processing to publish the app, we knew the following things,

- The bot is supported and all functionality works as expected.
- The app has integrated tabs in it that are visible on the top of the chat.
- The app shows the hosted content properly and the errors are handled well.
- To start the functionality, details of the user are required as context from Microsoft Graph API. The tab has SSO enabled so it fetches a token from Microsoft.
- It returns an error with token failure that the resource principal name is not found in the current tenant.
- We came to know that our tab does not have multi-tenant support.
- On converting the app to multi-tenant, it threw an error, on analyzing it, we came to know that we need a custom domain to make the app multi-tenant.

**Issues:**

- Documentations given by the Microsoft team do not align with our scenario and we are not able to add a custom domain directly to the tab app we have to add it in the bot and then we access it in tabs using "/webtab".
- Following the [GitHub Wiki](https://github.com/OfficeDev/TeamsFx/wiki/Multi-tenancy-Support-for-Azure-AD-app), we configured the app and now it is multi-tenant, supporting our custom domain. But after successful provision and deployment, it is unable to render the required tab.
- For further details refer to: [Question on Stackoverflow](https://stackoverflow.com/questions/76361305/adding-custom-domain-to-tabs-and-make-it-work-as-multi-tenant).  After implementing the solution we achieved multitenant with custom domain.
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/f196d50a-fbbe-463e-85f6-6bc5a4093886)

**Active Errors:**

- Error inside teams environment switching to teams.`OutOfRangeInputOne of the request inputs is out of range. RequestId:14e78267-001e-003c-7d43-95bea1000000 Time:2023-06-02T11:12:31.8502077Z`
![Inside Teams](https://github.com/OfficeDev/TeamsFx/assets/43265495/c5bd8a80-4813-4ccd-a936-a109d4060380)

- Error when manually opening the CDN URL in a browser
``` xml
<Error>
    <Code>InvalidQueryParameterValue</Code>
    <Message>Value for one of the query parameters specified in the request URI is invalid. RequestId:f07560bf-301e-007a-3444-958a26000000 Time:2023-06-02T11:20:23.0757441Z</Message>
    <QueryParameterName>comp</QueryParameterName>
    <QueryParameterValue/>
<Reason/>
</Error>
```
![direct url](https://github.com/OfficeDev/TeamsFx/assets/43265495/556fce1a-cf77-4a97-96b7-c5765b64625d)

- If we open the old Tab URL in the browser the content (our app UI) is still rendered there, where we handle the error with token and teams environment (app can be used inside Teams tabs only) dependency by rendering AUTH error page. Ignore the content inside as it is a custom text. It is supposed to come when the admin of the organization had not allowed our app to access organization information. The app takes a token to access the data and here it is failing hence the screen is presented.
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/8855850f-b1a5-4f29-a013-26813b14cc58)

## Primary Questions: For the given scenario.
1. What should be our storage domain and endpoint in `templates\azure\provision\azureStorageTab.bicep`?
2. What should be `"m365TenantId": ` "common"` or `"${{AAD_APP_TENANT_ID}}"` in the file `templates\azure\azure.parameters.dev.json`?
3. What will be the right value for "signInAudience": "AzureADMultipleOrgs" in `aad.manifest.json`?
4. What will be the right value for 
 ```json 
"identifierUris": [
        "api://${{PROVISIONOUTPUT__AZURESTORAGETABOUTPUT__DOMAIN}}/botid-${{BOT_ID}}"
    ]
``` 
in `aad.manifest.json`?
5.  Right value for 
```json 
    "auth": {
        "frontendDomain": "custom.domain.com/webtab"
    }
```
in `.backup\.fx\configs\config.local.json`?
7.  What would be the value for Application ID Uri in Azure?
![Aad App id uri](https://github.com/OfficeDev/TeamsFx/assets/43265495/c9b489d8-2b87-4f5b-8453-fd188caa6117)
8. What should be the auth url `"m365OauthAuthorityHost": "${{AAD_APP_OAUTH_AUTHORITY_HOST}}"` in in the file `templates\azure\azure.parameters.dev.json` and Azure aad?

**Expected behavior**
After implementing the multi-tenant app should render the tab UI inside teams or manually opening the custom domain URL in a browser but it is not happening.

**Teams Toolkit - VS Code Extension Information:**
 - OS: Windows 10
 - Version v5.0.0

We are unable to upload screenshots in forum question hence adding here.
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/253bbc29-bb6c-4d8f-a557-ce1508f3f8f1)

# **Explored Resources**
## Tab Multi-tenant handling (Step by step)
1. Multi tenancy Support for Azure AD app : https://github.com/OfficeDev/TeamsFx/wiki/Multi-tenancy-Support-for-Azure-AD-app 
5. https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-modify-supported-accounts#why-changing-to-multi-tenant-can-fail
8. https://github.com/OfficeDev/TeamsFx/blob/main/docs/fx-core/aad-help.md#action-1-note-frontend-info
9. https://github.com/OfficeDev/TeamsFx/blob/main/docs/fx-core/aad-help.md#action-2-provision-cdn-profile-on-azure-portal
10. https://learn.microsoft.com/en-us/azure/cdn/cdn-create-new-endpoint
11. https://github.com/OfficeDev/TeamsFx/blob/main/docs/fx-core/aad-help.md#scenario-one-setup-cdn-as-storage-custom-domain
12. https://learn.microsoft.com/en-us/azure/cdn/cdn-create-new-endpoint#create-a-new-cdn-profile
13. After completing all steps => Deployed => https://github.com/OfficeDev/TeamsFx/wiki/Manage-AAD-application-in-Teams-Toolkit#how-to-view-the-aad-app-on-the-azure-portal-for-v5
14. [Grant tenant-wide admin consent to an application](https://learn.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent?pivots=portal)

## Error Support 
- Self raised query : [Adding custom domain to tabs and make it work as multi-tenant](https://stackoverflow.com/questions/76361305/adding-custom-domain-to-tabs-and-make-it-work-as-multi-tenant)
- [**Error after changing my Application ID URI to CDN endpoint**](https://stackoverflow.com/questions/74132982/error-after-changing-my-application-id-uri-to-cdn-endpoint)

## Similar Resources 
- [Azure website returns ERR_CONNECTION_RESET error after adding custom domain and SSL Certificate](https://stackoverflow.com/questions/71017043/azure-website-returns-err-connection-reset-error-after-adding-custom-domain-and)
- [Error after changing my Application ID URI to CDN endpoint](https://stackoverflow.com/questions/74132982/error-after-changing-my-application-id-uri-to-cdn-endpoint)
- [What is the difference between 'Active Directory Custom Domain' and 'App Service Custom Domain'?](https://stackoverflow.com/questions/76089627/what-is-the-difference-between-active-directory-custom-domain-and-app-service)
- ["Blank tabs" on Teams App update deployment (Teams Toolkit)](https://stackoverflow.com/questions/74742391/blank-tabs-on-teams-app-update-deployment-teams-toolkit)
- [Custom domain URL with Azure App Function](https://stackoverflow.com/questions/69403933/custom-domain-url-with-azure-app-function)
- [Azure web app website - to a custom domain - does it need SSL certificate upload every few months?](https://stackoverflow.com/questions/64357443/azure-web-app-website-to-a-custom-domain-does-it-need-ssl-certificate-upload)
- [Azure Front Door custom domain not using correct cert](https://stackoverflow.com/questions/76031886/azure-front-door-custom-domain-not-using-correct-cert)
- [Azure CDN - redirect from *.azurewebsites.net to cdn generate ERR_TOO_MANY_REDIRECTS error](https://stackoverflow.com/questions/66472075/azure-cdn-redirect-from-azurewebsites-net-to-cdn-generate-err-too-many-redir)
- [Azure website returns ERR_CONNECTION_RESET error after adding custom domain and SSL Certificate](https://stackoverflow.com/questions/71017043/azure-website-returns-err-connection-reset-error-after-adding-custom-domain-and)
- [How to add a custom domain to Azure static web app by api](https://stackoverflow.com/questions/72410359/how-to-add-a-custom-domain-to-azure-static-web-app-by-api)
- [Azure Websites and wildcard domains](https://azure.microsoft.com/en-us/blog/azure-websites-and-wildcard-domains/)
- [az staticwebapp hostname](https://learn.microsoft.com/en-us/cli/azure/staticwebapp/hostname?view=azure-cli-latest)
- [Custom domains with Azure Static Web Apps](https://learn.microsoft.com/en-us/azure/static-web-apps/custom-domain)
- [Configuring custom domains with Azure Front Door](https://stackoverflow.com/questions/71963320/configuring-custom-domains-with-azure-front-door)
- [Tutorial: Configure HTTPS on a Front Door (classic) custom domain](https://learn.microsoft.com/en-us/azure/frontdoor/front-door-custom-domain-https)
- [Cannot update authentication as Multi tenant under registered application in Azure](https://stackoverflow.com/questions/60393330/cannot-update-authentication-as-multi-tenant-under-registered-application-in-azu)
- [Map an existing custom DNS name to Azure App Service](https://learn.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-custom-domain?tabs=root%2Cazurecli)
- [Adding a custom domain to Azure App Service](https://dev.to/dailydevtips1/adding-a-custom-domain-to-azure-app-service-28bh)
- [Error AADSTS50011: The redirect URI specified in the request does not match](https://learn.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50011-redirect-uri-mismatch#cause)
- ["One of the request inputs is out of range" when using Azure Storage PHP SDK](https://stackoverflow.com/questions/30210358/one-of-the-request-inputs-is-out-of-range-when-using-azure-storage-php-sdk)
- [How to update my Teams app already deployed in Azure?](https://stackoverflow.com/questions/76323776/how-to-update-my-teams-app-already-deployed-in-azure)
- [Managing custom domain names in your Azure Active Directory](https://learn.microsoft.com/en-us/azure/active-directory/enterprise-users/domains-manage?WT.mc_id=Portal-Microsoft_Azure_Support#add-subdomains-of-a-custom-domain)
- [https://learn.microsoft.com/en-us/azure/virtual-machines/custom-domain?wt.md_id=searchAPI_azureportal_inproduct_rmskilling&sessionId=37f4413221b54953aa1b751b4fb8a130](https://learn.microsoft.com/en-us/azure/virtual-machines/custom-domain?wt.md_id=searchAPI_azureportal_inproduct_rmskilling&sessionId=37f4413221b54953aa1b751b4fb8a130)
- [https://azure.github.io/AppService/2020/07/28/zero_to_hero_pt5.html#upate-dns](https://azure.github.io/AppService/2020/07/28/zero_to_hero_pt5.html#upate-dns)
- [Azure - New Restrictions To Azurewebsites.net Domain](https://www.c-sharpcorner.com/blogs/azure-new-restrictions-to-azurewebsitesnet-domain)
- [What's new for authentication?](https://learn.microsoft.com/en-us/azure/active-directory/develop/reference-breaking-changes#appid-uri-in-single-tenant-applications-will-require-use-of-default-scheme-or-verified-domains)

**Comment by KennethBWSong** [comment]
Hi @IAM5K Thank you for using our Toolkit. Here are answers to your question:
1. In `templates\azure\provision\azureStorageTab.bicep`, you need to set the value of domain and endpoint to your custom domain's domain and endpoint.
2. In `templates\azure\azure.parameters.dev.json`, you need to set value of `m365TenantId` to `common` and leave `${{AAD_APP_TENANT_ID}}` unchanged.
3. In `aad.manifest.json`, you need to set value of `signInAudience` to `AzureADMultipleOrgs` for multi-tenant app.
4. In `aad.manifest.json`, you don't need to update the value of `identifierUris`. If you want to see the result, you can go to `build/aad.{env}.json`.
5. All settings in `.backup` is backup content that will not be used in Teams Toolkit >= V5.0.0. You don't need to update this.
6. Teams Toolkit will update your AAD app to the same value of `identifierUris` in `aad.{env}.json` when provision. Please make sure you have run provision first.
7. You don't need to update the value of `m365OauthAuthorityHost` in `templates/azure/azure.parameters.dev.json`. Please keep the same as `https://login.microsoftonline.com`.

Since you can not render your custom domain, would you please try:
1. Open endpoint of your custom domain in browser to see whether it can successfully render
2. Check whether your custom domain has been pointed to the storage endpoint provisioned by Teams Toolkit

**Comment by IAM5K** [comment]
Thanks for your response, I am implementing the suggested changes and will get back if there are any further issues.

**Comment by IAM5K** [comment]
1. Modified Azure storage endpoint with a custom domain and endpoint.
   ![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/07918083-afff-4283-b023-91da563c4518)
2. Tenant Id set to common 
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/3cb89744-d0c5-4baf-97f1-bf8821676931)
3. Organisation changed to Multiple
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/fc3fc0ab-cdc4-4a94-8a79-24cdec4a340e)
4. IdentifierUri left as it is.
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/890bb9b4-a4e1-4408-b9de-91e169b6c1ef)
5. Provision runned.
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/85c493d6-d0fc-40e5-a46a-49da5b4108da)
6. Ignored backup data.
7. App authority as `https://login.microsoftonline.com`
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/38cab751-940b-4b94-978d-f1b41cf88948)
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/03b900ef-0ae1-4576-becd-dc6cb58ee1cb)

The current content of the tab :
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/34134190-8bcf-407d-b9f9-3c04dd0700a8)

Content when opening in the browser:
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/bf22471a-b8c5-44d0-959a-3cbde1456144)

Network calls made to the right URL
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/9dd85bd3-92c8-475d-8c62-c00973780c4e)

Custom domain is integrated into the CDN
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/eee4271d-eebc-4a6e-880a-16e8804400ef)

Snap from our DNS config panel.
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/ef642cf5-2510-483c-9c63-41455cac5544)

On opening the Azure endpoint in a browser 
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/694f40f1-9171-4109-b5ce-d320bd9bd8d8)

On opening the Azure Origin hostname in a browser 
![image](https://github.com/OfficeDev/TeamsFx/assets/43265495/61b7a214-c0fd-4410-a2d8-1ab21b355b0c)

Everything seems in place still not getting the expected output. 
It would we very helpful if anyone can connect with us if needed.
You can reach out to me on [Linkedin](https://in.linkedin.com/in/iam5k) 

Thanks in advance.

**Comment by KennethBWSong** [comment]
@IAM5K Thank you for your reply! Seems your tab app does not work even with origin hostname. The error indicates that the site is not correctly set. Please help to check:
1. Teams Toolkit is using Azure Storage to host static website. The endpoint should be web.core.windoes.net. Would you please help to verify `tweelinf9fb56tab.blob.core.windows.net` is the endpoint in `.env.{env}`?
2. When setting custom domain, do you correctly select `Storage static website` as shown below?
![image](https://github.com/OfficeDev/TeamsFx/assets/63089166/414bef63-c99a-4937-a008-bd581b2ef4b1)

**Comment by IAM5K** [comment]
Thanks for your response, 
Endpoint was different with a ` ___.z13.web.core.windows.net`
CDN endpoint was initially configured as storage.
Created a new endpoint with the suggested config and had to delete CNAME from DNS.
After applying all the above-mentioned configurations it worked perfectly.
Thanks again @KennethBWSong 👍
