### ISSUE TITLE
Support App Service Linux deployment

### ISSUE THREAD

**Issue by hktdc-spwong** [OfficeDev/TeamsFx#8943]
In Azure App Service, only windows instance support zipDeploy API.
Linux does not support such deployment approach

Is there any roadmap for TeamsFx to support Linux deployment other than `azureAppService/zipDeploy` ? Thanks

**Comment by Siglud** [comment]
@hktdc-spwong  The bug in our zip file packaging process created a Windows-like folder path, making it unreadable on Linux. We will fix this issue in #8975.

For now, you can use the script driver with Azure CLI to deploy to App Service Linux. Apologies for any inconvenience caused.

**Comment by hktdc-spwong** [comment]
Greatly appreciate the follow up.
