### ISSUE TITLE
BUG teamsfx cli login m365 exception when CI_ENABLED true

### ISSUE THREAD

**Issue by chtsscs** [OfficeDev/TeamsFx#8997]
**Describe the bug**
When attempting to login to m365 account with the CI_ENABLED true, an exception occurs. Looks like a bug, as login into azure account with CI_ENABLED works as expected. 

**To Reproduce**
1. Install latest teams-fx package (npm install @microsoft/teamsfx-cli@2.0.1-alpha.eebec21dd.0)
2. Export required env vars including ENABLE_CI ( export CI_ENABLED=true )
3. Log into Microsoft 365 account ( teamsfx account login m365 )
4. See error "(x) Error: TeamsfxCLI.UnknownError"

**Expected behavior**
Expect headless (no browser) microsoft 365 account login to succeed using CI_ENABLED, similarly to the azure account login.

**CLI Information (please complete the following information):**
 - Versions [@microsoft/teamsfx-cli@2.0.0 to 2.0.1-alpha.eebec21dd.0]
 
**Additional context**
We are attempting to log in our M365 account such that we can provision and deploy our teams app as part of a continuous deployment pipeline of our development environment. It looks like while the CI_ENABLED login feature operating as expected for the azure account login it is not for the m365 account login. 

teamsfx account login m365
TeamsFx/tree/dev/packages/cli/src/commonlib/m365LoginUserPassword.ts > removeStatusChangeMap

teamsfx account login azure
TeamsFx/packages/cli/src/commonlib/azureLoginCI.ts > removeStatusChangeMap > implemented via TeamsFx/packages/cli/src/commonlib/common/login.ts

**Comment by xiaolang124** [comment]
Now, m365 login does not support CLI command. You can use environment variables to set up m365 credential. You can follow this document to have a try.
https://github.com/OfficeDev/TeamsFx/wiki/How-to-automate-cicd-pipelines
