### ISSUE TITLE
bug report: Core.Error

### ISSUE THREAD

**Issue by sadalala** [OfficeDev/TeamsFx#9011]
getaddrinfo ENOTFOUND titles.prod.mos.microsoft.com

stack:
Error: getaddrinfo ENOTFOUND titles.prod.mos.microsoft.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:<REDACTED: user-file-path>:130:17)

**Comment by sadalala** [comment]
i am a new learner maybe my method is wrong or just got this up so wanted to share with you

**Comment by adashen** [comment]
Hi @sadalala thanks for reporting the issue. Can you provide the repro steps in detail?
