### ISSUE TITLE
aadAppUpdate Error

### ISSUE THREAD

**Issue by CarlosGuadamuz** [OfficeDev/TeamsFx#9053]
**Describe the bug**
In Visual Studio, using the Teams Tool Kit, when debugging the code, the customer is getting the following error:
[addAppUpdate.UnhandledUserError]: An unexpected error has occurred while performing the AadApp/Update task. The reason for this error is: Request failed with status code 400. Welcome to report this by clicking on the provided “issue link, so that we can investigate and resolve the problem as soon as possible. 
Even if the customer follows the below article they still getting the same error when debugging the code:
https://github.com/OfficeDev/TeamsFx/wiki/Available-actions-in-Teams-Toolkit#aadappupdate
**To Reproduce**
1. Go to 'Visual Studio'
2. Click on 'Debug in Chrome' (This occurs debugging locally and not locally)

Screenshot:

![image](https://github.com/OfficeDev/TeamsFx/assets/85959949/aa416379-3280-4cbd-90ef-6f9925425833)

**Expected behavior**
Not getting this error to be able to initialize the app.

**VS Code Extension Information (please complete the following information):**
 - Teams Tool Kit 
 - Version 5
**Additional context**

**Comment by blackchoey** [comment]
@CarlosGuadamuz can you install Teams Toolkit 5.0.1 and do same steps? The latest Teams Toolkit will show detailed errors to you. Please share the detailed errors here so we can provide suggestions based on the error message.

**Comment by CarlosGuadamuz** [comment]
With the Teams Toolkit version 5.0.1 the issue got resolved. Thanks.
