### ISSUE TITLE
  At random : The bot encountered unhandled error: Authorization has been denied for this request. 

### ISSUE THREAD

**Issue by whiteGhost-08** [OfficeDev/TeamsFx#9076]
**Describe the bug**
Receiving this error at random(sometimes work, sometimes it doesn't) ---  [onTurnError] unhandled error: Error: Authorization has been denied for this request. 
when simply trying to echo the user input on microsoft teams. 

more information : 

I have been trying to develop a notification bot. I made some progress, but since this morning, I suddenly started getting an error in my main bot app. I thought I had made a mistake in the code somewhere, so I decided to create a new one. I used the Teams Toolkit extension (version: 5.0.1) to create a new notification message Restify bot and started its debugging session. However, I'm still encountering the same error in the new bot as well.

Additionally, please note that sometimes I am able to send messages to the user from the bot, as shown in the screenshot provided below. Almost every second request fails.

I am using a Microsoft 365 developer account with sideloading enabled, and this code is running locally on localhost.

**To Reproduce**
1. Install Teams Toolkit
2. create a new notification message bot with Restify server
3. add the following code inside the constructor of TeamsBot class(in teamsBot.ts file) 

```
this.onMessage(async (context, next) => {
      await context.sendActivity(`Echo: ${context.activity.text}`);
      await next();
});
```
<img width="757" alt="Screenshot 2023-06-20 at 4 26 00 PM" src="https://github.com/OfficeDev/TeamsFx/assets/83160894/3e5e6192-55e6-4843-8cda-709391688733">

4. press f5, it will start debugging locally and open the teams page on a new browser window, then add the bot and try sending a message.

**Expected behavior**
It should always send the user input message back.
The code was working in my main bot app the day before, now it's not even working in the new bots (I've tried creating several bots, all are giving same error)

**Screenshots**
<img width="757" alt="Screenshot 2023-06-20 at 4 06 35 PM" src="https://github.com/OfficeDev/TeamsFx/assets/83160894/eddb6dbf-06ce-420e-a874-9d5abe9d95f6">

**OS information**
 - OS: macOS Monterey
 - Version 12.6.5

**Comment by ashikns** [comment]
+1 I'm facing this issue too. Tried with a new JS sample generated using Teams Toolkit v5 on VS Code, tried it on local and Azure problem persists.

**Comment by swatDong** [comment]
It's due to upstream service issue and we're contacting the service team for fixing.
Internally I also encountered this from yesterday but back to normal today.

**Comment by ashikns** [comment]
Hi, I am still facing this issue when developing on local. Me and my team members can reproduce this using a freshly generated sample from toolkit (again, while running in local). It seems outgoing message from web app is somehow not going across the dev.botframework service? Please advise, and whether this issue needs to be raised elsewhere.

**Comment by swatDong** [comment]
@ashikns - does you app only fail on local but work on Azure (or some Azure regions)? From source code `context.activity.serviceUrl` represents the botframework service location, and you can check if your request goes to the same endpoint/region.

BTW, there's an active issue (https://github.com/OfficeDev/TeamsFx/issues/9132) impacting the bot service, and raised to
https://github.com/MicrosoftDocs/msteams-docs/issues as well.

**Comment by ashikns** [comment]
@swatDong Currently we can make deployments to eastus and that works fine. Deployments to south central us and central india both do not work, haven't tried other regions.

To provide some more context, when I deployed to Central India, I was able to test the web chat from within the Azure Bot resource in Azure Portal. When I send a message from Teams it doesn't work.

**Comment by swatDong** [comment]
There was an upstream service issue (https://github.com/OfficeDev/TeamsFx/issues/9132) and had been fixed.
Please have a try again.

**Comment by whiteGhost-08** [comment]
> There was an upstream service issue (#9132) and had been fixed. Please have a try again.

Apologies for not informing you earlier, I have retested the bot, and I can confirm that it is now working as expected since yesterday. Thank you for your efforts in resolving the problem.
