### ISSUE TITLE
Factsets are displaying with an outline/border

### ISSUE THREAD

**Issue by adrian-spear** [OfficeDev/TeamsFx#9092]
I am rendering an adaptive card to Teams client from my chat bot solution (implemented using latest Teams Toolkit v5).
The adaptive card contains multiple Factsets - each item in all factsets are displayed with cell outlining. This occurs whether I have bound the factset to a '$data' attribute or not.

To simplify, I also tested rendering the sample Factset schema example from the documentation as follows:
```
{
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "type": "AdaptiveCard",
  "version": "1.0",
  "body": [
    {
      "type": "FactSet",
      "facts": [
        {
          "title": "Fact 1",
          "value": "Value 1"
        },
        {
          "title": "Fact 2",
          "value": "Value 2"
        },
        {
          "title": "Fact 3",
          "value": "Value 3"
        },
        {
          "title": "Fact 4",
          "value": "Value 5"
        }
      ]
    }
  ]
}
```
The output appears as follows:
![image](https://github.com/OfficeDev/TeamsFx/assets/79923757/b0df6eee-a91b-4ef8-b69f-51c805a35677)

 - OS: Windows 11
 - Version Teams Toolkit v5

Thanks.

**Comment by andrzej-zielinski** [comment]
Same issue here.
After the update 1.6.00.16472 (32-bit, it was last updated on 20.06.2023) the MS Teams bot displays adaptive cards incorrectly to all clients, showing FactSets in a table.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8912

**Comment by MuyangAmigo** [comment]
Close as copied over to upstream.
