### ISSUE TITLE
Notification Bot Team App - When deployed API app over Kubernetes (AKS), notification didn't works. Is this supported?

### ISSUE THREAD

**Issue by ajmal-yazdani** [OfficeDev/TeamsFx#9094]
1. I have created a notification bot app C# through template.
2. Create Azure Bot Service choosing option `UserAssignedMSI`.
3. Create Azure App service and with below change deployed the code to Azure App service.

`builder.Configuration["MicrosoftAppType"] = "UserAssignedMSI";
builder.Configuration["MicrosoftAppId"] = builder.Configuration.GetSection("BOT_ID")?.Value;
builder.Configuration["MicrosoftAppTenantId"] = builder.Configuration.GetSection("TENANT_ID")?.Value;`

4. Granting Azure Bot Permissions to the App Service using managed identity above created. Following this article, https://accessibleai.dev/post/create_and_deploy_bot/

![image](https://github.com/OfficeDev/TeamsFx/assets/1866370/6dd2fd99-5fbc-452a-82a2-bce719d34fa0)

All **works** perfectly when app running over Azure App Service  :)

**Issue:**

1. Now I am trying to deploy the app over Kubernetes (AKS) as this is a simple web API app
2. Granting Azure Bot Permissions to the AKS using managed identity above created.

![image](https://github.com/OfficeDev/TeamsFx/assets/1866370/85f6faef-aae5-4b90-85d6-754bb5e71843)

4. Now when I am trying to hit the url `Invoke-WebRequest -Uri "https://dev-aks.company.com/api/notification" -Method Post`, output is 200, but looks like empty and actually it's not hitting anything.

![image](https://github.com/OfficeDev/TeamsFx/assets/1866370/0e803297-2703-48df-8d7a-5862eb205d4e)

I have added logs for Notification Post API call and noticed that no logs output.

Now I am not sure why it's giving 200 without any output. I the approach right and feature supported over AKS?

![image](https://github.com/OfficeDev/TeamsFx/assets/1866370/d7fad227-377b-45d3-ab62-4453b5495f15)

**Comment by swatDong** [comment]
Notification app is a web API app so it should work on both App Service and AKS. Technically, notification logic works as:
- When any interaction with the bot via Teams, the API `api/messages` receives an event
- TeamsFx SDK recognizes the event and persists the information in storage
- When API `api/notification` is called, TeamsFx SDK retrieves the information from storage and sends message

So, please make sure:
- The `api/messages` works well
- The storage is correctly persisted

Please also see this [doc](https://learn.microsoft.com/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams) describing how notification works and how to add your own persisted storage.

**Comment by ajmal-yazdani** [comment]
> Notification app is a web API app so it should work on both App Service and AKS. Technically, notification logic works as:
> 
> * When any interaction with the bot via Teams, the API `api/messages` receives an event
> * TeamsFx SDK recognizes the event and persists the information in storage
> * When API `api/notification` is called, TeamsFx SDK retrieves the information from storage and sends message
> 
> So, please make sure:
> 
> * The `api/messages` works well
> * The storage is correctly persisted
> 
> Please also see this [doc](https://learn.microsoft.com/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams) describing how notification works and how to add your own persisted storage.

@swatDong Thanks for your reply. I tried the way it is, but unfortunately it's doesn't work. 

Regarding `RUNNING_ON_AZURE` I have not set anything while running over Azure App Service and everything works perfectly.

I tried this set this as a environmental variable for AKS, no change. Still same behavior's.

Any log/dislogistic I can enable?

**Comment by swatDong** [comment]
Then you may need to add your own storage (https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams#add-storage) to persist the notification connection data.

`RUNNING_ON_AZURE` enables TeamsFx SDK to use App Service's temp folder as storage, but in AKS that may not work.

**Comment by vamsitp** [comment]
The issue could be because of [this line in NotificationBot.cs](https://github.com/OfficeDev/teams-toolkit/blob/dev/packages/dotnet-sdk/src/TeamsFx/Conversation/NotificationBot.cs#L55) as `TEMP` env-var might not be available on Linux. Instead, using `Path.GetTempPath()` might solve the issue (note that this will return a path with a trailing slash)
