### ISSUE TITLE
Upload failed due to an invalid BotId in your manifest

### ISSUE THREAD

**Issue by whiteGhost-08** [OfficeDev/TeamsFx#9132]
**Describe the bug**
I was trying to create a notification bot using teamstoolkit v5.0.1 extension, on clicking on f5 it starts local debugging and when clicking add button in teams it gives me a pop up saying Upload failed due to an invalid BotId in your manifest.
I'm using developer account for sideloading.

I also tried https://github.com/OfficeDev/TeamsFx/issues/7608#issuecomment-1432603062
but this was already enabled for me you can see in one of the screenshots.

**Screenshots**
<img width="817" alt="Screenshot 2023-06-26 at 5 03 10 PM" src="https://github.com/OfficeDev/TeamsFx/assets/83160894/2dbf76a5-3b0c-4337-95fe-f2274214f7b6">

<img width="960" alt="Screenshot 2023-06-26 at 5 10 43 PM" src="https://github.com/OfficeDev/TeamsFx/assets/83160894/8b0ac302-0a6b-4434-94de-32f8847f0b65">

**Comment by cassidyRonan** [comment]
Also having the same issue as @whiteGhost-08 .

**Comment by ravindran-a** [comment]
also having the same issue as @whiteGhost-08

**Comment by hsteweri** [comment]
Having the same issue.
Also noted that after several hours F5 debugging works. Might be some issues in Azure currently?

**Comment by HuihuiWu-Microsoft** [comment]
Hi @whiteGhost-08, this should be an issue on App studio side, already reported to related team. The issue might not exist after a while or retries.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8919

**Comment by ethanabrooks** [comment]
Never mind. Getting `Error finding key for token. Available keys`.

**Comment by whiteGhost-08** [comment]
> Never mind. Getting `Error finding key for token. Available keys` again. Is there some way to preview a development build without interacting with the Azure server??

@ethanabrooks, I faced a similar error last week when I was deleting my bots from Azure Active Directory (AAD). Fortunately, the problem resolved itself when I cleared the values from the "env" folder.

**Comment by HuihuiWu-Microsoft** [comment]
Hi @whiteGhost-08, the issue has been fixed this morning. We've tested it on our side and works well. Please help create new app to verify.

**Comment by whiteGhost-08** [comment]
> Hi @whiteGhost-08, the issue has been fixed this morning. We've tested it on our side and works well. Please help create new app to verify.

I have tested the fix by creating a new app, and it worked perfectly.. Thank you for resolving the issue.
