### ISSUE TITLE
bug report: SPFx.Error

### ISSUE THREAD

**Issue by tedley63** [OfficeDev/TeamsFx#9134]
When trying to deploy to cloud the first time.. have tried multiple times. Still using Toolkit 4.2.5 as my last project had trouble upgrading the project & using Toolkit 5.0.0...

This is an SPFx tab (web part) project and the web part was ported from a previous webpart-only SPFX project.

I'm not sure what additional information you need.

-----

Request failed with status code 400

stack:
Error: Request failed with status code 400
	at createError (<REDACTED: user-file-path>:8:291871)
	at settle (<REDACTED: user-file-path>:8:296153)
	at IncomingMessage.handleStreamEnd (<REDACTED: user-file-path>:8:281452)
	at IncomingMessage.emit (node:events:538:35)
	at endReadableNT (node:<REDACTED: user-file-path>:1345:12)
	at process.processTicksAndRejections (node:<REDACTED: user-file-path>:83:21)

**Comment by HuihuiWu-Microsoft** [comment]
Hi @tedley63, the file paths are redacted and are hard to recognize, can you provide original call stack from output window?

**Comment by tedley63** [comment]
Attached is the whole log from the run...
[DeployError.pdf](https://github.com/OfficeDev/TeamsFx/files/11896389/DeployError.pdf)

Let me know if there is anything else you need.

**Comment by HuihuiWu-Microsoft** [comment]
Hi @tedley63, from the logs, the API call to deploy SharePoint solution package failed. It shouldn't be an issue from Teams Toolkit side. Can you help try to deploy SharePoint package to SharePoint app catalog manually and see whether it works?

**Comment by tedley63** [comment]
Sorry for the delay, I've been pulled to work on other issues, but it appears that the solution was at least partially deployed to the App Cat in SharePoint, but I'll have to do a bit more testing if I can in the couple days..

Ted

**Comment by HuihuiWu-Microsoft** [comment]
Great! Thanks for your help @tedley63. Please let us know after your testing.

BTW, you can also let us know what's the problem during your migration to TTK v5.0.0 if possible so we can troubleshoot and help to upgrade your project to latest.

**Comment by tedley63** [comment]
Well, now it appears to be working... I did notice that while the app packages was uploaded to the appcat, it was marked as invalid... I tweaked the package-solution file (bumped version number) and it then deployed as valid without the error...

I'll repost if the error presents itself again..

Thanks
Ted

**Comment by HuihuiWu-Microsoft** [comment]
@tedley63 Great! Then I'll close this issue and feel free to repost if it occurs again.
