### ISSUE TITLE
Error: "CancelledByUser" at p (https://res.cdn.office.net/teams-js/2.7.1/js/MicrosoftTeams.min.js:23404)

### ISSUE THREAD

**Issue by sayali-MSFT** [OfficeDev/TeamsFx#9143]
Copied -https://github.com/OfficeDev/microsoft-teams-library-js/issues/1798

We are currently importing Teams JS in C# project. However the error in step 6 appeared. After testing, the error only appears in Teams on the web, and works fine in Teams Desktop. Also tested with Teams JS 2.11.0, and the error still appeared.

You could reproduce the error by following the steps:

1. Install Visual Studio and Microsoft Teams development tools under individual components
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/e9a56716-f456-4975-a4ee-37527398599c)

2. Scaffold a new project - Microsoft Teams App - Tab - Configure With SSO.

3. Under Components/Welcome.razor, add await MicrosoftTeams.InitializeAsync() as follows
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/158d3f7c-5ef1-45f0-bf68-cc68af4204dc)

4. Prepare Teams App Dependencies and Press F5 to start local debug
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/f0a142a9-5e64-42d4-9459-5e4587579b17)

5. Click Authorize and the Auth page will pop out. Click Accept.
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/918c0326-9e87-441b-b801-3fb2427bce13)

6. Error appeared instead of the profile card.
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/04111afa-9053-4b77-8874-db79df48b016)

7.Refresh the page, the profile card appeared.
![image](https://github.com/OfficeDev/TeamsFx/assets/93527375/bbd93cba-e7fa-4603-9e83-c67a4e7eb16f)

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8918

**Comment by yiqing-zhao** [comment]
Actually I don't think this is caused by TeamsFx, as with same code, Teams desktop could work properly while Teams on the web showed the error. Any possible speculation is helpful to me, thanks!
