### ISSUE TITLE
Teams Toolkit v5 JS Message Extension failing with NotFound error

### ISSUE THREAD

**Issue by jatin-tarachandani** [OfficeDev/TeamsFx#9155]
We have been attempting to run a previously working message extension made using Teams Toolkit for VS Code v5.0.1. However, on attempting to run the extension from a message in a Teams dev client, we get an unexpected error ("unable to reach app, please try again"). Opening the browser console of the Teams Dev client shows more details, contents of which are in a screenshot below. We attempted to check if it was a problem with our codebase, by creating an entirely new Teams Toolkit messaging extension from the default template provided. That also fails with the same error as well, without any changes to the manifest or source code. Screenshot of the error from the console is attached.

Expected behavior is for the application to function like it did before. No error was previously received in the console on running the extension, either in the Teams client or the console. 

![48136304-0C2A-4CA3-9421-B4A9B9FE42CF](https://github.com/OfficeDev/TeamsFx/assets/80622158/9246e416-30fd-4319-8793-9c8ae276cce3)

OS: MacOS Monterey 12.5.1
VS Code Teams Toolkit Version: 5.0.1

**Comment by swatDong** [comment]
The same cause as (https://github.com/OfficeDev/TeamsFx/issues/9132), upstream service issue.

**Comment by swatDong** [comment]
Upstream issue resolved. Close this.
