### ISSUE TITLE
Teams Toolkit 5.0.1: No more deployment to azure storage

### ISSUE THREAD

**Issue by jkerst** [OfficeDev/TeamsFx#9181]
**Describe the bug**
Since a few days, we are not able to deploy our app to our azure storage via Teams Toolkit. The error message is:

[2023-06-29T20:12:45.630Z] [Info] - Executing action azureStorage/deploy in lifecycle deploy
[2023-06-29T20:12:45.826Z] [Error] -  Detail: {"name":"RestError","statusCode":401,"request":{
...
"bodyAsText":"{\"error\":{\"code\":\"InvalidAuthenticationTokenTenant\",\"message\":\"The access token is from the wrong issuer 'https://sts.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/'. It must match the tenant 'https://sts.windows.net/xxxxx-xxxxxx-xxxxxx-xxxxxx/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/xxxxx-xxxxxx-xxxxxx-xxxxxx' to get the token."
}

The tenant "xxxxx-xxxxxx-xxxxxx-xxxxxx" is our tenant ID where we try to deploy the app. Our research suggest that tenant ID 72f988bf-86f1-41af-91ab-2d7cd011db47 belongs to Microsoft. 

We don't understand what is happening there. This worked before update to 5.0.1 and as we remember correctly, this worked also with 5.0.1 a few days ago.

Can you please check?

**To Reproduce**
1. Create an example from Teams toolkit (e.g. Teams App with React)
2. Login to Azure subscription
3. Provision app.
4. Deploy app.

**Expected behavior**
We expect that deployment would work via Teams Toolkit. Manual upload of build files is very time consuming.

**Screenshots**

**Comment by jkerst** [comment]
For those having similar issues, we have developed a workaround to bypass storage deployment of TeamsFX.

1. Install Azure CLI extension.
2. Add new variable with your azure storage connection string to your env.dev file in env folder: AZURE_STORAGE_CONNECTION_STRING=xxxxxxxxxxxxxxxxx
3. Adapt teamsapp.yml to use azure cli blob upload for storage update.

In the deploy: section of teamsapp.yml, change the following:

  # Deploy bits to Azure Storage Static Website
  # - uses: azureStorage/deploy
  #  with:
  #    # Deploy base folder
  #    artifactFolder: build
  #    ignoreFile: .storageignore
  #    # The resource id of the cloud resource to be deployed to.
  #    # This key will be generated by arm/deploy action automatically.
  #    # You can replace it with your existing Azure Resource id
  #    # or add it to your environment variable file.
  #    resourceId: ${{TAB_AZURE_STORAGE_RESOURCE_ID}}

  # Run deploy to Azure Storage script
  - uses: script
    name: deploy to azure storage
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{AZURE_STORAGE_CONNECTION_STRING}}
    with:
      run: az storage blob upload-batch --source ./build --destination $web --connection-string ${{AZURE_STORAGE_CONNECTION_STRING}}

**Comment by rolandbodenstaff** [comment]
I'm having the exact same issue with the latest version of the toolkit and new project. The workaround @jkerst works but as stated  is not ideal.

**Comment by Siglud** [comment]
@jkerst  @rolandbodenstaff 
The 'azureStorage/deploy' will deploy to TAB_AZURE_STORAGE_RESOURCE_ID by default. 

Please check the value 
 of the `TAB_AZURE_STORAGE_RESOURCE_ID` in your env.dev file and system environmental. This string should be like `/subscriptions/[YOUR_SUBSCRIPTIONS_ID]/resourceGroups/[YOUR_RESOURCE_GROUP_NAME]/providers/Microsoft.Storage/storageAccounts/[YOUR_STORAGE_ACCOUNT_NAME]`

**Comment by jkerst** [comment]
@Siglud: Thank you for your comment. Yep, those values are all correctly maintained. The storage is also found but for some reason TeamsToolkit uses another issuer in the access token than our tenant. In the access token, the issuer is a microsoft tenent, but azure is expecting our tenant. In my opinion: There is either a bug in the new Teams Toolkit that is using the wrong issuer or Azure changed something recently where the issuer is not supported anymore.

**Comment by xiaolang124** [comment]
Could you please try signing out of your Azure account and signing in again within the Teams Toolkit tree view? When you open the login page, please check the URL and see if it is something like 'https://login.microsoftonline.com/common/oauth2/authorize...' or if it differs.

Additionally, you can try installing a different version of the Teams Toolkit to see if it resolves the issue.
![image](https://github.com/OfficeDev/TeamsFx/assets/13211513/08fe7812-60b1-43e9-bdfe-ad64bfc73b0c)

You can also check the version of your Azure Account extension and review the settings in your Azure configuration.
![image](https://github.com/OfficeDev/TeamsFx/assets/13211513/6f7903ab-00ad-423d-9fb4-6d97174935b1)

If none of the above solutions resolve the issue, please check your environment variables to see if there is anything related to the incorrect tenant ID.

Please let me know if there is anything else I can assist you with.

**Comment by jkerst** [comment]
@xiaolang124 : Thanks for the input!

Login url seems fine:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=

Downgrading the version is not an option. Version 5 is not backward compatible with version 4.x.

Azure settings are fine:
![image](https://github.com/OfficeDev/TeamsFx/assets/130495478/8deb0a3d-ba6e-435e-8b2a-2499bbbf1084)


Environment variables are fine. The tenant '72f988bf-86f1-41af-91ab-2d7cd011db47' is not mentioned anywhere in our project. Also the tenant is also not related to one of our accounts. Google research determines that this tenant is the official Microsoft tenant.

In my opinion: There is either a bug in the new Teams Toolkit that is using the wrong issuer or Azure changed something recently where the issuer is not supported anymore.

**Comment by xiaolang124** [comment]
@jkerst Understood. Could you please try using Teams Toolkit 5.0.0 and check if it resolves the issue?
Additionally, you can set your tenant ID in the 'Azure: Tenant' setting, reload VS Code, and then proceed to login and deploy your project.
![image](https://github.com/OfficeDev/TeamsFx/assets/13211513/0e998e73-8c2e-445a-976f-ed00e0f662e6)

Or you can try use [teamsfx cli](https://www.npmjs.com/package/@microsoft/teamsfx-cli) and see it has the same problem.

**Comment by ThomasPe** [comment]
same error on 5.0.0

**Comment by xiaolang124** [comment]
@ThomasPe Sorry for the inconvenience, have you tried to set your tenant ID in the 'Azure: Tenant' setting, reload VS Code, and then proceed to login and deploy your project.

![image](https://github.com/OfficeDev/TeamsFx/assets/13211513/0e998e73-8c2e-445a-976f-ed00e0f662e6)

**Comment by ThomasPe** [comment]
Thanks for your help. I ran the Azure: Select Tenant command in VS Code which I guess does the same thing and it worked (Y)
<img width="541" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/4225039/0c0ec9d9-67cc-47c0-bfc2-ad3e864653dc">
