### ISSUE TITLE
Unified manifest: Teams app does not run in Outlook

### ISSUE THREAD

**Issue by jkerst** [OfficeDev/TeamsFx#9190]
**Describe the bug**
We have upgraded with our teams app to new (unified) manifest v1.16. We adjusted our app to the example from teams Toolkit v5.0.1 for Teams, Outlook and Microsoft 365. Inside the app we are using teams-js and teamsfx with SSO. The app runs smooth.

However, in Outlook (Edge), we discover a strange behaviour:

* The app is loading as normal (SSO; everything works).
* When we hit refresh from Outlook toolbar, Outlook is not able to reach our app anymore. In the console, nothing happens.
* When we hit refresh again, the app is loaded again.

Does anyone know what is going on here? What happens when you try to hit refresh in the new outlook? I would expect that the iframe with our app is reloaded (like in Teams), but that does not happen.

Any idea?

**Screenshots**

![image](https://github.com/OfficeDev/TeamsFx/assets/130495478/43775aa9-9a1d-40c9-8e38-fe739dc740b4)

**Additional context**
Here is the content of our package.json:

        "@fluentui/react-components": "^9.18.0",
        "@fluentui/react-northstar": "^0.64.0",
        "@fluentui/react-teams": "^6.0.0",
        "@microsoft/mgt-element": "^2.8.0",
        "@microsoft/mgt-react": "^2.8.0",
        "@microsoft/mgt-teamsfx-provider": "^2.8.0",
        "@microsoft/microsoft-graph-client": "^3.0.1",
        "@microsoft/teams-js": "^2.7.1",
        "@microsoft/teamsfx": "^2.2.0",
        "@microsoft/teamsfx-react": "^3.0.0",
        "axios": "^0.21.1",
        "react": "^18.2.0",
        "react-device-detect": "^2.2.2",
        "react-dom": "^18.2.0",
        "react-router-dom": "^6.8.0",
        "react-scripts": "^5.0.1"

We are using Teams Toolkit v.5.0.1.

We are using manifest version v.1.16 (unified manifest).

**Comment by kuojianlu** [comment]
@jkerst What's the url of this app in your **new Outlook**? Is it `https://outlook.office.com/host/...` or anything else? I guess this issue has nothing with your app but is very likely caused by Outlook client.

**Comment by jkerst** [comment]
@kuojianlu : That is correct. Is there any workaround available?

![image](https://github.com/OfficeDev/TeamsFx/assets/130495478/07b2fba8-6459-47f0-a67c-85fb5417887e)

**Comment by kuojianlu** [comment]
@jkerst We never encountered this issue and cannot reproduce it now... By the way, have your manifest defined `showLoadingIndicator`? Not sure if it may affect the refresh behavior.

**Comment by jkerst** [comment]
@kuojianlu: Yep. That is the workaround. When we set showLoadingIndicator:false, the banner disappears. This would fit as a workaround. We will clarify with submissions team if this is feasable. We remember that showLoadingIndicator:true was mandatory for submission.

However, there still seems to be a bug. Our logs show that the app is not refreshed at all if the user hits refresh.

**Comment by kuojianlu** [comment]
@jkerst Does this issue only happens in Outlook? What's the refresh behavior in Teams and Office.com?

**Comment by jkerst** [comment]
@kuojianlu : Just Outlook. Teams and Office.com are fine. Refresh of our app works as expected in Teams. The iframe containing our app is completely reloaded.

**Comment by kuojianlu** [comment]
@Wajeed-msft Hi Wajeed, this is an upstream issue from Outlook, could you please help hanlde it?

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8991
