### ISSUE TITLE
Duplicate Message extension, action item appears when we add a bot to manifest 

### ISSUE THREAD

**Issue by sn-007** [OfficeDev/TeamsFx#9192]
**Describe the bug**

-  I am developing a message extension application for teams. By default the bots:[ ] section in the manifest is empty. 

- But in some cases, we might have to add the bot behind messaging extension to the manifest, for sending replies to the user. using ```context.sendActivity()```  method.

- However, by adding a bot into a channel, under the more actions section, each messaging extension declared in the manifest is duplicating itself. Both of them are functional, but it's not good to see right. 

**To Reproduce**
1. Run a message extension app locally.
2. Add the following piece of code to your bots:[ ] in the manifest, so the final manifest can look like this.
```
/* some default manifest above*/
    "bots": [
        {
            "botId": "${{BOT_ID}}",
            "scopes": [
                "team",
                "personal",
                "groupchat"
            ],
            "supportsFiles": false,
            "isNotificationOnly": false
        }
    ],
    "composeExtensions": [
        {
            "botId": "${{BOT_ID}}",
            "commands": [
                {
                    "id": "executeActions",
                    "context": [
                        "message"
                    ],
                    "description": "Command to run action to execute Jenkins / ES actions from Message Extension",
                    "title": "Run Jenkins actions",
                    "fetchTask": true,
                    "type": "action"
                }
            ],
            "messageHandlers": [
                {
                    "type": "link",
                    "value": {
                        "domains": [
                            "http://127.0.0.1",
                            "*.botframework.com",
                            "*.ngrok-free.app"
                        ]
                    }
                }
            ]
        }
    ],
     "configurableTabs": [],
    "staticTabs": [],
    "permissions": [
        "identity",
        "messageTeamMembers"
    ],
    "validDomains": ["127.0.0.1", "*.ngrok-free.app"]
}
```
3) Now start your message extension application, and add the bot to the channel. (Adding the bot into the channel is important to reproduce the issue.)
4) For each command in compose extension, you will see a duplicate entry in the team's client, with a [new] label attached to it.

**Expected behavior**
The commands should not be duplicated, at the same time the bot behind our messaging extension should be able to post messages in the channel , when we use context.sendActivity(). 

**Screenshots**

Before Adding the bot to the channel
<img width="544" alt="Before adding the bot to the channel" src="https://github.com/OfficeDev/TeamsFx/assets/57190755/acd80067-8666-404d-9f20-73262403fc8e">

After Adding the bot to the channel
<img width="524" alt="After adding the bot to the channel" src="https://github.com/OfficeDev/TeamsFx/assets/57190755/061c7fd0-d105-44f6-a7d4-e586d725c6a9">

As you can see, the 'Run Jenkins Actions' command linked to the messaging extension is being shown twice.

**VS Code Extension Information (please complete the following information):**
 - OS: Mac OS
 - Version: Ventura 13.4

Thanks for your time!

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/8966

**Comment by MuyangAmigo** [comment]
Close as copied over to upstream.
