### ISSUE TITLE
[Teamsfx/packages/sdk] npm run setup cannot complete with latest TeamsFx repo clone

### ISSUE THREAD

**Issue by deverin** [OfficeDev/TeamsFx#9202]
**Describe the bug**
- git clone teamsfx repo & cd into teamfx folder
- npm run setup
- process not finishing and failing on 
```
@microsoft/teamsfx@2.2.1 build
rollup -c && api-extractor run --local && npm run api-markdown
```

**Versions in use**
```
node --version
v18.16.1

npm --version
9.7.2
```

**Error output**
```
lerna ERR! npm run build stderr:
Error loading `tslib` helper library.
[!] Error: Package subpath './package.json' is not defined by "exports" in C:\Developer\TeamsFx\packages\sdk\node_modules\rollup-plugin-typescript2\node_modules\tslib\package.json
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in C:\Developer\TeamsFx\packages\sdk\node_modules\rollup-plugin-typescript2\node_modules\tslib\package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Developer\TeamsFx\packages\sdk\node_modules\rollup-plugin-typescript2\dist\rollup-plugin-typescript2.cjs.js:25170:26)

lerna ERR! npm run build exited 1 in '@microsoft/teamsfx'
```

**Expected behavior**
Expecting process to finish to proceed with SDK contribution process

**Comment by wenytang-ms** [comment]
@deverin Thanks for trying our repo, according to the [contribute guide doc](https://github.com/OfficeDev/TeamsFx/blob/main/packages/sdk/CONTRIBUTING.md) we suppose developer use node 14.
You may downgrade to node 14 which is fully supported.

**Comment by deverin** [comment]
> @deverin Thanks for trying our repo, according to the [contribute guide doc](https://github.com/OfficeDev/TeamsFx/blob/main/packages/sdk/CONTRIBUTING.md) we suppose developer use node 14. You may downgrade to node 14 which is fully supported.

Understood. Then I think contribution docs need to be more specific with the version use.
At the moment it stands on `Node 10.x or higher` current LTS is on 18.6.1 which people may resort to use/upgrade to. 

package.json also specifies it the same way
```
"engines": {
    "node": ">=10.0.0"
}
```

Or I am looking in a wrong place?

**Comment by deverin** [comment]
Success Confirmation with one Warning

> **WARNING: Unable to resolve reference "InvokeResponse": The member reference "InvokeResponse" was not found**

```
node --version
v14.21.3
```
```
npm --version
6.14.18
```

**OUTPUT `npm run setup`**

```
> teamsfx@ setup C:\Developer\src\TeamsFx-14
> npm install && npm run build


> teamsfx@ postinstall C:\Developer\src\TeamsFx-14
> npm run bootstrap --hoist


> teamsfx@ bootstrap C:\Developer\src\TeamsFx-14
> lerna bootstrap

lerna notice cli v4.0.0
lerna info versioning independent
lerna info Bootstrapping 14 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 14 packages

> teamsfx@ prepare C:\Developer\src\TeamsFx-14
> husky install

husky - Git hooks installed
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN teamsfx@ No repository field.
npm WARN teamsfx@ No license field.

audited 804 packages in 227.333s

107 packages are looking for funding
  run `npm fund` for details

found 41 vulnerabilities (37 moderate, 2 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

> teamsfx@ build C:\Developer\src\TeamsFx-14
> lerna run build

lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 4 packages: "npm run build"
lerna info run Ran npm script 'build' in '@microsoft/metrics-ts' in 4.1s:

> @microsoft/metrics-ts@0.0.4 build C:\Developer\src\TeamsFx-14\packages\metrics-ts
> rimraf build && npx tsc -p ./

lerna info run Ran npm script 'build' in '@microsoft/adaptivecards-tools' in 5.7s:

> @microsoft/adaptivecards-tools@1.3.1 build C:\Developer\src\TeamsFx-14\packages\adaptivecards-tools-sdk
> rollup -c

lerna info run Ran npm script 'build' in '@microsoft/teamsfx' in 34.9s:

> @microsoft/teamsfx@2.2.1 prebuild C:\Developer\src\TeamsFx-14\packages\sdk
> npm run clean


> @microsoft/teamsfx@2.2.1 clean C:\Developer\src\TeamsFx-14\packages\sdk
> rimraf dist dist-* temp types *.tgz *.log


> @microsoft/teamsfx@2.2.1 build C:\Developer\src\TeamsFx-14\packages\sdk
> rollup -c && api-extractor run --local && npm run api-markdown


api-extractor 7.19.4  - https://api-extractor.com/

Using configuration from ./api-extractor.json
Analysis will use the bundled TypeScript version 4.5.4

API Extractor completed successfully

> @microsoft/teamsfx@2.2.1 api-markdown C:\Developer\src\TeamsFx-14\packages\sdk
> api-documenter generate -i temp -o ../../docs/sdk


api-documenter 7.14.1  - https://api-extractor.com/

Reading teamsfx.api.json

Deleting old output from ../../docs/sdk
Writing @microsoft/teamsfx package
WARNING: Unable to resolve reference "InvokeResponse": The member reference "InvokeResponse" was not found
lerna info run Ran npm script 'build' in '@microsoft/teamsfx-react' in 8.8s:

> @microsoft/teamsfx-react@3.0.0 build C:\Developer\src\TeamsFx-14\packages\sdk-react
> rimraf build && npx tsc -p tsconfig.json && npx tsc -p tsconfig.es.json

lerna success run Ran npm script 'build' in 4 packages in 49.3s:
lerna success - @microsoft/adaptivecards-tools
lerna success - @microsoft/metrics-ts
lerna success - @microsoft/teamsfx
lerna success - @microsoft/teamsfx-react
```


**QUESTION**
#### Does this mean that for development with @microsoft/teamsfx-sdk we need to use node max v14?

**Comment by wenytang-ms** [comment]
@deverin Thank you for your contribution for the doc.
At present, there is no unified version requirement since our repo is monorepo, not only the sdk, but also other products, such as cli, fx-core, etc.. Therefore, we need to ensure that all products are ok when we upgrade node to 18. Now we are considering upgrading our current project to node18, then we'll update the docs to clarify this.

**Comment by deverin** [comment]
> @deverin Thank you for your contribution for the doc. At present, there is no unified version requirement since our repo is monorepo, not only the sdk, but also other products, such as cli, fx-core, etc.. Therefore, we need to ensure that all products are ok when we upgrade node to 18. Now we are considering upgrading our current project to node18, then we'll update the docs to clarify this.

Yeah, I know that is a monorepo, I am talking about [packages/sdk/CONTRIBUTING.md](https://github.com/OfficeDev/TeamsFx/blob/main/packages/sdk/CONTRIBUTING.md) document.

As a proposal to give a slight note to potential contributors.
Add a note under node version line in Prerequisites something along the lines:
> **NB!** if you experience errors at build time try to lower your node version - step down by lts releases

**Comment by wenytang-ms** [comment]
thanks you for you suggestion, currently we update the contribute docs 
https://github.com/OfficeDev/TeamsFx/blob/dev/packages/sdk/CONTRIBUTING.md
