### ISSUE TITLE
Bug: Can't run any task on V4 after V5 release

### ISSUE THREAD

**Issue by luizhrios** [OfficeDev/TeamsFx#9205]
**Describe the bug**
Can't keep using V4, can't run anything.

Everything I run opens the dialog, then I cancel and the task is also canceled.

The message says `If you are not ready to upgrade, please continue to use the old version Teams Toolkit 4.x.x.` but I can't use it.

**To Reproduce**
1. Using V4
2. Run any teamsfx task

**Expected behavior**
Run as normal

**VS Code Extension Information (please complete the following information):**
 - Version V5.0.1

**Comment by xzf0587** [comment]
Hi @luizhrios,
Thanks for reaching out.
This message will popup when you use the version 5.x.x toolkit to open a version 4 project.
If you do not want to upgrade the project, you should **reinstall the Teams Toolkit extension** with version 4.x.x like 4.2.5.
<img width="901" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/16380704/ef28af9a-327a-44ab-bdf6-633e292cdd5d">
If the 4.x.x toolkit has the same popup message, clean **TEAMSFX_V3** in the environment and relaunch vscode.

**Comment by luizhrios** [comment]
I downgraded and it worked, Thanks!
