### ISSUE TITLE
Action.Execute not including Input Values when operating within a channel

### ISSUE THREAD

**Issue by Tommo56700** [OfficeDev/TeamsFx#9223]
https://learn.microsoft.com/en-us/answers/questions/1295145/why-isnt-action-execute-including-input-values-whe?source=docs
I have the following Adaptive Card:

```
{
  contentType: "application/vnd.microsoft.card.adaptive",
  content: {
    type: "AdaptiveCard",
    version: "1.5",
    body: [
      {
        type: "Input.Text",
        id: "someText",
        value: "1",
        maxLength: 100,
      }
    ],
    actions: [
      {
        type: "Action.Submit",
        title: "Submit",
        id: "submit",
        verb: "submit",
        data: {"action": "submit"},
      },
      {
        type: "Action.Execute",
        title: "Execute",
        id: "execute",
        verb: "execute",
        data: {"action": "execute"}
      }
    ],
}
```

If I click either button in personal chat with a bot, the bot receives a value for someText as I'd expect.

In a Team Channel, I receive someText with the Action.Submit action, but not with the Action.Execute button. Action.Execute was working a few weeks ago.

How do I use the Action.Execute action type and also receive Input values from the Card?

In a Team Channel, we received someText with the Action.Submit action, but not with the Action.Execute button.

### extract from request payload with Submit action
```
"value": {
        "action": "submit",
        "someText": "Submit value"
},
```

### extract from request payload with Execute action
```
"value": {
        "action": {
            "type": "Action.Execute",
            "id": "execute",
            "title": "Execute",
            "data": {
                "action": "execute"
            },
            "verb": "execute"
        },
        "trigger": "manual"
},
```

This renders the [Workflow Bot](https://learn.microsoft.com/en-us/microsoftteams/platform/sbs-gs-workflow-bot?tabs=vscode) example pretty useless if hoping to extend this functionality.

**Comment by Tommo56700** [comment]
This is more likely a problem with Teams itself or adaptive cards, but either way this is a breaking change that effects existing applications built with the Teams Toolkit. Hoping this can get the right visibility from raising this issue here.

**Comment by jbufasttrack** [comment]
Any update on this issue? We have a Teams app that has basically been rendered useless because the Action.Execute method stopped working all of the sudden. This has been an issue for several months now.

**Comment by dooriya** [comment]
Hi @Wajeed-msft, this is an upstream issue that seems there's breaking change in Teams client on getting associated input data from `Action.Execute`, could you help to take a look it?

Related issue: https://learn.microsoft.com/en-us/answers/questions/1295145/why-isnt-action-execute-including-input-values-whe?source=docs

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/9291

**Comment by adashen** [comment]
Close as the upstream is already closed
