### ISSUE TITLE
Improve the azureAppServiceZipDeploy.MissingEnvrionmentVariablesError message

### ISSUE THREAD

**Issue by therealjohn** [OfficeDev/TeamsFx#9224]
**Is your feature request related to a problem? Please describe.**
When attempting to deploy, it's possible to get an error message like this: 
![image](https://github.com/OfficeDev/TeamsFx/assets/1501196/7d380854-2c39-44c2-ba2f-7c834773d339)

This usually happens with the default teamsapp.yml setup when Provision isn't run first. 

**Describe the solution you'd like**
![image](https://github.com/OfficeDev/TeamsFx/assets/1501196/dc562578-6bf5-4e95-b254-d301e664bf2b)

**Comment by jayzhang** [comment]
@therealjohn In this case, "Provision" is not the only path to solve the problem, user can provide .env with existing resources. 
So user have two paths: one is to run provision, another is to edit .env with existing resources.
