### ISSUE TITLE
`handleMessageExtensionQueryWithSSO` does not work for link unfurling. 

### ISSUE THREAD

**Issue by yuezk** [OfficeDev/TeamsFx#9272]
**Describe the bug**

The [wiki](https://github.com/OfficeDev/TeamsFx/wiki/SSO-for-Message-Extension#:~:text=actually%20this%20API%20also%20works%20in%20TeamsActivityHandler.handleTeamsAppBasedLinkQuery) says that `handleMessageExtensionQueryWithSSO` can be used with `TeamsActivityHandler.handleTeamsAppBasedLinkQuery`, but the fact is that it cannot be used with it.

The activity name for `handleTeamsAppBasedLinkQuery` is `composeExtension/queryLink`, while the implementation of `handleMessageExtensionQueryWithSSO` has the explicit validation against the activity name must be `composeExtension/query`.

https://github.com/OfficeDev/TeamsFx/blob/68d9c92b27b03d53f8ef9e5d99afe3a8ec253840/packages/sdk/src/messageExtension/executeWithSSO.ts#L254

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by wenytang-ms** [comment]
@yuezk thanks for your feedback. 
We have updated the [wiki](https://github.com/OfficeDev/TeamsFx/wiki/SSO-for-Message-Extension#api-limitation), please refer the link for reading.

**Comment by yuezk** [comment]
@wenytang-ms Thanks for the update.

What is the poor SSO effect for link unfurling? I just implemented the same SSO experience by following the source code of the `handleMessageExtensionQueryWithSSO` method. It just worked, so I would like to know if there are any pitfalls.

Shall we remove the `link unfurling` in the first paragraph?

<img width="918" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/3297602/4b39f28c-83d9-477e-a1be-500e1a2f4b99">

**Comment by wenytang-ms** [comment]
@yuezk thanks, I tried link unfurling SSO experience a long time ago, and it didn't work very well at that time, so I didn't add it later. 
Let's go back and discuss whether this feature needs to be implemented at present, I will modify the document first.
Anyway, the SSO only work for query and link unfurling is fact, it's just that our API doesn't support.
