### ISSUE TITLE
teamsfx.login(scopes) does not work in Microsoft 365

### ISSUE THREAD

**Issue by AnthonyPhan** [OfficeDev/TeamsFx#9364]
**Describe the bug**
When calling `teamsfx.login(scopes)` from an app running inside Microsoft 365, teamsfx will error with the messages show below. This error only occurs if the consent popup is required. However the same code will popup the consent dialogue if run inside of Microsoft Teams.

**To Reproduce**
Run the following code:
```typescript
const scopes = [
  'User.Read',
  'User.ReadBasic.All',
  'Team.ReadBasic.All',
  'Channel.ReadBasic.All',
  'Files.ReadWrite.All',
  'Sites.Read.All',
  'Sites.Manage.All',
];
const teamsfx = new TeamsFx(IdentityType.User, { clientId, initiateLoginEndpoint });
return teamsfx.login(scopes)
```

**Expected behavior**
A consent popup should show and the behaviour should made that inside Microsoft Teams.

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/12785492/6a39fd62-f221-49d6-b972-e70b9e440051)

**Comment by kuojianlu** [comment]
@AnthonyPhan What's the value of your AAD Application ID URI and manifest _webApplicationInfo.resource_? Try adding the port to these two configurations, like `api://localhost:port/xxx`.
