### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by jurisjansons** [OfficeDev/TeamsFx#9374]
**Describe the bug**
I'm having trouble authenticating users in MS Teams tab, because of Azure limits and teams example mismatch. Issue is with line:
`redirectUri: window.location.origin + '/auth-end.html?clientId=${clientId}'`. "redurectUri" is defined with query parameters to conveniently pass clientId to next file, but the problem is that AAD app registration doesn't allow query parameters in redirectUri. Can't add it neither from UI nor manifest.

Part of auth-start.html file content:
`<script type="text/javascript">
      microsoftTeams.initialize();

      // Get the tab context, and use the information to navigate to Azure AD login page
      microsoftTeams.getContext(async function (context) {
        // Generate random state string and store it, so we can verify it in the callback
        var currentURL = new URL(window.location);
        var clientId = currentURL.searchParams.get("clientId");
        var scope = currentURL.searchParams.get("scope");
        var loginHint = currentURL.searchParams.get("loginHint");

        const msalConfig = {
          auth: {
            clientId: clientId,
            authority: `https://login.microsoftonline.com/${context.tid}`,
            navigateToLoginRequestUrl: false
          },
          cache: {
            cacheLocation: "sessionStorage",
            storeAuthStateInCookie: true
          },
        }

        const msalInstance = new msal.PublicClientApplication(msalConfig);
        const scopesArray = scope.split(" ");
        const scopesRequest = {
          scopes: scopesArray,
          redirectUri: window.location.origin + `/auth-end.html?clientId=${clientId}`,
          loginHint: loginHint
        };
        await msalInstance.loginRedirect(scopesRequest);
      });
      </script>`

![image](https://github.com/OfficeDev/TeamsFx/assets/10829036/f459e9e9-5d8a-4635-8c25-bd64779be493)

**Comment by KennethBWSong** [comment]
Hi @jurisjansons Thank you for using our Toolkit.
I want to first confirm that are you using an Azure AD B2C app? Azure AD B2C app is not supported yet.
You can also try to hardcode the client id in the auth page to see whether it can fix your problem.

**Comment by jurisjansons** [comment]
@KennethBWSong Thank you for reply. Yes I am using Azure AD B2C app and hardcoding indeed fixes this issue, but then again problem starsts with dynamicly chaning html for different environments

**Comment by KennethBWSong** [comment]
@jurisjansons Would you please try to set 'state' property in auth-start page as shown [here](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-js-pass-custom-state-authentication-request)? Remember to update your auth-end page and your Azure AD manifest.

**Comment by jurisjansons** [comment]
@KennethBWSong How can I access state from auth-end.html page?

**Comment by KennethBWSong** [comment]
@jurisjansons You can access the state in [AuthenticationResult](https://azuread.github.io/microsoft-authentication-library-for-js/ref/modules/_azure_msal_common.html#authenticationresult) in auth-end page.

**Comment by jurisjansons** [comment]
@KennethBWSong Maybe you have an example code? As I need clientId before initializing msalInstance...
`var currentURL = new URL(window.location);

      microsoftTeams.app.initialize().then(() => {
        microsoftTeams.app.getContext().then(async (context) => {
          const msalConfig = {
            auth: {
              clientId: "<clientId>",
              authority: `https://login.microsoftonline.com/${context.tid}`,
              navigateToLoginRequestUrl: false,
            },
            cache: {
              cacheLocation: "sessionStorage",
            },
          };

          const msalInstance = new window.msal.PublicClientApplication(msalConfig);

          msalInstance
            .handleRedirectPromise()
            .then((tokenResponse) => {
              if (tokenResponse !== null) {
                microsoftTeams.authentication.notifySuccess(
                  JSON.stringify({
                    sessionStorage: sessionStorage,
                  })
                );
              } else {
                microsoftTeams.authentication.notifyFailure("Get empty response.");
              }
            })
            .catch((error) => {
              microsoftTeams.authentication.notifyFailure(JSON.stringify(error));
            });
        });
      });`

**Comment by KennethBWSong** [comment]
@jurisjansons Would you please try the following code?
In `auth-start.html`:
```
...
const scopesRequest = {
    scopes: scopesArray,
    redirectUri: window.location.origin + `/auth-end.html`,
    loginHint: loginHint,
    state: `${clientId}`
};
await msalInstance.loginRedirect(scopesRequest);
```
In `auth-end.html`:
```
...
// var clientId = currentURL.searchParams.get("clientId");
var state = getHashParameters()['state'];
var clientId = state.split('|')[1];
...
```

**Comment by jurisjansons** [comment]
@KennethBWSong Thank you for insight, thought that state access should be done through msal library, got it working

Woring code from `auth-end.html` for anyone that needs it

    ...
    const hash = window.location.hash.substr(1);
    const hashParameters = hash.split("&").reduce(function (res, item) {
        var parts = item.split("=");
        res[parts[0]] = parts[1];
        return res;
    }, {});

    const state = decodeURIComponent(hashParameters["state"]);
    const clientId = state.split("|")[1];
    ...
