### ISSUE TITLE
M365 web app can't get access token when switching tabs

### ISSUE THREAD

**Issue by ichivers** [OfficeDev/TeamsFx#9378]
**Describe the bug**
I have a Teams App based off Basic Tab sample which isn't working in M365 web app (office.com / apps). The app has 2 tabs, with the same code as below except one is TabA the other TabB. In Teams web app if I switch between TabA & TabB I get an access token displayed. In M365 web app when I switch tabs I don't, it only gets as far as the teamsFX.getCredential() line. No errors it just hangs, if I refresh the the tab then I get a token.  It also works when first opening the app in M365, it is just when switching tabs there is a problem.

**To Reproduce**
Create a new app based on Basic Tabs sample, add 2 new tabs to the manifest and route of app.tsx.  The tab code should look like this for both tabs, I have TabA & TabB:

```
import { useContext, useEffect, useState } from "react";
import { TeamsFxContext } from "./Context";
import { TeamsFx, ErrorWithCode } from "@microsoft/teamsfx";

export default function TabB() {
  const { themeString } = useContext(TeamsFxContext);
  const [token, setToken] = useState<string>();

  useEffect(() => {
    const scope = [`api://localhost:53000/<GUID>/access_as_user`];
    const teamsFx = new TeamsFx();
    let credential = teamsFx.getCredential();
    credential.getToken(scope).then((tokenResponse) => {
      if (tokenResponse) {
        setToken(tokenResponse.token)
      }
    }).catch((err: ErrorWithCode) => {
      if (err.code === 'UiRequiredError') {
        teamsFx.login(scope).then(() => {
          let credential = teamsFx.getCredential();
          credential.getToken(scope).then((tokenResponse) => {
            if (tokenResponse) {
              setToken(tokenResponse.token)
            }
          })
        })
      }
    });
  }, [])

  return (
    <div
      className={themeString === "default" ? "light" : themeString === "dark" ? "dark" : "contrast"}
    >
      <h1>Tab B</h1>
      {token}
    </div>
  );
}

```

**Expected behavior**
When I switch tabs in the M365 web app it should display an access token.

**Comment by kuojianlu** [comment]
I cannot reproduce this issue using two tabs with same code. Can you please press F12 to see the console log and provide more infromation for troubleshooting?

Hi @KennethBWSong , do you have any ideas about this authentication behavior?

**Comment by KennethBWSong** [comment]
I am not quite sure about the reason, but @ichivers would you please have a try to avoid new TeamsFx separately in two tabs and see whether it can work?

**Comment by ichivers** [comment]
Below is the console output after switching tabs.

useTeamsUserCredential.js:23 [Fri, 28 Jul 2023 08:12:04 GMT] : @microsoft/teamsfx : Info - Create teams user credential
useTeamsUserCredential.js:23 [Fri, 28 Jul 2023 08:12:04 GMT] : @microsoft/teamsfx : Verbose - Validate authentication configuration

I will try again with avoiding a new TeamsFX separately in two tabs.

**Comment by ichivers** [comment]
Ok so avoiding using a new TeamsFX fixed the issue for me, BUT if I try to use the context (which I need to get SubPageId) then the problem is back in Microsoft 365 web app. 

```
import { useContext, useEffect, useState } from "react";
import { TeamsFxContext } from "./Context";
import { app } from "@microsoft/teams-js";
import { TeamsFx, ErrorWithCode } from "@microsoft/teamsfx";

export default function TabB() {
  const { themeString, teamsUserCredential } = useContext(TeamsFxContext);
  const [token, setToken] = useState<string>();

  useEffect(() => {
    const scope = [`api://localhost:53000/<GUID>/access_as_user`];
    app.initialize().then(() => {
      console.log('hello m365')
      app.getContext().then((context) => {
        teamsUserCredential!.getToken(scope).then((tokenResponse) => {
          if (tokenResponse) {
            setToken(tokenResponse.token)
          }
        }).catch((err: ErrorWithCode) => {
          if (err.code === 'UiRequiredError') {
            teamsUserCredential!.login(scope).then(() => {
              teamsUserCredential!.getToken(scope).then((tokenResponse) => {
                if (tokenResponse) {
                  setToken(tokenResponse.token)
                }
              })
            })
          }
        });
      });
    });
  }, [])

  return (
    <div
      className={themeString === "default" ? "light" : themeString === "dark" ? "dark" : "contrast"}
    >
      <h1>Tab B</h1>
      {token}
    </div>
  );
}
```

**Comment by KennethBWSong** [comment]
@ichivers Would you please also try to avoid initialize the Teams SDK again? You may try code like following:
```
if (app.isInitialized())
{
    console.log('hello m365')
    ...
}
```
