### ISSUE TITLE
Outlook app does not display when debugging

### ISSUE THREAD

**Issue by hazzinator1** [OfficeDev/TeamsFx#9392]
**Describe the bug**
When using the Outlook workbench (Chrome) or Outlook workbench (Edge), no app appears. This does not happen when using any of the other options.

**To Reproduce**
1. Create a new SPFx Teams Tab app using the default sample
2. Choose the Outlook workbench (chrome) or Outlook workbench (Edge)
3. Outlook will open, but nothing is displayed except for three dots in the middle of the screen.

**Expected behavior**
App opens correctly with text displayed on screen

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/124360604/a9801ac8-daf6-45c0-b305-44a8991b79f6)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11
 - Version: 5.0.1

**CLI Information (please complete the following information):**
 - OS: Windows 11
 - Version: 1

**Comment by HuihuiWu-Microsoft** [comment]
Hi @hazzinator1, I tried your steps but failed to reproduce the issue. Everything works fine on my side:
![image](https://github.com/OfficeDev/TeamsFx/assets/73154171/b612d7d3-5340-46d7-9cfe-bea9086ca4a4)

Can you help attach the SPFx version you're using and is there any error in console from Developer tools?

**Comment by hazzinator1** [comment]
Very strange... here's the console log from my run. My SPFx version is 1.17.4
![image](https://github.com/OfficeDev/TeamsFx/assets/124360604/c3bc97fe-118f-4576-a041-af28afb75023)

**Comment by HuihuiWu-Microsoft** [comment]
From the console log, it looks like some error from outlook server side. Maybe you can try again after a while to see if the issue persists.
