### ISSUE TITLE
TeamsFx CLI preview not loading the app in MS Teams

### ISSUE THREAD

**Issue by Mayank-3e** [OfficeDev/TeamsFx#9432]
**Describe the bug**
I used Teams Toolkit to create a messaging extension app. It's manifest.json is here:
```json
{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.16/MicrosoftTeams.schema.json",
  "manifestVersion": "1.16",
  "version": "1.0.0",
  "id": "${{TEAMS_APP_ID}}",
  "packageName": "com.microsoft.teams.extension",
  "developer": {
    "name": "Teams App, Inc.",
    "websiteUrl": "https://www.example.com",
    "privacyUrl": "https://www.example.com/termofuse",
    "termsOfUseUrl": "https://www.example.com/privacy"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "teams-app-${{TEAMSFX_ENV}}",
    "full": "full name for teams-app"
  },
  "description": {
    "short": "short description of teams-app",
    "full": "full description of teams-app"
  },
  "accentColor": "#FFFFFF",
  "bots": [
    {
      "botId": "${{BOT_ID}}",
      "scopes": [
        "team"
      ]
    }
  ],
  "composeExtensions": [
    {
      "botId": "${{BOT_ID}}",
      "commands": [
        {
          "id": "addTask",
          "context": [
            "message"
          ],
          "description": "Test command to run action on message context",
          "title": "Add",
          "type": "action",
          "parameters": [
            {
              "name": "summary",
              "title": "Summary",
              "description": "Edit Summary",
              "inputType": "text"
            }
          ]
        }
      ],
      "messageHandlers": [
        {
          "type": "link",
          "value": {
            "domains": [
              "*.botframework.com"
            ]
          }
        }
      ]
    }
  ],
  "configurableTabs": [],
  "staticTabs": [],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": [
    "auth.abcd.com"
  ]
}
```
In Teams sample apps on github, it is instructed to run 3 commands for the app using `teamsfx cli, teamsfx provision, deploy and preview`. All commands show done, but in `teamsfx preview --env local` the app opens like this:
![image](https://github.com/OfficeDev/TeamsFx/assets/111231656/aee7d4c5-5343-4a12-8154-e8ec44376364)

There is no "Add" button now, also it looks like it is not reading `manifest.json` file. It was working a few days ago without any issues.
This is my folder structure:
![image](https://github.com/OfficeDev/TeamsFx/assets/111231656/0b2670de-39e5-4935-a136-031f3f29921f)

**To Reproduce**
1. `npm install` dependencies
2. `npx ngrok http 3978` to get the bot domain
3. `npx teamsfx provision --env local`
4. `npx teamsfx deploy --env local`
5. `npx teamsfx preview --env local`

**Expected behavior**
![image](https://github.com/OfficeDev/TeamsFx/assets/111231656/77f030f5-6811-4909-9bb6-8edc008ac74b)

**package.json**
```json
{
  "name": "teams-app",
  "version": "1.0.0",
  "msteams": {
    "teamsAppId": null
  },
  "description": "Microsoft Teams Toolkit message extension Bot sample",
  "engines": {
    "node": "16 || 18"
  },
  "author": "Microsoft",
  "license": "MIT",
  "main": "index.js",
  "scripts": {
    "dev:teamsfx": "env-cmd --silent -f .localConfigs npm run dev",
    "dev": "nodemon --inspect=9239 --signal SIGINT ./index.js",
    "start": "node ./index.js",
    "watch": "nodemon ./index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@microsoft/adaptivecards-tools": "^1.0.0",
    "botbuilder": "^4.18.0",
    "isomorphic-fetch": "^3.0.0",
    "node-html-parser": "^6.1.5",
    "restify": "^11.1.0"
  },
  "devDependencies": {
    "@microsoft/teamsfx-cli": "^2.0.1",
    "env-cmd": "^10.1.0",
    "ngrok": "^5.0.0-beta.2",
    "nodemon": "^2.0.7"
  }
}
```

**Comment by nliu-ms** [comment]
Hey @Mayank-3e , it might be a known issue. Occasionally server side responded with wrong manifest, so Teams cannot load this app.

Can you please try the workaround:
1) Remove TEAMS_APP_ID environment variable from {project}/env/.env.local
2) Execute above steps again:
npx teamsfx provision --env local
npx teamsfx deploy --env local
npx teamsfx preview --env local

This will create a new Teams app, to avoid data inconsistency problem. Please let me know if this solution works for you, thanks!

**Comment by Mayank-3e** [comment]
I did it, but the problem still persists. I can see that it created another bot (in [My Bots](https://dev.botframework.com/bots)) but even then it is not loading `manifest.json`

**Comment by nliu-ms** [comment]
Thanks for your prompt reply @Mayank-3e , let me check and get back to you.

**Comment by nliu-ms** [comment]
Hey @Mayank-3e , it might be a bug of @microsoft/teamsfx-cli, but it's hard to reproduce, still investigating.

As a workaround, you can use [Teams Toolkit VSCode extension](https://marketplace.visualstudio.com/items?itemName=TeamsDevApp.ms-teams-vscode-extension) to provision local resources and preview Teams app.
![image](https://github.com/OfficeDev/TeamsFx/assets/71362691/ea9cbd6a-fd91-46ad-b2c6-eb16ac0cfb60)

You can start with a new project. If you're using existing project with this error, don't forget to delete TEAMS_APP_ID from .env.local file.

**Comment by Mayank-3e** [comment]
Yes, the app is working from Teams Toolkit VSCode extension.

**Comment by nliu-ms** [comment]
@Mayank-3e  awesome! Thanks for letting me know it. I will continue investigating the issues of CLI and keep you updated.
