### ISSUE TITLE
Basic bot template launch targets names are not consistent

### ISSUE THREAD

**Issue by therealjohn** [OfficeDev/TeamsFx#9518]
**Expected behavior**
Launch targets for Teams should specify Teams in the name. i.e. https://github.com/OfficeDev/TeamsFx/blob/c10a0af37c3887178cdd665d1e220095d00a08db/templates/ts/default-bot/.vscode/launch.json#L69

vs. 

https://github.com/OfficeDev/TeamsFx/blob/c10a0af37c3887178cdd665d1e220095d00a08db/templates/ts/dashboard-tab/.vscode/launch.json#L139

**Comment by yukun-dong** [comment]
Thanks @therealjohn , the basic bot's launch config will be updated to include "Teams".

**Comment by yukun-dong** [comment]
updated in https://github.com/OfficeDev/TeamsFx/pull/9562.
