### ISSUE TITLE
bug report: coordinator.Error

### ISSUE THREAD

**Issue by bmbadveeti** [OfficeDev/TeamsFx#9558]
EACCES: permission denied, mkdir '<REDACTED: user-file-path> <REDACTED: user-file-path>'

stack:
Error: EACCES: permission denied, mkdir '<REDACTED: user-file-path> <REDACTED: user-file-path>'

**Comment by adashen** [comment]
@bmbadveeti  Thanks for reporting the issue. Can you help to provide the detail repro-steps for us to further investigating the issue?
