### ISSUE TITLE
bug report: AppStudioPlugin.DeveloperPortalAPIFailed

### ISSUE THREAD

**Issue by AhemMushtaq** [OfficeDev/TeamsFx#9595]
API call to Developer Portal failed: Error, Request failed with status code 404, API name: get-app-package, X-Correlation-ID: a01bc355-a2ee-4372-877e-a2cb33e9b367. This may come from some intermittent service error. Please wait for a few minutes and retry the current step. data: {"type":"https:/<REDACTED: user-file-path>

**Comment by HuihuiWu-Microsoft** [comment]
Hi @AhemMushtaq, the error seems incomplete, can you help provide more detailed error message from console log?
