### ISSUE TITLE
.notification.localstore.json not being generated

### ISSUE THREAD

**Issue by omarraja786** [OfficeDev/TeamsFx#9638]
**Describe the bug**
I had a Microsoft Teams TAB app (TeamsFX 5.0) and I wanted to also add a notification bot. My method was to simply take the key components from the notification bot template and add them to my tab app for example updating the manifest, yaml files, env files, controllers etc. I am able to provision my resources without any error and able to run the app without any issue. I have the the "chat" tab i assume that is created from the notification bot but when i post to my endpoint for example:` Invoke-WebRequest -Uri "http://localhost:2544/api/notification" -Method Post` although it returns a 200, nothing is sent. 

I noticed I didn't have a notification.localstore.json file and took one from a fresh solution and updated the Bot Id and Name hoping that would do the trick. This has lead to me getting a error:
`Invoke-WebRequest: Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)`

Maybe copying a localstore isn't the solution because of the unique guids but i'm not sure what else to do?
**To Reproduce**
Create a Microsoft Tab App
Create a Microsoft Notification Bot
Copy the main files needed for this notification bot i.e. update manifest.json, controllers, env config, models, resources, app settings and so on. BUT don't take the localstore file.
Run the app and see if it generates.

**Expected behavior**
You should expect the app to run and in the "About" section it will say "Tab" and "Bot" but when you try to post to an endpoint you will get a 200 OK, and if you try take the notification.localstore file from the other project you'll get a forbidden error.

**Screenshots**
This is when i take the notification localstore json file from another project and edit the bot id:
![image](https://github.com/OfficeDev/TeamsFx/assets/74924572/f43428f4-b62d-4067-8117-caba455f9da0)

This is when i have no notification.localstore.json file but no message is sent:
![image](https://github.com/OfficeDev/TeamsFx/assets/74924572/65981c7a-0932-429c-afc0-b368e2fd58cb)

**VS Code Extension Information (please complete the following information):**
Visual Studio 2022 17.7.1
TeamsFX 5

**Comment by TeuryBazzo** [comment]
I have same troble, did you find a solution ?
