### ISSUE TITLE
F5 experience for SPFx project fails with node version error

### ISSUE THREAD

**Issue by rabwill** [OfficeDev/TeamsFx#9648]
**Describe the bug**
When I run an SPFx project from teams toolkit it always picks up Node 18 instead of node 16 which is what I have made as a default node to test SPFx.

In terminal when I check node version it is 16.14.2 but as soon as I hit F5 it picks up my node 18 ( I don't know why). I use nvm to switch between node version on my mac. Even after making 16 the default this is my experience and the F5 breaks.

**Expected behavior**
F5 should pick default node version

**Screenshots**
Error: Your dev environment is running NodeJS version v18.14.0 which does not meet the requirements for running this tool. This tool requires a version of NodeJS that matches >=12.13.0 <13.0.0 || >=14.15.0 <15.0.0 || >=16.13.0 <17.0.0

**VS Code Extension Information (please complete the following information):**
 OS: macOS
TTK: v5.0.1

**Comment by HuihuiWu-Microsoft** [comment]
Hi @rabwill, thanks for reporting this to us! When you F5 to debug the SPFx project, actually we'll check prerequisites, provision and run `gulp serve` before launching. The error message you mentioned doesn't come from TTK actually. Instead, it's from `gulp serve` command. 
But when running `gulp serve`, it should use your default Node.js version to run the command, I'm not quite sure why you're seeing this error. Could you help go to `src` folder under your TeamsFx project and check your Node.js version? If the version is correct, try running  `node node_modules/gulp/bin/gulp.js serve --nobrowser` command under current directory and see if you're seeing the same error.

**Comment by rabwill** [comment]
Thanks for your reply. Below are some of the things I tried and now it's working, so you can close @HuihuiWu-Microsoft. 

Before I cloned the SPFx project, the default node version was 18 and I changed my node version to 16 and it did not work.

I deleted the project and changed my default node version to 16 and tried F5 (fresh start) it did not work. The error persists even though `node -v` shows version 16. 

I restarted my machine, deleted the project and did a fresh clone and then F5 works.

**Comment by HuihuiWu-Microsoft** [comment]
Great! There might be something wrong on the environment before restart. Anyway, I'll close the issue since it's working now.
