### ISSUE TITLE
Can Message Extension with no Query command and only Action commands do SSO in V5

### ISSUE THREAD

**Issue by sunshineo** [OfficeDev/TeamsFx#9705]
Our app is a Message Extension with just one action command.

The action command opens our website, then user select an image

Our bot then build an Adaptive card and put the image on the card and send to the channel/chat

The size limit on the message is 28KB specified [here](https://learn.microsoft.com/en-us/microsoftteams/limits-specifications-teams#chat)

So we have to create a public url for the image. This is a security risk for us.

We then saw [this Graph API call](https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http#example-6-send-a-card-with-inline-images) claiming it can take size up to 4MB which is good enough for us.

So we want to get our bot access to Graph API, which means we need to do SSO.

We are currently using V4 and from my previous try to do SSO on V4, our conclusion is: it is possible if the Message Extension has a Query command, but NOT possible if it only has Action commands.

**Has this changed in V5?**

**Comment by wenytang-ms** [comment]
hi, @sunshineo, congrats to successfully publish your app to store!
According to this [MSDN doc](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-code?tabs=cs1%2Ccs2%2Ccs3%2Ccs4%2Ccs5&pivots=mex-app), the second notification says that SSO only support for `query` and `link unfurling`. so teams native not support to do sso for command. [More about command, query and link unfurling](https://learn.microsoft.com/en-us/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=dotnet)
According to [this doc](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/authentication/bot-sso-overview#enable-sso-for-a-teams-app), it says `You'll need to register your web service as a bot to enable SSO for your message extension app.`
So maybe your app can add a bot to do such sso, and '@microsoft/teamsfx' also [support sso for `Graph API` client](https://github.com/OfficeDev/TeamsFx/blob/e1ef8a0429e92290e32cd43131995a807a7e42d6/templates/js/sso-tab-with-obo-flow/api/getUserProfile/index.js#L99).

**Comment by adashen** [comment]
As the question has been answered. Close here
