### ISSUE TITLE
bot.notification.findMember taking more time to find user.

### ISSUE THREAD

**Issue by sid-neo** [OfficeDev/TeamsFx#9734]
**Describe the bug**
bot.notificaiton.findMember is taking minimum more than 2.5 seconds to find an user, and sometime it takes around 4 to 8 seconds 
We are using below method to find user conversation reference 
 const selectedUser = await bot.notification.findMember(async (m) => m.account.aadObjectId === req.body.user_id);

**To Reproduce**

**Expected behavior**
We are expecting it to be the notification to find the user a bit faster than this, because overall it takes around more than 4 seconds to final user getting message.

**Screenshots**

![image](https://github.com/OfficeDev/TeamsFx/assets/142236623/0c47e018-6d9b-4478-88b2-e1e9c66505d3)

![image](https://github.com/OfficeDev/TeamsFx/assets/142236623/643b67ee-ffc9-4283-94ff-6375592fe504)

![image](https://github.com/OfficeDev/TeamsFx/assets/142236623/bfd08d92-c6fd-4d65-a21c-845ee95718b4)

**Additional context**

Reference code

```
if (req.body) {
      if (req.body.user_id && req.body.message && req.body.body_type) {
        console.log(new Date().toISOString() + '2. Searching for user');
        const selectedUser = await bot.notification.findMember(async (m) => m.account.aadObjectId === req.body.user_id);
        console.log(new Date().toISOString() + '3. Retrieved User');
        if (selectedUser) {
          if (req.body.body_type === "text") {
            console.log(new Date().toISOString() + '4. Sending Message');
            //removing await for faster execution
            selectedUser.sendMessage(req.body.message);
            console.log(new Date().toISOString() + '5. Message Sent');
            res.json(200, { message: "Message Sent" });
          } else if (req.body.body_type === "adaptivecard") {
            //removing await for faster execution
            selectedUser.sendAdaptiveCard(AdaptiveCards.declare(req.body.message).render());
            res.json(200, { message: "Message Sent" });
          }
        } else {
          res.json(500, { message: "User Not found" });
        }
      } 

```

**Comment by qinezh** [comment]
@sid-neo Could you share about how many bot installations (personal chat, group chat, channel chat) are there, and how many members are under each of these installations for your bot app?

Underlying, `findMember` will list all the members belong to these installations. If there're too many members of your installations, it would take quite a while to call Teams API to list all the members before finding the targeted member.

You may consider to set the [search scope](https://learn.microsoft.com/en-us/javascript/api/%40microsoft/teamsfx/searchscope?view=msteams-client-js-latest) to find members from the installations (personal chat, group chat, channel chat) to narrow down the search scope to speed up the process:

>
>  findMember(predicate: (member: Member) => Promise<boolean>, **_scope?: SearchScope_**)

**Comment by sid-neo** [comment]
hi @qinezh - thanks for prompt response.... as of now we are in testing phase and we only have 3 users who has installed bot.  does this depends on number of users installed ?

**Comment by sid-neo** [comment]
We will try search scope thing to see if it is making any difference.

**Comment by qinezh** [comment]
Could you also try below snippet to check the duration to call `findAllMembers` and the count of members?

```typescript
const members = await bot.notification.findAllMembers(() => Promise.resolve(true));
console.log(members.length);
```

**Comment by kunj-sangani** [comment]
Hi @qinezh 

Updated the code as mentioned above now the code looks like

const selectedUser = await bot.notification.findMember(async (m) => m.account.aadObjectId === req.body.user_id, 1);
        

Outcome after that

![image](https://github.com/OfficeDev/TeamsFx/assets/25693207/711a2691-8843-42ae-8829-9ff3c1b2fe24)

**Comment by qinezh** [comment]
It's weird that there're only 3 users from all your bot installations, I'll take a further look.

**Comment by torresedgar87** [comment]
Hello, i am having a similar issue
`const member = await bot.notification.findMember(m => Promise.resolve(m.account.id === msTeamsId), 1);`
this is taking a long time. The issue gets worse the more users that install the app. 

```
export const bot = new ConversationBot({
  // The bot id and password to create CloudAdapter.
  // See https://aka.ms/about-bot-adapter to learn more about adapters.
  adapterConfig: {
    MicrosoftAppId: config.botId,
    MicrosoftAppPassword: config.botPassword,
    MicrosoftAppType: 'MultiTenant',
  },
  // Enable notification
  notification: {
    enabled: true,
    storage: new DynamoDBStorage(config.aws.region, config.dynamoDb.tableName),
  },
});
```

I configured my bot to use DynamoDB for storage and I can tell that on `findMember` it does a request for all installations. If I look at the data that is stored on every installation it is not include that conversation info. This means that at some point its also reaching out to Microsoft external services to get the conversation info before returning on the `findMember` method. Could this also be considered as a possibility for such a long delay?

**Comment by qinezh** [comment]
@torresedgar87 Yeah, that's one of the main reasons. When `findMember` is invoked, it will:
1. List all installations from the conversation reference store.
2. Call Teams API to check if above installations are valid and remove the invalid ones.
3. Call Teams API to get all members from each installation.
4. Filter and return the particular member from all members.

For step 2 & 3, it would take a long delay to call Teams API and get the response. Especially when there's lots of installations and the number of members is huge.

One approach is to implement your customized conversation reference store using the latest SDK. (see [ConversationReferenceStore](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teamsfx/botbuildercloudadapter.notificationoptions?view=msteams-client-js-latest#@microsoft-teamsfx-botbuildercloudadapter-notificationoptions-store) and here's a [sample implementation with Azure Blob](https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/adaptive-card-notification/src/store/blobStore.ts)). 

Then you could add a method to find installations from the customized store with your own logic and convert the found conversation reference to notification target using [buildTeamsBotInstallation](https://learn.microsoft.com/en-us/javascript/api/@microsoft/teamsfx/botbuildercloudadapter.notificationbot?view=msteams-client-js-latest#@microsoft-teamsfx-botbuildercloudadapter-notificationbot-buildteamsbotinstallation).

**Comment by qinezh** [comment]
The default conversation reference store only supports for-loop lookup because it saves conversation reference in a fixed schema in local disk for general purpose, while the customized store can set database index on any field of the conversation reference according to the business requirement. 

So, it would be recommended to use a customized conversation reference store to retrieve a conversation reference if there’s performance concern.

**Comment by gupta-lakshay** [comment]
@qinezh can you please share how are you storing the conversationReference and retrieving the user out of blobstore based on member's email or UPN or aadObjectId

**Comment by qinezh** [comment]
For the way to store conversation reference, you may refer to the [sample implementation with Azure Blob](https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/adaptive-card-notification/src/store/blobStore.ts), and to retrieve the user using email or AAD object id, you could add a method like `getByUserEmail(email)` or `getByUserId(userId)` in your customized store.

**Comment by gupta-lakshay** [comment]
> For the way to store conversation reference, you may refer to the [sample implementation with Azure Blob](https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/adaptive-card-notification/src/store/blobStore.ts). As for the way to retrieve the user using email or AAD object id, you could add a method like `getByUserEmail(email)` or `getByUserId(userId)` in your customized store and call it when needed.

we have an existing method findMember for ConversationReferenceStore, is it good to use it ? Does it internally uses graph APIs to fetch UPN and do UPN based filtering as UPN is not stored as part of conversation Reference ?
Is it a recommendation to implement method `getByUserEmail(email)` or `getByUserId(userId)` or use existing `findMember` method ?

**Comment by qinezh** [comment]
Yes, the method `findMember` is good to use and internally it uses BotBuilder SDK to call Teams API to fetch all the members.
It would be recommended to use a customized conversation reference store to retrieve a conversation reference if **there’s performance concern**.

**Comment by tomflenner** [comment]
Hi 👋🏻 !

Any update on this ? We're facing the same issue.

> For the way to store conversation reference, you may refer to the [sample implementation with Azure Blob](https://github.com/OfficeDev/TeamsFx-Samples/blob/dev/adaptive-card-notification/src/store/blobStore.ts). As for the way to retrieve the user using email or AAD object id, you could add a method like `getByUserEmail(email)` or `getByUserId(userId)` in your customized store and call it when needed.

@qinezh Can you help to provide the method `getByUserEmail(email)` ? 🙏🏻 

We use blob storage and our installations are like this :
```
{
  "activityId": "",
  "user": {
    "id": "",
    "aadObjectId": ""
  },
  "bot": {
    "id": "",
    "name": "teams-bot"
  },
  "conversation": {
    "conversationType": "personal",
    "tenantId": "",
    "id": ""
  },
  "channelId": "msteams",
  "locale": "fr-FR",
  "serviceUrl": "https://smba.trafficmanager.net/emea/"
}
```

How can we easily search for mail inside this blob ?

Thanks in advance 🙏🏻

**Comment by lior-lew** [comment]
Did anyone found a solution for this problem? I was thinking about running getAllMembers periodically and then store them in a database with the email as the key. in this case, what do you think a good trigger be for initiating the data sync? cron, when an installation is added? 

@qinezh how would getByUserEmail(email) in your solution be implemented and invoked?
