### ISSUE TITLE
bot.notification.findMember returns "undefined" when azure function security level changes from anonymous -> function

### ISSUE THREAD

**Issue by iloveyeseul** [OfficeDev/TeamsFx#9767]
**Describe the bug**
Our team builds a custom teams app that deploys the notification bot using Azure bot service, azure function, and Teams toolkit with bot framework. We noticed that when our azure function security level changes from "anonymous" to "function", the bot framework returns "undefined" for finding member installation for this function

```
// Create bot.
export const notificationApp = new ConversationBot({
  // The bot id and password to create CloudAdapter.
  // See https://aka.ms/about-bot-adapter to learn more about adapters.
  adapterConfig: {
    MicrosoftAppId: config.botId,
    MicrosoftAppPassword: config.botPassword,
    MicrosoftAppType: "MultiTenant",
  },
  // Enable notification
  notification: {
    enabled: true,
  },
});

member = await notificationApp.notification.findMember(
    m => {
      console.log(JSON.stringify(m));
      return Promise.resolve(m.account.userPrincipalName.toLowerCase() === element.toLowerCase())
    })

```
**To Reproduce**
Update azure function security level from "anonymous" -> "function"
The BotBuilderCloudAdapter.ConversationBot returns "undefined" for the findMember function

**Expected behavior**
We expect the member is return when the app is installed from the user

**Screenshots**
Also, we noticed this error in azure when we ran diagnostics
<img width="509" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/31974437/e236e932-9747-43c3-86de-70dd954b4fa4">

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by qinezh** [comment]
@iloveyeseul The API endpoint `/api/messages` will be called by Bot Framework Service, if function level authentication is enabled, the endpoint will be failed to be called.

The bot id & password will be verified while calling `/api/messages`, so it's safe to keep the API endpoint for anonymous access. For other API endpoints, you're free to enable auth for them.

**Comment by iloveyeseul** [comment]
Hello @qinezh , the answer was helpful. I could be able to make /api/messages endpoint as anonymous and another endpoint of ours as function level auth and could be able to send/receive notifications. However, discuss further with the team, we would like to secure /api/messages endpoints as well as like the production app we don't want to expose any endpoints in the risk and accessible from external, which can be in the risk of DOS attacks or other security risk implication. Do you have any more suggestions or know ways how to secure /api/messages endpoint and not make it anonymous?

**Comment by qinezh** [comment]
> Do you have any more suggestions or know ways how to secure /api/messages endpoint as well and not make it anonymous?

As far as I know, there's no way to do that, otherwise Bot Framework Service can't access the endpoint `/api/messages` either.
