### ISSUE TITLE
Creating a new tab app in typescript using Teams Toolkit generates incorrect teamsjs code

### ISSUE THREAD

**Issue by TrevorJoelHarris** [OfficeDev/TeamsFx#9814]
**Describe the bug**
Creating a new tab app in typescript using Teams Toolkit generates incorrect teamsjs code

**To Reproduce**
1. Open VS Code
2. Using Teams Toolkit, click "Create a New App" button
3. Select "Tab", "Basic Tab", "Typescript", and choose a location
4. Open your new project and navigate to `teamsapp.js`

**Expected behavior**
Calls to microsoftTeams.app.initialize() are correctly awaited.

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/18446904/d810cac3-ce33-4556-8ae0-23764fd60a78)
The call to `microsoftTeams.app.initialize()` is not awaited, which is incorrect. That call returns `Promise<void>`

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version v 5.0.1

**CLI Information (please complete the following information):**
 - OS: <not sure what info you want here?>
 - Version <not sure what info you want here?>

**Comment by hund030** [comment]
Thanks for your feedback.
This issue is duplicated with https://github.com/OfficeDev/TeamsFx/issues/8761 and has been fixed in https://github.com/OfficeDev/TeamsFx/pull/8794.
I think this fix has been distributed to Pre-release version of TTK but not yet to stable version.
