### ISSUE TITLE
High vulnerabilities in teamsfx-cli 2.0.1 regarding the yaml dependency

### ISSUE THREAD

**Issue by brooklynb7** [OfficeDev/TeamsFx#9819]
**Describe the bug**
In teamsfx-cli version 2.0.1, there are 4 high vulnerabilities derived from the dependency of yaml.

**To Reproduce**
* use "@microsoft/teamsfx-cli": "2.0.1" in dependencies of package.json
* run `npm audit`

**Expected behavior**
The high vulnerabilities should be avoided.

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/883025/e81f9cab-967b-40f6-ab9c-9418131732e1)

**VS Code Extension Information (please complete the following information):**
N/A

**CLI Information (please complete the following information):**
 - OS: Win 10
 - Version 2.0.1

**Additional context**
N/A

**Comment by jayzhang** [comment]
@brooklynb7 Sorry for delay for the response, the issues are fixed in the latest CLI ([@microsoft/teamsapp-cli@3.0.0](https://www.npmjs.com/package/@microsoft/teamsapp-cli)).
