### ISSUE TITLE
Adaptive card fails to render with specific strings

### ISSUE THREAD

**Issue by Krumelur** [OfficeDev/TeamsFx#9826]
**Describe the bug**
Sometimes Teams would show me an error "Error encountered while rendering this message" without any further detail.

**To Reproduce**
One of the text fields in my adaptive card is supposed to output the following string (actually, a SQL query):
```sql
var sql = "SELECT COUNT(DISTINCT VisitorId) AS UniqueVisitors FROM sitedata WHERE eventdate>='2023-08-01' AND eventdate<'2023-08-08' AND Site =='foo.bar.com' AND Url RLIKE '^http?s://foo.bar.com/([^/]*)/answers/?'"
```

To render the card I'm using this code:

```csharp
var cardContent = new AdaptiveCardTemplate(cardTemplate).Expand(
			new
			{
				Query = sql
			}
		);

		var replyActivity = MessageFactory.Attachment
		(
			new Attachment
			{
				ContentType = "application/vnd.microsoft.card.adaptive",
				Content = JsonConvert.DeserializeObject(cardContent),
			}
		);

		await turnContext.SendActivityAsync(replyActivity);
```

The card's relevant portion is this:

```json
{
      "type": "TextBlock",
      "text": "${query}",
      "wrap": true,
      "fontType": "Monospace",
      "color": "Dark",
      "horizontalAlignment": "Left",
      "separator": true
    }
```

Send the adaptive card and Teams will show that it fails to render the card. There is no exception.

**Expected behavior**
Card is rendered fine without error.

**VS Code Extension Information (please complete the following information):**
 Teams web or client, both Mac and Windows

**Additional context**
I tried to figure out what exactly it is that breaks the rendering but the results are non-conclusive.
By trial and error I started removing bits from the SQL string and found that it will still fail with this reduced version of the original string:

```sql
"SELECT COUNT(DISTINCT VisitorId) AS UniqueVisitors FROM sitedata WHERE eventdate>='2023-08-01' AND"
```

However, if I change it further and only remove the last ` AND`, it renders just fine:

```sql
"SELECT COUNT(DISTINCT VisitorId) AS UniqueVisitors FROM sitedata WHERE eventdate>='2023-08-01'"
```

As a workaround I wrapped the assignment into `WebUtility.HtmlEncode(sql)`and that fixes the issue. This will however break potential formatting such as Markdown.

**Comment by adashen** [comment]
Track the issue in upstream and close here.
