### ISSUE TITLE
For a azure subscription with no resource group "Provision" fails

### ISSUE THREAD

**Issue by rabwill** [OfficeDev/TeamsFx#9921]
**Describe the bug**
I recently got a new azure subscription. I have no resource group created. In reality teams toolkit can create new resource group. But when I select "Provision" due to no resource group created in the new azure subscription I get the error.
`[coordinator.ListResourceGroupsError]: Unable to get resource groups in subscription 'e9a872b8-9c80-454d-877e-9d428b3c8b73'due to error: Cannot read properties of undefined (reading 'name'). 
If the error message specifies the reason, fix the error and try again.`

**To Reproduce**
1. Create a new app sample
2. Select Provision of app
3. Select an azure subscription with no resource group

**Expected behavior**
Expected user experience to create rg

**VS Code Extension Information (please complete the following information):**
 - OS: IOS
 - Version Ventura 13.5.2

**Comment by jayzhang** [comment]
@rabwill Thanks for reporting issue. Can you provide the Teams Toolkit Extension version?

**Comment by corderov** [comment]
I had the same problem, and the solutions worked for me. Thanks!
