### ISSUE TITLE
Bug report: Previewing local teams app results in Something Went Wrong

### ISSUE THREAD

**Issue by andrewackerman** [OfficeDev/TeamsFx#9963]
**Describe the bug**
In the dialog for adding the app to a meeting, after selecting the meeting and pressing "Set up a tab", I am greeted with a dialog window that simply says "Something went wrong." There is no corresponding error message either in the dialog or in the console.

**To Reproduce**
1. Run `teams preview --local` and wait for browser to appear.
2. In the dialog for the app that appears, select "Add to a meeting".
3. In the next view, select the meeting to add the app to and press "Set up a tab"
4. The dialog disappears, and a second later is replaced with the error dialog.

**Expected behavior**
If not a working app, at least a detailed message in the dialog window or the console explaining what went wrong so I have anything to go on as to how to resolve the issue.

**Screenshots**
This is the same dialog as appears in #8740 but I have no idea if it is related.

![](https://user-images.githubusercontent.com/45923533/239215204-f9ed9966-eae1-497c-9ee4-cd85e7753c62.png)

**VS Code Extension Information (please complete the following information):**
- OS: Windows 11 (22H2)
- Version: 5.0.1

**CLI Information (please complete the following information):**
 - OS: Windows 11 (22H2)
 - Version: 1.2.6

**Additional context**
This project has worked in the past (a couple months ago), and is only recently showing this error. I've reverted my local repo to a commit from that time and the error persists.

I am aware that I am running an outdated version of the TeamsFX CLI. This is coming from a code repository that was delivered to us, and there is already a ticket for updating the project to work with the latest version. But in the short term, I need to get the existing code working so I can implement some high priority tickets.

**Comment by nliu-ms** [comment]
Hey @andrewackerman , can you please share your app package to me?  I'm trying to reproduce the error. Thanks!

**Comment by andrewackerman** [comment]
@nliu-ms Here it is. [appPackage.zip](https://github.com/OfficeDev/TeamsFx/files/12665179/appPackage.zip)

**Comment by nliu-ms** [comment]
Thanks @andrewackerman , I tried your app package with my own local server. And it works, I can add the tab to a meeting. So the manifest should be correct.

I'm wondering if there is any issues in code/server. When you click `Set up a tab`, it actually trying to load configurationUrl:
![image](https://github.com/OfficeDev/TeamsFx/assets/71362691/ba20f0f3-cef8-4ad4-a5bf-33338c58ade0)
Possibly either it cannot access your local sever, or the SaveHandler is not correctly registered.

Can you please check your code with following example? @microsoft/teams-js SDK has been updated months before, not sure if it's your case.
https://github.com/OfficeDev/TeamsFx/blob/dev/templates/ts/dashboard-tab/src/TabConfig.tsx

If it still doesn't work, can you please share your codebase with me? Or at least the TabConfig.tsx so I can check. Thanks!

**Comment by andrewackerman** [comment]
@nliu-ms Nothing in the TabConfig.tsx file looks obviously wrong. Here are the contents:

```tsx
import { useEffect } from 'react';
import { app, pages } from '@microsoft/teams-js';
import appSettings from '../../settings';
import { Text } from '@fluentui/react-northstar';
import { useTranslation } from 'react-i18next';

/**
 * The 'Config' component is used to display your group tabs
 * user configuration options.  Here you will allow the user to
 * make their choices and once they are done you will need to validate
 * their choices and communicate that to Teams to enable the save button.
 */

const TabConfig = () => {
  const { t } = useTranslation();

  useEffect(() => {
    // Initialize the Microsoft Teams SDK
    app.initialize().then(() => {
      /**
       * When the user clicks "Save", save the url for your configured tab.
       * This allows for the addition of query string parameters based on
       * the settings selected by the user.
       */
      pages.config.registerOnSaveHandler((saveEvent) => {
        const baseUrl = `https://${window.location.hostname}:${window.location.port}`;
        const displayName = appSettings.environment.tabName;
        pages.config
          .setConfig({
            suggestedDisplayName: displayName,
            entityId: 'Test',
            contentUrl: `${baseUrl}/index.html#/lobby`,
            websiteUrl: `${baseUrl}/index.html#/lobby`,
          })
          .then(() => {
            saveEvent.notifySuccess();
          });
      });

      /**
       * After verifying that the settings for your tab are correctly
       * filled in by the user you need to set the state of the dialog
       * to be valid.  This will enable the save button in the configuration
       * dialog.
       */
      pages.config.setValidityState(true);
    });
  }, []);

  return (
    <div>
      <Text as="p">{t('config.tabDesc1')}</Text>
      <Text as="p">{t('config.tabDesc2')}</Text>
    </div>
  );
};

export default TabConfig;
```

The routing seems correct as well:

```tsx
<Router>
  <Routes>
    ...
    <Route path="/config" element={<TabConfig />} />
  </Routes>
</Router>
```

**Comment by nliu-ms** [comment]
@andrewackerman  Yes I cannot see any issue in the code. 

Sorry I have no idea right now, everything looks good. Can you please try some workarounds? E.g. 

1) Can you sideload the app with VSCode extension instead of TeamsFx CLI?
2) Can you please try uploading the package from Teams client and install it?
![image](https://github.com/OfficeDev/TeamsFx/assets/71362691/69cb9f2f-7cd2-4824-b24c-fb337071980f)
3) Does this issue only happen to you? Or other colleagues in your tenant cannot install this app either?

If none of above step works, please let me know. I will reach out to Teams team for help. Thanks!

**Comment by andrewackerman** [comment]
@nliu-ms 

1.  Between the time the first dialog appears and the "Something went wrong" dialog appears, there are no network calls that don't result in 200 responses, and only two warnings appear in the console about 404s and they are both about source maps and both target something in the "*.office.com" domain:

```
DevTools failed to load source map: Could not load content for https://statics.teams.cdn.office.net/hashed/[[staticsPath]]/hashed/jszip.min-18db2e9.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://local.teams.office.com/sourcemaps/hashed-assets/services-search-ddc9b752db1c146c.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

2. I'm not able to get the version of the Teams VS extension working with my project, presumably because the project uses an older version of the toolkit.

3. Uploading the app via "Manage your apps" results in the same error.

4. So far I've been the only one working on this project, but I can see if I can pull someone else in to see if they can reproduce the issue.

**Comment by Wajeed-msft** [comment]
This issue has been copied over to Microsoft Teams repo here: https://github.com/MicrosoftDocs/msteams-docs/issues/9521

**Comment by nliu-ms** [comment]
Thanks for the check @andrewackerman 

2. I'm not able to get the version of the Teams VS extension working with my project, presumably because the project uses an older version of the toolkit.

You can try this way to install an older version.
![image](https://github.com/OfficeDev/TeamsFx/assets/71362691/594da401-e76d-4a06-a7a6-6cf9b32e308d)


I added `MSTeams-Developer-Support` tag, this will generate a issue for Teams team. You can provide you app package in that issue to let them check the problem. As "Uploading via Manage your apps" doesn't work either, it seems some issue from Teams client. Hope it can help!

**Comment by andrewackerman** [comment]
@nliu-ms I was able to get version 4.2.5 of the VS code extension installed and sideload the app. It resulted in the same error.

**Comment by nliu-ms** [comment]
Thanks @andrewackerman , based on above information, I think it's more like an issue from Teams client. Can you please follow this issue https://github.com/MicrosoftDocs/msteams-docs/issues/9521 to get investigation results from Teams team? Thanks!

**Comment by adashen** [comment]
Close here and let's track at https://github.com/MicrosoftDocs/msteams-docs/issues/9521
