### ISSUE TITLE
Notification Bot (HTTP trigger Restify server) - failed to send notification to user after deploying it to azure.

### ISSUE THREAD

**Issue by pjpraveenjayakumar** [OfficeDev/TeamsFx#9973]
**Urgent**

We've developed a notification bot (HTTP trigger Restify server) using the Teams Toolkit, and it functioned correctly in our local environment. However, we encountered an issue where the notification target is lost when the bot app is restarted or redeployed to the Azure App Service. As per the documentation 
https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams?tabs=ts1%2Cts2%2Cts3%2Cts4%2Cjsts%2Cts5#add-storage
In the local environment, notification connections are stored in the .notification.localstore.json file. However, for the production instance, we haven't been able to locate the exact file or location where it stores these notification connections references.

Would you kindly assist us in determining the storage location of notification connections for production instances deployed on Azure, and also shed light on why the target notification connections are disappearing following bot app restarts or redeployment?

**To Reproduce**
1. Go to 'teams toolkit in vs code and select "create a new app-->Bot-->Chat notification message-->Http trigger restify server"
2. run the solution and deploy it to azure.
3. try to send post request with azure endpoint using postman to trigger notifications as given in below snap.
4.
![image](https://github.com/OfficeDev/TeamsFx/assets/109327327/919d1a87-3f43-4b45-88b4-84173656ba06)

5. See error
After redeploying to azure Able to send notification with 200k response but user was not able to receive any notification.

**Expected behavior**
it should send a notification adaptive card message to users personal chat.
![image](https://github.com/OfficeDev/TeamsFx/assets/109327327/a7bd1788-c48c-4baa-997e-eb226432e9bd)

**Screenshots**

**Additional context**

**Comment by qinezh** [comment]
@pjpraveenjayakumar  In production, the default file `.notification.localstore.json` is written to Azure App Service's temp folder, so it will be cleaned up after the app restarted or redeployed. It's always recommended to use your own storage in production.

**Comment by Yugender025** [comment]
In your local development environment, the notification connections might be temporarily stored in a local file like .notification.localstore.json. However, this local storage is not suitable for production scenarios. When your bot app is redeployed or restarted in a production environment, this local storage is typically cleared, leading to the loss of notification connections.

**Comment by DylanWoodhead** [comment]
I'm having the same issue, when I post the http trigger locally I get the response I need, however, I have now provisioned and deployed to Azure. Uploaded the app to Teams and when I try to post the http trigger with the Azure URL I get the status 200, OK but nothing appears in the chat on Teams.
I feel like I'm missing something I need to setup like authentication or blob storage but I'm not sure. 
Any help would be really appreciated! :)

**Comment by qinezh** [comment]
@DylanWoodhead yeah, you're recommended to add your own storage to store notification connections in production environment, and you may refer to the [documentation](https://learn.microsoft.com/en-us/microsoftteams/platform/bots/how-to/conversations/notification-bot-in-teams?tabs=ts1%2Cts2%2Cts3%2Cts4%2Cjsts%2Cts5#add-storage) for more details and [here](https://github.com/OfficeDev/TeamsFx-Samples/blob/main/adaptive-card-notification/src/store/blobStore.ts) for a sample implementation with azure blob.

**Comment by DylanWoodhead** [comment]
@qinezh thank you for the reply!
So, if I use the sample you linked and put it into my project, do I need to adjust any other files for example package.json etc so that the blob storage works? (apologises if dumb question, quite new to Teams bots)

**Comment by qinezh** [comment]
@DylanWoodhead yes, you also need to update your package.json to add related npm library and update [the notification option](https://github.com/OfficeDev/TeamsFx-Samples/blob/main/adaptive-card-notification/src/internal/initialize.ts#L19) to enable the customized store. For more details, please refer to [the sample app](https://github.com/OfficeDev/TeamsFx-Samples/tree/main/adaptive-card-notification) directly. 

For the question about authentication, the bot app's endpoint `/api/message` has already been protected by Bot Framework with bot id & password and no need authentication anymore.
