### ISSUE TITLE
Allow TeamsBotSsoPrompt to re-prompt

### ISSUE THREAD

**Issue by Krumelur** [OfficeDev/TeamsFx#9974]
**Is your feature request related to a problem? Please describe.**
I'm using `TeamsBotSsoPrompt` in a C# bot to allow users to benefit from SSO. Currently, there is a problem where one of the following happens:

a) The prompt to start the SSO is not showing up at all
b) The prompt shows but clicking "Continue" does not open the browser
c) The prompt was shown, but user clicked "Cancel"
d) The prompt was shown and the user signed in successfully

In all 4 cases I will never see the prompt again which makes it hard to debug.

**Describe the solution you'd like**
I would like to be able to force the SSO process to be repeated.
An option that forces the dialog into a non-smart mode would be good.

**Describe alternatives you've considered**
Currently I must change the requested scopes to force the prompt to appear again. This is cumbersome.

**Additional context**
Sometime, the prompt seems to "think" it has a valid token and won't be shown. But in reality, there is no token.
This seems to happen in the new Teams client apps.

**Comment by blackchoey** [comment]
@Krumelur  TeamsBotSsoPrompt does not persist any internal state to skip execution. The botframework dialog system will record the dialog status for you. So after TeamsBotSsoPrompt is triggered, the dialog system will not trigger TeamsBotSsoPrompt again.

One possible solution to your problem is to end current dialog when there's no SSO code (which may caused by User cancelled the consent or other reasons). So when user talks to your bot again, botframework thinks it's a new dialog and triggers TeamsBotSsoPrompt again. Here's an example about how to end the dialog: https://github.com/OfficeDev/TeamsFx-Samples/blob/v2.0.0/bot-sso/helpers/ssoDialog.ts#L114

**Comment by Krumelur** [comment]
Not sure if I can follow this. Simple example:

```
protected override async Task OnMessageActivityAsync(ITurnContext<IMessageActivity> turnContext, CancellationToken cancellationToken)
{
	await ssoDlg.RunAsync(turnContext, _conversationState.CreateProperty<DialogState>(nameof(DialogState)), cancellationToken);
}
```

This will ask for the token exactly once. I can restart my machine, I can log out of Teams and back in.

Isn't there logic in here that says: if I have a token, the SSO dialog will be ended and not ask again?

https://github.com/OfficeDev/TeamsFx/blob/7c487bff443c670e13f1c1f9a0e30dfda7f8bb0f/packages/dotnet-sdk/src/TeamsFx/Bot/TeamsBotSsoPrompt.cs#L193

**Comment by blackchoey** [comment]
> Isn't there logic in here that says: if I have a token, the SSO dialog will be ended and not ask again?
> 
> https://github.com/OfficeDev/TeamsFx/blob/7c487bff443c670e13f1c1f9a0e30dfda7f8bb0f/packages/dotnet-sdk/src/TeamsFx/Bot/TeamsBotSsoPrompt.cs#L193

No, the logic says: if it cannot exchange the SSO token for expected access token (e.g. MS Graph token), tell Teams to show the login buttons asking user to login and consent required permission. If it can exchange the SSO token for expected access token, do nothing and go to the next step of our dialog.

App users should only be asked to login and consent required permission once. After that, no explicit login is required - SSO happens behind the senses.

So please add some logic to end the current dialog when you think TeamsBotSsoPromt should re-prompt. The js bot-sso sample I shared previously should be a good reference. You can also share some repro steps so we can provide more detailed suggestions.

**Comment by Krumelur** [comment]
I ported the TS example to C#. However - as I expected - ending the dialog won't make Teams display the login buttons again. I bet the TS version behaves the same way. 

As you correctly said:

`
if it cannot exchange the SSO token for expected access token (e.g. MS Graph token), tell Teams to show the login buttons asking user to login and consent required permission. If it can exchange the SSO token for expected access token, do nothing and go to the next step of the dialog.`

If I have a (valid) token, the buttons won't be shown. It has nothing to do with me ending the dialog or not. Like I said: latest if I log out of Teams and back in, it should be a new dialog. But even then the buttons won't come back. This is not a big issue, unless you have a situation where Teams _thinks_ it has a valid token but actually has not.

**Comment by blackchoey** [comment]
Can you share your scenario that when your app can acquire a valid token, it still needs to show the login button and ask user login again? I'm not sure whether you're just referring to the `Teams thinks it has a valid token but actually has not` case. If yes, can you share the repro step that results in this?

One goal of Teams SSO is to reduce the need of user login when using an app. So it's expected to not show login button when the app can acquire the expected token. I will see whether there's other suggestions after you shared your user scenario.

**Comment by Krumelur** [comment]
Yes, it is mostly the case of "Team has a token but not". This happened to me when I cancelled the request to login and also when a user clicked "Continue" but the browser window would not open. From there on the dialog was skipped but there was no token either. These are the main scenarios.
The third one is simply about being able to demonstrate and document the steps.

**Comment by blackchoey** [comment]
Let me try to create an example for your first two situations ("cancelled the request to login" and "continue button does not open the login window").
For the third scenario, maybe cancel your previous consent is a better approach - you don't need to add special logic to you app. You can go to https://myapps.microsoft.com/ to search your app and cancel your consent. It may take some time to take effect.

**Comment by Krumelur** [comment]
Finally decided to abandon TeamsFx and Teams Toolkit for now and went back to fully relying on Azure & "good old" OAuthPrompt combined with auth middleware as shown in this example: https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-conversation-sso-quickstart/csharp_dotnetcore

IMHO the "only" problem is the lack of or confusing documentation.
